### ISSUE TITLE
Android Web App: Respect Dark mode on start up

### ISSUE THREAD

**Issue by menelic** [omnivore-app/omnivore#1005]
The Android web app does not respect Dark mode on start up, as the start up screen is the standard beige/ocher color. While the color scheme is nice, the start up screen can be too bright in situations where dark mode is chosen consciously, eg when reading at night.

**Comment by jacksonh** [comment]
Thanks, I know there is an API call we can make for this, I'll look into handling in the splash page.

**Comment by jacksonh** [comment]
Taking some notes on this:

This is set in the web manifest `background_color`: https://github.com/omnivore-app/omnivore/blob/f7e3a1657eb9c7af1a67bf25faf8265f75dc3d4a/packages/web/public/static/unused/pwa/manifest.webmanifest#L6 
Some information here: https://github.com/w3c/manifest/issues/975

**Comment by jacksonh** [comment]
Not a full solution but a bit of a compromise using a gray background here: https://github.com/omnivore-app/omnivore/pull/1033

**Comment by jacksonh** [comment]
@menelic we've deployed a change to make this a darker gray. Let me know if you see any improvement.

**Comment by jacksonh** [comment]
I'm going to close this one. We've set a more muted colour which seems to be the best we can do with the current PWA options.

@menelic if you are interested, we are starting to test our native Android app (its quite simple now, but should progress quickly)
