### ISSUE TITLE
Left menu for larger screens

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#1017]
On larger screens we want to display an updated left menu that gives users better access to our search filters, subscription filters, and label filters. 

The goal is to make it easier for user's to filter their libraries on larger screens.

Here is a slightly altered version of the menu from Figma. It removes user configurable searches, and counts from each item:

<img width="239" alt="Screen Shot 2022-07-25 at 16 39 05" src="https://user-images.githubusercontent.com/75189/180892662-36726dcf-6ef7-438a-b581-7d2d3b2c925b.png">

NOTE: the above screenshot has the incorrect icon for the listed subscriptions.

Original Figma: https://www.figma.com/file/ILgs6aXrPfukXOMf5Yibra/Omnivore---Deliverables?node-id=3573%3A89407 

The menu should be:

- Saved Searches (existing code here: https://github.com/omnivore-app/omnivore/blob/badd32ed39137d56de35b19afefe60e2a0aa32fc/packages/web/components/templates/homeFeed/HomeFeedContainer.tsx#L58 )
-- Inbox 
-- Read Later
-- Highlights
-- Today
-- Newsletters

- list of subscriptions
-- format should be `<Cards size={24} /> {{subscription.name}}`
when a subscription is clicked we just do a search for `subscription:{subscription.name}`

- list of labels
-- format should be `<TagSimple size={24} /> {{label.name}}`
when a label is clicked we just do a search for `label:{label.name}`

NOTE: We are ignoring the concept of user saved searches and recent searches for now and will leave that to a future iteration.

**Comment by jacksonh** [comment]
For this I would start by creating a storybook of this component.

**Comment by rupin90** [comment]
> For this I would start by creating a storybook of this component.

Sure, will start with that. Thank you

**Comment by rupin90** [comment]
https://github.com/omnivore-app/omnivore/pull/1031 - This is merged!
