### ISSUE TITLE
Allow ordering labels

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#1022]
There are a few screens where users see their labels in a list: in iOS on the labels page, in iOS on the extension, on the web when setting labels, and on the all labels page. We will also show the labels in a list on the left side menu when that is added. 

Because of this, users will want to order their labels. 

We can look at how GitHub allows you to move cards in Project using the `position` attribute as an example: https://docs.github.com/en/rest/projects/cards#move-a-project-card

**Comment by jacksonh** [comment]
@satindar FYI, need to think about how iOS would want to handle this.

**Comment by jacksonh** [comment]
Here is the GitHub GQL docs for this API: https://docs.github.com/en/graphql/reference/mutations#moveprojectcard

**Comment by satindar** [comment]
This looks like a LinkedList opportunity!

**Comment by sywhb** [comment]
I might store the order of label in the database

**Comment by jacksonh** [comment]
@sywhb yeah that could work, i trust your judgement. I expect most people to have less than 50 labels at the most.
