### ISSUE TITLE
Create sync API to allow propagation of deletes 

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#1032]
Currently we don't propagate delete's to iOS. If a user deletes an article on web and then syncs on iOS, if the deleted article had already been synced to iOS it wont be removed.

To fix this we can create a sync API to include deletes. A simple sync API could look like this:

```
type SyncUpdatedItemEdge {
    cursor: String!
    updateReason: String! `created | updated | deleted`
    itemID: ID!
    node: SearchItem /* for created or updated items, undefined for deletions */ 
}
```

```
Query {
    updatesSince(since: Date)
}
```

To do this we would also have to soft delete items (or store deletions elsewhere).

**Comment by jacksonh** [comment]
This is just some proposed API, I am open to different versions.

**Comment by sywhb** [comment]
@jacksonh are we making iOS to handle conflicts? Like changes on both iOS and Web but not yet propagated

**Comment by sywhb** [comment]
> @jacksonh are we making iOS to handle conflicts? Like changes on both iOS and Web but not yet propagated

Yeah, I think we could add a `timestamp` in response so iOS could use it to manage conflicts. 
Also, we could add `limit` and `offset` in the request for pagination.

**Comment by sywhb** [comment]
Actually, we could just use the `updatedAt` in the node item to manage conflicts.

**Comment by jacksonh** [comment]
Yeah that should work. I think newest wins is fine, we don't really need to merge. I think the only mutations are really adding/removing highlights and read position, and it is single user, so its not perfect but unlikely to have too many conflicts.

**Comment by sywhb** [comment]
API is ready in #1035
