### ISSUE TITLE
“Unable to save page” from Firefox extension

### ISSUE THREAD

**Issue by xplosionmind** [omnivore-app/omnivore#1051]
I get the error message in the title while trying to save [this page](https://alesahebi.substack.com/p/nessun-partito-mi-rappresenta). Could you reproduce the error?

**Comment by jacksonh** [comment]
@xplosionmind I'm not able to reproduce here. Tried a few different methods of saing and didn't see that error. 

If you get the error again could you try logging out and back in at https://omnivore.app/login ? I'm thinking one potential issue is the cookies aren't set properly.

**Comment by xplosionmind** [comment]
That was it: I did not log in yet, but I did not know.

Let me open another issue specifically for this problem.
