### ISSUE TITLE
Get icons for subscriptions

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#1068]
It would be nice if we can retrieve icons for subscriptions. Once we start displaying them more in the app it would make it easier to find the subscription you are looking for.

**Comment by jacksonh** [comment]
@sywhb I'll assign this one to you, we probably need to figure out what to fetch, but it would be nice if we assigned an icon to subscriptions, maybe using favicon or some other metadata from the site.

**Comment by sywhb** [comment]
@jacksonh Is the icon shown on the subscriptions page? It's easier if we could fetch it from the email headers

**Comment by sywhb** [comment]
There is no email header for the icon. So I get the icon URL from the parsed HTML page and return the proxy URL in the listing subscriptions API response. 
#1246

**Comment by sywhb** [comment]
@jacksonh I can see the icons in the `subscriptions` table and you could curl the API to fetch the icon from the new newsletter received:
```
curl 'https://api-demo.omnivore.app/api/graphql' \
  -H 'content-type: application/json' \
  -H 'authorization: <YOUR_API_KEY>' \
  --data-raw '{"query":"\n    query GetSubscriptions {\n      subscriptions(sort: { by: UPDATED_TIME }) {\n        ... on SubscriptionsSuccess {\n          subscriptions {\n            id\n            name\n            newsletterEmail\n            url\n            description\n            status\n            unsubscribeMailTo\n            unsubscribeHttpUrl\n            createdAt\n            updatedAt\n          icon\n          }\n        }\n        ... on SubscriptionsError {\n          errorCodes\n        }\n      }\n    }\n  "}'
```

**Comment by jacksonh** [comment]
I'm going to implement this one on iOS to test it out.
