### ISSUE TITLE
Add a background colour for the active menu item 

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#1075]
In the design we have a background colour on the active menu item to help the user know where they are in the app. Notice the background of `Home` in this screenshot:

<img width="298" alt="Screen Shot 2022-08-15 at 10 49 29" src="https://user-images.githubusercontent.com/75189/184569220-1681ef3a-f772-495a-ae5c-895e19f3cbe0.png">

There is an active boolean in the MenuItem that we are setting for this. But it doesn't look like the CSS is changing for the active item. In the screenshot you can see in web inspector that active is set, but the menu item still looks the same. 

<img width="1413" alt="Screen Shot 2022-08-15 at 11 00 43" src="https://user-images.githubusercontent.com/75189/184570091-493ad393-8b52-497f-93e1-f2972b37f008.png">

There's also a dark mode version here:

<img width="286" alt="Screen Shot 2022-08-15 at 11 06 38" src="https://user-images.githubusercontent.com/75189/184570564-bee40271-98f2-4f1e-a20f-3bbc2b296c08.png">

These background colours are available in our theme as `libraryActiveMenuItem`.

**Comment by jacksonh** [comment]
I'd start this by just trying to make the CSS set the correct background colour for `Home` which is hard coded to active. After that we can add something to figure out which filter is active, but we might want to experiment with a few options here.

**Comment by rupin90** [comment]
this is Fixed
