### ISSUE TITLE
Menu should be scrollable

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#1076]
When you have a large number of labels or subscriptions in the menu you should be able to scroll it. Right now, you can't access the bottom portion of content in the menu:

https://www.loom.com/share/f65967b8b1d44f97a6fd31530b66667e 

I tried adding some padding in `LibraryMenu` but that didn't seem to fix it. 

For a good example of how we should work, look at the new Gmail and how you can scroll the left menu to access elements at the bottom.

**Comment by rupin90** [comment]
This is Fixed
