### ISSUE TITLE
Add CMD+K key graphic to the search bar

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#1077]
In the LibrarySearchBar we need to add the CMD+K graphic to tell users about our command bar. This element is only visible when `searchTerm` is undefined. So once a user highlights the search bar and starts typing, it will disappear. 

<img width="626" alt="Screen Shot 2022-08-15 at 13 36 42" src="https://user-images.githubusercontent.com/75189/184581957-ee1efd5f-d2e6-4130-b21d-0bfef7979f4c.png">

This should not be visible for touch device users, for OSX users this should display `CMD+K`, and for Windows users it should say `Ctrl + K`.

For touch devices, we have a function `isTouchScreenDevice` that we can use to detect. If the user is on a touch device we will just hide this element.

LibrarySearchBar component: https://github.com/omnivore-app/omnivore/blob/28c7d7be90ce1820060ab34dc45cd851e416b067/packages/web/components/templates/library/LibrarySearchBar.tsx 

Figma: https://www.figma.com/file/ILgs6aXrPfukXOMf5Yibra/Omnivore---Deliverables?node-id=3573%3A91988

**Comment by jacksonh** [comment]
Lets pause this one for a minute. I am thinking instead of this maybe we should add something like Gmail where we display a "Filter" icon and allow users to do advanced search via a kind of drop down sheet

https://www.loom.com/share/80b71820d1824c868b66fe70d587e33e

**Comment by jacksonh** [comment]
I just added a filter button as a first step. Will go over the mockups to see about the advanced search filter sheet.

**Comment by jacksonh** [comment]
Assigning to myself to fix up the designs.

**Comment by jacksonh** [comment]
Will close this one.

**Comment by rupin90** [comment]
👍🏽
