### ISSUE TITLE
Add recent searches sheet

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#1078]
When a user starts a search, we can open a recent searches dropdown. These searches can just be saved in local storage for now, we will add an API in the future. 

<img width="807" alt="Screen Shot 2022-08-15 at 14 21 35" src="https://user-images.githubusercontent.com/75189/184586461-40ca30f4-1e98-44c6-b362-8a0802c5e28c.png">

This list should be keyboard navigatable by tapping the up/down arrows. If a user hits enter on a recent search, or clicks a recent search, that search should be performed. Clicking the `X` icon beside a search will remove it from the list.

Note that in figma there is a larger search sheet displayed, but we just need to implement saved searches for now.

https://www.figma.com/file/ILgs6aXrPfukXOMf5Yibra/Omnivore---Deliverables?node-id=3573%3A91202

**Comment by rupin90** [comment]
Is this the next thing to work on @jacksonh ? Any changes in the priority? I can start working on this tomorrow.  @jacksonh

**Comment by jacksonh** [comment]
Hey @rupin90 yeah I think so.

**Comment by rupin90** [comment]
> Hey @rupin90 yeah I think so.

Cool, sounds good.

**Comment by jacksonh** [comment]
@rupin90 do you have any questions on it?

**Comment by rupin90** [comment]
as of now, not really but will reach out if any confusion. 

I do see that there will be an API in the future and right now we are going to leverage local storage. So will see what can be done. Will get started on this. Thank you @jacksonh

**Comment by rupin90** [comment]
https://github.com/omnivore-app/omnivore/pull/1162 
PR is merged, closing this ticket.
