### ISSUE TITLE
Active state on menu extends too far to the left

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#1091]
Notice how on the left we are going all the way to the edge of the screen, but in the design its a bit different:

Screenshot:

<img width="327" alt="Screen Shot 2022-08-18 at 10 56 27" src="https://user-images.githubusercontent.com/75189/185283367-0a087797-4370-4d9d-aed8-ef972149c268.png">

Design:

<img width="502" alt="Screen Shot 2022-08-18 at 11 00 35" src="https://user-images.githubusercontent.com/75189/185283517-9933fcdc-113a-41f9-b6f7-eb704ed5e5d6.png">

**Comment by rupin90** [comment]
This is Fixed.
