### ISSUE TITLE
Use inter semibold font in left menu

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#1092]
Figma design:

<img width="1036" alt="Screen Shot 2022-08-18 at 11 04 14" src="https://user-images.githubusercontent.com/75189/185283940-16b87bc0-7e1b-4903-b503-2e5949954a40.png">

**Comment by jacksonh** [comment]
I think we just have to set to `font-weight: 600`

**Comment by rupin90** [comment]
This is Fixed
