### ISSUE TITLE
Add menu dividers from updated design

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#1096]
Notice how there are some lines between the top searches, the labels, and the subscriptions now:

<img width="364" alt="Screen Shot 2022-08-18 at 19 25 00" src="https://user-images.githubusercontent.com/75189/185383843-a55d03e1-bfa8-430b-820c-3bee68802048.png">

Figma link here: https://www.figma.com/file/ILgs6aXrPfukXOMf5Yibra/Omnivore---Deliverables?node-id=3798%3A102118

**Comment by rupin90** [comment]
This is merged and fixed
