### ISSUE TITLE
Issues with morning brew newsletter

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#1110]
We have two main issues with the morning brew newsletter. Both are probably related to tables:

1. The table of market info at the top is formatted as a single column.

2. The social media buttons under each section are a column instead of a row. 

![image](https://user-images.githubusercontent.com/75189/185825458-a6ddad6d-62d5-4551-88b0-84aa9f314d21.png)

![image](https://user-images.githubusercontent.com/75189/185825472-79a3703d-aa07-4656-8a63-817e274ec441.png)

**Comment by sywhb** [comment]
I managed to render the market info in separate rows and removed the social links in #1190 
Deployed this branch in Demo for testing

**Comment by sywhb** [comment]
It looks good on mobile browser but not iOS App. I wonder if I need to update it too.
Mobile browser:
![image](https://user-images.githubusercontent.com/12963965/191032793-1d704cc9-eb42-4019-b76b-9c8c017a821e.png)

iOS:
![image](https://user-images.githubusercontent.com/12963965/191032679-fbd3cc11-9228-43ef-bbf9-7d0b610741fd.png)

**Comment by jacksonh** [comment]
Ohh that is good. For this fix did you have to update stuff in `packages/web`?

**Comment by sywhb** [comment]
> Ohh that is good. For this fix did you have to update stuff in `packages/web`?

Yes, I updated the CSS file

**Comment by jacksonh** [comment]
Ok, I'll update the app bundle. Pretty easy to do, for reference you just run this command in the `packages/appreader` directory, and it generates new JS:

`appreader$ yarn build-and-update`

**Comment by jacksonh** [comment]
Next testflight build will have this included.

**Comment by sywhb** [comment]
Fixed another parsing issue of the newsletter here: #1217 

The whole newsletter was wrapped inside a table with `role=presentation` and it wasn't transformed into a `div`. We fixed it by only keeping tables with market info.

Newsletter is here:
https://www.morningbrew.com/daily/issues/royal-impact?utm_source=header_signup&utm_medium=newsletter&utm_campaign=mb&mid=9ab421de712275aea1b00553124b59a0

**Comment by sywhb** [comment]
CSS update: #1218

**Comment by jacksonh** [comment]
Will close this one now. Looks good!
