### ISSUE TITLE
There is a strange border appearing around "Read Later" button when the button is clicked

### ISSUE THREAD

**Issue by sywhb** [omnivore-app/omnivore#1197]
This happens on Web.
<img width="477" alt="Screenshot 2022-09-15 at 9 04 43 AM" src="https://user-images.githubusercontent.com/12963965/190306288-0f5d382d-8954-4263-ae66-a5c3d3c43a6d.png">

<img width="488" alt="Screenshot 2022-09-15 at 11 21 46 AM" src="https://user-images.githubusercontent.com/12963965/190306793-3d3372c2-d881-4703-a90e-d2798f55171a.png">

**Comment by jacksonh** [comment]
Ah yes, this is some of the default browser stuff. I will fix this one.

**Comment by jacksonh** [comment]
PR here: https://github.com/omnivore-app/omnivore/pull/1210
