### ISSUE TITLE
Give users more control over adding items to their library view email

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#1220]
Right now we attempt to detect if an email is an article, or forwarded from a certain source before adding.

**Comment by heliostatic** [comment]
I'd like to add to this request: I'd like to forward my newsletters to omnivore instead of changing delivery addresses for them. Today, this doesn't work as expected for, e.g., substack newsletters. Would be great to parse those forwards as the newsletter.

**Comment by jacksonh** [comment]
Hello with the recent classifier changes this should be working now. Please let me know if you still have issues.
