### ISSUE TITLE
Integrations page

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#1309]
We have a design for an extensible integrations page here: https://www.figma.com/file/ILgs6aXrPfukXOMf5Yibra/Omnivore---Deliverables?node-id=3751%3A92143

<img width="651" alt="Screen Shot 2022-10-14 at 07 24 14" src="https://user-images.githubusercontent.com/75189/195728600-92e02ae9-85cc-408d-a3b8-3c869e25651c.png">

This page allows users to connect with external apps using our three existing integrations: Readwise, Webhooks, and Logseq. Each of those integrations is handled in a slightly different way.

- Readwise: uses our integrations API (details below)
- Logseq: this is just a link to the logseg plugin repository (or maybe we should link to docs)
- Webhooks: uses our webhooks API, and is mostly a link to `/settings/webhooks`

**Comment by jacksonh** [comment]
Overview for the ticket: https://www.loom.com/share/f2cc819d2c9c46d3a62321bc63456ddd

**Comment by rupin90** [comment]
> Overview for the ticket: https://www.loom.com/share/f2cc819d2c9c46d3a62321bc63456ddd

Thank you, this is a pretty good to get started with. I don't have questions as of now because you pretty much answered in the video but in case anything comes up will reach out! 🙌🏽

**Comment by jacksonh** [comment]
Hey @rupin90 I think i created this issue on mobile web, notice how the `here` link is in a weird position.

<img width="345" alt="Screen Shot 2022-10-27 at 09 51 48" src="https://user-images.githubusercontent.com/75189/198172502-d4de982a-4361-4b00-bb76-7b254d44ba6d.png">

**Comment by rupin90** [comment]
> Hey @rupin90 I think i created this issue on mobile web, notice how the `here` link is in a weird position.
> 
> <img alt="Screen Shot 2022-10-27 at 09 51 48" width="345" src="https://user-images.githubusercontent.com/75189/198172502-d4de982a-4361-4b00-bb76-7b254d44ba6d.png">

aah I am sorry, I modified the page to make it similar and consistent. Forgot to pay attention to mobile layout. Let me go ahead and take care of this.

**Comment by rupin90** [comment]
> Hey @rupin90 I think i created this issue on mobile web, notice how the `here` link is in a weird position.
> 
> <img alt="Screen Shot 2022-10-27 at 09 51 48" width="345" src="https://user-images.githubusercontent.com/75189/198172502-d4de982a-4361-4b00-bb76-7b254d44ba6d.png">



> > Hey @rupin90 I think i created this issue on mobile web, notice how the `here` link is in a weird position.
> > <img alt="Screen Shot 2022-10-27 at 09 51 48" width="345" src="https://user-images.githubusercontent.com/75189/198172502-d4de982a-4361-4b00-bb76-7b254d44ba6d.png">
> 
> aah I am sorry, I modified the page to make it similar and consistent. Forgot to pay attention to mobile layout. Let me go ahead and take care of this.

https://github.com/omnivore-app/omnivore/pull/1357
@jacksonh  - This PR should fix the problem.

**Comment by rupin90** [comment]
I am going to continue the Webhook page because I didn't finish with my previous PR.

**Comment by rupin90** [comment]
Closing this ticket since it is completed
