### ISSUE TITLE
Multiple/batch selection

### ISSUE THREAD

**Issue by xplosionmind** [omnivore-app/omnivore#1365]
Suppose I would like to add the same label to several articles, or that I want to mark them all as read.

Right now, the only way to go so is to perform such actions on each article, one by one. It would be great if in the homepage a multiple selection tool could be offered, in order to select more than one or even all articles in one time, and then perform the same action to them all.

**Comment by jacksonh** [comment]
Yeah we had a few mockups for this but the user interaction wasn't very good. Thanks for adding this, we should definitely come up with something.

**Comment by jacksonh** [comment]
We have this on the web now. Rolling out label setting as well.
