### ISSUE TITLE
Rate limiting on text-to-speech

### ISSUE THREAD

**Issue by sywhb** [omnivore-app/omnivore#1387]
Could be done on the duration or count of words depending on implementation.
The limit can be high and we also need a way to ban users.
We probably can store usernames in Redis and a backing store for restoring the data

**Comment by jacksonh** [comment]
Does tts-streaming service have access to the database? I guess there are two places we could do this: when the speech file is generated, or when the audio segments are generated.

**Comment by sywhb** [comment]
No, the tts streaming service doesn't have access to the database currently.

I support doing the rate-limiting when the audio segments are generated because there might be some cases that the speech file is generated but not audio segments so we may be over-limiting the tts usage.

We could save the rate(count of words) in Redis in tts streaming cloud function
