### ISSUE TITLE
Bloomberg articles are not entirely saved

### ISSUE THREAD

**Issue by xplosionmind** [omnivore-app/omnivore#1393]
If I try to save, for example [this bloomberg page](https://www.bloomberg.com/news/articles/2019-01-22/remembering-geocities-the-suburbia-of-the-early-web), I only get the first two paragraphs in Omnivore.

**Comment by jacksonh** [comment]
Thanks @xplosionmind, when you save are you using the Firefox extension?

**Comment by xplosionmind** [comment]
> when you save are you using the Firefox extension? 

I tried only via link pasting, but I now tried again from the Firefox extension and it works wonderfully: the whole article is saved!

**Comment by xplosionmind** [comment]
Sorry for opening the bug report before comprehensive testing. I will double check next time.
