### ISSUE TITLE
Updated landing page

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#1400]
New landing page design. The main difference is the layout at the top and then some updated screenshots.

This is a minor upgrade to `pages/about.tsx` 

Desktop: https://www.figma.com/file/ILgs6aXrPfukXOMf5Yibra/Omnivore---Deliverables?node-id=4435%3A128546

Mobile: https://www.figma.com/file/ILgs6aXrPfukXOMf5Yibra/Omnivore---Deliverables?node-id=4435%3A130669

**Comment by rupin90** [comment]
Sounds good, on it today!

**Comment by jacksonh** [comment]
looks good now!
