### ISSUE TITLE
Android V1 Blockers

### ISSUE THREAD

**Issue by satindar** [omnivore-app/omnivore#1431]
Android tasks to get to V1:

- [x] - Single article renders at center of list - add spacer to bottom of list
- [x] - Highlight bar position - should render at location of highlight tap rather than top
- [x] - Tapping highlight doesn't show bar (should show delete and annotate buttons at tap location)
- [x] - Add note popup needs improvement. Closer to iOS sheet style.
- [x] - Add ability to add note to pdf highlight

**Comment by jacksonh** [comment]
Will close this one out.
