### ISSUE TITLE
[Feature] Create & assign labels from share menu 

### ISSUE THREAD

**Issue by Bad3r** [omnivore-app/omnivore#1433]
It would be extremely useful and convenient to be able to create labels when adding an article. 

### Browser
The browser add-ons does not support the ability to assign or create tags when saving articles.

### Mobile
Currently, on iOS, it's only possible to select one of the existing labels. I assume it's the same case for android, but I don't have an easy way to verify. 

![image](https://user-images.githubusercontent.com/25513724/202679376-0c44137e-eec7-479f-be95-9b36a8924265.png)

**Comment by jacksonh** [comment]
Thanks, this was missing from the latest version and I just added it back in. Should be available in a few days


<img width="488" alt="Screen Shot 2022-11-21 at 18 28 35" src="https://user-images.githubusercontent.com/75189/203027695-220c4b4e-af92-4e0a-a722-4c93a6bf45d4.png">

**Comment by ugurbolat** [comment]
This isn't available for browser extensions (e.g., firefox) yet? @jacksonh
