### ISSUE TITLE
Auto light-dark theme switch in the webapp

### ISSUE THREAD

**Issue by xplosionmind** [omnivore-app/omnivore#1438]
Automatically switch the app theme according to the device preferences.

**Comment by jacksonh** [comment]
Good idea. We just came up with a few new themes too, so ties in well

<img width="412" alt="Screen Shot 2022-11-22 at 16 29 06" src="https://user-images.githubusercontent.com/75189/203263749-7d5e016c-b0cc-454f-959d-bae8b31b5e4e.png">

**Comment by jacksonh** [comment]
Commenting to send this one back to the top of the list now that theme improvements are done.

**Comment by karkraeg** [comment]
+1 from me, would be nice if omnivore would follow the devices settings.
