### ISSUE TITLE
New York Times article is missing a part

### ISSUE THREAD

**Issue by xplosionmind** [omnivore-app/omnivore#1439]
I am logged into my NYT account and I am saving [this page](https://www.nytimes.com/2022/10/28/technology/twitter-changes.html) via the Firefox browser extension. As the screenshots below display, the initial part of the article is not saved.

The saved article begins from “Now, Mr. Musk…” but the paragraphs above are missing…

![Screenshot 2022-11-22 at 9 03 02 AM](https://user-images.githubusercontent.com/42862428/203259088-12cf582d-cd3b-46db-aa2c-e2d6a3a8c183.jpg)
![Screenshot 2022-11-22 at 9 03 44 AM](https://user-images.githubusercontent.com/42862428/203259100-e5fccd2f-f7aa-427b-9326-c99e38017134.jpg)

**Comment by sywhb** [comment]
Fixing in #1478 

And it looks good in Demo @jacksonh
<img width="950" alt="Screenshot 2022-11-30 at 1 22 01 PM" src="https://user-images.githubusercontent.com/12963965/204714194-f42a97e6-d7f6-4cdf-9c6b-3615257472f9.png">

**Comment by sywhb** [comment]
Will test more in demo

**Comment by jacksonh** [comment]
Nice
