### ISSUE TITLE
FR: Implement Web Share Target API

### ISSUE THREAD

**Issue by mturilin** [omnivore-app/omnivore#1453]
I'm suggesting implementing [Web Share Target API](https://developer.chrome.com/en/articles/web-share-target/) for the web app to be able to accept sharing in from the Android platform widget.

**Comment by jacksonh** [comment]
Hi @mturilin, have you installed the app as a PWA? With the app installed it should show up in your list of share targets.

**Comment by mturilin** [comment]
Gotcha. I installed it from Brave browser which apparently doesn't do it correctly. I reinstalled from Chrome and now it's working.
