### ISSUE TITLE
Enhancement for Android

### ISSUE THREAD

**Issue by electr1fy0** [omnivore-app/omnivore#1532]
Why should the Android users get PWAs?
It'd be great if a native app could be developed.

**Comment by satindar** [comment]
> Why should the Android users get PWAs?
> 
> It'd be great if a native app could be developed.

We've been working on a native Android app and just resolving a few final issues. We'll be submitting to to Google Play in the next few days. Hopefully ready for you soon after!

**Comment by jacksonh** [comment]
Hey @electr1fy0 we are starting to test our native android client now. You can join the testers here:  https://play.google.com/apps/testing/app.omnivore.omnivore

**Comment by jacksonh** [comment]
I'll close this one out for now. We will file some more issues around Android as we catch its featureset up to iOS / Web.
