### ISSUE TITLE
Links are not styled in Firefox

### ISSUE THREAD

**Issue by xplosionmind** [omnivore-app/omnivore#1552]
### Discussed in https://github.com/omnivore-app/omnivore/discussions/1392

<div type='discussions-op-text'>

<sup>Originally posted by **xplosionmind** November  3, 2022</sup>
By reading an article inside Omnivore, links are disguised within the text since they do not have any different graphical styling.

The only way to find a link is to pass the cursor over all of the text until the pointer changes into indicating that the element under it is clickable.

While the reading experience can become less distracting, I believe users should be given the choice whether to uniform links styling with the text or to make them pop out: #1391.</div>

As @Bad3r suggested, I tried saving articles by pasting the link and not via extension. The issue persists. I used [this article](https://www.theguardian.com/media/2022/nov/01/mastodon-twitter-elon-musk-takeover), but this happens with *any* article. I use uBlock Origin, but this error occurs both if it is enabled or disabled.

This is what my console shows:

```
09:46:18.373 SingleFile is hooking the IntersectionObserver API to detect and load deferred images. single-file-hooks-frames.js:1:541
09:46:18.382 SingleFile is hooking the IntersectionObserver API to detect and load deferred images. single-file-hooks-frames.js:1:531
09:46:18.435 The resource at “https://platform.twitter.com/widgets.js” was blocked because content blocking is enabled. trunk-for-the-fediverse-18517fa2d7f
09:46:18.635 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://vitals.vercel-insights.com/v1/vitals. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.
09:46:18.635 TypeError: NetworkError when attempting to fetch resource.
09:46:18.688 Some cookies are misusing the recommended “SameSite“ attribute 2
09:46:19.683 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://vitals.vercel-insights.com/v1/vitals. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.
09:46:19.683 TypeError: NetworkError when attempting to fetch resource.
09:46:34.777 Navigated to https://omnivore.app/tommi/trunk-for-the-fediverse-18517fa2d7f
09:46:35.430 SingleFile is hooking the IntersectionObserver API to detect and load deferred images. single-file-hooks-frames.js:1:541
09:46:35.434 SingleFile is hooking the IntersectionObserver API to detect and load deferred images. single-file-hooks-frames.js:1:531
09:46:35.477 The resource at “https://platform.twitter.com/widgets.js” was blocked because content blocking is enabled. trunk-for-the-fediverse-18517fa2d7f
09:46:35.803 Some cookies are misusing the recommended “SameSite“ attribute 2
09:46:35.958 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://vitals.vercel-insights.com/v1/vitals. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.
09:46:35.958 TypeError: NetworkError when attempting to fetch resource.
09:46:36.041 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://vitals.vercel-insights.com/v1/vitals. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.
09:46:36.041 TypeError: NetworkError when attempting to fetch resource.
```

**Comment by jacksonh** [comment]
Thanks for following up on this one. I'm taking another look at it now. @xplosionmind can you tell me what OS you are using (apologies if i asked before).

**Comment by xplosionmind** [comment]
> Thanks for following up on this one. I'm taking another look at it now. @xplosionmind can you tell me what OS you are using (apologies if i asked before).

MacOS 13.1 with LibreWolf 108.0-1

**Comment by jacksonh** [comment]
Oh LibreWolf is a very good clue. I wonder if a font or some CSS or something is being blocked. Going to see if I can replicate.

**Comment by xplosionmind** [comment]
Sorry for the late reply. Links styling works on Safari. It is probably a LibreWolf problem.

**Comment by jacksonh** [comment]
Interesting. I'll keep this open for a bit and try to replicate, it could maybe be something with how our CSS is loaded, but I don't particularly see why it would be blocked, its all coming from the same domain.

**Comment by xplosionmind** [comment]
Update: links styling for me is not working even in normal Firefox (110.0.1), both on Linux (Ubuntu) and macOS. I disabled all ad blockers.

**Comment by jacksonh** [comment]
Any chance you have the dark mode extension? Someone else mentioned this is happening with it.

**Comment by xplosionmind** [comment]
Links underlining works for me in Firefox 121.0 on Fedora 39!

Thanks!

**Comment by jacksonh** [comment]
Ah awesome, thanks for following up on this one!
