### ISSUE TITLE
Difficult to see sign in fields for Android app

### ISSUE THREAD

**Issue by bbkane** [omnivore-app/omnivore#1581]
I made a comment in [Discord](https://discord.com/channels/844965259462311966/943967463299764314/1057623629514412063) with a ![screenshot](https://media.discordapp.net/attachments/943967463299764314/1057623629094989914/Screenshot_20221228-033728.png)
Thanks!

**Comment by jacksonh** [comment]
Closing this one out, sorry I missed closing it before
