### ISSUE TITLE
Some trouble with local development setup

### ISSUE THREAD

**Issue by maksim77** [omnivore-app/omnivore#1584]
According instruction in README file all i need is start docker compose environment but in this step i see at least three problems: 

1. Link http://localhost:3000/email-signup lead to 404 error page...
2. Tryout register with email failed with `Error: Sendgrid API key not set` in log. Maybe we can add a demo user `user@example.com` to our db migration?
3. Kibana in compose file look strange to me. I understand that Kibana simplified debuging but it does much more heaviest environment. I think if developer need a GUI to Elastic then he will be able to install it himself. Maybe just comment this section in compose file?

**Comment by jacksonh** [comment]
1. Just put up a fix for the README here: https://github.com/omnivore-app/omnivore/pull/1585 
2. Yeah i wonder if we can create that user as part of the docker compose setup, so it never gets accidentally added to the live environment.
3. I think we can have it in there but not have it start? That's actually how I use the docker-compose file now. I just load one or two services from it. I am not sure how to disable it by default though.

**Comment by sywhb** [comment]
Agree with the idea to create a user account in docker-compose.

We could use [service profiles](https://docs.docker.com/compose/profiles/) to run Kibana only for debugging

**Comment by sywhb** [comment]
Something like this so Kibana will only be started if we run by `docker compose --profile debug up`
```
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.1
    container_name: "omnivore-kibana"
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
    depends_on:
      - elastic
    ports:
      - "5601:5601"
    profiles:
      - debug
 ```

**Comment by sywhb** [comment]
#1595

**Comment by jacksonh** [comment]
💯
