### ISSUE TITLE
Save link from existing article

### ISSUE THREAD

**Issue by maksim77** [omnivore-app/omnivore#1588]
Please add options to add link from existing article to omnivore instead open this in in-app browser.
Let's say I'm reading a large article containing references to somewhere else. It seems to me a possible option that I want to save them for later instead of opening them immediately.
Maybe long press on link and "Add to Omnivore" will be exactly what I'm looking for?

**Comment by jacksonh** [comment]
Hey @maksim77 for this, are you using iOS, Web, or Android right now (yes it should be consistent across all)

**Comment by jacksonh** [comment]
Got it, funny timing, i just worked on this yesterday: https://www.loom.com/share/04ab6705894848e0830eafb826370d8c

**Comment by jolpadgett** [comment]
> Got it, funny timing, i just worked on this yesterday: https://www.loom.com/share/04ab6705894848e0830eafb826370d8c

Will this be made available (iOS, iPadOS) or am I overlooking it (assume not since the issue is still open here)

**Comment by jacksonh** [comment]
> > Got it, funny timing, i just worked on this yesterday: https://www.loom.com/share/04ab6705894848e0830eafb826370d8c
> 
> Will this be made available (iOS, iPadOS) or am I overlooking it (assume not since the issue is still open here)

yeah it is on iPhone but because of a weird issue we don't have it on iPad yet.
