### ISSUE TITLE
Times of India newsletter not detected

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#1591]
https://timesofindia.indiatimes.com/india/timestopten.cms -- this one gets forwarded, not detected as an article.

**Comment by sywhb** [comment]
@jacksonh I could not access the logs.

Could you please show me the HTML of the newsletter email?

**Comment by jacksonh** [comment]
Yeah no problem, i think i have some saved will create gists

**Comment by sywhb** [comment]
Signed up the newsletter in demo

**Comment by sywhb** [comment]
#1768
