### ISSUE TITLE
Newsletters from economictimes.indiatimes.com are not being detected as articles

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#1592]
These newsletters are being forwarded, not saved:

[etauto latest news](https://auto.economictimes.indiatimes.com/)
[ETEnergyworld Latest News](https://energy.economictimes.indiatimes.com/)

**Comment by sywhb** [comment]
@jacksonh I could not access the logs.

Could you please show me the HTML of the newsletter email?

**Comment by sywhb** [comment]
Signed up the newsletter in demo

**Comment by sywhb** [comment]
#1768

**Comment by sywhb** [comment]
Preparse content to make it look better #1818
