### ISSUE TITLE
[Enhancement] Contrast color on login page - UI - Android App

### ISSUE THREAD

**Issue by AntheaLiles** [omnivore-app/omnivore#1597]
Hi,

I'm using the Android App of Omnivore and I've note that the font color need more contrast

It's really hard to read pale blue font on a light yellow background 

Is it possible to use a black or dark grey font color instead ?

![Screenshot_20221217-104558_Omnivore.jpg](https://user-images.githubusercontent.com/120063455/210175278-c7c5a31b-62ab-47d8-b523-b015d6df2789.jpg)

**Comment by satindar** [comment]
Hi thanks for reporting this issue @AntheaLiles

We shipped this version of the app with a few bugs related to theming so on a few pages the background didn't match up correctly. We have a fix but need to deploy a new build which we'll do in the next few days.

**Comment by bbkane** [comment]
Related to https://github.com/omnivore-app/omnivore/issues/1581

**Comment by jacksonh** [comment]
This one has been fixed for a bit.
