### ISSUE TITLE
Add wordsCount to Article type

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#1600]
In the latest web UI cards we want to display the word count to the user, (either as a word count or read time), to do this we need to add an optional `wordsCount` on the `type Article` in the schema. I think we are already storing this in elastic though.

**Comment by jacksonh** [comment]
A couple sample screenshots, see in top-right 

<img width="1061" alt="Screen Shot 2023-01-02 at 15 10 32" src="https://user-images.githubusercontent.com/75189/210202993-5621b8bf-bf1a-4c34-b5e8-9afaaf3988d9.png">

<img width="237" alt="Screen Shot 2023-01-02 at 15 08 50" src="https://user-images.githubusercontent.com/75189/210202999-477e4e72-570d-4d83-be8b-8c6ee5624b36.png">

**Comment by sywhb** [comment]
Added optional `wordsCount` to both `Article` and `SearchItem` schema in #1602
