### ISSUE TITLE
Twitter thread does not save correctly

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#1604]
This thread seems to save strangely: https://twitter.com/farnamstreet/status/1580700646835036160

**Comment by jacksonh** [comment]
The first URL is the last of the thread, but even if I save the first of the thread, it seems like the last item is missing: https://twitter.com/farnamstreet/status/1580680416846966784

**Comment by sywhb** [comment]
Working on a fix: https://github.com/omnivore-app/omnivore/pull/1648

**Comment by sywhb** [comment]
Can see the last two tweets saved in demo @jacksonh

**Comment by jacksonh** [comment]
awesome, thanks!

**Comment by sywhb** [comment]
https://twitter.com/mtaibbi/status/1610372352872783872 we need to click on "show more replies" for this thread

**Comment by sywhb** [comment]
Added "clicking on 'show more replies' button when scrolling in #1657

**Comment by sywhb** [comment]
Close this as we are now saving the thread correctly
