### ISSUE TITLE
Highlighting does not work on Firefox for Android

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#1622]
On Android if you select a few lines of text, then tap the highlight button only a single word is highlighted.

**Comment by thiswillbeyourgithub** [comment]
Still hapenning as of today on the web version on android.

**Comment by cesc1989** [comment]
This is still an issue.

I'm using Android 9. Firefox 116.2.0

**Comment by jacksonh** [comment]
Thanks, I thought we had this resolved will investigate more

**Comment by cesc1989** [comment]
FYI @jacksonh  In the Firefox 117.0 update this is no longer an issue.

**Comment by jacksonh** [comment]
@cesc1989 awesome thanks for following up! I'll close this one for now.
