### ISSUE TITLE
Add subscriptionCount on the NewsletterEmail type

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#1627]
I think we can do this by joining the `subscriptions` table. We just want to return a count of subscriptions a user has on a given email address so we can present it in the UI, like `email | created_at | num_subscriptions | confirmation_code `

**Comment by sywhb** [comment]
Yeah, a simple join should do the trick

**Comment by sywhb** [comment]
Merged #1633

**Comment by jacksonh** [comment]
💥
