### ISSUE TITLE
Handle unicode chars in slugs

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#1643]
Right now unicode chars are removed from slugs, so for articles with Chinese titles, we get useless slugs, this causes issues in apps like Obsidian that use the slug for the page title.

**Comment by sywhb** [comment]
#1657 
![](https://cdn.discordapp.com/attachments/1054319733152944189/1063470514326229062/Screenshot_2023-01-13_at_10.51.02_PM.png)

**Comment by sywhb** [comment]
We will generate `unicodeSlug` on the plugin side instead: https://github.com/omnivore-app/obsidian-omnivore/pull/8

**Comment by jacksonh** [comment]
Awesome. This morning I had a brilliant idea that we could do this on the client side.

**Comment by jacksonh** [comment]
I will close the issue here.
