### ISSUE TITLE
When a user deletes a label on the /settings/labels page it should be removed from all links

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#165]
Steps to reproduce:

- Create a new Label `foo` on /settings/labels
- Add the label to a link (navigate to link, press `l`, check box beside label)
- Go back to /settings/labels
- Delete the label

You'll note the label is still on the article if you refetch it

**Comment by sywhb** [comment]
@jacksonh This has been fixed in Demo. I guess we haven't deployed it to PROD

**Comment by sywhb** [comment]
Actually when i test it, it also works in PROD. Am I missing anything?

**Comment by jacksonh** [comment]
@sywhb oh this might have been the UI caching it when I tried.

**Comment by jacksonh** [comment]
Will move this to a web bug
