### ISSUE TITLE
Android app UI Enhancement

### ISSUE THREAD

**Issue by electr1fy0** [omnivore-app/omnivore#1650]
Android app's Status Bar and Navigation Bar color should be transparent.
Screenshots show how it is[1] v/s how it should be[2].
![Screenshot_20230113-090440](https://user-images.githubusercontent.com/87616300/212231431-b4202f3f-fa6e-4d36-bb71-65e2b6f6fcc9.png)
![Screenshot_20230113-090615](https://user-images.githubusercontent.com/87616300/212231440-828c9e41-593f-43a1-b605-2d02b7bd7620.png)

**Comment by akinsho** [comment]
![Screenshot_20240306-093004.png](https://github.com/omnivore-app/omnivore/assets/22454918/4d69a44d-d6a6-4bae-ad4f-42503c78085d)

I've also observed a similar problem for the reader view. I'd be happy to raise a similar PR if someone could point me towards where this code would need to be changed. I'm not sure what this view is actually called
