### ISSUE TITLE
Allow access to recently received emails

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#1653]
The recently received emails feature is an attempt to solve two issues users sometimes have with newsletters:

1. Sometimes they don’t receive forwarded emails, so they sign up for a newsletter and there is a confirmation email that they don’t receive. I think this is mostly it getting marked as spam or they don’t know the email account they signed up with because of Apple ID. 

2. Newsletters not being marked as articles. If that happens now there is nothing manual they can do to rectify they just have to wait for us to fix the classification

## Frontend

On the frontend we will display an ordered list of recently received emails. We will allow the user to view the sender and text content of the email. This will allow users to retrieve important items like confirmation emails that require them to confirm their subscription to a newsletter.

Users will also have the ability to mark an email as an article. This will give them the ability to move recent emails that we did not properly classify as newsletters into their library. **When a user does this, we should also notify the team by an email to feedback@ or some other mechanism**

Optional: we could also allow the user to forward the email to an address they provide. This gives them the ability to access the HTML content of the email without us having to create a full fledged email client.

## Backend

Likely this will require two API methods, one to list recently received emails for a user, and one to mark an email as a library item. We should also track the way the email was classified (eg article, non-newsletter, attachment, ...)

## Schema

The email item returned by the API could probably look like this:

```
type RecentEmail = {
    uuid: String
   to: the newsletter email address this was sent to
   from: the address sent from 
   type: how the email was classified (article, non-article...)
   text: the text content of the email
}

```

**Comment by jacksonh** [comment]
One thought is we have two ways this can be indexed, either per-user or per-NewsletterEmail address. It might be simplest for the user to make it per user, that way they can see all recently received, but we still need to track the NewsletterEmail address, so the user knows which address they used to subscribe.

**Comment by sywhb** [comment]
Working on this issue #1667
