### ISSUE TITLE
Label Search Operations

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#166]
There should be three ways of using Labels in search. We can use GitHub as a guide for each of these methods:

- [ ] contains: `label:foo` -- the returned items have the specified label
- [ ] `OR`: `label:foo,bar,baz` -- the returned items have any of the specified lablels
- [ ] `NOT` `-label:foo` -- the returned items do not have the specified label

**Comment by sywhb** [comment]
Should we add an `AND` relationship here?
Like `label:foo&bar&baz` which returns items have all the specified labels
@jacksonh

**Comment by jacksonh** [comment]
Yeah I think AND is a great idea. It could be `&` or `+`. 

Mostly I think these will be created via UI, but since we put them in the URL, I wonder if `+` would be easier than `&` -- or i guess both get URL encoded?

**Comment by sywhb** [comment]
Yeah both `&` and `+` get URL encoded.
Github uses `label:foo label:bar` to select items with both label `foo` and `bar` and maybe we can follow it so that a user can also type `https://omnivore.app/home?q=label:foo label:bar` in the address bar
