### ISSUE TITLE
Image parsing error

### ISSUE THREAD

**Issue by sywhb** [omnivore-app/omnivore#1663]
All the images in https://mp.weixin.qq.com/s/GOPZJy6e9JADeDN2M9rv8w are missing after saving

**Comment by sywhb** [comment]
Fixing in #1744 

Demo: https://www.loom.com/share/d2b157082a5846dc9bdcd74de9dc9f7f

**Comment by sywhb** [comment]
Deployed this fix in demo to do more testing

**Comment by sywhb** [comment]
Works in demo. Waiting to deploy in prod

**Comment by jacksonh** [comment]
nice!

**Comment by sywhb** [comment]
Closed as completed
