### ISSUE TITLE
How do I provide Chinese Simplified translations for iOS mobile?

### ISSUE THREAD

**Issue by holton-jiang** [omnivore-app/omnivore#1680]
How do I provide Chinese Simplified translations for iOS mobile?

**Comment by jacksonh** [comment]
Adding @satindar here. Probably what we need to do is create a strings file.

**Comment by holton-jiang** [comment]
@satindar I want to provide Chinese Simplified translations for my app.

**Comment by holton-jiang** [comment]
> Adding @satindar here. Probably what we need to do is create a strings file.

Thank you so much.
