### ISSUE TITLE
How do I translate for omnivore for Mac?

### ISSUE THREAD

**Issue by holton-jiang** [omnivore-app/omnivore#1690]
How do I translate to Chinese Simplified for omnivore for Mac?

**Comment by holton-jiang** [comment]
![Uploading 截屏2023-01-20 19.48.49.png…]()

**Comment by jacksonh** [comment]
@satindar are you able to create a strings file for the mac app? Or does the iOS one get used?

**Comment by holton-jiang** [comment]
> @satindar你能为mac应用程序创建字符串文件吗？还是iOS被使用？

Can iOS mobile and Mac be used together?

**Comment by holton-jiang** [comment]
> @satindar你能为mac应用程序创建字符串文件吗？还是iOS被使用？

I don't know which folder the string file is in.

**Comment by jacksonh** [comment]
Hi @holton-jiang we will set one up and tell you when ready.

**Comment by holton-jiang** [comment]
> Hi @holton-jiang we will set one up and tell you when ready.

Ok, thank you very much for your help

**Comment by holton-jiang** [comment]
> Hi @holton-jiang we will set one up and tell you when ready.

I found that Omnivore for MacOS is still missing the menu bar and I haven't translated it. The other parts are translated.

**Comment by satindar** [comment]
> > Hi @holton-jiang we will set one up and tell you when ready.
> 
> I found that Omnivore for MacOS is still missing the menu bar and I haven't translated it. The other parts are translated.

Hi @holton-jiang . Thanks so much for your work in translating! The same strings file is used by macOS and iOS. I started working through all the strings in the app to make sure we're using the strings file rather than using raw strings in code. It's taking a while. So far I found about 125 strings and started moving them. 

So it will probably take me a few more days to create the strings and add a reference but once that is done it will be a lot easier to know what needs translation.

**Comment by satindar** [comment]
@holton-jiang This is the file that will have all the strings. There's a few in there now that need translation from English. A lot more needed later though! Fortunately we have native speakers on our team as well.

**Comment by holton-jiang** [comment]
> @holton-jiang这是将包含所有字符串的文件。现在里面有一些人需要从英语翻译。不过以后还需要更多！幸运的是，我们的团队中也有母语人士。
> 
> 编辑：忘记添加参考文件：https://github.com/omnivore-app/omnivore/blob/main/apple/OmnivoreKit/Sources/Views/Resources/zh-Hans.lproj/Localizable.strings

Thank you so much for the strings you are looking for day and night, may the next version become even better, and wish you all the best in the new year.
