### ISSUE TITLE
Please add support for newsletters from every.to

### ISSUE THREAD

**Issue by dpschen** [omnivore-app/omnivore#1729]

**Comment by sywhb** [comment]
Subscribed to the newsletter to test

**Comment by sywhb** [comment]
#1768

**Comment by sywhb** [comment]
Hey @dpschen, we have added the support for newsletters from `every.to`.

Please let us know if it works for you

**Comment by dpschen** [comment]
Hey, thanks for this and sorry for the delay.
I did receive now one newsletter from every (was [this issue](https://every.to/p/the-radical-promise-of-nuclear-fusion)).

Some other issues still seem to get redirected. For example I got [this issue redirected](https://every.to/napkin-math/when-content-creation-goes-to-zero).
