### ISSUE TITLE
Incorrect title on page hosted on notion.site

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#1734]
This page gives an incorrect title after saving using the extension: https://luhmann-logseq.notion.site/A-new-approach-to-project-management-in-Logseq-8b36dd5eb25d4b9e9882742b5ee4368e

**Comment by sywhb** [comment]
#1745

**Comment by sywhb** [comment]
#1745 is merged and testing in demo

**Comment by sywhb** [comment]
Works well in demo

<img width="1031" alt="Screenshot 2023-01-31 at 9 55 53 AM" src="https://user-images.githubusercontent.com/12963965/215639912-44ba0285-b440-48f3-9616-7c945f9cebc0.png">

We could deploy it in prod

**Comment by sywhb** [comment]
Closed as completed
