### ISSUE TITLE
Safari extensions on Mac and iOS Unable to save page.

### ISSUE THREAD

**Issue by holton-jiang** [omnivore-app/omnivore#1737]
Always displayed “Unable to save page”.
<img width="1440" alt="截屏2023-01-28 16 52 45" src="https://user-images.githubusercontent.com/88922715/215256827-0654de9c-726a-4359-bc5d-17e7c54a6165.png">

**Comment by jacksonh** [comment]
Thank you @holton-jiang can you try logging out and then logging back in at https://omnivore.app and see if the issue continues?

**Comment by holton-jiang** [comment]
> 谢谢@holton-jiang，你能尝试注销，然后重新登录https://omnivore.app，看看问题是否仍然存在吗？

Yes, I tried it and it didn't work. It can only be sent to Omnivore by sharing.

**Comment by holton-jiang** [comment]
> Thank you @holton-jiang can you try logging out and then logging back in at https://omnivore.app and see if the issue continues?

Yes, it succeeded, but no-trace mode does not work.

**Comment by holton-jiang** [comment]
> Thank you @holton-jiang can you try logging out and then logging back in at https://omnivore.app and see if the issue continues?

Thinks for your help.

**Comment by jacksonh** [comment]
> @jacksonh I get the same error. Not sure what you mean by logging in through the website. I should log in using the app right?

Can you go to https://omnivore.app in Safari and log in and see if you get the error?

**Comment by eenpadvinder** [comment]
> > @jacksonh I get the same error. Not sure what you mean by logging in through the website. I should log in using the app right?
> 
> Can you go to https://omnivore.app in Safari and log in and see if you get the error?

When I go to the website I can log in without the error. Not sure how that relates to the error I get when saving pages through the app though.

**Comment by jacksonh** [comment]
> > > @jacksonh I get the same error. Not sure what you mean by logging in through the website. I should log in using the app right?
> > 
> > 
> > Can you go to https://omnivore.app in Safari and log in and see if you get the error?
> 
> When I go to the website I can log in without the error. Not sure how that relates to the error I get when saving pages through the app though.

Thanks, where are you getting the error, in the Safari extension or somewhere else?

**Comment by eenpadvinder** [comment]
> > > > @jacksonh I get the same error. Not sure what you mean by logging in through the website. I should log in using the app right?
> > > 
> > > 
> > > Can you go to https://omnivore.app in Safari and log in and see if you get the error?
> > 
> > 
> > When I go to the website I can log in without the error. Not sure how that relates to the error I get when saving pages through the app though.
> 
> Thanks, where are you getting the error, in the Safari extension or somewhere else?

It shows in the extension in the top right corner, just like the screenshot at the top of this issue. I can use the share-extension (the share button and then select Omnivore) without a problem, but the Omnivore-button (that does the scrolling thing) always shows the error

**Comment by jacksonh** [comment]
> > > > > @jacksonh I get the same error. Not sure what you mean by logging in through the website. I should log in using the app right?
> > > > 
> > > > 
> > > > Can you go to https://omnivore.app in Safari and log in and see if you get the error?
> > > 
> > > 
> > > When I go to the website I can log in without the error. Not sure how that relates to the error I get when saving pages through the app though.
> > 
> > 
> > Thanks, where are you getting the error, in the Safari extension or somewhere else?
> 
> It shows in the extension in the top right corner, just like the screenshot at the top of this issue. I can use the share-extension (the share button and then select Omnivore) without a problem, but the Omnivore-button (that does the scrolling thing) always shows the error

thanks, the share extension uses the cookie from omnivore.app, which is why I wanted to verify you are logged in there.

**Comment by jacksonh** [comment]
> > > > > > @jacksonh I get the same error. Not sure what you mean by logging in through the website. I should log in using the app right?
> > > > > 
> > > > > 
> > > > > Can you go to https://omnivore.app in Safari and log in and see if you get the error?
> > > > 
> > > > 
> > > > When I go to the website I can log in without the error. Not sure how that relates to the error I get when saving pages through the app though.
> > > 
> > > 
> > > Thanks, where are you getting the error, in the Safari extension or somewhere else?
> > 
> > 
> > It shows in the extension in the top right corner, just like the screenshot at the top of this issue. I can use the share-extension (the share button and then select Omnivore) without a problem, but the Omnivore-button (that does the scrolling thing) always shows the error
> 
> thanks, the share extension uses the cookie from omnivore.app, which is why I wanted to verify you are logged in there.

Is there a chance you have some security extension enabled so the extension can't access cookies?

**Comment by holton-jiang** [comment]
> @jacksonh I get the same error. Not sure what you mean by logging in through the website. I should log in using the app right?

I know what the reason is, because that's how it is in the case of private browsing.

**Comment by jacksonh** [comment]
Going to close this one out as I think its related to auth and we have a few tickets on better handling auth failures.
