### ISSUE TITLE
YouTube playlist Author name extra text parsed

### ISSUE THREAD

**Issue by Bad3r** [omnivore-app/omnivore#1740]
Notice the Author name:
![image](https://user-images.githubusercontent.com/25513724/215302244-c7cad4cb-f951-4756-a5df-1d62fed4326e.png)
author name value:
```
ClojureTV



  ClojureTV







  •
  135K views • 4 years ago


  
  
  •
```
Steps to reproduce:
1. save a Youtube playlist to Omnivore.App ([Rich Hickey Talks - YouTube](https://www.youtube.com/playlist?app=desktop&list=PLZdCLR02grLrEwKaZv-5QbUzK0zGKOOcr))
2. Notice the Author name value

**Comment by Bad3r** [comment]
Sidenote: the description retrieved appears to be YouTube.com description and not the video description. See screenshot in original post.

**Comment by Bad3r** [comment]
That looks great! :shipit:

**Comment by sywhb** [comment]
Deployed in demo for testing

**Comment by sywhb** [comment]
Works well in demo. We should deploy it in prod

Playlist:
<img width="743" alt="Screenshot 2023-01-31 at 11 22 04 AM" src="https://user-images.githubusercontent.com/12963965/215654931-660e72a8-d48a-4a0c-b310-1159b31dfac4.png">

Video:
<img width="760" alt="Screenshot 2023-01-31 at 11 23 10 AM" src="https://user-images.githubusercontent.com/12963965/215655037-99d510f5-5471-4a60-bba9-ae8a229b0051.png">

**Comment by sywhb** [comment]
Hey @Bad3r, this fix is live. Let me know if you still face the issue

**Comment by Bad3r** [comment]
@sywhb awesome, thank you for the quick fix!  
tested and its working great :shipit:.

BTW, I noticed one weird thing with the playlist I used for my example:  
[https://www.youtube.com/playlist?app=desktop&list=PLZdCLR02grLrEwKaZv-5QbUzK0zGKOOcr](https://www.youtube.com/playlist?app=desktop&list=PLZdCLR02grLrEwKaZv-5QbUzK0zGKOOcr)

notice the thumbnail in your screenshot:  
 

![Screenshot 2023-01-30 at 4 55 25 PM](https://user-images.githubusercontent.com/12963965/215431333-e941082c-a726-49ea-a792-9809181ff80d.png)

This is the same thumbnail I get; strangely, this thumbnail is not used for any of the videos or the playlist.   
I did test with another playlist, and it retrieves the correct thumbnail, so I don't think it's an issue.     
  
\--  
Good to close

**Comment by sywhb** [comment]
@Bad3r great that it works. 👍 

Ahh, I noticed the thumbnail and it is actually from the playlist cover on the Youtube channel.
https://www.youtube.com/@ClojureTV/playlists

<img width="1341" alt="Screenshot 2023-02-02 at 9 11 10 AM" src="https://user-images.githubusercontent.com/12963965/216206751-7f12bce1-ad71-4901-bd95-9a07c4b24af6.png">
