### ISSUE TITLE
No option to delete account?

### ISSUE THREAD

**Issue by sorenpeter** [omnivore-app/omnivore#1742]
Hi,

There doen't seem to be a way to delete ones account on omnivore.app?

I played around with the instapaper-api import and now my account is a mess of old stuff, so I want to either masse delete everything added today or simply whipe my account and start over - but neither seem to options available at the moment?

Bests, sørenpeter

**Comment by jacksonh** [comment]
Hey, sorry we need a proper link to it but you can use: https://omnivore.app/settings/delete-my-account

**Comment by sorenpeter** [comment]
Hey Jack, Thansk for the quick reply. If I delete my account can I then get the same username?

**Comment by jacksonh** [comment]
Yeah you should be able to unless someone happens to snag it in that minute or two between delete and create.

If you'd like you can email me jacksonh@omnivore.app and I might be able to help cleanup your account.

**Comment by jacksonh** [comment]
It'd probably be about 20th a from now though

**Comment by sorenpeter** [comment]
I have send you an email now with my username.

> It'd probably be about 20th a from now though 

20th what? Sorry I don't understand...

**Comment by jacksonh** [comment]
Sorry I think this one got lost in our filters. I'm checking my email and not sure if this was all taken care of. Please reopen if you still need this handled.
