### ISSUE TITLE
Highlight of images

### ISSUE THREAD

**Issue by linjunhe** [omnivore-app/omnivore#1747]
Is it possible to highlight an image and sync it to logseq?

**Comment by timjore** [comment]
This is a really important feature. I'd like to be able to select an image to include it in the highlights/notes that get exported (to Obsidian, in my case). How might we go about adding support for images?

**Comment by thiswillbeyourgithub** [comment]
I too would really love this feature!

**Comment by jacksonh** [comment]
Hello, now that highlights are stored as markdown images should be displayed. The images won't be downloaded so they won't work online but should link to our online cache.

Please let us know if that isn't working for you.

**Comment by thiswillbeyourgithub** [comment]
Great it is working actually. It does not appear to be imported as an image to logseq thought right? I only see the link to the image instead.

Cf https://github.com/omnivore-app/logseq-omnivore/issues/98

**Comment by jacksonh** [comment]
I will close this one for now and we will create another ticket about importing images into Obsidian and Logseq
