### ISSUE TITLE
Publish to F-Droid?

### ISSUE THREAD

**Issue by natrius** [omnivore-app/omnivore#1749]
As an open source app it might be worth thinking about publishing on https://f-droid.org/de/ . Information about it in the docs https://f-droid.org/en/docs/ 

It might even be possible to get it beforehand on https://android.izzysoft.de/repo if you need help or if something is unclear. Izzy is usally really helpfull and awesome at supporting app developers to get their app to f-droid :)

**Comment by satindar** [comment]
@natrius Thanks for opening an issue on this. Someone else had mentioned it a few weeks ago so we planned to look into it. Will try to get our next update (this week hopefully) on there.

**Comment by daviddavo** [comment]
This is a duplicate of #1853

**Comment by natrius** [comment]
Its actually the other way around but i don't care as long as it reaches f-droid at some time :)
