### ISSUE TITLE
Different Capture Results

### ISSUE THREAD

**Issue by StrollStars** [omnivore-app/omnivore#1776]
There are some differences in the view of the web page when different clients capture [the link](https://mp.weixin.qq.com/s/nd2GWMq13Lgf2O9PPJqusg), the difference comparison is as follows:
|content|[extensions](https://chrome.google.com/webstore/detail/omnivore/blkggjdmcfjdbmmmlfcpplkchpeaiiab)|[Android APP](https://play.google.com/store/apps/details?id=app.omnivore.omnivore)|
|----|----|----|
|image|normal|[abnormal](https://github.com/omnivore-app/omnivore/assets/10942225/1c032716-c320-49a8-a3bb-938c3f30c489)|
|text|原创 XX XX 发表于 XX|Original XX XX Posted on XX|
1. Obviously, the display captured by the extension is better, and I hope to fix the capture of the app.
2. The effect obtained through Add Link on the web page is the same as that obtained in the app.
3. Publish time in article fails to capture.

**Comment by jacksonh** [comment]
Thanks, yes this can happen because the extension can grab the actual content of the page vs the Android app which is saving a URL. I think what we need to do here is pass more client headers, like the user language to our `SaveURL` API.

**Comment by StrollStars** [comment]
@jacksonh I try to save via extension on Android([Kiwi Browser](https://play.google.com/store/apps/details?id=com.kiwibrowser.browser)), but the image does not display.

**Comment by StrollStars** [comment]
@jacksonh The issue has been resolved in the latest version of the Android client. Thank you to the developers!
