### ISSUE TITLE
Can metadata add time?

### ISSUE THREAD

**Issue by StrollStars** [omnivore-app/omnivore#1803]
Just like Title and Author.

**Comment by jacksonh** [comment]
@StrollStars do you mean you'd like to edit them? If so, yes I definitely agree.

**Comment by StrollStars** [comment]
@jacksonh I want the metadata of articles synced to Obsidian to include the publication date. Currently, there is only the save date in the metadata, and the value is empty.

**Comment by jacksonh** [comment]
@sywhb we should be pulling saved date into Obsidian, is there a chance it isn't exposed to the template?

**Comment by sywhb** [comment]
@jacksonh this was fixed in the last release. So we could close this one

**Comment by jacksonh** [comment]
Excellent, thanks!
