### ISSUE TITLE
Add API support for `no:label` and `no:highlight` search terms

### ISSUE THREAD

**Issue by edshamis** [omnivore-app/omnivore#1815]
I think it could be a useful option to filter all articles without a lable

**Comment by jacksonh** [comment]
Hey @edshamis yeah i highly agree. These filters are actually all editable but we haven't exposed UI to change them yet.

Which platform do you usually use? iOS, Web, or Android?

**Comment by edshamis** [comment]
Hi! @jacksonh I'm on Android but I use PWA there since the app isn't mature yet + web on PC

**Comment by jacksonh** [comment]
Thanks @edshamis 

Just looking at how we'd implement this, it looks like `no:label` is how GitHub does similar functionality for their issue search.

**Comment by edshamis** [comment]
To me no:label looks just fine

**Comment by edshamis** [comment]
kudos for no:highlight :))

**Comment by jacksonh** [comment]
So despite the filters being editable, unfortunately we don't have the search term for this yet, so its a bit more work to get this in than i initially thought. We can add to the API, and then update the default filters to include this one.

**Comment by sywhb** [comment]
Add the search term to the API #1819
