### ISSUE TITLE
Add API to Add Link from outside

### ISSUE THREAD

**Issue by edshamis** [omnivore-app/omnivore#1820]
Please fix the subject to better reflect what I mean:

I'd like to be able to Add Links for example from Telegram bot or connect other things via IFTTT/Make(Integromat) or directly from cli 

This would make the workflow so flexible and convenient

**Comment by jacksonh** [comment]
Hi @edshamis we just added an API endpoint so you can save URLs like this now: `https://omnivore.app/api/save?url=<the url>`

**Comment by edshamis** [comment]
@jacksonh Great news! Can you please give an example how to use it with curl or httpie including authentication?

**Comment by jacksonh** [comment]
@edshamis yeah, first go to https://omnivore.app/settings/api and generate an API key, then you can make a curl request like this:

```
curl -H 'authorization: <the api token>' "<the url>"
```

For example:

```
curl -H 'authorization: afa24a3e-86a1-4cc7-b2ef-a2d5ebcd6640' "https://omnivore.app/api/save?url=https://jacksonh.org/"
```

**Comment by edshamis** [comment]
@jacksonh wow, works like a charm!
It returns some string: /sr/707b1a53-cdf6-4512-82a5-fa19544cfc1c
Does it mean anything?

**Comment by jacksonh** [comment]
@edshamis yeah that is a redirect URL, if you go to a URL like https://omnivore.app/sr/707b1a53-cdf6-4512-82a5-fa19544cfc1c it will wait until the item is ready and then load it.

**Comment by edshamis** [comment]
@jacksonh cool! Thanks a lot! Appreciate your work

**Comment by jacksonh** [comment]
I guess it probably could return the full `https://omnivore.app` URL, I'll look to see what the standard is
