### ISSUE TITLE
Offline highlights does not sync

### ISSUE THREAD

**Issue by jakemkc** [omnivore-app/omnivore#1824]
Hi,

Thanks for releasing the wonderful Omnivore app, which is a great read it later app and one of the best in the town.

I don't have mobile internet connection. When I read offline article in Omnivore (iOS) while traveling, I add/remove highlighting as usual. However, once my internet connection resumed, the offline edits did not save and sync. The offline edited article was overwritten by its original status in the server.

I wonder is it a bug or a feature of the app?

Best,
Jake

**Comment by jacksonh** [comment]
Hi @jakemkc sorry for the delay in reply. This does sound like a bug. Definitely we are designed to store highlights locally and then sync them when the user next comes online. 

I'm looking into this one.

**Comment by jacksonh** [comment]
I haven't been able to replicate this one. What I have been doing is opening an article on iPhone, putting my phone in airplane mode, adding highlights, going back to the library mode, then going out of airplane mode. After that I am seeing my highlights synced to web. 

@jakemkc is your workflow different from that? The one issue I have is i have to refresh on the web to see my new highlights.

**Comment by jakemkc** [comment]
Thanks for looking into the problem. Somehow starting from late Feb/ early March this problem is gone itself. I just tried omnivore again while commuting in this morning, and it works, so I think problem is fixed!

Best
Jake
