### ISSUE TITLE
Add ability to add labels along with web API SaveUrl

### ISSUE THREAD

**Issue by edshamis** [omnivore-app/omnivore#1836]
When I add an url through API I'd like to be able to attach some labels alongside the same command

**Comment by jacksonh** [comment]
Yeah, we'd like to add this and archive status to all Save operations.

**Comment by sywhb** [comment]
#1812

**Comment by sywhb** [comment]
Hey @edshamis, you are now able to attach labels and define the status of the saved item through `saveUrl` API.

Sample request input:

```
{
  "input": {
    "url": "https://www.straitstimes.com/singapore/property-firm-orangetee-tie-fined-37k-over-data-breach-affecting-more-than-250000-customers-employees",
    "state": "ARCHIVED",
    "labels": {
      "name": "Test"
    },
    "source": "add-link",
    "clientRequestId": "128688ec-7255-4759-b5fb-ee32910f232a"
  }
}
```

For the details, you could refer to our latest graphQL schema

**Comment by jacksonh** [comment]
oh we probably need to add this to `packages/web/pages/api/save.tsx` also, which calls that API

**Comment by sywhb** [comment]
@jacksonh I added this to `packages/web/pages/api/save.tsx` here: #2084

**Comment by thiswillbeyourgithub** [comment]
Can we have examples showing how to use curl or python requests to handle the API?

**Comment by jacksonh** [comment]
Will update the docs site but here is a quick example:

```
curl -H 'authorization: <an API key>' "https://omnivore.app/api/save?url=https://jacksonh.org&labels=Singapore&labels=Asia"
```

that would save the URL https://jacksonh.org with the two labels: Singapore and Asia
