### ISSUE TITLE
Date_published is a bit late

### ISSUE THREAD

**Issue by StrollStars** [omnivore-app/omnivore#1837]
The date_published of saved article is dated one day after the date_published of original.
![2023-02-22_215225](https://user-images.githubusercontent.com/10942225/220641720-b3c7f591-8f77-4e9d-bef9-d62b8a05ac11.png)
![2023-02-22_215139](https://user-images.githubusercontent.com/10942225/220641745-13500e83-1f10-4dc2-91b2-002bc0b20b51.png)

**Comment by jacksonh** [comment]
I wonder if this is the UTC date, not your local time (assuming you are in Asia time, so sometimes ahead of UTC by a day). We should format in local time in the reader for sure

**Comment by StrollStars** [comment]
@jacksonh I find that the website in the screenshot uses the local time. Most of our websites here use this time. The local time is UTC+8, and the difference is exactly 8 hours, so can it be adjusted?

**Comment by sywhb** [comment]
Hey @StrollStars, this has been fixed and you should see the published and saved date in your local timezone now (maybe need to clear cache)

**Comment by StrollStars** [comment]
@sywhb ,thank you for responding to me.
I checked the existing articles and found that the dates of the most recent articles have been changed to local dates, but the dates of the earlier articles are still UTC dates.
I bookmarked an article through the Chrome extension, and found that it is still a UTC date.
BTW, I have cleared the cache.

**Comment by sywhb** [comment]
#1969

**Comment by jacksonh** [comment]
Hey @StrollStars except in extreme cases we don't override historical data when making updates as we don't want to "mess" with people's libraries, so this change will only take effect on newly saved items.

**Comment by StrollStars** [comment]
@jacksonh Thank you for your reply, I will manually modify the saved articles first, hoping to fix this problem as soon as possible.

**Comment by StrollStars** [comment]
@jacksonh @sywhb The latest testing has discovered that the issue of the publishing date being eight hours late on the Android client has been resolved, but it still persists on the Chrome extension. However, the problems of duplicated titles and missing publishing dates and times continue to exist on both the Android client and the Chrome extension.

**Comment by sywhb** [comment]
Hey @StrollStars , sorry for the delay.

We have fixed "the problems of duplicated titles and missing publishing dates and times" in the backend so you can now get them right on your "Android client and Chrome extension".

For "the issue of the publishing date being eight hours late" on the Chrome extension, although we have fixed it, we are still waiting for the new release of the extension.

I shall let you know once it's released. Thanks for the patience!

**Comment by StrollStars** [comment]
@sywhb I feel that there are still some issues with favoriting articles on the Android client, and now the problem is that the time has been changed to an earlier time.
![1](https://github.com/omnivore-app/omnivore/assets/10942225/e4ce3d82-d641-4dd2-b4ca-74970502db7e)
![2](https://github.com/omnivore-app/omnivore/assets/10942225/538ab010-bef5-4481-bb3c-a376bec19e42)

**Comment by sywhb** [comment]
@StrollStars oh my, I think the time is in UTC which is based on the server timezone.

Let me think about it

**Comment by sywhb** [comment]
@StrollStars Yeah, there is a variable `currentTime` which is a timestamp value but it doesn't have the author's locale information.

I will try to find the locale info in the article

**Comment by StrollStars** [comment]
@sywhb Thank you for your hard work, and I look forward to resolving this issue as soon as possible.

**Comment by StrollStars** [comment]
@sywhb I've tested it and there's no problem, which is great. Thank you to the developers.
