### ISSUE TITLE
Android app is slow to open articles

### ISSUE THREAD

**Issue by StrollStars** [omnivore-app/omnivore#1843]
When I open a bookmarked article on the Android app, it always takes a few seconds to open.

**Comment by jacksonh** [comment]
I think this is improved quite a bit now. I'll post an update to Play store later today and validate.

**Comment by StrollStars** [comment]
@jacksonh Just tested and the issue still persists.

**Comment by StrollStars** [comment]
@jacksonh This issue still exists in the latest version of the Android client.

**Comment by StrollStars** [comment]
@jacksonh This problem still exists in the latest version of the Android client.

**Comment by jacksonh** [comment]
Thank you!

**Comment by jacksonh** [comment]
Hey I think this is improved quite a bit in the latest release, please let me know if you still have issues.
