### ISSUE TITLE
Problems with title and time fetching

### ISSUE THREAD

**Issue by StrollStars** [omnivore-app/omnivore#1901]
1. Some titles can be obtained, but some cannot be obtained. For articles without a title, the word "original" will be missing at the same time, as shown in the red box in the following figure.
![有](https://user-images.githubusercontent.com/10942225/224467168-c287edbf-cb66-4774-a59f-53a9a55308cf.png)
![无](https://user-images.githubusercontent.com/10942225/224467170-e908cd87-3981-43c6-b574-bd3f8a209c80.png)

2. Publication date and time are missing from the article (not metadata). Just like the red box in the picture below.
![原](https://user-images.githubusercontent.com/10942225/224467323-d9c00f74-4ed2-4bdb-8cb7-0022ede8502b.png)
![存](https://user-images.githubusercontent.com/10942225/224467363-60717716-f306-4929-bead-6b0c885e74ff.png)

**Comment by sywhb** [comment]
We have been working on this in #1837

**Comment by StrollStars** [comment]
@sywhb OK, I closed it.

**Comment by sywhb** [comment]
Hey @jacksonh, do we remove the title and published date on purpose when we run readability?

**Comment by sywhb** [comment]
Thanks @jacksonh. I'm asking because I found this code in `readability` which I'm not sure if it is intended
```
        // Check to see if this node is a byline or published, and remove it if it is.
        if (this._checkByline(node, matchString) || this._checkPublishedDate(node, matchString)) {
          node = this._removeAndGetNext(node);
          continue;
        }
```

**Comment by sywhb** [comment]
This code tries to match the date string and remove it if it matches

**Comment by sywhb** [comment]
I agree with @jacksonh that we should only remove it where it is duplicated like this one

<img width="565" alt="Screenshot 2023-04-03 at 5 54 14 PM" src="https://user-images.githubusercontent.com/12963965/229476134-bfb0b522-4a2e-403f-8864-a131f6e2ad04.png">

**Comment by StrollStars** [comment]
> we should only remove it where it is duplicated like this one
Is this problem fixed?

**Comment by jacksonh** [comment]
@sywhb can clarify but I think it is fixed in some cases, but we still need to roll out extension updates for it to be handled in all cases.

**Comment by jacksonh** [comment]
Discussed in person. Our plan is to add a handler for wexin.qq.com that will replace this classname: `rich_media_meta_list`
 with `_omnivore_rich_media_meta_list`.

That way this entire node block will be preserved:

```
<div id="meta_content" class="rich_media_meta_list">
                                      <span id="copyright_logo" class="wx_tap_link js_wx_tap_highlight rich_media_meta icon_appmsg_tag appmsg_title_tag weui-wa-hotarea">Original</span>
                                                      <span class="rich_media_meta rich_media_meta_text">
                                                                                    <span role="link" tabindex="0" id="js_author_name" class="wx_tap_link js_wx_tap_highlight weui-wa-hotarea" datarewardsn="" datatimestamp="" datacanreward="0">赵传文</span>
                                                                            </span>
                                      
                                                                <span class="rich_media_meta rich_media_meta_nickname" id="profileBt">
              <a href="javascript:void(0);" class="wx_tap_link js_wx_tap_highlight weui-wa-hotarea" id="js_name">
                维客笔记              </a>
              <div id="js_profile_qrcode" aria-hidden="true" class="profile_container" style="display:none;">
                <div class="profile_inner">
                  <strong class="profile_nickname">维客笔记</strong>
                  <img class="profile_avatar" id="js_profile_qrcode_img" src="" alt="">

                  <p class="profile_meta">
                  <label class="profile_meta_label">Weixin ID</label>
                  <span class="profile_meta_value">slash1037</span>
                  </p>

                  <p class="profile_meta">
                  <label class="profile_meta_label">About Feature</label>
                  <span class="profile_meta_value">因为热爱，所以分享！效率工具/科研绘图/数据处理/实用干货......</span>
                  </p>
                </div>
                <span class="profile_arrow_wrp" id="js_profile_arrow_wrp">
                  <i class="profile_arrow arrow_out"></i>
                  <i class="profile_arrow arrow_in"></i>
                </span>
              </div>
            </span>
            <em id="publish_time" class="rich_media_meta rich_media_meta_text">2023-01-10 07:07</em>
            <em id="js_ip_wording_wrp" class="rich_media_meta rich_media_meta_text" role="option" style="display: inline-block;">Posted on <span id="js_ip_wording">湖北</span></em>

          </div>
          ```

**Comment by StrollStars** [comment]
@jacksonh @sywhb "The issue has been resolved in the latest version of the Android client. Thank you to the developers!"
