### ISSUE TITLE
Allow scoping searches to `site:`

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#1907]
Ideally we should allow both domain and sitename in this scope, such as:

`site:cnn.com` 
`site:CNN` (the siteName returned by their metadata)

**Comment by sywhb** [comment]
<img width="411" alt="Screenshot 2023-03-14 at 6 28 43 PM" src="https://user-images.githubusercontent.com/12963965/224972563-0405d840-d8c0-49cf-aeb6-3c4be408413b.png">
<img width="446" alt="Screenshot 2023-03-14 at 6 28 37 PM" src="https://user-images.githubusercontent.com/12963965/224972589-931eccfe-356d-4a7e-974f-3d4fc002c3c9.png">
<img width="737" alt="Screenshot 2023-03-14 at 6 28 28 PM" src="https://user-images.githubusercontent.com/12963965/224972596-04d624b9-6903-4d14-abe3-52d6bdb66c72.png">
<img width="731" alt="Screenshot 2023-03-14 at 6 28 21 PM" src="https://user-images.githubusercontent.com/12963965/224972604-2e0803cc-5cea-42e2-aeb5-6b28c165447c.png">

Some samples from my local machine

**Comment by sywhb** [comment]
<img width="807" alt="Screenshot 2023-03-15 at 7 59 30 PM" src="https://user-images.githubusercontent.com/12963965/225302797-c15299e7-a7ff-44b0-98c0-4f9d13ed12a2.png">

Chinese in the site name

**Comment by jacksonh** [comment]
that is fantastic. Will be really useful when combined with Saved Searches

**Comment by sywhb** [comment]
Speaking of saved searches, we have the category API available if we want to add that to the UI

**Comment by jacksonh** [comment]
Yeah once we have a more scalable system for forms we should add it. Getting close on that stuff.
