### ISSUE TITLE
Allow saving HTML with highlights

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#1908]
When we save a highlight we should be able to include an optional html attribute, the backend shouldn't need to do any special handling on this. We should also expose it as part of the `Highlight` response type.

**Comment by sywhb** [comment]
Should we make the `html` searchable or it is just used to display?

**Comment by jacksonh** [comment]
@sywhb i think it would just be used for presentation, the main use case I can think of is it there is useful markup like a list or image that the user would want embedded, maybe in the logseq plugin (I know this could be hard) or just display in Omnivore highlight cards.

**Comment by jacksonh** [comment]
I'll move this over to a web task now
