### ISSUE TITLE
Subtitle bullet in article appears above popup menus

### ISSUE THREAD

**Issue by xplosionmind** [omnivore-app/omnivore#1913]
Using Firefox 110.0.1, both on macOS and on Linux (Ubuntu)

![Screenshot from 2023-03-14 06-28-54](https://user-images.githubusercontent.com/42862428/224905431-7099cf33-b75d-4290-8447-1ab98b570da2.png)

**Comment by jacksonh** [comment]
hah thank you!

**Comment by jacksonh** [comment]
Not seeing on `109.0.1 (64-bit)` -- updating to test `110`

**Comment by jacksonh** [comment]
Will test out on linux tonight, I'm not able to replicate now, but i have seen something similar in the past where z-indexes were not setup properly.

**Comment by jacksonh** [comment]
Haven't been able to reproduce this one yet. Going to try a different device.

**Comment by jacksonh** [comment]
Finally figured this one out.
