### ISSUE TITLE
adapt size to smaller windows 

### ISSUE THREAD

**Issue by Bad3r** [omnivore-app/omnivore#1950]
I enjoy using Omnivore on my 2k monitor, positioning it in the corner, and running it in a browser window with dimensions 1266 x 690. However, at this specific size, Omnivore does not resize properly, causing a few UI issues:

- The corners of the cards appear cropped.
- The left sidebar is disproportionately wide.
- The gap between the cards is disproportionately wide.
- The space at the top is too wide.

Screenshot:
![2023-03-26_13-49](https://user-images.githubusercontent.com/25513724/227794697-782cf0f4-c978-45ca-a371-f23c366fa58b.png)

Compared to Raindrop, which has a similar UI at the same size:
![2023-03-26_13-51](https://user-images.githubusercontent.com/25513724/227794723-9e9d3ab0-e888-454d-82e6-affbad21bfac.png)

**Comment by Bad3r** [comment]
Thank you for considering fixing the issue. I am unsure if I am the only one that uses Omnivore at this size, but a 2k monitor size is common.

**Comment by jacksonh** [comment]
@Bad3r no i think its quite common, i was using my Windows laptop yesterday for some testing and it happened to be exactly the same size. I'm playing with a few options, both breaking the cards down to less columns earlier, and shrinking the left menu a tiny bit.

In the meantime, the list view seems to work a lot better.

**Comment by Bad3r** [comment]
I have noticed that the UI now fits as expected, thank you!
Feel free to close the issue :D

**Comment by Bad3r** [comment]
on a second look.. I see now that there is a horizontal scrollbar 
![image](https://user-images.githubusercontent.com/25513724/229263890-8974db64-05fd-4312-a2dd-30077c18d78b.png)

**Comment by Bad3r** [comment]
could the gaps on the right, left, or between the cards be slightly shrunk to make everything fit better?

**Comment by jacksonh** [comment]
Yeah, there are a few issues here. I think the main one is on windows we shouldn't be showing that scrollbar at the bottom. It would be nice if the card gap was a little more flexible, we do constrain the cards to a container so we can keep them centred, but it seems like there is more space than there should be on the left, and ideally the gab could grow instead of the margin spacing.

**Comment by markpinero** [comment]
> Yeah, there are a few issues here. I think the main one is on windows we shouldn't be showing that scrollbar at the bottom. It would be nice if the card gap was a little more flexible, we do constrain the cards to a container so we can keep them centred, but it seems like there is more space than there should be on the left, and ideally the gab could grow instead of the margin spacing.

I've run into this issue elsewhere so I can make a PR with updates when I can.
