### ISSUE TITLE
Feature Request: allow wildcard search

### ISSUE THREAD

**Issue by dbobak** [omnivore-app/omnivore#1951]
In many languages (inflected languages), the basic form of a word is supplemented with suffixes. Which makes a search without wildcards a tedious one. For example, when I search for texts about Ukraine, in Polish I have to search for the following forms: `Ukraina`, `Ukrainy`, `Ukrainie`, `Ukraina`, `Ukraino`. A wildcard search would allow the use of a single expression, e.g. Ukrain* or Ukrain%.

Would it be possible to add such a function to Omnivore?

**Comment by jacksonh** [comment]
Not sure what options elastic gives us here.

**Comment by sywhb** [comment]
@jacksonh Elasticsearch has `wildcard` query and the it looks like this:
```
GET /_search
{
  "query": {
    "wildcard": {
      "content": {
        "value": "Ukrain*",
        "boost": 1.0,
        "rewrite": "constant_score"
      }
    }
  }
}
```
Two operators:
- ?, which matches any single character
- *, which can match zero or more characters, including an empty one

But we use `multi_match` query now so we might need to detect `*` or `?` in the filter string and add `wildcard` query if there is such operator

**Comment by sywhb** [comment]
Hey @dbobak, we have implemented this feature and we use `*` for wildcard search.

Could you please try and let us know if it suits your need? Thank you

**Comment by dbobak** [comment]
@sywhb, I'm not sure if I'm using it as intended, but it does not work for me. I was trying different combinations of of expressions with `*`, but none of it works.

![image](https://user-images.githubusercontent.com/6285546/234384768-2421100a-5da9-4fae-9c78-a1032f403ee5.png)

![image](https://user-images.githubusercontent.com/6285546/234384897-82398ff0-e85d-478c-a139-292d43e6d090.png)

**Comment by sywhb** [comment]
Sorry @dbobak , we reverted this feature yesterday because there was a regression bug but we have fixed it now and could you please try again?

**Comment by dbobak** [comment]
@sywhb, now it works perfectly! Thank you!
