### ISSUE TITLE
Feature Request: Support Reading/Highlighting in EPUBs

### ISSUE THREAD

**Issue by pedersen** [omnivore-app/omnivore#1955]
I'm planning on purchasing a Supernote. I'd love for my highlights in the books I read (which I focus on keeping as epub) to be available after a sync in LogSeq and Obsidian.

**Comment by pedersen** [comment]
That's still a huge step up, so thank you!

**Comment by doKill** [comment]
yes pls add epub to iOS i think it's a big feature for me，i have tried share my iCloud epub file to Omn but showing unsupported format.

**Comment by doKill** [comment]
> yes pls add epub to iOS i think it's a big feature for me，i have tried share my iCloud epub file to Omn but showing unsupported format.

i don't know if this repo could be helpful

**Comment by doKill** [comment]
> yes pls add epub to iOS i think it's a big feature for me，i have tried share my iCloud epub file to Omn but showing unsupported format.

i don't know if this repo could be helpful
https://github.com/pacexy/flow

**Comment by jacksonh** [comment]
Going to add a few subtasks for this here:

- [ ] https://github.com/omnivore-app/omnivore/issues/2006

**Comment by DngrslySkeptical** [comment]
I’m really looking forward to ePub support. One thing that I think is almost necessary for good epub support is a way to access the TOC. Raindrop has ePub support but not support for the TOC. It really hampers its usefulness.
I’d love to see TOC support for PDF’s and webpages too (like Reader and Cubox), but it’s an even bigger deal for ePub.

if you guys can add those features, you’ve got an app ton the way to competing with Readwise Reader.

**Comment by mrapino** [comment]
Hey there, I just want to check in to see if this is a feature being worked on, or just talked about at this point in time?

Thanks!

**Comment by jacksonh** [comment]
@mrapino we did some experiments to gauge the work effort but haven't done much since. We'd still like to do this, but have had some higher priority issues like RSS in front of it.

**Comment by domonnss** [comment]
hello @jacksonh ,I want to know how the plan is going.I really neet the epub import function.
Thanks.

**Comment by jtrv** [comment]
I'm very interested in seeing this feature come to fruition! This should help reach a quick MVP on the frontend: https://github.com/gerhardsletten/react-reader.

Then it narrows down the work to backend logic, an epub and pdf filter and gallery/card views (cover, title, author), and [search-indexing](https://github.com/gerhardsletten/react-reader/issues/84#issuecomment-804744867).

**Comment by nickwild-999** [comment]
+z1 for me too please

**Comment by fernando4893204** [comment]
with epub reading and highlighting omnivore will be the perfect reading app

**Comment by 42Craft** [comment]
Please!
