### ISSUE TITLE
newsletters from Bloomberg law are not being detected as articles.

### ISSUE THREAD

**Issue by tyk1203** [omnivore-app/omnivore#1961]
I have marked them as articles but next time it still not being detected as articles.
Is it possible to set up automatic filters to categorize all emails from the same email address as articles?

**Comment by jacksonh** [comment]
Hey @tyk1203 right now we have to manually update our classifier. We are working on a more permanent solution for this that would improve the classification though.

**Comment by tyk1203** [comment]
> Hey @tyk1203 right now we have to manually update our classifier. We are working on a more permanent solution for this that would improve the classification though.
Thank you very much for your diligent efforts!

**Comment by tyk1203** [comment]
Thank you very much for your diligent efforts!

**Comment by jacksonh** [comment]
Assigning this one to track with the newsletter handler changes.

**Comment by sywhb** [comment]
Fixed in #1994
