### ISSUE TITLE
Text to Speech Research - Android

### ISSUE THREAD

**Issue by satindar** [omnivore-app/omnivore#1974]
Look into text to speech for Android and create a plan to implement it.

**Comment by micmalti** [comment]
Are there any plans to implement such functionality?

**Comment by jacksonh** [comment]
Yes we will definitely add it to Android, just a very small team

**Comment by stefanosansone** [comment]
Looking into this now

**Comment by justeepin** [comment]
Any updates? This is the only thing keeping me using Pocket. I don't use text-to-speech a lot but it's nice to have, especially if I'm going on a walk.
