### ISSUE TITLE
Improve Dark theme support on Android

### ISSUE THREAD

**Issue by eightHundreds** [omnivore-app/omnivore#1978]
在Android上,默认使用系统主题, 我的系统设置中用黑暗模式, omnivore的黑暗模式效果不好, 所以希望支持手动切换到明亮模式

**Comment by jacksonh** [comment]
google trasnlated:

> On Android, the system theme is used by default. I use dark mode in my system settings. The dark mode of omnivore does not work well, so I hope to support manual switching to bright mode

**Comment by sywhb** [comment]
> so I hope to support manual switching to bright mode

A small issue with the translation. It should be `light mode`

**Comment by jacksonh** [comment]
I think this is much better now
