### ISSUE TITLE
Landingpage image 4 missing

### ISSUE THREAD

**Issue by Lionstiger** [omnivore-app/omnivore#1995]
The 4th image on the landing page seems to be missing.
The location (https://omnivore.app/static/landing/landingPage-04@1x.png) returns a 404 error.

The file is present in the code base but without the scaling modifier here:
https://github.com/omnivore-app/omnivore/blob/main/packages/web/public/static/landing/landingPage-04.png

**Comment by jacksonh** [comment]
https://github.com/omnivore-app/omnivore/pull/2004

**Comment by jacksonh** [comment]
Thank you for reporting this one!
