### ISSUE TITLE
Suggest to support modifying the source link

### ISSUE THREAD

**Issue by StrollStars** [omnivore-app/omnivore#1996]
In case the original link becomes invalid, it is recommended to modify the original link.

**Comment by jacksonh** [comment]
What I am thinking is we might want an API that exposes all attributes, and then we can use a basic table/form editor for this page as its a more advanced tool.

**Comment by StrollStars** [comment]
> really every attribute should be editable. One issue is if there are conflicts, as we do require URLs to be unique internally.

I think so too, but why is there a conflict?

**Comment by jacksonh** [comment]
@StrollStars oh if you changed the URL to one that you also have already saved. So you have one page with the URL omnivore.app/xyz and then you try to change the URL to omnivore.app/xyz we would have to fail the operation because you can't have two pages with the same URL in our database.

**Comment by StrollStars** [comment]
@jacksonh I think there is no problem, when repeated, the save fails and prompts.

**Comment by StrollStars** [comment]
I feel this suggestion is unreasonable, so close it.
