### ISSUE TITLE
Detect color mode change on iOS sends wrong event

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#1999]
- With the new themes we need to send Black not Dark on color change to dark mode if the user has the system theme selected.

**Comment by satindar** [comment]
Oh this probably explains the bug I'm having in Android themes!

**Comment by jacksonh** [comment]
Oh it could be, depending on whether you updated your bundle. I introduced a new theme just for iOS called "Black" since our web "Dark" theme doesn't use a full back background.

**Comment by jacksonh** [comment]
Fixed.
