### ISSUE TITLE
[Firefox extension] 'You are not logged in' when logged in to Onminvore on a Firefox Multi-Account Container tab

### ISSUE THREAD

**Issue by stoic-cat** [omnivore-app/omnivore#2000]
## Description
Trying to save an article when already logged in to Omnivore in a [firefox mult-account container](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers) tab results in a confusing 'You are not logged in' message. 

## Reproduction steps
1. Log in to Omnivore in any firefox container tab
2. Click on Omnivore extension
3. Error message shows up

## Screenshots
![Screenshot from 2023-04-07 13-45-40](https://user-images.githubusercontent.com/109066175/230549056-fab4aefc-734f-49dd-b156-c2df1bd78f7e.png)

## Solutions/Workarounds
The issue here is that I was not logged in to Omnivore in a non container tab and Omnivore probably has problems trying to read cookies of containers. There are 2 ways I can currently think of:
- Log in to Omnivore on the default tab. - I prefer not to do this as I am using Firefox containers to segregate my cookies and browsing activity from one another.
- Allow configuration of credentials via extension preferences, similar to how Wallabag's Firefox extension authenticates to the backend. - This also allows us a place to specify a different endpoint for those who want to self host https://github.com/omnivore-app/omnivore/issues/25

Thanks!

**Comment by jacksonh** [comment]
Thanks, allowing users to paste in an API key is a good idea. I had been wondering about a solution to this issue.

**Comment by thelazyoxymoron** [comment]
+1

We can take a reference from wallabag: store the API token and adding a key in extension options to renew the token periodically.

**Comment by jacksonh** [comment]
Fix here, not published yet, need to do a bit more testing with other features like PDF handling: https://github.com/omnivore-app/omnivore/pull/2210

**Comment by jacksonh** [comment]
Submitted to the Firefox extension store.

**Comment by jacksonh** [comment]
ok, this is available as `2.0.4` in the add-ons store. Here is a quick demo: 

https://www.loom.com/share/8d47fecd6454431b96e074dbea2fd8a6
