### ISSUE TITLE
plugin/firefox: invisible text w/ dark theme

### ISSUE THREAD

**Issue by Bad3r** [omnivore-app/omnivore#2003]
The popup menu seems to not respect Firefox's dark theme; the input text color gets converted to white because Firefox is in dark mode. The Omnivore background is still white, resulting in an invisible text when editing the title, adding labels, etc.
![image](https://user-images.githubusercontent.com/25513724/230759190-daf2b367-a773-4c51-a717-03d0c51bad69.png)
![image](https://user-images.githubusercontent.com/25513724/230759217-f7a043e0-b770-48c8-9e41-9b6a16bdb58a.png)

* might be a Linux only issue; testing needed.

**Comment by jacksonh** [comment]
Thanks, likely some CSS we need to set here

**Comment by jacksonh** [comment]
Should be fixed now
