### ISSUE TITLE
"Edit Labels" button not working for PDF

### ISSUE THREAD

**Issue by sywhb** [omnivore-app/omnivore#2012]
<img width="380" alt="Screenshot 2023-04-10 at 4 05 24 PM" src="https://user-images.githubusercontent.com/12963965/230856955-6d8cfde9-8159-423c-9a87-bb81e3be7d78.png">

It doesn't respond when the button is clicked

Only for PDF

**Comment by jacksonh** [comment]
@sywhb you mean not working for non-PDF, right?

**Comment by sywhb** [comment]
> @sywhb you mean not working for non-PDF, right?

@jacksonh I meant for PDF. We don't have the "Edit Labels" button for non-PDF

**Comment by jacksonh** [comment]
oh, on smaller screens it will show up for Web. I think I have fixed for both now.

**Comment by sywhb** [comment]
For instance

<img width="1727" alt="Screenshot 2023-04-10 at 6 55 24 PM" src="https://user-images.githubusercontent.com/12963965/230888827-3f33a564-cc86-406c-864b-5e451f41b361.png">

**Comment by sywhb** [comment]
Thanks. I just tested and close this issue now
