### ISSUE TITLE
Feature Request: Bionic Reading

### ISSUE THREAD

**Issue by david-vaclavek** [omnivore-app/omnivore#2019]
Hello. Any plans on implementing the [Bionic Reading](https://bionic-reading.com) into Omnivore (at least the iOS app)?

Thanks for clarifications.

**Comment by jacksonh** [comment]
Hello! I had looked into it once before but it seemed like they weren't quite ready for licensing. I suspect if we did add it, it would need to be a paid feature as there is a licensing cost involved. I will look into this some more.

**Comment by david-vaclavek** [comment]
Thank you for the answer.

It's pretty much possible that it would need to be a paid feature.
I think contacting their [Sales](https://bionic-reading.com/br-for-suppliers/) and asking for further details would be the best now.

I currently use [Reeder 5](https://reederapp.com), which offers the Bionic Reading feature.
And as it really helps me to concentrate on the content, I'm sure I would mind paying for the "Omnivore Pro" or something like that :)

Thanks for considering at least.

**Comment by jacksonh** [comment]
Yeah I will definitely reach out to them. I have heard its quite helpful for some people.

**Comment by thiswillbeyourgithub** [comment]
For anyone interested, there is a bionic reading addon on logseq and there is a font called sans forgetica that might be of interest to people in this issue.

**Comment by BetaPictoris** [comment]
Just popping in to see if there was an update on this feature.  It would be a very nice QoL addition.
