### ISSUE TITLE
Feed/rss support

### ISSUE THREAD

**Issue by avelino** [omnivore-app/omnivore#2029]
Bring news (blogpost) automatically from pre-registered feed

**Comment by daviddavo** [comment]
In the meantime, I've been using an RSS to e-mail service as a workaround

**Comment by I7T5** [comment]
UI/UX and RSS are my only concerns for moving from NetNewsWire.

**Comment by thisisjasonmurphy** [comment]
Being able to collate newspapers is a major advantage for me over Readwise Reader at the moment. Integrating RSS would seal the deal.

**Comment by cs-mshah** [comment]
An RSS integration would make this a killer reading app.

**Comment by ThinkSalat** [comment]
Would bring omnivore one step closer to feature parity with Reader

**Comment by kkiani** [comment]
bump!

**Comment by jacksonh** [comment]
Starting testing on this one soon!

**Comment by FetchFast** [comment]
Has it been removed recently? I added 2 RSS feeds. Now I want to remove one, but can't find it anywhere in the interface

**Comment by davidrsim-p** [comment]
> Has it been removed recently? I added 2 RSS feeds. Now I want to remove one, but can't find it anywhere in the interface

Just in case anyone else is looking: https://omnivore.app/settings/feeds

**Comment by ugurbolat** [comment]
Would be cool to have an import functionality from OPML files :)

**Comment by cori** [comment]
> Would be cool to have an import functionality from OPML files :)

c.f. https://github.com/omnivore-app/omnivore/issues/2870

**Comment by anarcat** [comment]
this seems to have been implemented in https://omnivore.app/settings/feeds ?

**Comment by daviddavo** [comment]
Yeah this issue should be closed @sywhb
