### ISSUE TITLE
The z-index of edit labels modal is too low

### ISSUE THREAD

**Issue by sywhb** [omnivore-app/omnivore#2034]
Some article text can be seen in the "Edit Labels" modal in the reader

<img width="451" alt="Screenshot 2023-04-13 at 10 29 53 AM" src="https://user-images.githubusercontent.com/12963965/231633082-1d0cfe73-0552-46fb-b024-69a9e951f5ec.png">

**Comment by jacksonh** [comment]
Thanks, someone had reported something similar before but I couldn't replicate. Is this from a wikipedia article? I wonder if some formatting is copied over

**Comment by sywhb** [comment]
@jacksonh yeah, and it doesn't have to be a Wikipedia article. You can see the "dot" in any article and that dot comes from the separator between the author and "See Original"

<img width="436" alt="Screenshot 2023-04-13 at 10 37 48 AM" src="https://user-images.githubusercontent.com/12963965/231633787-b6a5309e-4708-4e45-a60b-f5813bb00325.png">

<img width="464" alt="Screenshot 2023-04-13 at 10 38 31 AM" src="https://user-images.githubusercontent.com/12963965/231633797-9badc4dc-007b-49b8-a5c8-fa548655a5a3.png">

**Comment by jacksonh** [comment]
Strangely it never happens for me. This is Chrome?

**Comment by sywhb** [comment]
> Strangely it never happens for me. This is Chrome?

In any browser. You just need to have the "dot" underneath the "Update Labels" modal

**Comment by sywhb** [comment]
Oh, don't use keyboard shortcut @jacksonh

**Comment by jacksonh** [comment]
aha yes, i just discovered that its because I've been testing with the shortcut. Strange that it makes a difference.

**Comment by jacksonh** [comment]
Don't quite understand why, but this happens when we have `<span style={{ position: 'relative', bottom: 1 }}>`

**Comment by jacksonh** [comment]
Linking these two: https://github.com/omnivore-app/omnivore/issues/1913

**Comment by jacksonh** [comment]
Fixed on demo now.
