### ISSUE TITLE
pocket integration: Cannot POST `/api/integration/pocket/auth`

### ISSUE THREAD

**Issue by avelino** [omnivore-app/omnivore#2050]
POST `https://api-prod.omnivore.app/api/integration/pocket/auth`
<img width="542" alt="Screenshot 2023-04-14 at 13 41 26" src="https://user-images.githubusercontent.com/31996/232105508-7b5a8ebf-b646-4613-852f-2af75fee1b76.png">

**Comment by jacksonh** [comment]
Sorry this button wasn't supposed to be visible yet. We are just doing internal testing on this feature now.  Button should disappear shortly.

**Comment by jacksonh** [comment]
OK, button is hidden but hopefully will be back later this week.

**Comment by daviddavo** [comment]
Two weeks have passed. Are there any beta versions of this feature?

**Comment by daviddavo** [comment]
I'm trying to use the following Python code to upload my Pocket export file:

```python
from gql import gql, Client
from gql.transport.requests import RequestsHTTPTransport

# Select your transport with a defined url endpoint
transport = RequestsHTTPTransport(
    url=OMNIVORE_API_URL,
    headers = {
        'Authorization': OMNIVORE_API_KEY,
    }
)

# Create a GraphQL client using the defined transport
client = Client(transport=transport, fetch_schema_from_transport=False)

# Provide a GraphQL query
mutation = gql(
"""
mutation($file: Upload!) {
    uploadImportFile (file: $file, type: POCKET, contentType: "text/html") {
        errorCodes
    }
}
"""
)

# Execute the query on the transport
with open('ril_export.html', 'rb') as f:
    params = {"file": f}

    result = client.execute(mutation, variable_values=params, upload_files=True)
    print(result)
```

But it raises a TransportQueryError

`TransportQueryError: {'message': 'Unexpected server error'}`

**Comment by daviddavo** [comment]
I ended up creating a [Jupyter Notebook](https://github.com/daviddavo/pocket2omnivore/blob/main/pocket2omnivore.ipynb). I share it here in case anyone finds it useful.

**Comment by jacksonh** [comment]
I think this can be closed now.
