### ISSUE TITLE
Issue with Save to Omnivore menu on iOS 

### ISSUE THREAD

**Issue by josemas79** [omnivore-app/omnivore#2073]
I don't know if it has been reported before (at least I can't find it here), but the text "generic" appears in the labels of several buttons in this menu. Screenshot attached, thanks!
![Foto 18-4-23, 8 16 47](https://user-images.githubusercontent.com/101247622/232694229-2cf045bc-f585-44ce-a54e-f16772ed2690.jpg)

**Comment by jacksonh** [comment]
@josemas79 thank you, i assume this is with Test Flight build?

**Comment by jacksonh** [comment]
@josemas79 can i also ask what language your device is set to?

**Comment by josemas79** [comment]
Nope, normal download from App Store. My iPhone is set to Spanish

**Comment by jacksonh** [comment]
aha, thank you. I expect this is an issue just for Spanish as that was included as a default language. Fixing now. Thank you very much for reporting!

**Comment by josemas79** [comment]
It makes a lot of sense! Thank you so much for the quick anwser :)

**Comment by jacksonh** [comment]
Fix https://github.com/omnivore-app/omnivore/pull/2075 -- working on uploading a new build now.

**Comment by jacksonh** [comment]
Fix is in TestFlight now: https://testflight.apple.com/join/BRGk9QCF probably a couple days before it hits the AppStore, will leave this open until then.

**Comment by josemas79** [comment]
Thank you! Now it works perfectly! 
![Foto 18-4-23, 9 47 09](https://user-images.githubusercontent.com/101247622/232710674-c8fad8a9-ad33-4dc5-9689-ae3332e3b2bb.jpg)
