### ISSUE TITLE
Refreshing library after archiving while in filter

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#2080]
Steps to reproduce:

1. On the web select a Subscription from the side menu
2. On a library item open the menu and pick archive
3. Refresh the browser
4. Notice the item re-appears

**Comment by jacksonh** [comment]
Another example of this same issue:

1. From the library click on an article
2. Add a label to a page
3. Press back, notice the label is not visible

**Comment by sywhb** [comment]
@jacksonh I think we are now also refreshing library after updating labels. I committed the change along with archiving changes

**Comment by jacksonh** [comment]
This seems to be working properly now.
