### ISSUE TITLE
unexpected behavior when clicking on links

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [omnivore-app/omnivore#2096]
Hi!

When reading a wikipedia pagr in omnivore, if I click on a link the omnivore app will apparently open it but not save it. In effect I can't easily add a link from a saved article as a new saved article. But I also can't open it in firefox to then share it back to omnivore.

Expected behavior : clicking on list should open a pop up asking if I want to add the link as a new saved article or open it in Firefox.

What do you think?

**Comment by jacksonh** [comment]
Hello, if you right click on the link is Save to Omnivore an option?

**Comment by thiswillbeyourgithub** [comment]
Hi! No, simple clicking just changes the page to the one linked. Long clicking is not doing anything.

Btw : when the new page loads, I can still select text but clicking on highlight does not do anything. And the darkmode is reset to daylight.

**Comment by jacksonh** [comment]
Hi, just confirming, this is on Android?

**Comment by thiswillbeyourgithub** [comment]
On android yes.

I just tested this on the webapp (firefox android) and clicking on links does open the link in firefox (same tab)

**Comment by thiswillbeyourgithub** [comment]
Working great, thanks a lot :)

**Comment by jacksonh** [comment]
Thank you! was trying to find this issue
