### ISSUE TITLE
bulk api

### ISSUE THREAD

**Issue by sywhb** [omnivore-app/omnivore#2103]
something like: `changePages(pageIds: string[], action: 'ARCHIVE' | 'DELETE' | 'MARK_READ' | 'ADD_LABELS', arg -- labelIds: [])`

**Comment by jacksonh** [comment]
Maybe to match some other APIs `update` is better than `change`

**Comment by sywhb** [comment]
@jacksonh Agree!

**Comment by sywhb** [comment]
I'm just writing down this and we can finalize the API later
