### ISSUE TITLE
ability to download pictures from highlights?

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [omnivore-app/omnivore#2113]
Hi!

I'm testing omnivore to see how it could fit with my logseq to anki setup. I cant make images import from highlights work, is it planned? Currently I only see links to wikipedia images instead of it being downloaded.

Thanks!

**Comment by jacksonh** [comment]
Latest Android supports Markdown highlights now. These wont download the image, but they will include the image as a markdown image url.

I will close this ticket, but we will do some work in the future to have images downloaded to the local folder

**Comment by jacksonh** [comment]
@thiswillbeyourgithub can you try this out now and see if it is working for you?

**Comment by thiswillbeyourgithub** [comment]
My images do indeed appear in logseq now :)
