### ISSUE TITLE
Poor performance on iOS article list

### ISSUE THREAD

**Issue by ArttuLai** [omnivore-app/omnivore#2117]
I’ve noticed that while the article itself scrolls smoothly on iPhone 14 Pro, the article list skips and jumps while scrolling through it. I have barely 20 articles, and another 10 in archive.

**Comment by jacksonh** [comment]
Thanks, this is a bit surprising, i wonder if a sync or the AsyncImages causing issues. Can I ask which device you use?

**Comment by ArttuLai** [comment]
> Can I ask which device you use?

iPhone 14 Pro

**Comment by jacksonh** [comment]
> > Can I ask which device you use?
> 
> iPhone 14 Pro

thanks, device is definitely not the problem then. I'm still using an SE.

**Comment by fer0n** [comment]
I've also noticed some minor hiccups while scrolling the article itself, could be related to images there

**Comment by jacksonh** [comment]
Thanks, yeah I suspect async image, but also wonder if there are some background sync operations that are slowing everything down. 

@fer0n can I ask what device you are on? Also, if you scroll a bit, then scroll back/forth do you still see the issue?

**Comment by fer0n** [comment]
- iPhone 12 Pro
- iOS 17.1
- Omnivore 1.36.0

Afaict it's only happening when I initially scroll down. When I scroll up and down afterwards it's all smooth.

**Comment by ArttuLai** [comment]
iPhone 15 Pro Max 
iOS 17.1.1
Omnivore 1.36.0

Yeah I think there's slight jitters when image thumbnails load when scrolling down the article list.

Same happens when going back up though if you have enough articles so that the thumbnails at the top start reloading again.

**Comment by jacksonh** [comment]
Thanks. Unfortunately we are using Swift's built-in AsyncImage loader, we might have to create our own.

**Comment by jacksonh** [comment]
I added some caching in the latest testflight beta, if you are using the beta let me know if it helps
