### ISSUE TITLE
Pulling {{content}} into Obsidian has issues.

### ISSUE THREAD

**Issue by achampion** [omnivore-app/omnivore#2126]
There are several issues when pulling {{content}} into Obsidian. The Markdown conversion of websites struggles with special characters, e.g. here's small section of a website that shares some obsidian templates:

```
&#x60;&#x60;&#x60;yaml
---
when: &lt;% tp.date.now(&quot;YYYY-MM-DD&quot;, 0, tp.file.title, &quot;YYYY-MM-DD&quot;) %&gt;
tags:
  - note
---
&lt;% tp.file.cursor(0) %&gt;

&#x60;&#x60;&#x60;
```

There are similar issues with image URLs they are full of html special characters, this is an example link to a cached image:
`https:&#x2F;&#x2F;proxy-prod.omnivore-image-cache.app&#x2F;1000x420,sOX7WD0NWkM_lJMJ9Ymys259QWICy82-kZ1feISC8Yuo&#x2F;https:&#x2F;&#x2F;res.cloudinary.com&#x2F;practicaldev&#x2F;image&#x2F;fetch&#x2F;s--JrYnSCUR--&#x2F;c_imagga_scale,f_auto,fl_progressive,h_420,q_auto,w_1000&#x2F;https:&#x2F;&#x2F;dev-to-uploads.s3.amazonaws.com&#x2F;uploads&#x2F;articles&#x2F;78ffg3gv7ldjslallyj0.jpg)`. Which of course doesn't render.

There doesn't seem to be an option to pull down local copies of the images so this can be read offline.

**Comment by jacksonh** [comment]
Hi @achampion can you try `{{& content }}` that will fix the escaping.

**Comment by achampion** [comment]
That was quick and thank you - yes it seems to have fixed things. 

Note: the reference link in the Options page in Obsidian sends you to https://docs.omnivore.app/obsidian.html#customizing-which-data-is-synced-from-omnivore-to-obsidian which is a 404.

**Comment by jacksonh** [comment]
Thanks! Working on updating docs now!

**Comment by jacksonh** [comment]
Hey the docs for this have been updated now so I am going to close it out. Let us know if you have any other issues.
