### ISSUE TITLE
Add support for Table of Contents / Chapters

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#2127]
Example article: https://timozander.de/blog/why-you-should-teach/ 

It looks like something like this query selector would get all heading text nodes: `h1[data-omnivore-index], h2[data-omnivore-index], ....`

**Comment by jacksonh** [comment]
Another example here: https://jacksonharper.substack.com/p/creating-a-test-post-with-sections

**Comment by DannieBGoode** [comment]
This is offered by Readwise already and it's very helpful.
I agree with @jacksonh , it shouldn't be too complex to implement
![image](https://github.com/omnivore-app/omnivore/assets/4180198/5382297f-a928-4e24-8416-d71c00fd224c)
