### ISSUE TITLE
Pagination for reader

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#2133]
it would be very nice if we can have "pages" in the reader with a page turn effect.

**Comment by felixbinder** [comment]
I want to second that this would be a very valuable feature for those using the app on eg. Book Onyx eink devices. Pocket has this features, using vertical swipes

**Comment by northgardner** [comment]
Just to add: this feature is especially helpful for larger touchscreens (tablets and ereaders), where users typically have a lot of text on the screen and scrolling is more burdensome.

**Comment by lukgreen** [comment]
I second this. Pocket removed page flipping feature probably in an attempt to increase user involvement, that is hijacking the wetware of humans who are prone to be addicted to swiping and doing other things with their fingers. Please, don't be Bender, love humans. Add page flipping.

**Comment by jonaskoeppel** [comment]
I can only agree with what was written above. E-ink tablets are becoming more common (it's better for your eyes!) and page flip functionality would be really much appreciated (scrolling on e-ink hurts your eyes!). 
Many thanks for all your work!

**Comment by jason-mehmel** [comment]
Another vote for page turning!

Though I wonder how easy something like this is to implement: It's probably essentially a whole other view of the text, maybe rendered overtop of or replacing what's on the screen?

**Comment by teaswift** [comment]
Another vote for pagination! Find it to be much easier to use then scrolling, especially on displays with slow refresh like Eink. 

As mentioned above, the ability to turn off the page turn animation (if implemented) would also be very helpful to minimize unnecessary screen refreshes.

**Comment by lukgreen** [comment]
There is research showing that scrolling is not healthy for the vision system. The research is done for smartphones and social media, and I believe the results can be extrapolated to any scrolling and by extension to cognitive ability and health overall.

[Continuous Social Media Scrolling Negatively Impacts Eye Movement](https://www.optometryadvisor.com/home/meetings/aaopt-2021/social-media-scrolling-detrimental-to-ocular-health/)

Maybe it'll help you to market the feature as something that is good for health. Nowadays a lot of people realize the downsides of using gadgets and exessive information consumption in general.

**Comment by tent4kel** [comment]
I added the code to the android version of omnivore to allow for several enhancements like paginated articles with multiple gestures and volume buttons control, paginated library (volume buttons) and two column layout in landscape mode. 

It's unofficial and might have one or two glitches but it's more than usable on my eInk device, especially compared to the original. 

https://github.com/tent4kel/omnivore/releases/

Btw: The omnivore team is planning to pick up on some of these features, once the android codebase is beyond pre-release state.

**Comment by phdpe** [comment]
> Btw: The omnivore team is planning to pick up on some of these features, once the android codebase is beyond pre-release state.

You are a great human being!

**Comment by lazerwalker** [comment]
@tent4kel You rock! Pagination on my Android e-ink device has been the one feature that's been holding me back from jumping into Omnivore as my main read-later solution, so your fork is absolutely appreciated. Hoping we can get these changes merged upstream sooner rather than later.

**Comment by wirfandeneinenpfad** [comment]
Also eagerly waiting for better eink/pagination-support!

**Comment by ricrui3** [comment]
A friend introduced me to omnivore recently and this is the main feature I think it's missing!

**Comment by boomboxnation** [comment]
Another vote. Just keeping the dream alive.

**Comment by BrendanOerlemans** [comment]
Putting some extra weight to this. Would be extremely useful to e-ink readers.
