### ISSUE TITLE
Web Share Target doesn't work

### ISSUE THREAD

**Issue by ianwill93** [omnivore-app/omnivore#2147]
Sending a link via the Chrome "Share" button just opens to a 404 page.  

[Screen recording 2023-05-01 8.18.42 AM.webm](https://user-images.githubusercontent.com/63332328/235450644-7d1f8271-ec15-4607-9afb-134a5bcd55df.webm)

**Comment by jacksonh** [comment]
Thank you, was this on Windows? This does look like a bug but you should also get better results by using the Chrome extension here (if you are able to install extensions): https://omnivore.app/install/chrome

**Comment by ianwill93** [comment]
It was on ChromeOS. Being able to use the share sheet on that platform is nice, because Chromebooks can send items from the web or Android apps. 

The extension works, but then I'd be losing out when I send from reader apps in the Android environment.

**Comment by jacksonh** [comment]
Got it, thank you.

**Comment by widal001** [comment]
I get redirected to the same page when I try to share from the chrome browser on Android with the Omnivore app installed. 

I am logged in on the app as well. 

![Screenshot_20230910-070423_Chrome](https://github.com/omnivore-app/omnivore/assets/21350331/8b117276-ee09-42d8-afc0-4ad6aa8dd074)
![Screenshot_20230910-070433_Chrome](https://github.com/omnivore-app/omnivore/assets/21350331/d127947c-b460-4ec9-accc-f74d8a9e534c)
![Screenshot_20230910-070438_Chrome](https://github.com/omnivore-app/omnivore/assets/21350331/06f1429d-9e15-4695-a106-2938025a2bfe)

**Comment by widal001** [comment]
It looks like my issue is similar to #884 I wonder if that could also be the source of the issue on chromeOS which supports/uses some Android apps IIRC

**Comment by jacksonh** [comment]
Hi, I think this should be fixed now. Sorry for not updating the ticket.
