### ISSUE TITLE
android : readd oled black mode

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [omnivore-app/omnivore#2155]
Hi,

I noticed that sometime ago the background in the reader in dark mode of the android app was actually black and it now is more brown/grey. I miss the old oled black mode when I'm reading at night. I also think this might be quite important for eink device.

Would it be possible to add back the oled black background?

Thanka!

**Comment by jacksonh** [comment]
@thiswillbeyourgithub thank you, i think this might be a bug. Do you mind posting a screenshot? Also, do you mind checking which version you are on?

**Comment by thiswillbeyourgithub** [comment]
Indeed it's actually a bug! I openned omnivore and the background was black. Then switching theme went to nrown again.

Here are pictures
![Screenshot_20230502-094439](https://user-images.githubusercontent.com/26625900/235608864-dcee1f16-7209-457f-b080-6187a244d87b.png)
![Screenshot_20230502-094430](https://user-images.githubusercontent.com/26625900/235608867-cac6d10a-99d5-4eea-baec-dce4cc8d413c.png)


My version is 0.0.52

**Comment by jacksonh** [comment]
Great, thank you!

**Comment by thiswillbeyourgithub** [comment]
Don't know how to reproduce but I think I saw at some point the theme setting with no box checked (neither light, dark nor system) but might have hallucinated. Not sure it helps.

**Comment by jacksonh** [comment]
OK, this should be fixed in tonight's update.

**Comment by thiswillbeyourgithub** [comment]
You're awesome thank you very very much :)
