### ISSUE TITLE
Subscribe/Unsubscribe actions for newsletters

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#216]
It would be nice to unsubscribe from newsletters directly from Omnivore. To do this we probably need to track all inbound newsletters, and see if they have Unsubscribe list headers. Some examples bellow:

```
'x-unsubscribe-web': 'https://link.axios.com/oc/......',
'list-unsubscribe': '<https://link.axios.com/oc/......>, <mailto:unsubscribe_....@mx.....
```

Using the email unsubscribe method should work for us, since I don't think there would be a confirmation step. The web link method might require UI

**Comment by jacksonh** [comment]
@sywhb interested in your thoughts on this one. I'd love to be able to unsubscribe from newsletters directly from Omnivore. 

For onboarding, it would be really nice if we could automatically subscribe users to some newsletters also. Like if we had a set of ten or so that we know how to subscribe to.

**Comment by sywhb** [comment]
@jacksonh I love the idea too. We could add an `unsubscribe` button on every newsletter page and we can also add a page "/settings/subscriptions" to list down all the subscriptions of a user which the user can unsubscribe newsletters or subscribe more from a list of available ones.

For onboarding, I strongly agree with you. One of the problem I have when I sign up to Omnivore is that the library is too empty. I also think we could redirect a user from sign up page to the new page "/settings/subscriptions" and the user could choose to subscribe newsletters from the predefined list based on interests.

**Comment by jacksonh** [comment]
@sywhb yeah I am finding that just having two or three newsletters is a really nice experience, so we should try to help people get that setup. 

Do you think you can come up with an architecture for listing subscriptions + unsubscribe methods? Obviously with some newsletters its hard or impossible, but I bet for most there is a header we can use to track.

**Comment by sywhb** [comment]
Only Substack has a `list-url` header and for the others we might be able to extract the subscription list name from url or content.

We could get the subscriptions and unsub address when saving newsletters and store them on a new table in postgres

**Comment by jacksonh** [comment]
Ah yeah I think there are a few standard things too: https://www.sendinblue.com/blog/list-unsubscribe-header/ 

Also, I suppose we have the content and can parse in some cases

**Comment by sywhb** [comment]
Yeah. We are fetching this `list-unsubscribe` header in the inbound email handler now

**Comment by sywhb** [comment]
#217
