### ISSUE TITLE
Emails are case sensitive in login

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#2166]
User just reported that they couldn't login, their email was capitalized in the login form, but lower case in the database. We should be ignoring case when we login with email.

**Comment by sywhb** [comment]
Hey @jacksonh , I fixed this in #2128 but we haven't deployed it in prod. I have verified that it works in demo. Could you help to deploy the fix in prod?

**Comment by jacksonh** [comment]
deployed now.
