### ISSUE TITLE
数学公式显示问题

### ISSUE THREAD

**Issue by orangestara** [omnivore-app/omnivore#2168]
背景：
知乎文章加入Omnivore后，出现数学公式显示问题，具体显示效果如下：
<img width="845" alt="image" src="https://user-images.githubusercontent.com/95871544/236117543-1b7438e6-01e1-4b85-a9dd-8fae93fca1cd.png">
对于每一个公式产生了两部分渲染，前部分正确，后部分展示了latex源码，请问后部分如何删除？

**Comment by jacksonh** [comment]
Thank you. I am going to link to this issue: https://github.com/omnivore-app/omnivore/issues/2148

**Comment by jiengup** [comment]
@jacksonh Now math latex can't be rendered normally in [zhihu.com](zhihu.com) link article like this:
<img width="522" alt="image" src="https://github.com/omnivore-app/omnivore/assets/46430425/6dd895af-04d6-4150-8075-51dcb72b6fbf">
This issue shows in the ios app, macOS desktop, and web app.
