### ISSUE TITLE
Twitter images are not passing through the image proxy

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#2169]
Save the following URL and look at the image URLs, they should be image proxy URLs: https://twitter.com/cwolferesearch/status/1653168297649623041

**Comment by ashutoshsaboo** [comment]
Hi @jacksonh , bumping this up -- I just stumbled on this exact same issue while saving a tweet. Can this please be fixed for both images and GIFs - i.e, ideally omnivore should save them internally, currently it seems to point to twitter's original asset url (which can 404 tomorrow, if the tweet is deleted)  - coming from tweets?

**Comment by ashutoshsaboo** [comment]
@jacksonh , just tried saving the same tweet that you mentioned above in the issue description - omnivore still seems to point to pbs.twimg.com urls for images? For articles it seems to point to omnivore internal links of the images - which means the images are being saved and archived internally correctly for article images. Not sure if this change is yet to be deployed because of which maybe i don't see the same archived omnivore internal hosted link for images on twitter?

**Comment by jacksonh** [comment]
Here is what I see for that tweet:

```
<img data-omnivore-anchor-idx="8" data-omnivore-original-src="https://pbs.twimg.com/media/FvE5kL_XwAEGr_c.jpg" src="https://proxy-prod.omnivore-image-cache.app/0x0,sG2DAfiNxtAqFwfwyALrcCFTexObRDXVFjheY3FThDJI/https://pbs.twimg.com/media/FvE5kL_XwAEGr_c.jpg">
```

**Comment by ashutoshsaboo** [comment]
I think the problem is with the parent <a> tag: 

```
<a data-omnivore-anchor-idx="6" href="https://pbs.twimg.com/media/FvE5kL_XwAEGr_c.jpg">
          <picture data-omnivore-anchor-idx="7">
            <img data-omnivore-anchor-idx="8" data-omnivore-original-src="https://pbs.twimg.com/media/FvE5kL_XwAEGr_c.jpg" src="https://proxy-prod.omnivore-image-cache.app/0x0,sG2DAfiNxtAqFwfwyALrcCFTexObRDXVFjheY3FThDJI/https://pbs.twimg.com/media/FvE5kL_XwAEGr_c.jpg">
          </picture>
          </a>
```

The <a> tag should like to the proxied image url like it does for articles as well? @jacksonh

**Comment by ashutoshsaboo** [comment]
For normal articles if it contains images, omnivore would show the images and when you click on it, it would open the proxied (internally archived) image in a new tab rather than the source image url which can 404. I believe that's the right thing, which should happen for tweet images too?

**Comment by jacksonh** [comment]
We don't rewrite any link URLs for any articles. So if an article wraps an image in a link to the image we don't rewrite the link. Twitter wraps most media in a special link that will take you to the original tweet.

**Comment by ashutoshsaboo** [comment]
Not sure what you mean. Here's what I checked, for this tweet link: https://twitter.com/cwolferesearch/status/1653168297649623041 , the img tag shows this, the same url to which omnivore links -: 

```
<img alt="Image" draggable="true" src="https://pbs.twimg.com/media/FvE5kL_XwAEGr_c?format=jpg&amp;name=medium" class="css-9pa8cd">
```

Similarly for this article: https://medium.com/s/story/so-you-want-to-be-a-research-scientist-363c075d3d4c

the src img tag shows this: 
```
<img alt="" class="bg ln lo c" width="700" height="609" loading="eager" role="presentation" src="https://miro.medium.com/v2/resize:fit:1400/1*f_0of-xqHVqhTx7PwWWkUw.jpeg">
```
But omnivore correctly maps it: 

```
<div data-omnivore-anchor-idx="7" tabindex="0" role="button"><picture data-omnivore-anchor-idx="8"><source data-omnivore-anchor-idx="9" srcset="https://proxy-prod.omnivore-image-cache.app/640x0,sSqHFeRE_Acf4MkVaPLzGF-rqZdJ7uk7IEGaZOszJdgc/https://miro.medium.com/v2/resize:fit:640/format:webp/1*f_0of-xqHVqhTx7PwWWkUw.jpeg 640w,https://proxy-prod.omnivore-image-cache.app/720x0,ssV_cz4gM6UtYPZ-sfHLxa6lsZwIO-u1ymnKnww4MvIo/https://miro.medium.com/v2/resize:fit:720/format:webp/1*f_0of-xqHVqhTx7PwWWkUw.jpeg 720w,https://proxy-prod.omnivore-image-cache.app/750x0,s-JCH6gLolW9nLL0nbAilpeHlHyxqz7wvavq23BoMiy4/https://miro.medium.com/v2/resize:fit:750/format:webp/1*f_0of-xqHVqhTx7PwWWkUw.jpeg 750w,https://proxy-prod.omnivore-image-cache.app/786x0,s4RreLjByulb4YOspgM-X6azG9Fs-q97ilm4BtJZGxFg/https://miro.medium.com/v2/resize:fit:786/format:webp/1*f_0of-xqHVqhTx7PwWWkUw.jpeg 786w,https://proxy-prod.omnivore-image-cache.app/828x0,sobyXOpucl3pQlxY8trmweoTgY-3VcSoRaitG4G0K-yc/https://miro.medium.com/v2/resize:fit:828/format:webp/1*f_0of-xqHVqhTx7PwWWkUw.jpeg 828w,https://proxy-prod.omnivore-image-cache.app/1100x0,sX1iasQXMmL_niKUeLPTPucmhXeF1yv02VkUuZNKqv0E/https://miro.medium.com/v2/resize:fit:1100/format:webp/1*f_0of-xqHVqhTx7PwWWkUw.jpeg 1100w,https://proxy-prod.omnivore-image-cache.app/1400x0,sAk7wURefi4K3Fy5QfjYA-aLGpcd7H29vcUNTpcREjlQ/https://miro.medium.com/v2/resize:fit:1400/format:webp/1*f_0of-xqHVqhTx7PwWWkUw.jpeg 1400w," sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px" type="image/webp"><source data-omnivore-anchor-idx="10" data-testid="og" srcset="https://proxy-prod.omnivore-image-cache.app/640x0,sVPEP3ZzNQB4SFr2rDfiD6qEje2FxSxoXUK6tFOXPpbc/https://miro.medium.com/v2/resize:fit:640/1*f_0of-xqHVqhTx7PwWWkUw.jpeg 640w,https://proxy-prod.omnivore-image-cache.app/720x0,s2MqLz8Y-Ka8C6nmHaI9b7I1P0yaP7gMMdO0k10BSsFc/https://miro.medium.com/v2/resize:fit:720/1*f_0of-xqHVqhTx7PwWWkUw.jpeg 720w,https://proxy-prod.omnivore-image-cache.app/750x0,sXU2P7KupsPRZz2MK2fW8RhjcuSPpfXMeb9JgU_d2fFI/https://miro.medium.com/v2/resize:fit:750/1*f_0of-xqHVqhTx7PwWWkUw.jpeg 750w,https://proxy-prod.omnivore-image-cache.app/786x0,sYQgbUWqeNQ4ycgSZgqUU2z8LUxdc2uCKSkgj6OKoRng/https://miro.medium.com/v2/resize:fit:786/1*f_0of-xqHVqhTx7PwWWkUw.jpeg 786w,https://proxy-prod.omnivore-image-cache.app/828x0,spfOBzT0gU67mbJ3tybqzD0jOMl00dqhXjkrDJkEfiq8/https://miro.medium.com/v2/resize:fit:828/1*f_0of-xqHVqhTx7PwWWkUw.jpeg 828w,https://proxy-prod.omnivore-image-cache.app/1100x0,s2selewEw0xkwEd2sKvTDy7gIjPmhV-pA73R0f-GiYlI/https://miro.medium.com/v2/resize:fit:1100/1*f_0of-xqHVqhTx7PwWWkUw.jpeg 1100w,https://proxy-prod.omnivore-image-cache.app/1400x0,sOC4JbO9cMFaPKv0KhviLGcl0cLzD8ucfAstH5By-a9k/https://miro.medium.com/v2/resize:fit:1400/1*f_0of-xqHVqhTx7PwWWkUw.jpeg 1400w," sizes="(min-resolution: 4dppx) and (max-width: 700px) 50vw, (-webkit-min-device-pixel-ratio: 4) and (max-width: 700px) 50vw, (min-resolution: 3dppx) and (max-width: 700px) 67vw, (-webkit-min-device-pixel-ratio: 3) and (max-width: 700px) 65vw, (min-resolution: 2.5dppx) and (max-width: 700px) 80vw, (-webkit-min-device-pixel-ratio: 2.5) and (max-width: 700px) 80vw, (min-resolution: 2dppx) and (max-width: 700px) 100vw, (-webkit-min-device-pixel-ratio: 2) and (max-width: 700px) 100vw, 700px"><img data-omnivore-anchor-idx="11" data-omnivore-original-src="https://miro.medium.com/v2/resize:fit:700/1*f_0of-xqHVqhTx7PwWWkUw.jpeg" alt="" width="700" height="609" loading="eager" role="presentation" src="https://proxy-prod.omnivore-image-cache.app/700x609,smfwBGppFvzf0raqYcTMEf8DK0egx4__xofNmtZYyLnA/https://miro.medium.com/v2/resize:fit:700/1*f_0of-xqHVqhTx7PwWWkUw.jpeg"></picture></div>
```

I guess the difference is that for tweets omnivore creates an a tag mapping to the source tweet image (not the source tweet), while for article images it wraps it in a div not linking the image. 

Any idea why this disparity, given in both sources above it has it's image embedded behind a separate URL? @jacksonh

**Comment by jacksonh** [comment]
Can you resave https://twitter.com/cwolferesearch/status/1653168297649623041 and then paste the full `<img` attribute you see?

**Comment by jacksonh** [comment]
Yeah we don't modify the content, the reason twitter images link to twitter images is because thats what's in their source code vs what is in medium's original source. 

I don't think we will go to the point of rewriting links to internal links, in this one case we could special case it but I don't see much value there, we are more focused on being a reading tool that an archiving tool.

**Comment by ashutoshsaboo** [comment]
How about the latter - Rather than rewriting links, is it possible to remove the a tags altogether from tweet images and just wrap them in a div like it works for medium page links? @jacksonh

**Comment by jacksonh** [comment]
We don't intentionally remove image links from Medium, it looks like they don't really wrap their images in links

We try to minimize site specific handlers and I don't see this as very important. If the tweet is deleted the same readable version will contain broken links to the deleted tweet.

**Comment by ashutoshsaboo** [comment]
Hmm makes sense, thank you for all your hard work! 🚀  This should solve for both twitter images as well as GIF images going through the proxy now, is that the correct understanding? @jacksonh

**Comment by jacksonh** [comment]
Yeah the GIFs should go through the proxy now as well as long as they are embedded in `<img src=...` tags.

**Comment by ashutoshsaboo** [comment]
Gotcha, thanks!
