### ISSUE TITLE
Login on Android app not working

### ISSUE THREAD

**Issue by domsch1988** [omnivore-app/omnivore#2182]
I just set up omnivore. Login on the PWA through chrome works, but filling the same login from bitwarden tells me my login is wrong.
This is on a Pixel 7, Android 13, Omnivore installed from Playstore.
I also tried resetting my Password already.

**Comment by jacksonh** [comment]
Thanks Dom, do you mind emailing me the email address you are using to login at jacksonh@omnivore.app -- I have a feeling it's a formatting thing like a space after the address not being removed.

**Comment by domsch1988** [comment]
Thanks for looking into this. Mail is send.

**Comment by jacksonh** [comment]
Going to close this issue as I think it has been resolved, duplicate of https://github.com/omnivore-app/omnivore/issues/2166

**Comment by domsch1988** [comment]
Yes, works fine now. Thank you
