### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by I7T5** [omnivore-app/omnivore#2186]
See [WebBites](https://eliasruiz.com/webbites).

**Comment by jacksonh** [comment]
Thanks @I7T5 do you have a few specific things you'd like to see improved, also can I ask which client this refers to (Web, iOS, Android, Mac OS)?

**Comment by I7T5** [comment]
Currently I'm only using Omnivore Web, but I have downloaded both the iOS and macOS (not exactly useful now) app. There's a few specific UI/UX things I'd like to see addressed: 

1. Better hover and on-click transitional animations (box shadows etc.)
2. Faster load!!!
3. Do this since the Subscript menu has only 1 field
<img width="300" alt="Screenshot 2023-05-12 at 11 18 06" src="https://github.com/omnivore-app/omnivore/assets/105357663/ac574563-33aa-43cc-8716-61c32d27fa57">
4. Bulk edit (delete) articles and subscriptions

**Comment by jacksonh** [comment]
Thank you, regarding load time, can i ask where you are located? It might be some response latency as we normally have a fairly good load time. Regarding items 1 and 3, we actually have some hover changes in design now, and some changes that would allow more customization of the side menu.

**Comment by I7T5** [comment]
I'm in Shanghai, China, using a VPN at Boston. 

> Regarding items 1 and 3, we actually have some hover changes in design now, and some changes that would allow more customization of the side menu.

That is good news!

**Comment by I7T5** [comment]
# Omnivore vs. Matter

## Inbox
![Inbox](https://github.com/omnivore-app/omnivore/assets/105357663/ca28238f-d40f-4bd1-842f-41028f53e572)

## Read Later
![Read Later](https://github.com/omnivore-app/omnivore/assets/105357663/3aba54e9-e35f-47ef-b4a7-8f14d2e33c40)

## Article
![Article](https://github.com/omnivore-app/omnivore/assets/105357663/8409aca4-e4c6-4159-b027-a92105a46789)

## Reader Preference
![Reader Apperance](https://github.com/omnivore-app/omnivore/assets/105357663/5bb37b88-ff75-47ba-8110-ef2a66e73c5d)

Download [Matter](https://hq.getmatter.com) and try it out! The UI is very worth respecting. They used to have Hoefler Co.'s fonts too...(I don't work for them, just personal opinion.)

**Comment by jacksonh** [comment]
Going to close this one out as we have some new designs on iOS
