### ISSUE TITLE
Issues with saving mp.weixin.qq.com on the Android client include

### ISSUE THREAD

**Issue by StrollStars** [omnivore-app/omnivore#2191]
- [x] 1. Non-local language for original articles and published content. https://github.com/omnivore-app/omnivore/issues/1776
- [x] 2. Duplicate titles and missing publication date and time. https://github.com/omnivore-app/omnivore/issues/1901
- [x] 3. Images in articles saved on the Android client [become invalid](https://github-production-user-asset-6210df.s3.amazonaws.com/10942225/238109832-1c032716-c320-49a8-a3bb-938c3f30c489.jpg) when viewed on the web.
- [x] 4. Articles saved in the Android client remain even after they have been deleted from the web version.

**Comment by jacksonh** [comment]
Hmm, yes one very basic issue here is we aren't passing language through when calling `SaveURL` API method.

**Comment by StrollStars** [comment]
> Hmm, yes one very basic issue here is we aren't passing language through when calling `SaveURL` API method.

Is this problem easy to solve?

The third question is quite strange. Isn't it supposed to cache the images on the server? Why is there still a problem when viewing on the web page?

**Comment by jacksonh** [comment]
On the web are you able to open developer tools, inspect the image element and paste its contents here? the full `<img src` element if possible.

**Comment by StrollStars** [comment]
@jacksonh The recent update is great! I found that the first three problems with favoriting articles on the Android client have been solved, and the fourth problem can be resolved by resetting the cache. While I also found other issues and reported them in separate issues. Thank you very much to the developers, and this issue can now be closed.
