### ISSUE TITLE
Does Omnivore want to become more Matter-like?

### ISSUE THREAD

**Issue by I7T5** [omnivore-app/omnivore#2194]
In the features, I means. I really like Matter's all-in-one idea, the fancy yet not cumbersome features, and the sleek and modern design. But after reading their privacy policy my only hope lies in open-sourced omnivore...Would be great if Omnivore can catch up on those, while protecting privacy 💪💪💪

**Comment by jacksonh** [comment]
Hey @I7T5 do you mind describing some of the features they have that you'd like. I haven't looked at Matter much. I know it has some staff suggestions for reading lists.

**Comment by I7T5** [comment]
Now that I think of it, the key difference between Omnivore and Matter, other than RSS feeds #2029, send to kindle #2142, and algorithmic ranking #2195, is the UI/UX #2186. Will close the issue and write a comprehensive comparison between Omnivore and Matter there.

**Comment by jacksonh** [comment]
Will close thos one.
