### ISSUE TITLE
Ability to create newsletter emails (not linked to username) in Omnivore

### ISSUE THREAD

**Issue by ashutoshsaboo** [omnivore-app/omnivore#2198]
I'm not sure why is the generated email linked to username (in the prefix) in omnivore? If the idea is to just have a unique email, then that can be done with a global email unique check similar to how it's done for usernames currently too isn't it? 

The place where i'm coming from is that, one might want to have a personally identifiable username to engage in sharing features (like omnivore club etc) with a personal username - but one might not want to give those out to newsletters to let them perceive identity of the user. Otherwise I could have might as well used my personal email id to register with the newsletter (let them have my identity), and then forward it to omnivore. 

Any thoughts? @jacksonh

**Comment by jacksonh** [comment]
Got it, I understand the need now. 

A big part of the reason it is so constrained is because letting it be user editable means it becomes another attack vector, so we have to think through all the security aspects both from an input perspective and from a naming perspective, like a user could create an email something like `webmaster@inbox.omnivore.app` which would grant certain access to some tools like this: https://support.dnsimple.com/articles/ssl-certificates-email-validation/#requirements

**Comment by ashutoshsaboo** [comment]
@jacksonh Well that's easy to solve for isn't it? Just have webmaster and all such sensitive keywords, as already occupied aliases so that the automated check itself wouldn't let it use it (similar to the checks for username as of today)? 

Or atleast if you're worried about the attack (even though it can be kind of solved), maybe atleast provide user with choosing a separate non-personal prefix which can be used for newsletter emails different from username? I think this might ensure people don't just hoard on to these good aliases like small one's/original site names etc, and might be a good middle ground.  Thoughts? @jacksonh

**Comment by jacksonh** [comment]
Yeah its not an impossible problem but we need to make sure we figure out "all such sensitive keywords"

**Comment by LightTemplar** [comment]
What if emails will still have their unique symbol sequence? Unique pro email address, of course. 
This could even serve as internal ID, letting to rename the wording part so many times, as user wants and still protect server from emails like "webmaster".

**Comment by ashutoshsaboo** [comment]
What's the usecase of renaming an existing email to which one already might be getting existing newsletters? if you rename, then newsletter won't be able to send to the correct address right.

**Comment by LightTemplar** [comment]
Just a thought, I can't find a use case for renaming of existing ones. 
But this is not that important, as using of an unique symbol sequence - this is my actual suggestion as solution to a problem.

**Comment by LightTemplar** [comment]
I mean letting user to create an email, consisting of two parts: first part is defined from user, and second is unique generated. There you can have any name or word you want, and the server is still protected too.

This is similar to my feature request https://github.com/omnivore-app/omnivore/issues/2196

**Comment by ashutoshsaboo** [comment]
Yeah my suggestion above was that: the prefix should be allowed to be customisable and not tied to the username. That is currently not the case. Latter suffix can be anything. I think in your feature request, we can add an added request that prefix should be one time configurable as per user - sort of a "newsletter username", if we really want to go this route. Or ofcourse the alternative option could be that, everything can be entered that the user wants. But I think former would be better and more simpler for the server to handle. My uber level request was that, the main account level username shouldn't be tied to the newsletter prefix email - the former also helps in achieving for the same. 

@jacksonh what are your thoughts?

**Comment by ashutoshsaboo** [comment]
Any update on this? @jacksonh if this is being still considered? Kind of having emails in omnivore linked to your personal username, and floating around the web for newsletters isn't the most ideal.

**Comment by ashutoshsaboo** [comment]
Hi, is this request being considered?

**Comment by jacksonh** [comment]
yes it is, it just hasn't made its way to the top of priorities.
