### ISSUE TITLE
How to search with "OR"?

### ISSUE THREAD

**Issue by LightTemplar** [omnivore-app/omnivore#2201]
I would like to search something like this "type:highlights OR label:ready" - this filter is intended to use in Obsidian plugin. But "OR" doesn't work here, it gives results as if it would be "AND".

I read this, but couldn't find an answer: https://docs.omnivore.app/using/search.html

**Comment by jacksonh** [comment]
Thanks, I don't think we support anything like this, it would be useful for some cases when we allow saved search, but I'm not sure what the best way to implement would be. /cc @sywhb

**Comment by sywhb** [comment]
@jacksonh I didn't come up with a good solution. Need to do some research

**Comment by sywhb** [comment]
Hey @LightTemplar , we now support "AND", "OR", "NOT" and parenthesis in the search string.

Please try out and let me know if it works for you :)
