### ISSUE TITLE
How and where does Omnivore save / store data? Does it use a SQL database?

### ISSUE THREAD

**Issue by Oneechan69** [omnivore-app/omnivore#2213]
I just did a bunch of looking up about this and haven't found any answers. What are the file location(s) where pages and data are saved for Omnivore, and what is the format in which they're saved?

**Comment by jacksonh** [comment]
Hello @Oneechan69, do you mean on the backend or on the frontend?

In our backend we store data in three places: 

1. Postgres for structured data like account info, subscription info, and labels
2. Elasticsearch for page data
3. Google Cloud Storage for documents like PDFs and long term archives of data

**Comment by Oneechan69** [comment]
I meant all the webpage content. Is it all stored in Elasticsearch?

**Comment by jacksonh** [comment]
Yeah the page content is stored in elasticsearch.

**Comment by silloy** [comment]
Whether to consider supporting storage in a private cloud such as google driver, dropbox, or a WebDAV-enabled cloud drive, which can reduce server costs while focusing more on user privacy
