### ISSUE TITLE
Is there a way to automatically / programatically download Omnivore articles as markdown documents, or download articles using Omniore without saving them as articles first?

### ISSUE THREAD

**Issue by Oneechan69** [omnivore-app/omnivore#2222]
What caught my attention for Omnivore is the ability to download pages as markdown documents in Obsidian using the [Obsidian Omnivore plugin](https://github.com/omnivore-app/obsidian-omnivore). However, it does require opening the app and maybe running the sync command in it. I did find the [C-Sharp demo](https://github.com/laurentkempe/omnivore-api-demo-csharp) for doing so but that's not an efficient way to do so. I'm wondering if there are other ways . Omnivore is very good for stripping down webpages as articles.

**Comment by jacksonh** [comment]
Hello, you can only convert content that has been saved to your library.

**Comment by jacksonh** [comment]
I'll close this but feel free to re-open if it doesn't answer.
