### ISSUE TITLE
Page header covers text

### ISSUE THREAD

**Issue by karlemilnikka** [omnivore-app/omnivore#2223]
The transparent page header covers the text so that the text can’t be highlighted. Tested on Firefox (screenshot) and Chromium. 
<img width="1675" alt="Skärmavbild 2023-05-20 kl  11 56 28" src="https://github.com/omnivore-app/omnivore/assets/20514810/916cc6b7-4a6a-4729-818b-39952f3da43f">

**Comment by karlemilnikka** [comment]
A related feature suggestion: please consider reducing the height of the top bar when displaying PDFs.

**Comment by jacksonh** [comment]
Fixed here https://github.com/omnivore-app/omnivore/pull/2247

**Comment by jacksonh** [comment]
Also have some updated designs with shorter header that I am trying to implement.

**Comment by jacksonh** [comment]
OK, this one should be fixed. Thank you very much for the report!
