### ISSUE TITLE
Hex equals sign for highlights in full articles synced to Obsidian

### ISSUE THREAD

**Issue by karlemilnikka** [omnivore-app/omnivore#2225]
When syncing full articles to Obsidian ({{content}}), the highlights indicators are synced as hex characters (&#x3D;&#x3D;), making Obsidian show equals signs around the highlighted text instead of highlighting it. 

Tested with Omnivore plugin 1.3.0 on Obsidian 1.3.2.

**Comment by jacksonh** [comment]
Can you try using `{{{ content }}}` ?

**Comment by karlemilnikka** [comment]
It works. Sorry for incorrectly reporting this as a bug when it was just my mistake.

**Comment by jacksonh** [comment]
Ah no worries, its incorrect in some of our docs. With the "triple `stache" `{{{` the value is not escaped.
