### ISSUE TITLE
Bug with Omnivore Obsidian Plugin

### ISSUE THREAD

**Issue by DudeThatsErin** [omnivore-app/omnivore#2228]
Reported this on Discord but I wanted to open an issue as well.

I found a bug.
This is with the Omnivore -> Obsidian Plugin.

Images aren't displaying correctly. I am just using `{{content}}` in the template.

Pictured is the article (center) in Omnivore and then the article (right) in Obsidian. You can see images show up as 
```
![](https:&#x2F;&#x2F;proxy-prod.omnivore-image-cache.app&#x2F;550x0,s_9qyFi4SlO6dQVQjUJSLS5nyXV0pDbTzjpsihax5ORk&#x2F;https:&#x2F;&#x2F;substackcdn.com&#x2F;image&#x2F;fetch&#x2F;w_2912,c_limit,f_auto,q_auto:good,fl_progressive:steep&#x2F;https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F51385208-56de-4c22-a999-dd08c5fc1ef0_1998x1020.png)](https:&#x2F;&#x2F;substack.com&#x2F;redirect&#x2F;a8d775e4-6c80-4d89-ab74-8b48bc717aeb?j&#x3D;eyJ1IjoiMmNzZ2J5In0.DuaNNESnF%5FjTPPH1p2k9vgsIIKYJ6cZDx4nXzc82c9Y)
```

![](https://cdn.discordapp.com/attachments/943967463299764314/1109660699073986613/image.png)

**Comment by karlemilnikka** [comment]
I also thought it was a bug, but @jacksonh told me I just had to change {{content}} to {{{content}}}. 

https://github.com/omnivore-app/omnivore/issues/2225

**Comment by jacksonh** [comment]
hey @DudeThatsErin thanks, i believe this is a duplicate / notabug, as you should use `{{{ content }}}` but do you mind pointing to any docs you saw that used `{{ content }}`. We were using it incorrectly in docs for a while, so I need to make sure we clean it up everywhere.

I will close for now, but feel free to re-open if you see issues.
