### ISSUE TITLE
Bug when installing as a PWA on Windows & CSS Bug

### ISSUE THREAD

**Issue by DudeThatsErin** [omnivore-app/omnivore#2236]
If you have a link that doesn't work (like below) at first, there is no way to reload back to the home page within the app without using F5 on your keyboard. Even that didn't work in my testing.
![image](https://github.com/omnivore-app/omnivore/assets/2681022/46a5fbb1-3f75-4001-be67-8ce4dfb331e2)
I'm stuck at ^^ this page in my PWA via the web app. In a normal browser you have the back and forward buttons like so:
![image](https://github.com/omnivore-app/omnivore/assets/2681022/7826fb9e-2774-4fbd-b152-62a9fef1c951)
But I was wanting a windows app so I installed it as a PWA on Windows.

All it needs is a back button built-into the website.

---

Also, no matter how wide I make my window (I have a 27 or 28" widescreen LG monitor) there is always a scrollbar at the very bottom.
![image](https://github.com/omnivore-app/omnivore/assets/2681022/4cb8b106-8b17-43a0-8beb-8358c5d8c615)

That seems like some simple CSS that coded right or something. Cause my text fits on the page. Entire page for reference:
![image](https://github.com/omnivore-app/omnivore/assets/2681022/f5f8d159-3b1f-4ab9-b4dd-8efbe5aa9eed)

**Comment by jacksonh** [comment]
Fix for the home button in this PR: https://github.com/omnivore-app/omnivore/pull/2249

**Comment by jacksonh** [comment]
Hey @DudeThatsErin can you tell me if you are still having the issues with the icon in the PWA on Windows?

**Comment by DudeThatsErin** [comment]
It works now thanks! The CSS issue with the horizontal scroll bar is still there though. Seems like a minor CSS glitch with padding or something.

**Comment by jacksonh** [comment]
Thank you, yes it seems on some browsers we need to set the overflow differently. I will have to test this on Windows as I haven't been able to replicate elsewhere.

**Comment by jacksonh** [comment]
Potential fix: https://github.com/omnivore-app/omnivore/pull/2308

**Comment by jacksonh** [comment]
Fixed here: https://github.com/omnivore-app/omnivore/pull/2312
