### ISSUE TITLE
Feature suggestion: Add a copy button to highlights

### ISSUE THREAD

**Issue by karlemilnikka** [omnivore-app/omnivore#2267]
When sentences are highlighted, they become harder to mark and copy. I suggest adding a copy button to the existing action bar that’s displayed when clicking on a highlight (i.e., the bar with “delete”, “labels” and “note” buttons).

**Comment by jacksonh** [comment]
Thanks @karlemilnikka this is on web, right?

**Comment by karlemilnikka** [comment]
@jacksonh Yes, exactly.

**Comment by jacksonh** [comment]
From the community: https://github.com/omnivore-app/omnivore/pull/2414 -- hopefully in production soon

**Comment by jacksonh** [comment]
Done!
