### ISSUE TITLE
Creating labels fails in app

### ISSUE THREAD

**Issue by dagomar** [omnivore-app/omnivore#2270]
In the android app (0.0.80) creating new labels doesn't work. Adding existing labels does. Specifically what happens:

- Edit labels of an article
- type a non-existing label
- click the 'create new label' button that appears
- see that the new label is added in the labels field
- hit save
- notice that the screen is refreshed and back on the overview

**Comment by lsolesen** [comment]
@jacksonh Any idea when this missing feature will work in the app?

**Comment by hemanti0503** [comment]
Unfortunately, I have a similar (same?) issue. I can create labels and they show up in the article, but as soon as I close it and go back, the labels are gone. When I go back to adding labels, none of those that I previously defined, show up.

**Comment by stefanosansone** [comment]
@jacksonh labels creation is working fine in both published and upcoming versions. This issue can be closed.
