### ISSUE TITLE
Question about the datePublished

### ISSUE THREAD

**Issue by StrollStars** [omnivore-app/omnivore#2285]
Is it necessary to manually select the datePublished for collecting articles now in the "edit metadata" menu, with the default value being empty?
Can the datePublished be automatically get from the article's datePublished?

**Comment by jacksonh** [comment]
Hi @StrollStars some pages don't expose a date published value, so it isn't always set. Do you have a page where it isn't set that you could share?

**Comment by StrollStars** [comment]
@jacksonh Could you please solve this problem?

**Comment by jacksonh** [comment]
@StrollStars can you give a URL i could test with?

**Comment by StrollStars** [comment]
@jacksonh https://mp.weixin.qq.com/s/F29v8bcswk6TLb1VbaCi4w

**Comment by StrollStars** [comment]
@jacksonh I found the "datePublished" can be get, but there are other issues. This issue has been closed for now.

**Comment by jacksonh** [comment]
@StrollStars thank you for following up
