### ISSUE TITLE
URL Import: Provide details on which URLs failed to import in email

### ISSUE THREAD

**Issue by Nezteb** [omnivore-app/omnivore#2301]
Yesterday I did my first import of 591 URLs (from a Raindrop.io export). https://github.com/omnivore-app/omnivore/issues/2094#issuecomment-1575205100

The email I received read:
> 591 URLs have been processed and should be available in your library. 1 URLs failed to be parsed.

I have no way of knowing which one failed. I'd like to know so that I could go back and manually add said URL to Omnivore.

It'd be nice if the email said something like:
> 591 URLs have been processed and should be available in your library. 1 URLs failed to be parsed:
> - invalid_scheme://invalid-url.asdf

**Comment by jacksonh** [comment]
Thank's we do have some metrics stuff coming on the importer, this makes sense.

Just a guess, but if its one URL, its most likely the header column of your CSV in this case.

**Comment by jacksonh** [comment]
This should be done now.
