### ISSUE TITLE
CSS Bug in Brave/Chrome Extension

### ISSUE THREAD

**Issue by DudeThatsErin** [omnivore-app/omnivore#2302]
<img width="359" alt="brave_Sfj42rCeH4" src="https://github.com/omnivore-app/omnivore/assets/2681022/ddfb5051-f1e7-4b27-ac9c-27b75246b65d">
<img width="359" alt="brave_zasLSo2oTY" src="https://github.com/omnivore-app/omnivore/assets/2681022/606b6327-6e3d-4ef9-89dc-ae321ca08500">
As you can see the label is typed there but nothing shows up. Possibly because I'm using a dark theme on my installation cause white blinds me.

**Comment by jacksonh** [comment]
@DudeThatsErin let me know if you still have this issue.
