### ISSUE TITLE
Showing of the query string in the UI depends of the size of the browser window

### ISSUE THREAD

**Issue by LightTemplar** [omnivore-app/omnivore#2324]
If you make your browser narrow, as on smartphones, so that left panel and query field is hidden, there is a magnifier icon:
![image](https://github.com/omnivore-app/omnivore/assets/453783/7b1b205d-2185-4033-b675-3857b5b50b1a)

and if clcik there, you get the actual query string, which is cool:
![image](https://github.com/omnivore-app/omnivore/assets/453783/d4809dfc-4709-48da-a447-914c2feda014)

but, if your browser is wide enough, so that query field is always shown, there is no query string:
![image](https://github.com/omnivore-app/omnivore/assets/453783/8d8476e6-1b08-41c0-883e-29a852cbfdd3)

Would it be possible also to show that string, if the browser is wide?

**Comment by jacksonh** [comment]
Thanks, this is updated in https://github.com/omnivore-app/omnivore/pull/2327 hopefully live soon.

**Comment by LightTemplar** [comment]
It works, as I imagined! Thanks!
