### ISSUE TITLE
FR: clicking on link should show the url also

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [omnivore-app/omnivore#2362]
Followup to #2096 

Hi, on android i find that I frequently click on links in omnivore article just to see to which domain a link goes to (is it wikipedia? A blog? Something I read already?).

I think it would be an improvement to have the link be displayed in the "popup" window of link context introduced in #2096

Have a nice day, omnivore is really improving fast and more and more indispensable!

**Comment by jacksonh** [comment]
yes i agree, this is a nice idea. Thank you!

**Comment by remychantenay** [comment]
- [X] Android
- [ ] iOS

**Comment by remychantenay** [comment]
I believe this issue can now be closed @jacksonh WDYT?

**Comment by jacksonh** [comment]
Thanks!

**Comment by thiswillbeyourgithub** [comment]
Hi, I think this should be reopen: on android the current link color is barely visible. Like black on dark grey.

**Comment by remychantenay** [comment]
> Hi, I think this should be reopen: on android the current link color is barely visible. Like black on dark grey.

I probably didn't take into account both light and dark mode, I will take a look and fix this this week 👍

**Comment by remychantenay** [comment]
This was fixed and merged @thiswillbeyourgithub

Thank you @jacksonh for reviewing :)
