### ISSUE TITLE
Remove article using API

### ISSUE THREAD

**Issue by daviddavo** [omnivore-app/omnivore#2380]
The only way I found to do this is using a bulk action of type DELETE. Is it possible to do it just using the ID?

**Comment by jacksonh** [comment]
Hey, yeah it is weirdly named but `setBookmarkArticle` with `bookmark` set to false. You can see it in the web frontend code here: 

https://github.com/omnivore-app/omnivore/blob/07ae720cf57539e1360774b1bc7fb1892cc1a434/packages/web/lib/networking/mutations/deleteLinkMutation.ts#L4

```
mutation SetBookmarkArticle($input: SetBookmarkArticleInput!) {
    setBookmarkArticle(input: $input) {
      ... on SetBookmarkArticleSuccess {
        bookmarkedArticle {
          id
        }
      }
      ... on SetBookmarkArticleError {
        errorCodes
      }
    }
  }`
```

**Comment by jacksonh** [comment]
I'll close this ticket since we have the API, but let me know if you need any assistance
