### ISSUE TITLE
Feat:  extension add right click menu

### ISSUE THREAD

**Issue by bingryan** [omnivore-app/omnivore#2385]
right click menu more convenient to handle save article

**Comment by jacksonh** [comment]
Hi @bingryan which browser are you using? It should be in the firefox, chrome, and edge extensions

**Comment by bingryan** [comment]
> Hi @bingryan which browser are you using? It should be in the firefox, chrome, and edge extensions

browser : chrome 114.0.5735.133  (arm64)

**Comment by jacksonh** [comment]
Do you see this menu when you right click on a link? 

<img width="486" alt="Screen Shot 2023-06-20 at 15 19 54" src="https://github.com/omnivore-app/omnivore/assets/75189/6b8f5ed9-ec28-4e96-8b9d-103a4d3edfab">

**Comment by bingryan** [comment]
> 

yes

**Comment by bingryan** [comment]
> Do you see this menu when you right click on a link?
> 
> <img alt="Screen Shot 2023-06-20 at 15 19 54" width="486" src="https://user-images.githubusercontent.com/75189/247036794-6b8f5ed9-ec28-4e96-8b9d-103a4d3edfab.png">

yes

**Comment by jacksonh** [comment]
@bingryan is that what you are looking for, or something different?

**Comment by jacksonh** [comment]
Ah so you want Right Click to save the current page, not Right Click on a link

**Comment by bingryan** [comment]
> Ah so you want Right Click to save the current page, not Right Click on a link

right :)

**Comment by bingryan** [comment]
I try to  click a link and find `Save to Omnivore` 👍

**Comment by bingryan** [comment]
Why no choice for the current page 🤣

**Comment by jacksonh** [comment]
Looks like we need to allow it in different contexts, this is in the manifest `contexts: ['link'],` we would need to add an action for the current page too `(contexts: ['page'],)`. I think I'd give it a different title so the two weren't confused. Like Save this page to Omnivore, Save link to Omnivore
