### ISSUE TITLE
Feature Request: Reset Reading Progress / Mark Unread

### ISSUE THREAD

**Issue by ZeinHajjAli** [omnivore-app/omnivore#2398]
It would be useful to have the ability to reset the reading progress of a saved article. Similar to how other read-it-later applications do (Readwise Reader, etc.)

Use case for this could be if you skim the article once before wanting to go back and read it more thoroughly later.

Right now, archiving and unarchiving doesn’t achieve this either.

**Comment by jacksonh** [comment]
Hi @ZeinHajjAli is this on Android? (We should have this on iOS, and Web does have mark as read/unread)

**Comment by ZeinHajjAli** [comment]
My bad, didn’t see the option for it on iOS since it was only in the read page and not in the menu that comes up from long pressing on an item in the inbox. Would be great for Android as well though.
