### ISSUE TITLE
Chrome extension doesn't work in the Android Kiwi browser

### ISSUE THREAD

**Issue by Arcyne** [omnivore-app/omnivore#2402]
Hey folks I love the ability for the desktop plugin to pull down the entire page whereas sometimes the Android share to functionality doesn't. To that end I was trying to use the kiwi browser which supports extensions but ran into errors.

Screenshot_20230620_200629_Kiwi Browser

Writing this from my phone so apologies ahead of time for the screenshot instead of the individual error messages. If desired I can update with the additional information when I get to a desktop.

**Comment by Arcyne** [comment]
![image](https://github.com/omnivore-app/omnivore/assets/19860164/0924af7f-cb9c-40ba-998d-19278922be4e)

**Comment by jacksonh** [comment]
INteresting, thanks. I wonder if prefetch-src is really needed. One thing we could do is package differently for Kiwi

**Comment by dairefagan** [comment]
I have been using this fine in recent weeks, it may be worth trying again.
