### ISSUE TITLE
The datePublished is incorrect, and I cannot modify it.

### ISSUE THREAD

**Issue by StrollStars** [omnivore-app/omnivore#2425]
As shown in the image, the publication time is 12:09.
![2023-06-26_212400](https://github.com/omnivore-app/omnivore/assets/10942225/d2188e56-0134-4d14-b2e7-97100fd77716)
![2023-06-26_212450](https://github.com/omnivore-app/omnivore/assets/10942225/e4255e52-723f-419e-99f6-cfb655466f84)
However, the metadata displays 20:09.
![2023-06-26_212538](https://github.com/omnivore-app/omnivore/assets/10942225/ed647ef1-43c6-45f9-9828-827bf0e49b36)
@jacksonh @sywhb Is it possible to correct this error and make the value editable?

**Comment by jacksonh** [comment]
@StrollStars so when you select the `20:09` in the editor you can't change it?

**Comment by StrollStars** [comment]
@jacksonh Yes, as you said, I cannot change it.

**Comment by StrollStars** [comment]
@jacksonh Win7, Chrome 109.0.5414.75

**Comment by StrollStars** [comment]
@sywhb @jacksonh 之前提的发布时间获取依旧存在：https://github.com/omnivore-app/omnivore/issues/2285
刚刚又重现的问题：https://mp.weixin.qq.com/s/aXAKDgeBZm4mfstuTuW9Rg
总结起来就是两种情况都存在：
1. 发布时间获取不到（上面的链接），这种情况可以手动修改发布时间；
2. 发布时间能获取到（本issue），这种情况发布时间无法被修改。

**Comment by sywhb** [comment]
@StrollStars 微信公众号的发布时间的时间戳好像不是每个文章都有，无法修改时间的可能是个前端的bug

**Comment by StrollStars** [comment]
@sywhb 可否给个例子我看下？因为我看到目前都是有时间的，除了一些纯文字的。
其实纯文字的也是有时间的，只是它在文章的右下角，而普通的都在标题下方。

**Comment by StrollStars** [comment]
@sywhb 我知道unix时间，不过我没做过网页开发，这是大多数网页的标准？wechat的文章，基本是自成一个体系，如你所说，直接用抓取到的发布时间就好，应该实现起来更方便些吧？就是要单独处理了。

前端的Bug我也觉得很神奇，空的可以修改，已有的就无法修改。
既然这样，要不先把8小时时差的问题修复了可好？我删除重新添加一次试试。
PS：早先的时候我发现另外一个问题，就是网页界面删除的文章，服务器缓存还在，第二次添加的时候和第一次的效果一样。

**Comment by sywhb** [comment]
@StrollStars 可以请你再试一下吗？我刚刚修复了时区的 bug ，用 extension 保存微信公众号应该会显示正确的发布时间。
另外前端的 bug 也已修复，我测试了一下，现在在网页上可以修改和保存发布时间。

**Comment by sywhb** [comment]
> PS：早先的时候我发现另外一个问题，就是网页界面删除的文章，服务器缓存还在，第二次添加的时候和第一次的效果一样。

是的，我们在后端做的是软删除，重新保存的话会覆盖掉之前的数据。我最近刚刚写了个恢复的功能，正在 beta 测试中。

**Comment by StrollStars** [comment]
@sywhb 刚刚试了下，extension（电脑上）保存微信公众号显示了正确的发布时间，但是Android客户端依旧不行，保存后没有发布时间。
还有个相关的问题是，安卓端保存会将发布时间一行的一些内容翻译成英文，如Original和Posted on。
Android上的扩展，保存效果和安卓客户端一致，也就是存在问题。

恢复功能是用来恢复删除的？

**Comment by sywhb** [comment]
@StrollStars Android 端可能得等 Jackson 回来再修了，他这周出差。

我感觉 Android 端可能是把链接发给后端的虚拟浏览器来抓取页面，所以时区和语言是基于我们服务器的位置（美国）。而 extension 或者 iOS 端是把本地浏览器的页面发回后端。

> 恢复功能是用来恢复删除的？

对

**Comment by StrollStars** [comment]
谢谢，Android 端还有别的问题，等 @jacksonh 回来再说吧。

**Comment by StrollStars** [comment]
@sywhb Jackson 回来了吗？

**Comment by sywhb** [comment]
@StrollStars , 他回来了，我们正在修复 Android 端 #2485 

copy @jacksonh here too

**Comment by StrollStars** [comment]
@jacksonh @sywhb 今天试了下，问题依旧存在，可否再修复下？

**Comment by sywhb** [comment]
> @jacksonh @sywhb 今天试了下，问题依旧存在，可否再修复下？

Hey @jacksonh , may I know if we have new release on Android?

**Comment by StrollStars** [comment]
The problem has been solved.
