### ISSUE TITLE
Improve full-text search result

### ISSUE THREAD

**Issue by sywhb** [omnivore-app/omnivore#2436]
* sort by score, savedAt
* boost title score probably by three `title^3`
* tie-breaker

**Comment by sywhb** [comment]
ref: https://www.elastic.co/guide/en/elasticsearch/reference/7.17/query-dsl-multi-match-query.html#field-boost

**Comment by jacksonh** [comment]
Linking this somewhat related item here as well: https://github.com/omnivore-app/omnivore/issues/2129
