### ISSUE TITLE
How does Omnivore scrape content from articles?

### ISSUE THREAD

**Issue by YousufSSyed** [omnivore-app/omnivore#2467]
Omnivore seems to be very good at scraping content, it can export articles to Obsidian in markdown with the Obsidian plugin. I want to write my own script that downloads articles into markdown like that.

**Comment by jacksonh** [comment]
Hey, you can look at our code on packages/content-fetch and packages/content-handler.

**Comment by YousufSSyed** [comment]
@jacksonh Can you reopen this? I had already spent some time looking at the code but am still unsure, it looks like I'd have to really look at it to understand all of the moving parts. The answer does not seem straightforward.

**Comment by jacksonh** [comment]
Hi, @YousufSSyed how we scrape code isn't really straight forward, its quite complicated and we spend a lot of time refining it. 

I think if you want more details Discord could be a better place to discuss as GitHub issues is more meant for bug + feature requests.
