### ISSUE TITLE
FR: Filter by URL

### ISSUE THREAD

**Issue by jorosy** [omnivore-app/omnivore#2490]

**Comment by jacksonh** [comment]
Hey @jorosy you can try `site:<the url>` like `site:jacksonh.org` it is fulltext search, so just URL parts should work, like `site:https://jacksonh` will also work.

**Comment by jorosy** [comment]
Hi, @jacksonh 
Thanks for the solution. It works well. Cheers .

**Comment by jacksonh** [comment]
awesome, will close this one. Obviously we need more docs.
