### ISSUE TITLE
TTS not working on email newsletter items [iOS app]

### ISSUE THREAD

**Issue by saeedesmaili** [omnivore-app/omnivore#2491]
I've been using the iOS app for the past few weeks. The text-to-speech works fine for the articles I save manually on iOS or the web. Today I sent an email to my omnivore account (to `<my-name>@inbox.omnivore.app` address) and tried to listen to it on iOS as always, but when I tap on the headphone icon on the document's screen, it changes to a play icon but nothing plays. The horizontal TTS bar also appears at the bottom, but with a refresh button, which nothing happens when I tap it.

Then when I go back to the home screen and try to play another normal (non-email) document, the app crashes and closes. The normal document's TTS works fine when I play it without trying out the TTS on the email document.

I'm using the latest version of the app.

**Comment by jacksonh** [comment]
Thanks, any chance you can forward me the email at jacksonh@omnivore.app ?

**Comment by saeedesmaili** [comment]
> Thanks, any chance you can forward me the email at [jacksonh@omnivore.app](mailto:jacksonh@omnivore.app) ?

Done.

**Comment by jacksonh** [comment]
Thanks, just replicated the issue. Quite strange, looking into it more.

**Comment by jacksonh** [comment]
Fix here: https://github.com/omnivore-app/omnivore/pull/2493

**Comment by sywhb** [comment]
TTS should be working for the new newsletter items received

**Comment by sywhb** [comment]
> I can confirm the issue is fixed. Thanks for the quick follow-up!

Thanks for the update!
