### ISSUE TITLE
API,  Obsidian,  dateSaved generate a blank after Date, Bug or Feature?

### ISSUE THREAD

**Issue by lap42** [omnivore-app/omnivore#2507]
hi

i have this Problem with the API between Omnivore an Obsidian.

Result of {{{dateSaved}}} is a "YYYY-MM-DD "

unfortunately I am not able to localise myself whether this space after the date is caused by the API or the plugin

**Comment by jacksonh** [comment]
Hey @lap42 do you mind adding a screenshot too just so we have a bit more context?

**Comment by lap42** [comment]
Thank you for the quick response. After I deleted and completely reinstalled, the error with the space disappeared. I probably parameterised something incorrectly.
Can be closed
