### ISSUE TITLE
Support URL schemes for desktop

### ISSUE THREAD

**Issue by yoghurtdewdew** [omnivore-app/omnivore#2517]
I see there are Omnivore desktop and Omnivore URLs. 

Hope to use Omnivore URL schemes to open pages right in Omnivore desktop!

**Comment by timespaced** [comment]
I have the same request, but for the iOS app.  Right now, omnivore:// will open the app, but it would be great to have a URL scheme (à la Wallabag's app) where you can pass articles from other apps, something like omnivore://add?subject={title}&body={url}

This would allow any number of apps to be able to pass articles to Omnivore from iOS, such as the RSS Reader, Lire.
