### ISSUE TITLE
Add support for youtubetranscript.com 

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#2523]
test case: https://youtubetranscript.com/?v=kvN5_GXlg2Y

**Comment by italovieira** [comment]
Just to know, with this we would be able to take notes of a video as you watch it so you can refer to the video time and the notes later?

**Comment by italovieira** [comment]
With this will we be able to take notes of a video as you watch it so you can refer to the video time and the notes later?

**Comment by jacksonh** [comment]
@italovieira yeah in the first version probably not, but that is something we will add to our YouTube support (which we are starting to roll out this week).
