### ISSUE TITLE
[FR] Pinned and Sort Label Consistency 

### ISSUE THREAD

**Issue by jorosy** [omnivore-app/omnivore#2525]
I would like to suggest a label can be pinned. 

In web app, the Pinned label will pop to top. The other label sorts in alphabetical or custom order via a extra switch button or current label hamburger menu. When label collapse, only the pinned label will be shown.

<img src="https://github.com/omnivore-app/omnivore/assets/5779706/1c1c832d-3f3e-48c0-bd5f-666d782e041f" width="15%">

In IOS, this pinned label can list in top section instead of current design to assign article with label named "Pinned". 
<img src="https://github.com/omnivore-app/omnivore/assets/5779706/838a1858-c01b-4ee9-a701-68399c3ff6ed" width="30%">

please also consider set the label pane to full expand instead of collapse by default to utilize the screen space. 
<img src="https://github.com/omnivore-app/omnivore/assets/5779706/1f9b43c8-bde9-4666-ad99-a589834f2624" width="15%">

**Comment by jacksonh** [comment]
Hey @jorosy just trying to understand this better: do you want to choose the label that is pinned?

**Comment by jacksonh** [comment]
Just implemented a simple part of this, maintaining this state of the viewall value (just in local storage, per device): https://github.com/omnivore-app/omnivore/pull/2547

**Comment by jorosy** [comment]
Hi, @jacksonh 
Yes, I would like to set a label to be pinned. So it will pop to top of label list and persistent in web app, and appear in the top section of IOS. Thanks for considering it.

**Comment by jxstxn1** [comment]
I would like to be able to search for pinned articles with `pinned:true` or something similar.
I had to look into this Issue to find the Pinned Label on the Website, since it wasn't obvious that `pinned` is a label.
