### ISSUE TITLE
Feature request: Bulk actions

### ISSUE THREAD

**Issue by howarddo2208** [omnivore-app/omnivore#2564]
Hi, I'm using android and web app of Omnivore, with the release of RSS, I'm using it and got many items on my Inbox coming from feeds. Many of them I don't want to read and wanting to simultaneously remove/archive them.

I think this is a very important feature, hope you guys can implement this in near future, thank u!

Also, I've used Readwise Reader app before, their bulk action feature looks pretty neat, maybe u can get a reference on it.

**Comment by jacksonh** [comment]
Hi @howarddo2208 on web you can choose `Select Multiple` in the dropdown. We are trying to improve this UX and add it to mobile also.

<img width="764" alt="Screen Shot 2023-07-31 at 15 21 04" src="https://github.com/omnivore-app/omnivore/assets/75189/80b67cc1-5501-43e3-9819-45bfba85aee8">

**Comment by howarddo2208** [comment]
Thank you! It's kinda hard to see and use for end users. Maybe long press gesture or something like control+click and shift+click on Windows would be nice additions to this.

**Comment by jacksonh** [comment]
Thanks @howarddo2208 we're actually trying to ship an "easier to see" version of this right now, especially with people subscribing to too many things.
