### ISSUE TITLE
Request to add feature: toggle marker - to automatically highlight text 

### ISSUE THREAD

**Issue by markky21** [omnivore-app/omnivore#2568]
Hi! 

I have idea for new feature.
I'am using touch device with pen. I would like to be able to toggle the button and when I select text (with pen or with mouse), I would like the text to be highlighted automatically (without having to select the highlight from the context menu). 

What do you think about it? If you need help, I could help you with the implementation.

**Comment by jacksonh** [comment]
Hey, I think I understand it. 

One thing: are you using iOS with the Apple Pen?

**Comment by markky21** [comment]
Nope. I use Surface Go with pen, but this functionality also makes a lot of sense when using a mouse. It would simply speed up the process of highlighting.
