### ISSUE TITLE
[FR] Swipe gesture to archive/delete from the library on Android

### ISSUE THREAD

**Issue by howarddo2208** [omnivore-app/omnivore#2609]
Hi, I would like to suggest adding swipe gesture to archive/delete items on the mobile apps. Maybe swipe left to right to archive and otherwise to delete?

**Comment by codeRSH** [comment]
Yes me too!

**Comment by jacksonh** [comment]
Hi, we have swipe in the library to archive/delete. Do you mean on the reader?

**Comment by codeRSH** [comment]
Hi Jackson,

Thanks for response.

I am using the Android app. I am on the library screen (screen shot attached) and I don't see swipe left or right options here. Currently I have to select each note individually to archive or delete it .

Only swipe down to refresh works.

![Screenshot_20230823-080018.png](https://github.com/omnivore-app/omnivore/assets/4953198/bca5061d-73bf-42f8-bb02-9fcc3b9455fb)


Regards
Ravi

**Comment by jacksonh** [comment]
Ah got it, yeah its a bit more work on Android but we should definitely add this.

**Comment by codeRSH** [comment]
Sure thank you! Will look forward to it.

Also *unrelated feature request* : Is it in pipeline to select multiple
articles to do a 'mass delete/archive' ?

Regards,
Ravi

**Comment by jacksonh** [comment]
yeah we just added that on the web recently, so need to add it on both iOS and Android to match

**Comment by jacksonh** [comment]
Done!
