### ISSUE TITLE
[FeatureRequest] search operator for article source/URL

### ISSUE THREAD

**Issue by kquinsland** [omnivore-app/omnivore#2630]
My motivation for this is to create a more powerful rule set that looks like this:

```pseudo-code
if content.url.host in ['www.siteA.com', www.siteB.com', 'news.siteC.net']:
  apply_label("news")
  apply_label("tech")
```

But it appears **that there is no way to filter by the origin URL for a particular bit of content**.

Example:

Let's say that I add these three articles to my "inbox"

- https://www.androidpolice.com/samsung-galaxy-s24-ultra-telephoto-camera-rumor/
- https://www.theverge.com/2023/8/9/23822742/cadillac-escalade-iq-ev-reveal
- https://security.googleblog.com/2023/08/android-14-introduces-first-of-its-kind.html

And then I search for some terms:

returns the article I expect:

- https://omnivore.app/home?q=verge
- https://omnivore.app/home?q=androidpolice

Does not return anything:

- https://omnivore.app/home?q=theverge
- https://omnivore.app/home?q=verge.com
- https://omnivore.app/home?q=theverge.com
- https://omnivore.app/home?q=androidpolice.com

Returns something, but is not the article I expect:

- https://omnivore.app/home?q=android+police  (this returns the blogspot article was linked above. The article is tagged `android` and the body content does mention `android`)

-----

**The Ask:** Add a new search operator for article origin URL. For my needs, I really only care about the host and not the full URL but I can see some use cases where a user may wish to perform a search over the _full_ url. To this end, can I suggest two search operators:

- `url.host:www.example.com` which searches only the fqdn portion of the URL
- `url:/articles/2022` which searches over the entire/full URL. In _this_ example, I am searching for any content that has `/articles/2022` in the URL.

Thoughts?

**Comment by jacksonh** [comment]
hi @kquinsland can you try `site:verge.com` ?

**Comment by kquinsland** [comment]
> hi @kquinsland can you try `site:verge.com` ?

Thanks @jacksonh ... That works as expected! 

I do not know why I didn't bother _trying_ that **first** / didn't see it as an option and just assumed it wasn't currently possible.

**Comment by jacksonh** [comment]
We need to update the docs I think, along with the onboarding article.
