### ISSUE TITLE
run `trim()` on user input text when creating a new label

### ISSUE THREAD

**Issue by kquinsland** [omnivore-app/omnivore#2641]
This is a _super minor_ bug/issue that I've noticed.
I hit this "bug" on iOS but it probably applies to other platforms as well.

**EDIT:** Yep, same behavior with the [android app](https://play.google.com/store/apps/details?id=app.omnivore.omnivore) as well.

When creating a new label, the keyboard will try to predict a word. If you select the prediction, the text will be updated to the selected word **and an additional white space**.

When the user clicks the "create this label" button, consider trimming the trailing white space off.

To illustrate this, see attached image.

![omnivore-label-issue](https://github.com/omnivore-app/omnivore/assets/1808375/9dc13cde-6fb0-4ab1-9f94-753ef4ea8208)

**To reproduce:**

- Start the "create new label" flow
- Type `Examp` and by now your keyboard should suggest `Example`. Select the suggestion.
- Notice that the keyboard has helpfully added a space as it expects you to keep typing new words.

**Comment by jacksonh** [comment]
- [ ] iOS: https://github.com/omnivore-app/omnivore/pull/2642
- [ ] Android:
- [ ] Web:
