### ISSUE TITLE
[Feature request] Show archived when filtering by label (Webapp)

### ISSUE THREAD

**Issue by emkay5771** [omnivore-app/omnivore#2649]
When setting a filtered category on the side bar, it would be nice to have the option to see all articles within that tag automatically, instead of needing to manually choose "Archived" and then selecting the label. This would be much more similar to the functionality of raindrop, for example, which makes it easier to view all articles even after having read them.

I noticed that this functionality is already implemented in the Android app by having an "All" filter in the top bar. Enabling users to select "All" as the default view, and adding that functionality to the webapp, would be awesome.

**Comment by jacksonh** [comment]
Yeah I guess when we add the ability to customize saved searches we will have that functionality, since you could add `All`, right now what you could to is type `in:all` in your search box and then add your label filter.

**Comment by jacksonh** [comment]
I'll call this done now that you can create saved searches you could create one like "Archived Studying" with the query `in:all label:Studying`
