### ISSUE TITLE
Preserve state when deleting/archiving an article from article view

### ISSUE THREAD

**Issue by thelazyoxymoron** [omnivore-app/omnivore#2667]
Steps to reproduce:

- Sort the articles by saved date in ascending order: `sort:saved-asc`
- Open an article
- Delete/archive the article
- The home page reverts to default state i.e. sorted via recently-added articles

This should go back to custom sorted view.

**Comment by jacksonh** [comment]
Hey just confirming this is on web?

**Comment by thelazyoxymoron** [comment]
Yes, on web

**Comment by jacksonh** [comment]
This should be resolved now as the previous query is cached
