### ISSUE TITLE
Uploading local PDF files fails

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#267]
Currently we have a bug because we don't support uploading local files. We treat the `file://` URL as a URL and silently fail on the backend.

`scrapeURLOnly does not throw an error for "file://" URLS`

Steps to reproduce:

1. Save a PDF to your google drive
2. Open Drive app on iOS
3. Tap the `...` menu in top right
4. Select `Send a Copy` and choose Omnivore
5. You will see a `Saved to Library`

**Comment by jacksonh** [comment]
Investigating this one a bit more. It might actually be uploading and then getting messed up on the backend.

**Comment by jacksonh** [comment]
Hmm, can't replicate at all after running in the debugger.

**Comment by satindar** [comment]
I think we're good now after all the pdf upload improvements and fixes.

**Comment by jacksonh** [comment]
:nice:
