### ISSUE TITLE
[Feature Request] Ability to rename email subscriptions

### ISSUE THREAD

**Issue by bustinbung** [omnivore-app/omnivore#2689]
New user here. I've been migrating some of my email newsletters to Omnivore, and noticed that some of my newsletters aren't named properly. I know that pulling the newsletter name from the email sender's name works most of the time, but in this case, I wish I was able to rename a newsletter within Omnivore. For example, The Verge's _Installer_ newsletter is named "David Pierce," the author of the newsletter. While this isn't a big deal for now, I can see this becoming confusing in the future.

<img width="865" alt="image" src="https://github.com/omnivore-app/omnivore/assets/22670587/e255bac6-3e46-4ed1-8184-3c8c33fe7e82">

**Comment by jacksonh** [comment]
Thanks, maybe an easy way we can handle this is adding a "Display Name" field that users can customize, and then we display that if its set, and fallback to our internal name if its not set. The one sort of tricky issue I see is we also allow searching by subscription name, so we might have to fallback there too.

It makes a lot of sense to do this though, the Subscriptions view is a bit of a jumbled mess right now.

**Comment by jacksonh** [comment]
/cc-ing @sywhb as it goes along with some data improvements we are working on.

**Comment by sywhb** [comment]
@jacksonh Yeah, we actually have the API to update the name of the subscription but the UI is not ready yet.

Previously we used the author's name as unique ID for the subscription but we are now using the author's email address for that so changing the name of the subscription is totally fine.

I will add another field `author` to the subscription db table to hold the internal name too

**Comment by jacksonh** [comment]
> @jacksonh Yeah, we actually have the API to update the name of the subscription but the UI is not ready yet.
> 
> Previously we used the author's name as unique ID for the subscription but we are now using the author's email address for that so changing the name of the subscription is totally fine.
> 
> I will add another field `author` to the subscription db table to hold the internal name too

Oh so querying for a subscription should use `subscription:<author name>` right now it uses `subscription:\"${item.name}\"` on the web.

**Comment by sywhb** [comment]
> > @jacksonh Yeah, we actually have the API to update the name of the subscription but the UI is not ready yet.
> > Previously we used the author's name as unique ID for the subscription but we are now using the author's email address for that so changing the name of the subscription is totally fine.
> > I will add another field `author` to the subscription db table to hold the internal name too
> 
> Oh so querying for a subscription should use `subscription:<author name>` right now it uses `subscription:\"${item.name}\"` on the web.

I think both make sense. Should we support both `subscription_author:<author name>` and `subscription:<display name>`?

**Comment by jacksonh** [comment]
> > > @jacksonh Yeah, we actually have the API to update the name of the subscription but the UI is not ready yet.
> > > Previously we used the author's name as unique ID for the subscription but we are now using the author's email address for that so changing the name of the subscription is totally fine.
> > > I will add another field `author` to the subscription db table to hold the internal name too
> > 
> > 
> > Oh so querying for a subscription should use `subscription:<author name>` right now it uses `subscription:\"${item.name}\"` on the web.
> 
> I think both make sense. Should we support both `subscription_author:<author name>` and `subscription:<display name>`?

yeah ideally both would be nice

**Comment by pradeepmurugesan** [comment]
@sywhb  anyone actively working on this ? I can give it a shot
