### ISSUE TITLE
On latest iOS beta swipe make the app unresponsive

### ISSUE THREAD

**Issue by bitboxer** [omnivore-app/omnivore#2690]
I know reporting things on a beta version of iOS is kinda meh, but wanted to do so anyway.

If I swipe left to go to the previous screen, the app gets unresponsive on my  device. Cannot click anywhere any more. Using the back buttons works.

**Comment by jacksonh** [comment]
hey thanks, yeah a few people have reported this. I spent a bit of time on it this weekend and think i at least understand the issue, I hope that I have time to resolve it this week as its getting closer to launch date.

**Comment by jacksonh** [comment]
Fixed, has created a few issues but hopefully as iOS17 stabilizes we can improve
