### ISSUE TITLE
Unable to subscribe directly to TLDR newsletter through Omnivore email address.

### ISSUE THREAD

**Issue by bustinbung** [omnivore-app/omnivore#2694]
When subscribing to the [TLDR newsletter](https://tldr.tech/), they ask you to reply to the email to confirm the subscription. Through Omnivore's current email implementation, it's impossible to reply and successfully confirm the subscription.

![image](https://github.com/omnivore-app/omnivore/assets/22670587/6301abd1-7e48-42cc-8e71-4f99082dfb8a)

**Comment by jacksonh** [comment]
> When subscribing to the TLDR newsletter

hi can you describe the issue more?

**Comment by bustinbung** [comment]
Just edited, sorry! Hit enter on accident.

**Comment by jacksonh** [comment]
oh TLDR says they need you to reply but they just put that in there to get around spam controls by email providers. They don't actually require it.

**Comment by bustinbung** [comment]
Interesting, I haven't been receiving emails from them into my inbox. Should I try subscribing again?

**Comment by bustinbung** [comment]
Resubscribing sent me a different confirmation email than before. Maybe it had something to do with clicking the "update subscription preferences" link?

**Comment by jacksonh** [comment]
@bustinbung how long ago did you subscribe? I'll check on this again, but I know a bunch of people use it. Maybe they've changed something in the last week or so.

**Comment by bustinbung** [comment]
First time I used the Omnivore email address with TLDR was the 25th. Will update if I get it tomorrow morning.

**Comment by jacksonh** [comment]
Yeah I don't think they send on the weekends, so maybe you just missed the 25th cut off. 

One place you can also look is https://omnivore.app/settings/emails/recent

**Comment by bustinbung** [comment]
If that's the case, then it was probably just that. I'll check in the morning and see. Thanks!
