### ISSUE TITLE
Sort by estimated reading time

### ISSUE THREAD

**Issue by jml** [omnivore-app/omnivore#2696]
Hello! I've just switched from Pocket to Omnivore and love it. Thanks to all involved!

I would love to be able to sort the main inbox & library views by estimated reading time. There are a couple of use cases for this.

The first is that I've got a pretty big reading backlog, and sorting by reading time would let me read the shortest items first, thus letting me clear off a lot of items in one reading session, making me feel like I'm making good progress.

The second is that sometimes I have a rough idea of how much time I have, and I'd like to be able to read something, say, about 20 minutes long. Sorting by read time would make such a thing easier to find. I guess _filtering_ by time would also address this.

**Comment by jacksonh** [comment]
Thanks, we are updating our internal data model and it makes sense to include this feature with that update. Or right after that update.

**Comment by jml** [comment]
Thanks! I tried using this filter just now (2023-10-10 07:17+00:00), and it came up with no matches.

e.g. https://omnivore.app/home?q=in%3Ainbox+wordsCount%3A%3C%3D100000 and https://omnivore.app/home?q=wordsCount%3A%3C%3D100000

<img width="824" alt="Screenshot 2023-10-10 at 08 17 54" src="https://github.com/omnivore-app/omnivore/assets/125674/3313f112-fcd1-49e8-8e90-51f27302f48f">
<img width="698" alt="Screenshot 2023-10-10 at 08 18 06" src="https://github.com/omnivore-app/omnivore/assets/125674/3a9b98d7-bd62-4e40-ab61-ce92c40bc4fe">

Is it just that the new version hasn't been deployed yet?

**Comment by jacksonh** [comment]
Hey @jml yeah not quite in production yet, but getting close. Just a bit of a deployment logjam as we finally wrap up this data migration. 

I just tested your queries in our staging environment though and they worked for me. So getting really close.

**Comment by jacksonh** [comment]
I'll open just until its deployed since this deployment could take longer than norma.

**Comment by sywhb** [comment]
sorry, github automatically closes issues again...
