### ISSUE TITLE
Auto-highlighting on selection in iOS

### ISSUE THREAD

**Issue by owengot** [omnivore-app/omnivore#2720]
The Matter application on iOS does this particularly well - simply swiping over the text highlights it. Wondering if this could be implemented eventually?

**Comment by jacksonh** [comment]
@owengot you can enable this by hitting Advanced on the bottom of the reader display settings (where you adjust your font). Look for `Auto Highlight Mode`

Note that depending on your device size you might need to slide the settings up a bit to see the advanced options.

**Comment by jacksonh** [comment]
@owengot I'll close this one but let me know if you were expecting something a bit different.
