### ISSUE TITLE
Feature Request : button to filter by preset reading time

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [omnivore-app/omnivore#2723]
Hi,

Omnivore is already near perfect, this will not stop me from suggesting perfection :)

I frequently have blocks of time at my disposal and would love to filter my reading queue by the time to read.

The UI would be a clock next to the filters. Clicking on it would toggle a popup window that allows to set minimum and maximum reading time. Those presets would be remembered across uses.

Of course if I specify article between 5 and 30 minutes, I expect the suggestion to include articles with such reading length, but also for example an article 50 minutes long, of which I read 50% (hence I only have 25 minutes left, which matches the time filter).

What do you think?

**Comment by jacksonh** [comment]
Thanks, i see this as part of saved searches + more filtering options, so you could easily create a "Short reads" type saved search.

**Comment by thiswillbeyourgithub** [comment]
Hello again. Just bumping this feature request as I think it would be awesome and does not sound too complicated to add so I just want to avoid this getting burried :)

In short:
- Pretty much just adding filters for the reading time would be awesome.
- The extra mile would be to add another filter for "remaining reading time" that would take the reading time minus the read proportion.
Have a nice day!

**Comment by fbtot** [comment]
There is a [new filter](https://blog.omnivore.app/i/139949692/new-search-filters) called `wordsCount` that allows you to filter articles based on word count (i.e. read time):

> wordsCount:<=1000: will return articles with less than 1001 words. 
>
> wordsCount:>=1000: will return articles with more than 1000 words.
>
> With the last two filters, you can now easily create saved searches such as "Short Reads" or "Long Reads".

You can also it with [rules](https://docs.omnivore.app/using/rules.html) and label automatically the articles when you add them.

**Comment by thiswillbeyourgithub** [comment]
Thank you so much.

Here's what I end up with:
0 to 5 minutes: in:inbox wordsCount:<=1500 sort:wordsCount-desc

5 to 15 minutes: in:inbox wordsCount:>=1500 wordsCount:<=3000 sort:wordsCount-desc

15+ minutes: in:inbox wordsCount:>=3000 sort:wordsCount-asc
