### ISSUE TITLE
Subscribing to newsletters which require a reply for verification

### ISSUE THREAD

**Issue by mohit2152sharma** [omnivore-app/omnivore#2765]
Hi, 
I am using omnivore app and it's email id to subscribe to newsletters, but some of the newsletters require me to reply to their welcome message for verification. For example, newsletters like TLDR, ByteByteGo etc etc. 
I assumed that these welcome messages will be forwarded to my email id (which I used for signup), but it's not the case. These welcome messages are loaded in the app as newsletters.

Is there a way to reply to these newsletters from within the app?

**Comment by jacksonh** [comment]
Hi, both TLDR and ByteByteGo do not require a reply, they just ask you to to work around Gmail-style spam rules which will hide senders you haven't interacted with before. 

I'll keep this ticket open as it is a valid issue, but 99% of newsletters that ask for a reply don't actually require one. Notice how in TLDR they actually state you don't need to reply if using a third party reader.

**Comment by qkxie** [comment]
Some newsletter need I click the verify url to make sure this is my email. If I do not click this url, it will not send newsletter to me.

**Comment by jacksonh** [comment]
Hi @qkxie you should be able to find those newsletters welcome messages in your recent emails. Login on the web and go to this page: https://omnivore.app/settings/emails/recent -- from there you can open the email and click the button.

**Comment by qkxie** [comment]
Thanks

**Comment by freybe** [comment]
HI,
My Gmail verification email will not load in the settings/emails/recent emails screen, it just loads a blank screen.
Other emails load fine. I have tried resending gmail verification email but same result.
Any help would be appreciated :)

<img width="1233" alt="omniv" src="https://github.com/omnivore-app/omnivore/assets/153485391/dea24f53-e393-4213-809a-58db7adeeafa">
