### ISSUE TITLE
Create profile view on Mac OS not scrolling

### ISSUE THREAD

**Issue by LeTarrask** [omnivore-app/omnivore#2788]
When trying to create a new account via the Mac OS app, the complete registration form is not displayed, and it's not possible to scroll down.

It also happens with the create an account with email view.

<img width="655" alt="Screenshot 2023-09-21 at 11 29 22" src="https://github.com/omnivore-app/omnivore/assets/14889546/bceae7b7-9332-4370-b772-047fdcf353c9">
![Screenshot 2023-09-21 at 11 17 55](https://github.com/omnivore-app/omnivore/assets/14889546/2e2debc0-b004-4193-902b-a0d5c00e5c0a)

Maybe it's just a matter of adding a ScrollView {} ?

**Comment by jacksonh** [comment]
Yikes

**Comment by jacksonh** [comment]
It does scroll for me, but correct solution is to make it taller. Submitting a fix now. Thanks for reporting!

**Comment by jacksonh** [comment]
I guess just profile scrolled. Ok, all fixed and adding some loading spinners while at it. Thanks again for the report. 

https://github.com/omnivore-app/omnivore/pull/2799
