### ISSUE TITLE
Imported articles without 'published_at' Unix time show '54 years ago' but Omnivore knows the correct publish date 

### ISSUE THREAD

**Issue by DavidMetcalfe** [omnivore-app/omnivore#2794]
I exported all 15,279 articles from my Pocket account a few nights ago. The exported HTML only has the URL, tags, and saved Unix time, but not the Published Unix time. I converted the HTML into a CSV, following the format detailed in the [Importing docs](https://docs.omnivore.app/using/importing.html#importing-csv-files). Import was successful and I wasn't surprised to see the articles in the Inbox showing 54 years since there was no Unix time provided in the CSV (note the top article in the screenshot was saved after the import, directly with the browser extension):

<img width="996" alt="image" src="https://github.com/omnivore-app/omnivore/assets/80915/89fe98a5-8754-480d-b8e6-038b6bc66815">

However, in each of these articles, I can see there is a **Published At** date/time stamp. So, it appears the system is storing and showing a different value in the Inbox view than in the Article view.

<img width="979" alt="image" src="https://github.com/omnivore-app/omnivore/assets/80915/3dbe664a-08cd-4928-b70d-2dc6bd4bc698">

Hopefully I'm just misunderstanding some basic about the system, but couldn't see prior issues raised on this so here it is.

**Comment by jacksonh** [comment]
Thanks, do you mind pasting just one line from your CSV also so i can verify the formatting?

**Comment by DavidMetcalfe** [comment]
Certainly. Here's one line with SUCCEEDED and another with ARCHIVED state.

```
url,state,labels,save_at,published_at
https://blog.google/outreach-initiatives/arts-culture/the-latest-from-nasas-search-for-life-beyond-earth/,SUCCEEDED,"[computer science,google,the keyword]",1686748885,
http://www.chron.com/news/houston-texas/article/Online-hackers-threaten-to-expose-cartel-secrets-2242068.php,ARCHIVED,,1570646666,
```

**Comment by sywhb** [comment]
thanks @DavidMetcalfe, we use the unix timestamp in milliseconds as stated in the docs here: https://docs.omnivore.app/using/importing.html#importing-csv-files

```
url,state,labels,saved_at,published_at
https://jacksonh.org,SUCCEEDED,"[Handsome Developers, Profile Page]",1614556800000,1614556800000
```

**Comment by DavidMetcalfe** [comment]
An oversight on my part, granted, but what is the behaviour when the Unix timestamp is in Seconds format instead of Millisecond format? Does the system just assume January 01, 1970? The import showed no errors or warnings, so it seems like this could be improved either way.

**Comment by sywhb** [comment]
> An oversight on my part, granted, but what is the behaviour when the Unix timestamp is in Seconds format instead of Millisecond format? Does the system just assume January 01, 1970? The import showed no errors or warnings, so it seems like this could be improved either way.

Thank you. you are right about the warnings or error messages. I will update the validation and create more detailed ones.

**Comment by sywhb** [comment]
Also should probably ignore invalid timestamp format instead of assuming January 01, 1970
