### ISSUE TITLE
Handle text only newsletters

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#2801]
Some newsletters don't contain an HTML element, for these, if text is present we should create a text element using markdown to HTML

**Comment by jacksonh** [comment]
This is where the error manifests: https://github.com/omnivore-app/omnivore/blob/4bd2ac2ac37fe5798741cdc8ce6921aed165c18c/packages/content-handler/src/content-handler.ts#L166

**Comment by sywhb** [comment]
Thanks for the details. I'm working on it @jacksonh
