### ISSUE TITLE
[Feature Request] Can highlight direclty from a website

### ISSUE THREAD

**Issue by ekarious** [omnivore-app/omnivore#2817]
When you want to save a specific sentence, you need to save the page then go to the page on Omnivore and highlight it there.

It would be better if we could just select a text on a website directly and right click "Save  highlight to Omnivore".

If no page save already concerning this website, then one is save and the highlight added.
If already exists, then just add the new highlight to the omnivore version of the page.

So we do not have to constantly switch to Omnivore to do highlights.

**Comment by jacksonh** [comment]
Thanks, we did add this on iOS, so it shouldn't be too hard to add on the web too.

**Comment by Kitefr** [comment]
@jacksonh I notice it was now possible to highlight directly from the website without have to save to omnivore first.
So it seems it was added.
Can you verify so we can close this ticket ? Thanks

**Comment by jacksonh** [comment]
Actually TBH, meant to not release this quite yet but had a bit of an emergency Chrome fix that got in the way.

**Comment by Kitefr** [comment]
Ok, I will continue testing this on my end to see if I can catch weird behaviour

**Comment by mdbraber** [comment]
@jacksonh is this (hidden) feature still available
on iOS? Would love to help testing as this is my exact workflow.

**Comment by HealsCodes** [comment]
same here - being able to share just a highlight to omnivore on iOS is the last missing part for my mobile read-it-later workflow
