### ISSUE TITLE
Choose highlight color using Android app.  

### ISSUE THREAD

**Issue by theotheo** [omnivore-app/omnivore#2820]
Tell me please, is this possible to use another color that yellow to highlight text with Android app?

**Comment by jacksonh** [comment]
Hi, right now its not possible to change the color in the native apps.

**Comment by remychantenay** [comment]
@jacksonh out of curiosity, do you have designs for this? Or even a vague prototype? A drawing? 😄

**Comment by jacksonh** [comment]
Hey, that's actually part of the hold up, but the Web design is probably really close to what we want. Two screenshots attached
<img width="790" alt="Screenshot 2023-10-05 at 20 56 42" src="https://github.com/omnivore-app/omnivore/assets/75189/95e8b953-e088-4f12-b287-4d97b89d0493">
<img width="841" alt="Screenshot 2023-10-05 at 20 56 52" src="https://github.com/omnivore-app/omnivore/assets/75189/99d58d4a-7d40-4143-8f4a-c4abd3effa01">

**Comment by Lorite** [comment]
Hi. Are there any updates on this issue? 😊

**Comment by remychantenay** [comment]
Hey @Lorite, 

I sort of put that one on the back burner and eventually forgot. I am pretty busy these days so it's hard for me to find time to contribute, but I will try to squeeze that in for a coming weekend.

From what I remember, I was almost there.
