### ISSUE TITLE
OPML import/export for RSS feeds.

### ISSUE THREAD

**Issue by Southpaw1496** [omnivore-app/omnivore#2870]
[OPML](https://en.wikipedia.org/wiki/OPML) is an XML format that is commonly used by RSS readers to exchange lists of feeds. If Omnivore had support for OPML importing, it would allow users to migrate an existing list of RSS/Atom feeds into Omnivore without having to do them all manually. An export feature is less critical, but it would give users peace of mind that they can retrieve their feeds and migrate to another application at any time, making them more likely to try Omnivore over their existing solution.

**Comment by cocoonkid** [comment]
sorry, bumping this :-) I know that's not helpful but imho Omnivore without this basic feature is neither.

**Comment by Benbinbin** [comment]
In my opinion, it would be great if Omnivore could support both importing and exporting OPML files at the same time. This way, Omnivore would be seen as more welcoming and accommodating, without any intention of luring users onto the platform. We understand how important it is for users to have control over their data, so we ensure that they can easily back up their OPML files whenever they need to.

**Comment by Jolg42** [comment]
I really like Omnivore but I'm not ready to switch without this feature honestly.

After a quick look, I found the following
- the current add feed page: https://github.com/omnivore-app/omnivore/blob/main/packages/web/pages/settings/feeds/add.tsx uses `subscribeMutation()`
- `subscribeMutation()` https://github.com/omnivore-app/omnivore/blob/main/packages/web/lib/networking/mutations/subscribeMutation.ts#L30
- its resolver is here https://github.com/omnivore-app/omnivore/blob/main/packages/api/src/resolvers/subscriptions/index.ts#L174

Along the way I found this important detail, the maximum number of feeds is hard-coded, I can understand why it exists though it would be better to have this configurable for self-hosting I think.
https://github.com/omnivore-app/omnivore/blob/b464734cc9c3bdff4f605f6674566001bb3ef7ba/packages/api/src/resolvers/subscriptions/index.ts#L223-L224C1

**Comment by Jolg42** [comment]
Additionally
- Here is the spec for OPML: http://opml.org/spec2.opml
- This looks like an interesting implementation of an import & export https://github.com/chhoumann/PodNotes/blob/83f3dd96e0f7b071baf2e7f9796f6ea52c4650e9/src/opml.ts#L63

**Comment by cori** [comment]
TO build on @Jolg42's comment I want to try Omnivore as a replacement for feed reading in another app, from where I can export my OPML. I have the OPML, but manually adding feeds made me lose momentum after a dozen or so and I haven't been back to Omnivore since. 

If heavy RSS users are a target audience I don't think you'll get that many when onboarding is so painful.

**Comment by edleeman17** [comment]
I built a quick script for importing OPML into Omnivore, you can find it [here](https://github.com/edleeman17/omnivore-opml-import)
