### ISSUE TITLE
Bug: on iOS, any vertical swipe returns to the last screen

### ISSUE THREAD

**Issue by felixbinder** [omnivore-app/omnivore#2880]
On the iOS app, any small swipe to the right anywhere in reader view returns to the list of articles. This is frequently triggered during normal scrolling and makes reading quite frustrating. 

To reproduce: open article on iOS, swipe slightly to the right in the middle of the screen. Even very short swipes trigger it. 

Expected: nothing happens. Only swipes starting on the left edge of the screen should return to the previous screen

Actual result: the article closes and the article list view is opened.

This is on version 1.33.0 in iOS 17.0.2 on an iPhone 15 Pro and on an iPad Air.

**Comment by felixbinder** [comment]
(I hope this is the right place for iOS app request/bug reports, I couldn't find the iOS repo)

**Comment by jacksonh** [comment]
Hey thanks @felixbinder this had been tweaked a bit in 1.33.0 , The logic is 30% of the screen distance or a high velocity swipe. Can you take a guess at which is triggering this for you? Do you think you have a longer slower drag, or a quick flick? I can keep playing with the tolerances.

**Comment by felixbinder** [comment]
It was mostly a quick flick that was rapid, but only travelled a short distance

**Comment by justinsteven** [comment]
+1 from me. In my experience I think it's being triggered by high velocity swipes while reading fenced code blocks with long lines

**Comment by jacksonh** [comment]
I think this is resolved now with the new swipe gestures.
