### ISSUE TITLE
Highlight Resurfacing

### ISSUE THREAD

**Issue by TariqMK** [omnivore-app/omnivore#2881]
Having a way to get (say) a random 5 of our highlights a day presented within the app would be great.

It would help us retain what we read.

**Comment by northgardner** [comment]
+1. This sounds like part of what Readwise does. If this is impractical to build into Omnivore, it would be great if Readwise could ingest Omnivore highlights. I would pay for that.

**Comment by johnlunney** [comment]
I'd love even a limited version of this.

**Comment by jacksonh** [comment]
> +1. This sounds like part of what Readwise does. If this is impractical to build into Omnivore, it would be great if Readwise could ingest Omnivore highlights. I would pay for that.

Hey we do have a Readwise integration that will send your highlights from Omnivore to readwise, check it out on the integrations page on the web.
