### ISSUE TITLE
Kindle Highlight Import

### ISSUE THREAD

**Issue by TariqMK** [omnivore-app/omnivore#2882]
Having the ability to import Kindle highlights (via MyClippings.txt especially!) would be great.

Having Omnivore as the all in one reading app for articles and Kindle is the dream!

**Comment by jgodoy** [comment]
Processing the HTML exported file would also be nice. And applying some templates over the received date.

**Comment by geothefaust** [comment]
This would be most welcome. It's the only missing feature stopping me from completely switching over from another tool to Omnivore. 👍

**Comment by ShaneNZ** [comment]
Agreed, would love this (and the following bit of then syncing them out to Obsidian).
