### ISSUE TITLE
Can not upload .epub 

### ISSUE THREAD

**Issue by ourines** [omnivore-app/omnivore#2894]
My EPUB file won't upload.

This is the epub mimetype content I viewed using decompression software.
![image](https://github.com/omnivore-app/omnivore/assets/15307679/a42b3f9d-158b-4516-8182-99142e528868)

When I drag and drop epub to omnivore, an unsupported `application/epub` format appears.
<img width="644" alt="image" src="https://github.com/omnivore-app/omnivore/assets/15307679/575e6004-256a-4b89-80c9-db0b5a625e56">

However, I use the Choose Your Files button to upload an EPUB and it works fine.

'application/epub+zip' is used in this line of the source code, but it becomes 'application/epub' when dragged.
https://github.com/omnivore-app/omnivore/blob/b4528153d3b60b862b0c11e3187720091ba02fb1/packages/web/components/templates/UploadModal.tsx#L305

Can I add 'application/epub' to the 'accept' array?

**Comment by jacksonh** [comment]
Hi, epubs are not currently support. We do have some functionality for uploading but thats just for internal testing now.
