### ISSUE TITLE
Use video duration for estimating reading time

### ISSUE THREAD

**Issue by bomberstudios** [omnivore-app/omnivore#2896]
When saving a link to a page with a video to watch it later, it would be super nice if Omnivore used the duration of the video to estimate the reading time (at least on pages where there’s clearly not a lot to read, like Vimeo or YouTube).

At the moment, I assume Omnivore takes into account the text surrounding the video itself, and seems to give an estimate of “1 min read” for most of the videos I’ve saved. In this example, the video is around 18 minutes:

<img width="1020" alt="SCR-20231009-mjsk" src="https://github.com/omnivore-app/omnivore/assets/3832/1d4851a0-13b7-4c56-8b90-393e7ce60512">

**Comment by jacksonh** [comment]
Thanks @bomberstudios we will probably split this one up into separate pieces for youtube and vimeo. I know it shouldn't be a problem using the youtube data we get, but I haven't looked at vimeo APIs yet.

**Comment by bomberstudios** [comment]
Thanks for taking a look! 🙌🏼
