### ISSUE TITLE
BUG: Web: Cannot change Label description

### ISSUE THREAD

**Issue by juanbretti** [omnivore-app/omnivore#2934]
Using the web application, I am not able to edit or remove the labels descriptions.
I have the following at https://omnivore.app/settings/labels

![image](https://github.com/omnivore-app/omnivore/assets/10165911/3c60ff96-8b49-485b-88e0-266f28e3ab48)

And I am not able to remove or change the description for "Newsletter" or "RSS".
Any ideas why?
Thanks!

**Comment by juanbretti** [comment]
I think this should be marked as [[BUG]].

**Comment by DvdB66** [comment]
Problem persists and exists on IOS app, too. When I am in Omnivore app, I can only ever “delete” or “create a new” label, but there is no way to edit those already existing.
