### ISSUE TITLE
Bug on iOS - unable to scroll for a few seconds after saving a new link

### ISSUE THREAD

**Issue by lily-mara** [omnivore-app/omnivore#2935]
Environment
- iOS 17.0.3
- Omnivore 1.34.0

Steps to reproduce
1. open an article in Omnivore that contains a link
2. click on the link
3. click "save to omnivore" in the context menu
4. find that you are unable to scroll the article for several seconds until the "saving link" toast disappears

**Comment by jacksonh** [comment]
Thanks, i have a feeling this is our new snackbar library on iOS. The thing that popsup up a "Link Saved"

**Comment by jacksonh** [comment]
ok just fixed this one locally. Should be in the next iOS beta tonight
