### ISSUE TITLE
feature req: scroll with volume buttons

### ISSUE THREAD

**Issue by nergdron** [omnivore-app/omnivore#2936]
hi omnivore folks,

I've just been getting into the app, primarily on android. I *really* like it, but there's one critical feature that's missing for me for reading on my phone: scrolling the page using the volume buttons. most e-reader apps I use support this already, and it makes a huge difference, means I can comfortably read one handed instead of two. it'd be lovely if the mobile apps supported this feature as well.

thanks!

**Comment by jacksonh** [comment]
Thanks, cool idea that i haven't heard of.

**Comment by nergdron** [comment]
Kindle's app does it, and so does Tachiyomi, and a few open source ebook readers. it's such a nice quality of life thing that I hope will be easy to implement here. and honestly the only suggestion I have for the app so far, it works awesome.

**Comment by nergdron** [comment]
yayy! thanks so much!
