### ISSUE TITLE
Adding RSS feed -  bad request

### ISSUE THREAD

**Issue by shawn1thompson** [omnivore-app/omnivore#2956]
I've had some difficulties adding some feeds with an error showing up:

`There was an error adding new feed: Bad request`

Currently, I'm trying to add https://blog.filen.io, but there have been others. I can add them if I come across more. For a possible solution, I had the same problem with the Android [Feeder app](https://github.com/spacecowboy/Feeder), and they somewhat recently fixed the issue.

**Comment by shawn1thompson** [comment]
That worked. In Firefox on Android, the complete URL didn't show. How would I discover that for others with the same difficulty?

**Comment by jacksonh** [comment]
oh, i looked at the source code of their page. A lot of sites that expose RSS will have something like this in their page content.

```
<link rel="alternate" type="application/rss+xml" title="" href="https://blog.filen.io/rss/">
```

in the future we should do all that automatically and parse it out for you.

**Comment by shawn1thompson** [comment]
Sounds good. Thank you.

**Comment by jacksonh** [comment]
I will close this one out, since somewhere there is an issue for parsing those out. Will try to link it up tomorrow. Hope the app works out for you!

**Comment by shawn1thompson** [comment]
Opening with a couple others if you get time to check them:
`
https://www.abuaminaelias.com/dailyhadithonline/
https://www.abuaminaelias.com/feed/`

By the way, I'm loving the app so far. Thank you.
