### ISSUE TITLE
Page not found(Android) and can't extract twitter text and image (Android and windows)

### ISSUE THREAD

**Issue by shriar** [omnivore-app/omnivore#2988]
Original Link = `https://blog.abacus.ai/blog/2023/10/19/open-source-llms-fine-tunes-and-rag-based-vector-store-apis/`

Omnivore convert this link to = `https://blog.abacus.ai/blog/2023/10/19/open-source-llms-fine-tunes-and-rag-based-vector-store-apis/?s=09`

And show page not found on android when I share from twitter(X).

**Comment by jacksonh** [comment]
Hi @shriar so someone posted that link on Twitter, and in the twitter android app you shared that to Omnivore?

**Comment by shriar** [comment]
Yes.

**Comment by shriar** [comment]
Hi @jacksonh, I notice that when I share any link from twitter(actually twitter open the link in browser and then share),  `?s=09` is automatically added at the end of the link.  (This may be helpful.)
