### ISSUE TITLE
Highlights can disappear when positions are changed on Android

### ISSUE THREAD

**Issue by shriar** [omnivore-app/omnivore#3002]
If I remove one highlight, all the highlights are removed on the android app.

**Comment by jacksonh** [comment]
@shriar if you reload the page are they visible again?

**Comment by shriar** [comment]
Yes, you are right. They all are visible again. They were not actually removed, just not visible.

**Comment by jacksonh** [comment]
Phew that is good. I will leave this open as I think i know the issue. Obviously not good to have them temporarily dissapear.

**Comment by jrswab** [comment]
I have experienced the non-visible highlights on Android after adding a note to a highlight as well.

**Comment by jacksonh** [comment]
yeah we've had a few reports. I wonder if this was related to some work done to add the multi-coloured highlights to Android.

**Comment by remychantenay** [comment]
Out of curiosity, did the issue disappear after removing the experimental multi-color highlights?

**Comment by sonjoonho** [comment]
This also occurs when the system theme is changed from light to dark or vice versa.
