### ISSUE TITLE
UI bug on macOS app

### ISSUE THREAD

**Issue by marr00n** [omnivore-app/omnivore#3008]
v1.32.0 (93)
On the macOS app, where the articles are previewed on the left, a number of horizontal break lines appear between articles instead of just one.

I have tried uninstalling and reinstalling which did not fix the error. Similarly logging out and logging in did not help either. Nor did restarting my Mac.

Thanks for your help when able.

<img width="487" alt="Screenshot 2023-10-24 at 7 22 53 pm" src="https://github.com/omnivore-app/omnivore/assets/141917830/2b3997ab-1684-4183-84f0-6aff2125d97b">

**Comment by jacksonh** [comment]
@marr00n do you mind posting your version number also?

**Comment by marr00n** [comment]
Yes, rookie of me.
1.32.0 (93) on Mac w apple silicon. Sanoma 14.0

**Comment by jacksonh** [comment]
I do have a 1.33 version ready to be submitted, I can't replicate with this one, but I haven't seen that issue before either.

**Comment by marr00n** [comment]
just touching base when you're submitting 1.33, or is it delayed on the App Store approval side?

What I've realised is that they may be an artifice of the 'selected article's' lighter grey background. If you see the screen shot above, the light grey background for the selected article forms the bottom of the line triplet above, and the top of the line triplet below.
