### ISSUE TITLE
Code readability Issue in Omnivore

### ISSUE THREAD

**Issue by shriar** [omnivore-app/omnivore#3016]
When I use the app on a website that contains code, the extracted data does not display the code in a Coding format or structure. It will be helpful, if it does.

**Comment by jacksonh** [comment]
Hi it will depend on how the site has embedded it. Do you mind sharing a link that didn't work?

**Comment by shriar** [comment]
Link :
***@***.***/multi-head-attention-7924371d477a

**Comment by shriar** [comment]
Link : https://medium.com/@hunter-j-phillips/multi-head-attention-7924371d477a

**Comment by shriar** [comment]
Hi @jacksonh, I think omnivore recognize the code in the website, but background does not change and the font is quite similar. So it's not quite distinguishable.
