### ISSUE TITLE
Unrendered Markdown in iOS Push Notification Settings

### ISSUE THREAD

**Issue by nhandler** [omnivore-app/omnivore#3018]
In version 1.34 of the iOS application, if you open up `Profile -> Push Notifications`, it says:

> Enabling push notifications gives Omnivore
> device permission to send notifications,
> but you are in charge of which notifications
> are sent.
> Push notifications are triggered using your
> [account rules](https://omnivore.app/
> settings/rules) which you can edit online.

The included Markdown is not being rendered.
![IMG_2366](https://github.com/omnivore-app/omnivore/assets/102499/2f39d6d8-3ef3-4378-8cfd-157495d127ca)

**Comment by jacksonh** [comment]
Thanks, seems like an iOS17 change

**Comment by jacksonh** [comment]
Fix in here https://github.com/omnivore-app/omnivore/pull/3037/commits/afe25c34fe30142f69aa1833a39582a9bfd1aa5e

**Comment by jacksonh** [comment]
I'll close this one out now even though the app is still in review.
