### ISSUE TITLE
Label can't be added [Android] 

### ISSUE THREAD

**Issue by shriar** [omnivore-app/omnivore#3026]
Labels can't be added to note from android app. But added labels from web app, can be removed from android.

**Comment by hiepph** [comment]
I can't create a new label in the Android app, either.

**Comment by hemanti0503** [comment]
Same here. I can create them and they show up in the article, but as soon as I close it and go back, the labels are gone.

**Comment by jacksonh** [comment]
Can you add some details? Are you adding from the library or the reader view? And how are you creating the new label? (Typing it in vs using the button to create one)

**Comment by hiepph** [comment]
> Are you adding from the library or the reader view?

Reader view.

>  And how are you creating the new label? (Typing it in vs using the button to create one)

In reader view, I click three dots, and then "Edit labels". I type in a new label, and then tap "Create a new label named [...]". The app shows a label tagged to the article, then I tap "Save". 
However, when I go out to the list view, the new label disappears.

**Comment by jacksonh** [comment]
This should be fixed in this PR, waiting for Play store review right now (version 0.0.128) 

https://github.com/omnivore-app/omnivore/pull/3095

**Comment by hemanti0503** [comment]
It seems to work now. Thank you very much! :)
