### ISSUE TITLE
could not add a url in android app

### ISSUE THREAD

**Issue by zhuoqiang** [omnivore-app/omnivore#3041]
I could not find a way to add a url into android app directly.

- no button for adding a url

it would be great if we could:

- add a button for adding a url
- detect if there is url in paste clipboard and ask if we would like to add the url into read list automatically when open omnivore app. (just like what pocket app do)

**Comment by remychantenay** [comment]
Hello @zhuoqiang 

In #3065, we added the "+" button to the nav bar to add URLs.

So it is now possible.

**Comment by zhuoqiang** [comment]
> Hello @zhuoqiang
> 
> In #3065, we added the "+" button to the nav bar to add URLs.
> 
> So it is now possible.

@remychantenay thank you very much. May I know when will it be avaible? the latest android APK release is 0.0.102, is this contains the feature? could not wait to try the new version :)

BTW, there's a really convenience feature in the pocket app:

whenever I open / switch to the pocket app, it will ask you if you would like to save the URL to read later list if there's an URL text detected in clipboard.

I wonder if omnivore could apply the similar workflow here.

**Comment by remychantenay** [comment]
> @remychantenay thank you very much. May I know when will it be avaible? the latest android APK release is 0.0.102, is this contains the feature? could not wait to try the new version :)

Sorry for the late reply @zhuoqiang. I think it should be there from [android-0.0.126](https://github.com/omnivore-app/omnivore/releases/tag/android-0.0.126) onwards. The latest release should definitely have it by now.


> BTW, there's a really convenience feature in the pocket app:
whenever I open / switch to the pocket app, it will ask you if you would like to save the URL to read later list if there's an URL text detected in clipboard.
I wonder if omnivore could apply the similar workflow here.

Yeah, that's a great UX improvement, I am not sure if that's been discussed in the past. Happy to take a look at that. FYI @jacksonh

**Comment by jacksonh** [comment]
@remychantenay yeah I'd love to have that, not sure about the permissions on Android, but I think on iOS it will re-ask for it all the time.
