### ISSUE TITLE
Feature/Integration Idea: Embedded LLM and LocalAI API support to search/query bookmarks via chat?

### ISSUE THREAD

**Issue by Nezteb** [omnivore-app/omnivore#3060]
It'd be cool if there was an optional integration in Omnivore that implemented one or more AI/LLM APIs:

- [`.gguf` file format](https://github.com/ggerganov/ggml/blob/master/docs/gguf.md)
	- OSS implementation: [node-llama-cpp](https://www.npmjs.com/package/node-llama-cpp)
- [OpenAI API](https://platform.openai.com/docs/api-reference)
	- OSS implementation: [LocalAI](https://localai.io/howtos/easy-request-openai/index.html)
	- Another: [gpt4all](https://github.com/nomic-ai/gpt4all/tree/main/gpt4all-api#gpt4all-rest-api)
- [ollama](https://github.com/jmorganca/ollama/blob/main/docs/api.md)
	- "[Using LangChain with Ollama using JavaScript](https://github.com/jmorganca/ollama/blob/main/docs/tutorials/langchainjs.md#using-langchain-with-ollama-using-javascript)"

Some "basic" functionality would be the ability to chat with your bookmarks or even specific labels as different "agents".

As for the UX, here is an example screenshot of BoltAI's UI for adding new model APIs/interfaces:

![screenshot_2023-11-01_at_22 32 45@2x](https://github.com/omnivore-app/omnivore/assets/3588798/aa7e5991-6a4c-4de5-b18e-3df598be1ece)

**Comment by aldrinjenson** [comment]
+1
This feature to ask AI and get answers based on the links I've saved could be huge
I imagine the process would involve doing RAG over the article content. 

There's [this properiatary app](https://mymind.com/) which is similar and very cool. 

Are there some plans to do this in the near future?
