### ISSUE TITLE
Fullscreen reading should span safe area

### ISSUE THREAD

**Issue by fer0n** [omnivore-app/omnivore#3085]
This is a minor thing and probably not necessary, but I think it makes the reading experience nicer.

Currently, the fullscreen article reading on iOS doesn't expand into the save area:
![image](https://github.com/omnivore-app/omnivore/assets/20093825/f702b0ed-5486-4d87-8348-0687acd777ad)

I think it would look a lot nicer if it did:
![image](https://github.com/omnivore-app/omnivore/assets/20093825/03ac5ba9-359a-4536-a8a7-9e2aceb49af3)

The bottom save area should definitely be ignored, I'd also like the top one to be ignored as well, but there's an argument to be made that seeing the time/battery is helpful.

**Comment by jacksonh** [comment]
https://github.com/omnivore-app/omnivore/pull/3157/files
