### ISSUE TITLE
[Bug] Omnivore Web does not log in properly with Gnome Web

### ISSUE THREAD

**Issue by distefam** [omnivore-app/omnivore#3087]
[Gnome Web (Epiphany)](https://wiki.gnome.org/Apps/Web/) is a web browser based on WebKit. It is able to load Omnivore.app. However, when logging in (with email/password) it drops me into an empty inbox that appears to be logged in but is in fact not. There is no account avatar in the upper right, for example, and none of my items load.

The errors I get in console:
```
Not allowed to request resource
Cannot load blob ... due to access controls.
```

**Comment by jacksonh** [comment]
Do you mind adding a screenshot, also could you open the network tab in the developer console, refresh, and take a screenshot?

**Comment by distefam** [comment]
Sure, here is a screenshot of the empty inbox page:
![Screenshot from 2023-11-08 22-23-44](https://github.com/omnivore-app/omnivore/assets/65571/d462fc46-2c38-4bb4-828e-c563253304e6)

Here's a screenshot of the network tab in the developer console:
![image](https://github.com/omnivore-app/omnivore/assets/65571/c020d21d-43aa-4745-af8d-a24520635d38)

And, here's a screenshot of the console:
![image](https://github.com/omnivore-app/omnivore/assets/65571/73adbd53-a02c-4e51-8d8a-4cc195163901)

Let me know if there is anything else I can do to help. Thanks for looking into this.

**Comment by jacksonh** [comment]
Got it, looks like something with the content security policy. Probably this which I don't think is even used on newer browsers: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/block-all-mixed-content

**Comment by jacksonh** [comment]
https://github.com/omnivore-app/omnivore/pull/3096

**Comment by distefam** [comment]
> #3096

I just tested again on the Vercel prod link in this issue (https://omnivore-prod-1l7093edt-omnivore.vercel.app/) but still have the problem.
