### ISSUE TITLE
Feature request: Nested Labels

### ISSUE THREAD

**Issue by delafthi** [omnivore-app/omnivore#3092]
I'm a big fan of the nested tag system in [Bear](https://bear.app/), which allows structuring in a tagging or labeling system. What do you think, about implementing such a system in Omnivore?

Similar to bear, an article labeled with `foo/bar/baz` would be contained within the labels `foo`, `foo/bar`, and `foo/bar/baz`. Accordingly, it would make sense to make the labels section (in the left pane) hierarchical. For example:

```
- otherLabelWithNestedLabels <
- foo v
  - bar v
    - baz
  - nestedLabel
- otherLabel
```

**Comment by sywhb** [comment]
Hey @delafthi , thanks for the suggestion. We have this feature in the backend now so you can tag your items with nested labels like `foo` or `foo/bar` or `foo/bar/baz`;
And wildcard searching for `label:foo*` will return items with label `foo` or `foo/bar` or `foo/bar/baz`;
And wildcard searching for `label:foo/*` will return items with label `foo/bar` and `foo/bar/baz`;
and so on.

We will be working on the UI for the display of labels in hierarchy.

**Comment by delafthi** [comment]
Thanks, I'm looking forward to the UI changes as well.

**Comment by anschein** [comment]
Very much looking forward to seeing the nested tag feature coming, currently I am implementing PARA using nested tags in obsidian and rely heavily on being able to use nested tags in omnivore in order to preprocess information in omnivore
