### ISSUE TITLE
Margin Slider Behavior Opposite Of Each Other Depending On Platform

### ISSUE THREAD

**Issue by MagFlux** [omnivore-app/omnivore#3108]
Currently the slider for the margin with is opposite of each other between the Chrome extension and the iOS app.

I'm not sure which is the right way as I could convince myself of either the icons meaning to expand the margin or expand the body text and I'm assuming that's how it came to be regarding the slider's having opposite behavior.

![image](https://github.com/omnivore-app/omnivore/assets/26913665/a3e88753-6521-4969-b037-9fe5ac9987b1)

As can be seen in the screenshot with the slider all the way left, the margin is at it's smallest and the body text has the most room. On the iOS app when all the way to the left, the margin is at it's largest and the body text has the least room.

Referencing Chrome extension 2.8.0 and iOS app 1.37

**Comment by SaphireLattice** [comment]
Seems to straight up be a bug, judging by icons. In web app, it's left for less margin, right for huge margin. On iOS meanwhile, it's the other way around, yet icons are the same.

Just bumped into this on iOS app version 1.45.0

**Comment by jacksonh** [comment]
Yeah i guess I would say iOS is the incorrect one. You can probably rationalize both ways "less margin" vs "more space" but the icons i think indicate it well. There is some historical reason for them being different underlying values, one is actually max width percentage while the other is margin width. At this point we could probably standardize them though.
