### ISSUE TITLE
Feature Request: Ability to edit content / article body that was pulled into Omnivore

### ISSUE THREAD

**Issue by MattTheVV** [omnivore-app/omnivore#3110]
Appreciate Omnivore, it really is great.

I sometimes struggle while syncing from Omnivore to Obsidian: I regularly sync highlights that contain `#tags`, which get interpreted by Obsidian as note tags (thus cluttering my list of tags in Obsidian).

Ideally I'd like to edit the article body/content of some of my articles on Omnivore via the web interface (e.g. via markdown), to prevent this from happening.

**Comment by fr3fou** [comment]
Did you figure this out? I just started using Omnivore and this was the first thing that occured to me
