### ISSUE TITLE
Omnivore web not working with Firefox if security.OCSP.require is set to true

### ISSUE THREAD

**Issue by vkeerthivikram** [omnivore-app/omnivore#3113]
If I harden Firefox and set security.OCSP.require to true, omnivore web does not work

**With security.OCSP.require set to true**

![image](https://github.com/omnivore-app/omnivore/assets/61373970/df027b7f-8a36-4a64-b1b9-b3c31e624b3f)

**With security.OCSP.require set to false**

![image](https://github.com/omnivore-app/omnivore/assets/61373970/b92159cc-0b2b-4287-9164-0635d27637be)

**Comment by jacksonh** [comment]
Can you add a screenshot of the network tab?

**Comment by jacksonh** [comment]
I'm not getting the same results, any chance you were rate limited when testing?

**Comment by vkeerthivikram** [comment]
Sorry just saw the reply. It's working perfectly now.
