### ISSUE TITLE
Wildcard search for labels?

### ISSUE THREAD

**Issue by berot3** [omnivore-app/omnivore#3115]
when importing through obsidian plugin, I would like to import by searching `label:test,test/*`

So I would like to import not only #test but also #test/sub1 and #test/nest2

What do you guys think? :)

**Comment by berot3** [comment]
btw also on the web I can not search for `label:test*` which also would be nice if I wanted all nested tags.

related to #3092

**Comment by sywhb** [comment]
Hey @berot3 , wildcard search for labels is added now.

Please try out and let me know if it works :)
