### ISSUE TITLE
Feature Request: Show actual duration of Youtube videos instead of "1 min read"

### ISSUE THREAD

**Issue by konsuko** [omnivore-app/omnivore#3133]
Currently, when I save a Youtube video, Omnivore displays "1 min read" instead of the actual duration of the Youtube video, like seen here: 
![image](https://github.com/omnivore-app/omnivore/assets/1736929/2d1656ef-81c0-46f3-8a59-4c678289e105)

It would be great if Omnivore displays the actual runtime of the video instead, like e.g. "16 min read" for a video with a 16 min duration.

**Comment by konsuko** [comment]
I tried getting my hands dirty by fixing this myself but failed at setting up the `docker compose up`...
Maybe the issue stems from installing Docker from homebrew? Not sure.

In any case, it would be really cool if this was added by anyone, it can't be super difficult to implement and would make sorting my videos by duration possible, which would be a huge time saver:
- Got 5 minutes? Watch a 5 min video
- Got the whole afternoon? Watch a few 1 hour long video essays

**Comment by jacksonh** [comment]
Hey this is done now

**Comment by konsuko** [comment]
> Hey this is done now

Very cool, thanks!
Right now it seems to only work when adding new pages to Omnivore, is there any way to apply it to my existing items?

**Comment by jacksonh** [comment]
> > Hey this is done now
> 
> Very cool, thanks! Right now it seems to only work when adding new pages to Omnivore, is there any way to apply it to my existing items?

We probably wont backport it as we don't like to touch user's existing data unless there's a really good reason to.
