### ISSUE TITLE
more templates / mustache-tags for folders

### ISSUE THREAD

**Issue by berot3** [omnivore-app/omnivore#3136]
Hi!

it would be great if we could use more mustache tags /templates for the folder where the markdowns will be stored.

For me, it does not make sense to use `{{{title}}}` and I dont understand why someone would do that, except maybe to use it as a folder-note?

I understand `dateSaved `and `datePublished`, but I have them saved to the front matter, so for me they are redundant and not needed. But some might prefer a folder-structure in this case, ok.

**What I would love to have** is a folder-structure for: `siteName` or `originalUrl `, depending and how/if I can format it a little bit.
- `siteName` would be great to have in cases where I save a lot of articles from only a couple of sites, this way I can find them faster and they are grouped together in one folder.
- `originalURL` would be great for saving from sites where there is a folder-structure - for example docs or guides but maybe also a blog. Of course when an article is saved it will not create **one** folder named "_domain/sub-site/sub-sub-site_" but instead will create/replicate all the sub-folder in obsidian :)

optional:
- `type` maybe as a main/top-folder so i can see/navigate directly to an article or file and have them more seprated.
- `state` maybe also interesting, but not sure if possible to update through a sync or if a resync would be needed, since it isnt static. So for example I have 2 main-folders under the omnivore-folder: reading and completed. Sounds interesting.

---

I hope I'm not asking to much, omnivore until now was a great expirince, only Memex.garden is something I look to from time to time besides Omnivore :)
Keep it going, you are doing a great job!
Thanks!

**Comment by jacksonh** [comment]
hey, one issue is not every item will have a siteName or originalURL (uploaded PDFs, and some newsletters for example). I suppose in that case we could default to `unknown`?
