### ISSUE TITLE
Text size on iOS app changes on autorotate

### ISSUE THREAD

**Issue by northgardner** [omnivore-app/omnivore#3138]
On an iPhone, (iPhone 13, iOS 16.6) when I open an article in "portrait" orientation, and then rotate the device to "landscape" mode, the text size change drastically (it gets much bigger).

**Comment by jacksonh** [comment]
Does Safari do the same for you?

**Comment by northgardner** [comment]
Yes.

**Comment by jacksonh** [comment]
ok, looks like we can prevent this by injecting some CSS, not sure people would want it as a default though, as Apple's probably done this on purpose.

**Comment by jacksonh** [comment]
will need: 

```
    -webkit-text-size-adjust: 100%; /* Prevent font scaling in landscape while allowing user zoom */
```

**Comment by northgardner** [comment]
I’ll just note that other read-later apps (Pocket, Instapaper) seem to have corrected for this. I do see this behavior on other websites on Safari, but for whatever reason the difference seems more drastic on Omnivore. Maybe related to font, line spacing, and margins.   
  
  
  
  
  
  
  

  
  
>

**Comment by jacksonh** [comment]
Yeah Pocket and Instapaper are just using text, they don't have full HTML support in their readers. I'll add a setting to disable this but i think most will prefer it enabled from my testing.
