### ISSUE TITLE
[feature request]: website add setting switcher to show aside when reading article

### ISSUE THREAD

**Issue by ishowman** [omnivore-app/omnivore#3142]
currently, when I need to read an article, after click it,the left sidebar will hide.
So if I finish reading, I need to click browser back button to see reading list.
In my opinion,this is a unfriendly design.

**Comment by jacksonh** [comment]
One thing that could help is using the keyboard shortcuts. `e` to archive the item you just finished reading `u` to go up to your library.

**Comment by ishowman** [comment]
> One thing that could help is using the keyboard shortcuts. `e` to archive the item you just finished reading `u` to go up to your library.

what about show some useful shortcuts in website version.for example, show an keyboard icon and click to show shortcuts.
