### ISSUE TITLE
[feature request]: extension is lack of convinient way to save page

### ISSUE THREAD

**Issue by ishowman** [omnivore-app/omnivore#3143]
It is not supported to save via context menu just like Pocket or readerwise extension, it would be great if I click save, it will auto disappear after some seconds(For example, 5s).

**Comment by jacksonh** [comment]
Hi @ishowman are you not seeing a popup like this when you save?

<img width="527" alt="Screenshot 2023-11-17 at 20 18 20" src="https://github.com/omnivore-app/omnivore/assets/75189/78140842-637a-49a2-98e8-e41ef412149f">

**Comment by ishowman** [comment]
> Hi @ishowman are you not seeing a popup like this when you save?
> 
> <img alt="Screenshot 2023-11-17 at 20 18 20" width="527" src="https://user-images.githubusercontent.com/75189/283797923-78140842-637a-49a2-98e8-e41ef412149f.png">

I can see  popover now, but it will not appear when I first time setting api，you could ignore it

**Comment by ishowman** [comment]
> Also the simplest way to save with the extension is with the keyboard shortcut.

Is therr any guidance page about keyboard shortcut? I can't see it.

**Comment by jacksonh** [comment]
@ishowman it depends on your browser, but in Chrome keyboard shortcuts are controlled by extension settings. If you go in the Chrome menu: Extensions -> Manage Extensions you should see a "Keyboard Shortcuts" on the right hand side like this, there you can set the shortcut for the extension.

<img width="1134" alt="Screenshot 2023-11-17 at 20 23 37" src="https://github.com/omnivore-app/omnivore/assets/75189/9fa3255d-3354-4eb8-ac82-f1e744f557b4">
