### ISSUE TITLE
iOS Bug: Some labels in article list do not adjust color when switchng between dark and light mode

### ISSUE THREAD

**Issue by igorkulman** [omnivore-app/omnivore#3144]
Steps to reproduce:
- open the app on the article list
- switch to dark mode
- observe the author / web label or the first reading length label not switching to the correct dark mode color

You have to scroll the list so the cells get recycled to get labels to show in the correct color.

Here is a video showing the problem:

https://github.com/omnivore-app/omnivore/assets/4746070/6b3cd03e-49a7-4a3b-99e6-681b3795e656

This is quite annoying when you have your device set to auto switch to dark mode at night and to light mode during the day.

**Comment by jacksonh** [comment]
https://github.com/omnivore-app/omnivore/pull/3154
