### ISSUE TITLE
Add an "Add Link" button in a more accesible area

### ISSUE THREAD

**Issue by gary-host-laptop** [omnivore-app/omnivore#3145]
I found out about Omnivore yesterday, I have been looking for a tool like this for years, specially given it is libre software, so right away I started to move all my bookmarks over there. Sadly, more or less around the same time when I found out about it, the extension got removed from Mozilla's store. I didn't want to wait so I added everything from the menu within the web app instead of using the extension, which made me realize the placement of the "Add Link" button is in a place which takes a lot of work to use when you need to do this hundreds of times.

First you need to click on your user, and then click on "Add Link" and then paste your link, I think it would make much more sense if the placement of this button was right next to the search bar just like how the Android application does it, it makes things much faster and you also don't have look specifically where in the drop-down menu it is located, a couple of times I misclicked on "API Keys", for example. I think maybe having a "Paste" button after you click the "Add Link" button would be nice so that you could also save some time by not having to do either 'ctrl+v' or 'right click > paste'

**Comment by jacksonh** [comment]
Hi, you can also use the `a` key to open the dialog.

**Comment by gary-host-laptop** [comment]
> Hi, you can also use the `a` key to open the dialog.

Hey, really good for working with they keyboard, I just searched in the docs and found out about the whole keyboard support, but still I think adding that in a more visible place would be nice, even if it takes time to be added.

**Comment by alirezaalavi87** [comment]
I could add it to the UI if it's agreed upon (add button next to search)

**Comment by gary-host-laptop** [comment]
> I could add it to the UI if it's agreed upon (add button next to search)

I'd guess that since that's how they designed the Android application, I don't think they would oppose to it being added on the web version.
