### ISSUE TITLE
Add Lexend as a font option.

### ISSUE THREAD

**Issue by andrei-akopian** [omnivore-app/omnivore#3152]
Please add [https://www.lexend.com/](https://www.lexend.com/) font as one of the font options, it was designed to be easy and fast to read.

Note: here is it on Google fonts: [https://fonts.google.com/specimen/Lexend/about](https://fonts.google.com/specimen/Lexend/about) and it is under Open Font License:

> These fonts are licensed under the [Open Font License](https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL).
> 
> You can use them in your products & projects – print or digital, commercial or otherwise.
> 
> This isn't legal advice, please consider consulting a lawyer and see the full license for all details."

It is supposed to be an easy to read font, but if you are going to tell me that I am being a productivity nerd and I am overthinking this font is better than any other, I will take that.

**Comment by jacksonh** [comment]
https://github.com/omnivore-app/omnivore/pull/3153

**Comment by andrei-akopian** [comment]
I guess I can close the issue now that the font was added and merged.

**Comment by jacksonh** [comment]
@andrei-akopian yeah not deployed for web yet but should be soon. just have a couple other things holding up a web deployment right now. Should be available on Android, and in Testflight beta for iOS
