### ISSUE TITLE
Android share intent with selected text should create a highlight

### ISSUE THREAD

**Issue by johnlunney** [omnivore-app/omnivore#3167]
Mentioned on Discord, posting here for completeness.

When you share a page to Omnivore app on Android, it adds the article, but selected text is ignored.
On the web, you can directly create a highlight from selected text, it would be great if this worked on Android too. 

(Other apps like Gmail will e.g. include the selected text in the email)

**Comment by johnlunney** [comment]
I'm not sure whether you get useful location information from the share intent, but you could walk the text of the article to find the location of the quote.

(You'd probably want a minimum number of characters to trigger this behaviour)

**Comment by dairefagan** [comment]
I would find this useful.
