### ISSUE TITLE
Cannot save page with Firefox add-on anymore

### ISSUE THREAD

**Issue by Cito** [omnivore-app/omnivore#3169]
Since yesterday, I am not able to save pages with the Firefox add-on anymore.

The error I get is
> You have not granted the Omnivore extension consent to save pages.
> Check the extension options page to grant consent.

However, I did not change any settings. Under "manage - permissions", I see the green checkmark for "access data on all web sites". I have even added an API key and permission for restricted and private pages, which did not help (and was not needed before anyway). Removing the add-on and adding it again didn't help either. The problem exists for any web site I want to save, not just for some.

This may be related to #3100 since it happened after the (automatic) update to 2.8.9 (Firefox 120 on Windows).

**Comment by david-askari** [comment]
@Cito Do you have the _I consent to data collection_ checkbox enabled? This just fixed the issue to me and after reading the privacy section I can see why. You can find it on the add-ons own preference page.

**Comment by jacksonh** [comment]
Hey @Cito you should have been presented with a page when the extension updated, but you can go to the plugin options and click the consent button. Mozilla keeping us all safe 🤷 

I'll keep this open, but feel free to close if doing that resolves the issue.

**Comment by jacksonh** [comment]
Hey @Cito you should have been presented with a page when the extension updated, but you can go to the plugin options and click the consent button. Mozilla keeping us all safe 🤷 

I'll keep this open, but feel free to close if doing that resolves the issue.

**Comment by Cito** [comment]
Thanks a lot @david-askari and @jacksonh - yes, this was the reason, and it's a bit embarrassing that I didn't see it.

Somehow I only looked on the *Manage* page which has 2 sub-pages with permission options, but not on the *Options* page. Maybe it's a bit confusing that permission options are spread out to three places. And if you're on a Non-English FF, the menu is also not called *Options* as in the error message. Maybe it's also easily overlooked since in most other apps "data collection" refers to collection of app *usage* data which is not necessary for the functioning of the app.

I don't think anything can or should be changed here. It was mainly a case of PEBKAC. Sorry for the noise.
