### ISSUE TITLE
Issue with the Pocket integration

### ISSUE THREAD

**Issue by northgardner** [omnivore-app/omnivore#3170]
I am a longtime Pocket/Read It Later user who is trying to move over to Omnivore. I have now tried to import my articles from Pocket twice. I have around 18,000 articles in Pocket. The first time, 21 articles got imported, the second time, 31 articles got imported. Is this is bug in the integration, or is there something I could do to make it work?

**Comment by jacksonh** [comment]
Querying the API for this token i see more than 100 items returned for the first page of data, but only 31 items in the CSV file so something seems off. I tried querying with state `all` and state `unread` and both returned a full 100 item page of data.

**Comment by sywhb** [comment]
@jacksonh may I know the number of archived items in the list?

**Comment by sywhb** [comment]
We only import unarchived items for now

**Comment by sywhb** [comment]
> returned

They don't have a status filter for archived items so we filter them manually after fetching all

**Comment by northgardner** [comment]
There should be 5931 unarchived items being imported.

**Comment by sywhb** [comment]
> There should be 5931 unarchived items being imported.

Got it. Thanks. I'll take a look into this issue

**Comment by sywhb** [comment]
Hey @northgardner , I have fixed this bug. Could you please try to import from Pocket again?

**Comment by sywhb** [comment]
@northgardner Thanks for letting me know. Let me check if the email queue is stuck or something

**Comment by northgardner** [comment]
Thanks @sywhb. I did receive notifications when the import started and when it finished.
