### ISSUE TITLE
Bulk selection improvements

### ISSUE THREAD

**Issue by northgardner** [omnivore-app/omnivore#3186]
The UI is confusing for bulk select the web app. The box at the top that selects all items on the page has an arrow next to it, which opens a menu. That menu has one item, "All." I thought when I saw that that it would select all items that met the criteria in the search box (not just the ones showing on the page), but it just has the same function as the check box itself. It would be great to be able to select _all_ items that met a certain criteria, but in any case, it would be good to make the UI clearer.

**Comment by javiavid** [comment]
+1
