### ISSUE TITLE
Twitter thread from Android not well formed like chrome extension

### ISSUE THREAD

**Issue by dairefagan** [omnivore-app/omnivore#3194]
[Thread](https://twitter.com/biancoresearch/status/1729640047496823289?t=AW5ToYeCGJ1VVq2qT8r7Bg)

Android version:

![image](https://github.com/omnivore-app/omnivore/assets/12515718/af91b630-e075-48d2-96eb-696db626dfaa)

Chrome extension version:

![image](https://github.com/omnivore-app/omnivore/assets/12515718/65718ea9-e175-44a3-a0db-602b1a4e9bea)
![image](https://github.com/omnivore-app/omnivore/assets/12515718/f89a665a-19f6-4e6f-aa62-c5acb94cc15f)
![image](https://github.com/omnivore-app/omnivore/assets/12515718/f9966139-a1a1-4380-8ba7-a2a1311e84b4)
![image](https://github.com/omnivore-app/omnivore/assets/12515718/f9602eb1-f222-45c5-be97-f3e8b465ec98)

**Comment by jacksonh** [comment]
With the extension we can capture the visible content but with android we have to save the URL and unfortunatley twitter blocks us now since their API changes, I'll leave this open but we don't really support twitter threads anymore.
