### ISSUE TITLE
Not working on Android: View all your highlights 

### ISSUE THREAD

**Issue by johnlunney** [omnivore-app/omnivore#3196]
https://blog.omnivore.app/p/view-all-your-highlights
This feature doesn't seem to work on Android app.

Would be awesome for reviewing highlights on the go, as a step towards Readwise-like functionality.

**Comment by EnGassa** [comment]
+1

**Comment by vardecab** [comment]
In the meantime you could search for `has:highlights in:all` — that's gonna show you some (looks like the cap is 10?) of your articles with highlights.

**Comment by johnlunney** [comment]
> In the meantime you can click the search icon and search for `has:highlights in:all`
Unfortunately that search query doesn't work on Android either.
