### ISSUE TITLE
FR: More obvious color when selecting an item

### ISSUE THREAD

**Issue by javiavid** [omnivore-app/omnivore#3200]
When you use J and K to select an item the background of the text changes and becomes slightly darker.

Is it possible to make it a little darker to make it more obvious?
Another option could be to add a very thin yellow border to the article or even have the background have a little yellow.

I like the Omnivore interface, but I think this is too subtle, if you stop looking at the screen when you return it is difficult to know which item you are on quickly.

**Comment by jacksonh** [comment]
@HW05 we'd discussed this one before and I think you did mock something up. We need a better color or border mode for cells when using keyboard selection.

**Comment by jacksonh** [comment]
@HW05 demo of what I mean: https://www.loom.com/share/0a372fc037dc4fa4a926d24a8c983b74
