### ISSUE TITLE
FR: Paragraph mode

### ISSUE THREAD

**Issue by javiavid** [omnivore-app/omnivore#3203]
I'm currently switching from readwise reader to omnivore and there is one thing I would love to have in omnivore.

The paragraph mode they use within the articles to advance is great, in addition to indicating where you are reading (for large texts it is interesting), it allows you to highlight paragraphs with the H key. This allows you to be very fast highlighting.

https://github.com/omnivore-app/omnivore/assets/7627504/924b8b3e-0f14-44b5-89e6-bacb22c1d0ed

**Comment by johnlunney** [comment]
It's nice how the up and down arrows move you quickly through the article.

**Comment by javiavid** [comment]
I think it is the best system I have seen for reading and marking ideas quickly. I hope they do something similar in omnivore.
