### ISSUE TITLE
iOS: dismiss the sharing extension after it is done sharing

### ISSUE THREAD

**Issue by igorkulman** [omnivore-app/omnivore#3205]
When I share a link to Omnivore the Omnivore extension shows app and I have to manually click the Dismiss button to get rid of it. It should just dismiss automatically like every other share extension I use. I never want to immediately go read the shared article (the other button next to Dismiss).

Or at least make it a settings so people who never want to immediately go read the shared article do not have to click the Dismiss button all the time.

**Comment by jacksonh** [comment]
Yeah I plan on adding this as a setting. I'm similar to you but a majority of our users want to do things like set labels.
