### ISSUE TITLE
Easier way to Open Original from main home/list on the web

### ISSUE THREAD

**Issue by bretthoerner** [omnivore-app/omnivore#3208]
I'd appreciate a faster way to access the original content without navigating through the menu for each item.

For certain items, I know I want to open them without using the reader view. I prefer to open these in background tabs and then remove them from my list. It would be great if the domain text under each item could be a direct link to the original URL. That way, I could simply middle-click or option-click to open them. Alternatively, if there was an option in the top menu for multi-select to "open all originals in tabs," that would also be helpful.

I started working on implementing this myself, but I thought it would be a good idea to seek approval or consensus from others to ensure it's a desired feature and to determine the best way to incorporate it into the user interface. :)

**Comment by DannieBGoode** [comment]
Allowing the user to customize this toolbar would solve this. For example I rarely ever delete articles, so I wouldn't mind having it behind a dropdown.
![image](https://github.com/omnivore-app/omnivore/assets/4180198/abee3a3e-cf32-435d-afe7-f94b5d9cbc06)
