### ISSUE TITLE
Hope to release the official docker image

### ISSUE THREAD

**Issue by jerryc127** [omnivore-app/omnivore#3209]
Hope to release the official docker image

**Comment by jacksonh** [comment]
I've just stated created official images for the backend and content-fetch services. You can access them here: https://github.com/orgs/omnivore-app/packages?repo_name=omnivore

**Comment by gygy** [comment]
> I've just stated created official images for the backend and content-fetch services. You can access them here: https://github.com/orgs/omnivore-app/packages?repo_name=omnivore 

How do I install and configure it?

**Comment by BitNike** [comment]
I'm facing the same problem. I can't log in to my self host.
