### ISSUE TITLE
iOS Bug: cells stay randomly selected

### ISSUE THREAD

**Issue by igorkulman** [omnivore-app/omnivore#3210]
I was not able to figure out any pattern but sometimes when I get from an article back to the list the cell for that article stays selected, sometimes even 2 cells get randomly selected:

![IMG_0375](https://github.com/omnivore-app/omnivore/assets/4746070/9018d3d7-2bca-4508-a2ce-4a8b26bc4f37)

**Comment by jacksonh** [comment]
yeah i guess this is an issue in swiftui the only solution i can see is to override the selection colour if not in edit mode.
