### ISSUE TITLE
Android App: hardware authentication keys not supported during Apple signin flow

### ISSUE THREAD

**Issue by felixbinder** [omnivore-app/omnivore#3215]
Android App version 0.0.162 on Android 11

I am using an Apple account with two factor authentication and a hardware key as second factor. When I try to log in via the Apple sign in flow on the Android app, it tells me to update my web browser to allow for the use of security keys (see attached photo). 
![IMG_0960](https://github.com/omnivore-app/omnivore/assets/24477285/226c59a9-4ccd-499a-b24d-091007b00a47)

Using the web browser I can sign into the web app fine using my security key. But currently I am unable to sign into the app. Perhaps the sign in flow could redirected to the web browser rather than a web view?

**Comment by jacksonh** [comment]
Thanks, have you had this issue with other apps?

**Comment by jacksonh** [comment]
Yeah, you might have to use an app password. I think you can create one at appleid.apple.com
