### ISSUE TITLE
Request: Dutch text-to-speech voice

### ISSUE THREAD

**Issue by igorrust** [omnivore-app/omnivore#3217]
As I read a lot of Dutch articles, and I do highly value the read-aloud feature of Omnivore, is it an option to add also the Dutch language as a speech voice?

**Comment by igorrust** [comment]
Sure :)

> Hoi, ik ben een voorbeeld stem voor Omnivore tekst-toe-spietsch. Kies mij alsjeblieft! Want anders verwijderen ze me straks weer van de stemmenlijst!

**Comment by jacksonh** [comment]
tested this and was almost sure it said "kiss my ass" lol

**Comment by jacksonh** [comment]
Going to close this one as its in the beta that should be shipped soon.
