### ISSUE TITLE
Make cmd+enter save note

### ISSUE THREAD

**Issue by therohitdas** [omnivore-app/omnivore#3226]
In the Mac app, when writing a note, it will be better to use `cmd+enter` to save the note.
Right now, we need to click the save button. 

`cmd+enter` on Mac and `ctrl+enter` everywhere else will increase the user's speed because the hands are already on the keyboard when typing the note.
Also, it is the default way to complete interaction with textboxes in many places including GitHub, I will press `cmd+enter` to post this issue.

**Comment by hereAlexT** [comment]
@jacksonh Hi, Jackson, are you working on this issue, if not can you assign it to me?

**Comment by jacksonh** [comment]
@hereAlexT go for it!

**Comment by hereAlexT** [comment]
this issue is done by this PR https://github.com/omnivore-app/omnivore/pull/3451

**Comment by therohitdas** [comment]
Closing this issue as the PR was merged.
