### ISSUE TITLE
Please Consider Adding Literata as a Font Option

### ISSUE THREAD

**Issue by h9nara** [omnivore-app/omnivore#3230]
I really like the Bookerly font on Kindle but it's exclusive to Amazon so I found this Literata(https://www.type-together.com/literata-font) font to be a very similar alternative.

It's used by Google for Google Play Books and is now under OpenFont License:
>Literata 3 is published with an OpenFont License (OFL) so it’s free to own and use — no strings attached! 

I think there is good reason that this style is used by Amazon for their Kindles and Google for their Books app - I feel comfortable and cozy reading in this font on my e-readers. Please consider! Thanks.

**Comment by jacksonh** [comment]
This is available on the web now
