### ISSUE TITLE
Google Cloud blocks access from Iran and some other countries.

### ISSUE THREAD

**Issue by alirezaalavi87** [omnivore-app/omnivore#3243]
Sanctions are inhumane and absolutely against the philosophy of freedom. I liked this app and even wanted to write a CLI client for it but when I turned off my VPN I realised people from my country (Iran) are fully forbidden to access these sites. 
very shameful behavior for anyone to participate in. It does not matter what our government believes and does, the people all around the world must have equal access to the Internet. Governments are restricting our access to the internet enough, don't be the 100th problem out of our 99 problems.

Anyone who participates in restricting the free access to the internet, knowledge, and free software must be ashamed (Docker, Gitlab, medium, omnivore, and many more )

**Comment by jacksonh** [comment]
Hi @alirezaalavi87 we don't explicitly restrict access to anyone, however Google Cloud our hosting provider does block access.

**Comment by jacksonh** [comment]
There isn't a lot of info on this posted by Google, but some info here: https://support.google.com/a/answer/2891389?hl=en

**Comment by jacksonh** [comment]
OK, well do you have a proposed action here?

**Comment by alirezaalavi87** [comment]
Changing the hosting provider from google cloud is an option of course. Also this issue just gaining attention is very important. Most people around the world might not think about how being blocked from a big portion of the internet can effect our lives.

**Comment by ntelogo** [comment]
@jacksonh I understand that cloud storage alternative to Google might incur significant costs for your service. But have you perhaps considered reaching out to the community for support? I'd become a Omnivore's patron if I knew it is safeguarding privacy (another downside of using Google services) and providing equal access opportunities for all.

**Comment by jacksonh** [comment]
Hi @ntelogo thanks you can donate here: https://opencollective.com/omnivore

**Comment by ntelogo** [comment]
> Hi @ntelogo thanks you can donate here: https://opencollective.com/omnivore

Happy to.. and please follow-up with news on any efforts to de-Google your service. I'd be happy to amplify the message!
