### ISSUE TITLE
Bug: Archive API does not work

### ISSUE THREAD

**Issue by ribtoks** [omnivore-app/omnivore#3254]
I'm importing data from Instapaper using [this repository](https://github.com/davidohlin/instapaper-to-omnivore-import) and although it's not officially supported, I was able to verify that underlying API does not work as expected.

I'm speaking about `setLinkArchived()` GraphQL API as defined here:

https://github.com/davidohlin/instapaper-to-omnivore-import/blob/f5f832ea447dbb46485cab7c5dd0c7f51f52a593/index.ts#L48-L58

When I run the API against article that I just saved by URL, I receive the following response:

```
{
  linkId: 'a6a6edd0-9b2c-11ee-b3d9-0fbdc042a750',
  message: 'link_archived'
}
```

However, when I navigate to the https://omnivore.app, the Archived section is fully empty and the said article is left in the Inbox.

**Comment by jacksonh** [comment]
The archive API definitely works, without looking at that code I'm guessing the archive call is being made before the item is completely saved. When you save a URL we have to fetch the content of the URL which can take some time, especially with older pages.

What you could do if you want to archive all your imported items is use this tool: https://omnivore.app/tools/bulk

**Comment by ribtoks** [comment]
Thanks for fast response. Is there any way to know when the item is "ready" to be archived?

**Comment by ribtoks** [comment]
Another comment: I don't think this qualifies as "archive API definitely works", because the response status is both confusing and incorrect: it says "link_archived" in the message, however the link is not archived in reality.

**Comment by jacksonh** [comment]
@ribtoks there is actually a better way if possible (I haven't looked at that tool's code) but `SaveURL` takes a state for this purpose:

```
  input SaveUrlInput {
    url: String!
    source: String!
    clientRequestId: ID!
    state: ArticleSavingRequestStatus
    labels: [CreateLabelInput!]
    locale: String
    timezone: String
    savedAt: Date
    publishedAt: Date
    folder: String
  }
  ```
  
 those fields are for tools like our importer, and allow a page to be archived as it is saved.

**Comment by jacksonh** [comment]
Also, just want to make sure you are aware of our CSV importer: https://docs.omnivore.app/using/importing.html#importing-csv-files

**Comment by ribtoks** [comment]
Nice, I will try to set `state` in `SaveUrlInput`

**Comment by jacksonh** [comment]
Going to close this one. Let me know if you have issues still
