### ISSUE TITLE
The Search API does not work on mobile devices.

### ISSUE THREAD

**Issue by goldenages1989** [omnivore-app/omnivore#3278]
I wrote a script for Obsidian that retrieves archived data through an API. 
It runs successfully on Mac, but when executed on iOS, it throws a TypeError: Load failed error. 
My network connection is fine.

![image](https://github.com/omnivore-app/omnivore/assets/3285965/fd518f11-ff97-4a8d-9135-ea83ae528716)

**Comment by jacksonh** [comment]
Hi, you'll need to provide some more details so we can diagnose this. Search API definitely works on mobile you can open https://omnivore.app on mobile to verify. Do you have some sample code we could look at?

**Comment by goldenages1989** [comment]
I apologize for not providing enough information. Here is the code

`
async function fetchTraces(authToken) {
  let mappedResults = [];
  try {
    const cursor = 0;
    const limit = 10;
    const data = JSON.stringify({
    variables: {
      after: "0",
      first: 30,
      format: "",
      includeContent: false,
      query: "sort:updated-desc"
    },
    query: `query Search(
      $after: String
      $first: Int
      $query: String
      $includeContent: Boolean
      $format: String
    ) {
      search(
        first: $first,
        after: $after,
        query: $query,
        includeContent: $includeContent,
        format: $format
      ) {
        ... on SearchSuccess {
          edges {
            node {
                id
                title
                  slug
                  siteName
                  originalArticleUrl
                  url
                  author
                  updatedAt
                  description
                  savedAt
                  pageType
                  content
                  publishedAt
                  readAt
                  wordsCount
                  isArchived
                  readingProgressPercent
                  archivedAt
                  contentReader
            }
          }
          pageInfo {
            hasNextPage
            endCursor
            totalCount
          }
        }
        ... on SearchError {
          errorCodes
        }
      }
    }
  `,
  });
    const url = `https://api-prod.omnivore.app/api/graphql`;
    const completedTraceMetadata = await fetch(url, {
      method: 'POST',
      headers: {
        "Content-Type": "application/json",
        "Authorization": "${authToken}",
        "X-OmnivoreClient": "obsidian"
      },
      body: data
    }).then(function(response) {
      return response.json();
    });
`

**Comment by jacksonh** [comment]
OK, my guess is what you are hitting here is a CORs error. Can you look in the developer console and on the network tab?

**Comment by goldenages1989** [comment]
I can only access console information on my Mac computer. The console information on the mobile device cannot be obtained within Obsidian.

<img width="1374" alt="image" src="https://github.com/omnivore-app/omnivore/assets/3285965/4b29c375-f148-4c92-bfd6-d16c590f3ecc">

**Comment by jacksonh** [comment]
Thanks, I didn't understand that you were running within Obsidian. I am still guessing this is related to CORS somehow. I wonder if on Mac Obsidian is proxying the fetch request to avoid CORs but on iOS its running through the browser. 

Is this installed as a plugin?

**Comment by goldenages1989** [comment]
Yes, this is a obsidian plugin I wrote myself. In this plugin, I fetch data from Omnivore for processing.
I searched for some information about Obsidian CORS, and one [suggestion](https://forum.obsidian.md/t/make-http-requests-from-plugins/15461/18) was to switch the request api from fetch to requestUrl to handle CORS. After trying this, I found that it now throws a 500 error.

<img width="2252" alt="image" src="https://github.com/omnivore-app/omnivore/assets/3285965/d76670d0-b5bd-4499-aae5-585ace7f8373">

**Comment by jacksonh** [comment]
Can you paste the full stack here? (Make sure it doesn't have your token in it)

**Comment by goldenages1989** [comment]
Do you means the result of `console.log(e.stack)`?

**Comment by jacksonh** [comment]
> Do you means the result of `console.log(e.stack)`?

Yeah

**Comment by goldenages1989** [comment]
That's the only information available

<img width="506" alt="image" src="https://github.com/omnivore-app/omnivore/assets/3285965/51e11247-bebb-4ba2-a510-3306f22bee79">

**Comment by jacksonh** [comment]
Long shot because its hard to tell from our logs, but there was a request right around that time with an invalid API key. Maybe in the code update the `authToken` variable was changed? 

Also, your key was visible in a previous screenshot, so you should probably delete that key on our API keys page.

**Comment by goldenages1989** [comment]
Indeed, it was indeed the token error that caused the problem. Now the API calls are working correctly. Thank you so muxh for your guidance!

**Comment by jacksonh** [comment]
Awesome, please let us know more about your tool when you have it ready to demo...if you plan on sharing it. Might want to checkout our Discord also.

I'll close this one out, but let me know if there are still issues

**Comment by goldenages1989** [comment]
It is a plugin that pulls out articles from the Omnivore archive that you have read on a given day and writes them into your Obsidian journal. I wrote it based on this [plugin](https://github.com/Ledaryy/obsidian-todoist-completed-tasks). If anyone is interested, I would be happy to share it.

**Comment by jacksonh** [comment]
I think people would really like this actually
