### ISSUE TITLE
Feature request: Right-to-Left (RTL) support

### ISSUE THREAD

**Issue by PandaBrrr** [omnivore-app/omnivore#3279]
Texts in languages that are written right-to-left (Hebrew, Arabic, Persian, etc.) are currently displayed incorrectly. With close to a billion of speakers worldwide, this issue likely affects tens of millions of potential users.

There are two main issues that make reading RTL languages in LTR configuration difficult:

1. All text is aligned left when it should be aligned right (minor)
2. The order of words and sentences with LTR (e.g., English) words gets messed up (major)

_Example_

1. Original article:
![image](https://github.com/omnivore-app/omnivore/assets/154873861/d94b27ef-e1a3-4063-bf2c-0dd26c163b8a)

2. Article in Omnivore
![image](https://github.com/omnivore-app/omnivore/assets/154873861/897c5712-fb7a-41a1-b1f6-daed6538f6e4)

As you can see, the red line representing the first part of the sentence, gets broken in two in Omnivore, with the first half appearing before blue and green, and the second half after. It should be displayed unbroken before the two other parts of the sentence.

A solution to this issue would be greatly appreciated.

**Comment by PandaBrrr** [comment]
This would be the best gift for 2024 for many users like myself! Fingers crossed.

**Comment by PandaBrrr** [comment]
@jacksonh 
I just thought of a temporary quick workaround.
Would it be possible to add an RTL display option per article? Similar to justify text or changing the color of the display.

**Comment by jacksonh** [comment]
@PandaBrrr sorry i missed your comment before. That's exactly what I am starting to do here: https://github.com/omnivore-app/omnivore/pull/3619 

Basically our next steps are:

- Allow user to switch to RTL mode (its actually set as a cookie value, so it will always be the last set value)
- Roll out a change to start detecting the page's RTL value when parsing (sadly this requires extension and iOS updates also)
- Start setting the value based on the parsed page value.

I am also wondering about changes to the library view, it might be tricky to mix RTL and LTR titles in the library, along with summaries.

**Comment by jacksonh** [comment]
oh funny, so they do RTL the title but left everything else LTR?

**Comment by PandaBrrr** [comment]
@jacksonh 
Yup. It works well on a small-ish mobile screen. IIRC, they do it similarly in the web client.

**Comment by jacksonh** [comment]
@PandaBrrr the code to detect RTL isn't live yet but you can manually enable it now on web by going into the reader settings (the thing where you set the font), going to advanced, and enabling right to left text. Unfortunately this will set it for all articles at the moment. You'll also have to do a refresh of your browser after enabling it.

**Comment by PandaBrrr** [comment]
@jacksonh That's brilliant, thank you!

I'm testing it now.

**Comment by jacksonh** [comment]
Thanks, i did some testing for library changes to support too. The detection changes might take a bit more as it requires extension updates and mobile app updates.

**Comment by kbdragon** [comment]
@jacksonh 
Hi Jackson, is there any update on implementing the automatic encoding detection? It sometimes works when I use the extension on android, but doesn't work on the web.

**Comment by yonatankremer** [comment]
any update? Specifically with the macos client
