### ISSUE TITLE
Add Liqe copy command to self-hosting Dockerfile

### ISSUE THREAD

**Issue by ClarkLindsay** [omnivore-app/omnivore#3291]
When running docker build on the self-hosting Dockerfile, the following error was being returned:

Request "https://registry.yarnpkg.com/@omnivore%2Fliqe" finished with status code 404.
Error: Couldn't find package "@omnivore/liqe@1.0.0" required by "@omnivore/api@1.0.0" on the "npm" registry.

Comparing the api Dockerfile to the self-hosting one, I noticed that the liqe copy command was present in the former but not the latter. Adding the following lines to the relevent sections of the self-hosting Dockerfile resolved the error:

COPY /packages/liqe/package.json ./packages/liqe/package.json

COPY /packages/liqe ./packages/liqe

RUN yarn workspace @omnivore/liqe build

COPY --from=builder /app/packages/liqe/ /app/packages/liqe/

**Comment by jacksonh** [comment]
This one is done, thanks!
