### ISSUE TITLE
bulk deleting function doesn't work

### ISSUE THREAD

**Issue by jostyee** [omnivore-app/omnivore#3292]
On the web app, select multiple items and click the delete button
<img width="670" alt="image" src="https://github.com/omnivore-app/omnivore/assets/88564/8b7eb156-4d90-4d86-b3d9-0aa4a9aad586">

it says 'Items deleted' but none of them get deleted actually.

**Comment by jostyee** [comment]
> Are they still there if you refresh?

yes there are, it's been over 2days and I've tried countless times:

1. use custom query to find out the items I don't want any more
2. select all or multiple
3. click the delete button
4. refresh webpage, nothing changes

**Comment by jacksonh** [comment]
Do you mind opening the developer console and looking for any errors? Both on the console tab and the network tab? If there is anything private you can either obscure it in the screenshot or send through the feedback tool

**Comment by jostyee** [comment]
@jacksonh there's no error in develop console, here attached the exported HAR for the `delete` operation.
[omnivore.app_Archive [24-01-02 09-38-02].har.zip](https://github.com/omnivore-app/omnivore/files/13806587/omnivore.app_Archive.24-01-02.09-38-02.har.zip)

**Comment by jacksonh** [comment]
Thanks, it does look like everything went right there. Can you also try just a simple search like `in:inbox` with no label filters or anything to see if the items display?

**Comment by jacksonh** [comment]
Going to assign this one to @sywhb to look into more. Based on the data here I do see the correct call being made, but the library item status not being updated on the backend.

**Comment by jacksonh** [comment]
Going to delete this HAR file too as it includes some authentication info

**Comment by jostyee** [comment]
> Thanks, it does look like everything went right there. Can you also try just a simple search like `in:inbox` with no label filters or anything to see if the items display?

it works for `in:inbox`

**Comment by jacksonh** [comment]
@jostyee thanks. Can you add the search query here that isn't working?

**Comment by jostyee** [comment]
@jacksonh the query is `in:archive author:admin no:label` , ty.

**Comment by jacksonh** [comment]
I think maybe the core error here is `no:label` creates an exception with our new search parser. /cc @sywhb

**Comment by jostyee** [comment]
@jacksonh I don't think so, see my updated reply https://github.com/omnivore-app/omnivore/issues/3292#issuecomment-1873571692 w/o `no:label` the function doesn't work, neither.

**Comment by sywhb** [comment]
hey @jacksonh, the `delete` function was failed because a recent change we made (default scope is `in:inbox` instead of `in:all`) and @jostyee was trying to delete items from archive folder so the params of the api were `includes:id` which converts to `in:inbox includes:id` and then no items were actually deleted

**Comment by jacksonh** [comment]
ahhh so on the web client i should change this, taking a look at it now

**Comment by sywhb** [comment]
i think we probably should revert this change so defaults to `in:all` if no folder is defined but it creates some other problems with saved searches like `no:label` or `type:file` which we want to show only unarchived items

**Comment by sywhb** [comment]
> ahhh so on the web client i should change this, taking a look at it now

no, it's something i changed in the backend here #3276

**Comment by jacksonh** [comment]
Hmm, yeah i do think that patch is correct but we probably need to update defaults in a bunch of places.

**Comment by sywhb** [comment]
> Hmm, yeah i do think that patch is correct but we probably need to update defaults in a bunch of places.

oh okay. like when you selected multiple items, the query should be `in:inbox includes:id1,id2`

**Comment by jacksonh** [comment]
Yeah, or maybe whenever includes is used we should use `in:all`

**Comment by sywhb** [comment]
> Yeah, or maybe whenever includes is used we should use `in:all`

yeah, sounds right

**Comment by jostyee** [comment]
> Yeah, or maybe whenever includes is used we should use `in:all`

should be, otherwise tabs such as `highlights` won't show archive items, and I have to adjust the Obsidian sync plugin query to fetch them.

**Comment by sywhb** [comment]
@jostyee, we just fixed this. could you please check again?

**Comment by jostyee** [comment]
@sywhb confirmed fixed, thank you again.
