### ISSUE TITLE
Feature Request: Open Articles in Original Links from Saved Searches

### ISSUE THREAD

**Issue by itizarsa** [omnivore-app/omnivore#3293]
I kindly request the addition of a feature that allows users to open articles in their original links when clicked within saved search views.

This feature would be especially helpful for RSS feeds, as some sites do not provide full articles in RSS format. It would also provide flexibility for users who prefer to read articles in their original formatting.

Ideally, this feature would include the ability to configure it for each view, allowing users to choose their preferred behaviour for different content sources.

Thank you for considering this request.

<img width="1439" alt="SS" src="https://github.com/omnivore-app/omnivore/assets/77574889/0f2faf42-bc9f-4748-8f69-823f8b1851a5">

**Comment by jacksonh** [comment]
Hey, one thing you can do is use keyboard navigation. Just tap `o` to open the selected item. We have an update later this week to make it cleaner to see the selected item (maybe it should use focused as well as selected).

We can probably make the easier in the grid but it does become a bit of a mess of links on top of links. Another idea would be something like `Hold down O while clicking`

**Comment by itizarsa** [comment]
@jacksonh Using the keyboard would work in web, but what about the mobile apps?

**Comment by jacksonh** [comment]
yeah i see what you mean. I guess we can have an `Open In` variable that we track for items that could be set with a rule, but it does feel like a lot of work on user end. 

We probably also just need easier way of opening original, like the above solution on web and long press + menu on mobile

**Comment by DannieBGoode** [comment]
could be done by allowing the user to customize this toolbar. For example I rarely ever delete articles, so I wouldn't mind having it behind a dropdown.
![image](https://github.com/omnivore-app/omnivore/assets/4180198/a8d22672-9b5e-4a5f-8c76-c75bda399910)
