### ISSUE TITLE
Sync issues with Android app on Boox

### ISSUE THREAD

**Issue by northgardner** [omnivore-app/omnivore#3295]
I use three Omnivore apps—the web app, the iOS app on an iPhone 13 with iOS 17.1.2, and the Android app on a Onyx Boox Note 5 and the the Android app does always stay in sync with the others. When I delete or archive a link or annotate text on the iOS or web app, changes sometimes not appear on the Android. The same seems to be true in reverse. I cannot reliable reproduce this bug, but there are a number of links that appear in my Inbox on the Android app and in Archived on the other platforms (and likewise highlights that are not synced across platforms).

**Comment by northgardner** [comment]
A more specific example: I read an article (https://theracket.news/p/the-anti-wokes-are-doing-us-a-favor, for which I needed to sign in) on the Android app on the Boox Note5, then archived the article. The article now appears as archived (and 90% read) on that Android app as well archived as on the web app, but on the iOS app, it still appears in the Inbox with 0%, indicating that changes have not been synced.

**Comment by jacksonh** [comment]
Did you refresh the feed in iOS?

**Comment by northgardner** [comment]
Yes. That was the first thing I did when I noticed there was a discrepancy between the two feeds. And I do this each time. It seems to not work sometimes, until (like in this example) it does.   
  
  
  
  
  
  
  

  
  
>

**Comment by jacksonh** [comment]
Thanks, think we know whats going on here. Working on an update.

**Comment by jacksonh** [comment]
https://github.com/omnivore-app/omnivore/pull/3332
