### ISSUE TITLE
Update default highlights saved search

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#3298]
For `Highlights` we want to also show items in the archive so it should be `in:all has:highlights mode:highlights`

**Comment by tooniz** [comment]
Thanks, I also found this to be annoying. My archived highlights are no longer showing, no longer syncing with Obsidian etc.

Please either use the suggested filter or allow the user to save a custom one

**Comment by jacksonh** [comment]
> Thanks, I also found this to be annoying. My archived highlights are no longer showing, no longer syncing with Obsidian etc.
> 
> Please either use the suggested filter or allow the user to save a custom one

You can use a custom query in the Obsidian plugin settings. In the interm you can also create a custom saved search.

**Comment by jacksonh** [comment]
This one is done now.
