### ISSUE TITLE
Firefox Extension not saving articles due to permissions issue 

### ISSUE THREAD

**Issue by nikhil-nayyar** [omnivore-app/omnivore#3313]
I observed the following behavior on **Firefox for Linux 106.0.1 (64-bit)** using the Omnivore Extension **Version 2.8.9**

When attempting to save an article, I was prompted with a modal stating: 

> You have not granted the Omnivore extension consent to save pages. Check the extension options page to grant consent.

![image](https://github.com/omnivore-app/omnivore/assets/13279016/5ac10757-dac0-419a-baed-ce0b8d44fa91)

I've provided permission through both Firefox and the application. Additionally, I generated an API key via the Omnivore web application and saved it in the settings, but for obvious reasons, did not include a screenshot of it loaded here. 

![image](https://github.com/omnivore-app/omnivore/assets/13279016/43474f75-baec-44f9-b991-a78ce918fd0b)
![image](https://github.com/omnivore-app/omnivore/assets/13279016/cfbbcf8f-a8ef-4a70-aafa-50dc5811fe93)

I figure one of two things could be occurring:
1. The issue lies with me and I haven't given the proper consent. In this case, it may be useful to add more detail to the modal as to what settings to fix.
2. There is an issue with the extension itself. Though, if anyone is able to reproduce the issue that would help narrow it down. From what I can see, I check the 'I consent' box and hit save, however upon reloading, the box becomes unchecked. Not sure if this is not saving the setting.

I'm happy to provide any more information as needed or if anything isn't clear. Thanks!

**Comment by jacksonh** [comment]
Thanks, yeah this consent is kind of an annoying requirement. 

It sounds like the extension might not have permission to write the API key and consent values to storage. When you refresh the settings is the API key also cleared?

**Comment by nikhil-nayyar** [comment]
Appreciate the quick response!

When I refreshed the page, the API key disappeared. However, I clicked 'Load API Key' and it now persists in the box upon refresh. The 'I consent' box still clears on refresh.

**Comment by jacksonh** [comment]
Thanks. Are you familiar with using the Firefox developer console? If you could open the console, set the consent, then refresh the page maybe we will see something being blocked in the dev console

**Comment by nikhil-nayyar** [comment]
I'm a firmware guy by trade but I can make do

![image](https://github.com/omnivore-app/omnivore/assets/13279016/8b2acfd3-a4a7-4fe1-9214-5b9a6550af5a)

Checking the box, refreshing, doesn't yield anything different from the above console output. That gets printed as soon as the page loads but is unaffected by any of the actions on the page.

If I understand this correctly, it looks like the JS file might not even be loading in correctly?

**Comment by jacksonh** [comment]
Thanks, i think that gives me something to work with. Annoyingly adding this consent thing requires removing some of our content security policy. 

I will see if i can set up a replication of this.

**Comment by nikhil-nayyar** [comment]
Hey, following up on this, were you able to recreate this?

Otherwise, is there another way I can manually add articles from the browser to omnivore without using the extension?

**Comment by LaundroMat** [comment]
I fixed it by 
* right clicking on the Omnivore extension
* selecting "Manage Extension"
* Clicking the three dots in the extension options screen
![image](https://github.com/omnivore-app/omnivore/assets/42320/2b3708a1-0860-4368-adad-44fa8a8b14f5)
* Concenting to the privacy statement (checkbox under last paragrpah).

Reload the page you want to submit and it works. I didn't use an API key.

**Comment by Dan-Essin** [comment]
Yes, setting the api key and consent works but if these are essential, shouldn't the extension prompt for them on first run or when they are not set. It's both useless and frustrating to istall something only to have it not work.

**Comment by ptsl** [comment]
Hi guys. I stumbled on the same problem.
The same error message, the permissions seem to be alright.

Here are my observations:
1. I didn't know that I have to set the API key manually. (Or I might have overlooked it, if there was a message.) Having to use an API key in a Firefox extension seems quite strange to me. I have used several bookmarking services and none of them asked me to do such a thing. I just installed a plugin and it worked.
2. If it is necessary, for some reason, such an important setting should not be hidded in the "three dots" menu. Plugins usually create a new tab (in addition to Details and Permissions).

But I think you should not use a key in the Firefox plugin. Obsidian plugins are another thing, API keys are commonplace there.

Anyway, I'm not a plugin developer and I don't know what is technically or practically feasible. I just wanted to share my thoughts, with the risk that I'm not aware of the implementation details.

**Comment by jacksonh** [comment]
> Hi guys. I stumbled on the same problem. The same error message, the permissions seem to be alright.
> 
> Here are my observations:
> 
>     1. I didn't know that I had to set the API key manually. (Or I might have overlooked it, if there was such a message.) Having to use an API key in a Firefox extension seems quite strange to me. I have used several bookmarking services and none of them asked me to do it. I just installed a plugin and it worked.
> 
>     2. If it is necessary, for some reason, such an important setting should not be hidden in the "three dots" menu. Plugins usually create a new tab (in addition to Details and Permissions).
> 
> 
> But I think you should not use a key in the Firefox plugin. Obsidian plugins are different, API keys are commonplace there.
> 
> Anyway, I'm not a plugin developer and I don't know what is technically or practically feasible. I just wanted to share my thoughts, given that I'm not aware of the implementation details.

Normally you shouldn't need to set the API key manually, but I think your Firefox settings are preventing the extension from accessing the authentication cookie (maybe you have Firefox containers enabled?). 

I think we probably need a better way of detecting this for Firefox users as its becoming more common.

**Comment by ptsl** [comment]
You're right, I was trying to save a Facebook page when the error message was produced. And Facebook runs in its own container.

Then I tried it on other pages. The issue didn't go away, though. It appeared on all pages I tried.

Later I realized that the "I consent to data collection" checkbox was unchecked. Checking it seems to have resolved the issue.

But I'm pretty sure I've allowed data collection yesterday (not sure where - it might have been during the registration). But still, these setting should not be hidden in the hamburger menu, I think.

**Comment by jish** [comment]
I have the same issue.

Steps to reproduce:

1. Install Firefox Omnivore extension: https://addons.mozilla.org/en-US/firefox/addon/omnivore/
2. Go to a webpage
3. Click on the omnivore extension icon
4. Error dialog is shown

<img width="404" alt="Screenshot 2024-07-28 at 10 54 00 AM" src="https://github.com/user-attachments/assets/2d38d56e-3049-432c-a302-6f647a8b0d93">

Expected behavior

* No error is displayed
* Article is saved to Omnivore

**Comment by jacksonh** [comment]
Can you go into the plugin options and grant data collection consent? 

First click this three dots thing and choose preferences

<img width="830" alt="Screenshot 2024-07-29 at 10 56 28" src="https://github.com/user-attachments/assets/b451577a-1697-4db8-9bab-8c5f1a17759e">

then grant consent at the bottom of the page


<img width="1023" alt="Screenshot 2024-07-29 at 10 56 38" src="https://github.com/user-attachments/assets/ae9d6b5f-d4ca-49ce-95c0-160222817f5f">
