### ISSUE TITLE
Feature Request:Request banner sync

### ISSUE THREAD

**Issue by anschein** [omnivore-app/omnivore#3318]
I noticed that there is no banner or image option in the synchronization with obsidian in the document.
Request to add article banner as an optional synchronization item between omnivore and obsidian.

Like this ⬇️
![image](https://github.com/omnivore-app/omnivore/assets/49552476/4ee53866-0559-42bb-9581-608c1cc6ef05)

**Comment by jacksonh** [comment]
Thanks, is that just in the Obsidian front matter?

**Comment by anschein** [comment]
> Thanks, is that just in the Obsidian front matter?

Yes, to be precise, I think {{{image}}} can be placed anywhere as an optional variable. omnivore's obsidian plug-in provides powerful customization options. If we can have {{{image}}} As for variables, I think I can place them in frontmatter `banner: {{{image}}}` as data used by the banner plug-in, or directly in the text as illustrations like this:
# {{{title}}}
{{{image}}}
## highlights

**Comment by jacksonh** [comment]
https://github.com/omnivore-app/obsidian-omnivore/pull/175
