### ISSUE TITLE
FR: Mark & filter by items containing notes or highlights 

### ISSUE THREAD

**Issue by dairefagan** [omnivore-app/omnivore#3324]
Can you please use an icon, or otherwise mark inbox items we took the time to add a note to or highlight, and an option to filter by same.

Use case: view at a glance articles that are likely more significant, or those we still need to note or highlight.

Not sure if I need to request desktop and Android?

**Comment by jacksonh** [comment]
hi, on web we show the highlight count, we need to do the sam on Android. You can use the `Highlighted` saved search or just search "in:all has:highlights"

**Comment by dairefagan** [comment]
Thanks, not sure how I missed the saved search. "in:all has:highlights" is what I had in mind. What are your thoughts on has:notes?

The highlight count from mode:highlights is perfect, though I would like to be able to see that in the regular view, where articles without highlights have no count, and those without notes no (notepad?) icon. To me highlights and notes are at least as relevant as tags, and as such should be evident from the regular view, even if this requires an option in settings or a search argument to display.

**Comment by jacksonh** [comment]
Yeah we definitely want `has:notes` although right now notes are stored as a highlight, so `has:highlights` would return both.

**Comment by vardecab** [comment]
> hi, on web we show the highlight count, we need to do the sam on Android. You can use the `Highlighted` saved search or just search "in:all has:highlights"

I found an interesting behavior in which `has:highlights in:all mode:highlights` returns precisely 20 articles with highlights but `has:highlights in:all` returns all, ie. 108 articles. Is there a pagination issue when using `mode:highlights`? 

Context: I wanted to export all my highlights which is not possible without adding `mode:highlights`.  

PS. Looks like using `has:highlights in:all` is capped at 10 articles on Android? #3196

**Comment by jacksonh** [comment]
Hi, `mode:highlights` is actually only used by the frontend for display, so in terms of exporting you can just ignore that value I think.

**Comment by darthwalsh** [comment]
> right now notes are stored as a highlight, so `has:highlights` would return both.

Would it be right to document this workaround in https://docs.omnivore.app/using/search.html#finding-highlights ? 
Or if this is just an implementation detail, yes please add `has:notes`!
