### ISSUE TITLE
BUG: Failed to delete label

### ISSUE THREAD

**Issue by omerfarukabaci** [omnivore-app/omnivore#3327]
Hello, first I want to thank you for this great project!

I have an issue about deleting a label that I have created. The `id` of the label is `11982d46-95df-11ee-b11e-d70aa689ff0e`. It is being returned in the following request:

POST https://api-prod.omnivore.app/api/graphql
```
  query GetLabels {
      labels {
        ... on LabelsSuccess {
          labels {
            ...LabelFields
          }
        }
        ... on LabelsError {
          errorCodes
        }
      }
    }
    
  fragment LabelFields on Label {
    id
    name
    color
    description
    createdAt
  }
  ```

But when I try to delete it via the following request
POST https://api-prod.omnivore.app/api/graphql
```
mutation {
  deleteLabel(id: "11982d46-95df-11ee-b11e-d70aa689ff0e") {
    ... on DeleteLabelSuccess {
      label {
        id
        name
        color
        description
        createdAt
      }
    }
    ... on DeleteLabelError {
      errorCodes
    }
  }
}
```

I got a not found error:

```
{
  "data": {
    "deleteLabel": {
      "errorCodes": [
        "NOT_FOUND"
      ]
    }
  }
}
```

I don't know the exact reason, if needed I can provide further information. Again thanks for maintaining this great project! 🚀

**Comment by jacksonh** [comment]
Hey is there any chance this is one of the system labels, like `RSS`?

**Comment by omerfarukabaci** [comment]
Hey @jacksonh, name of the label is "Favorites", I am not sure if that's a system label.

**Comment by jun6lee** [comment]
I also still have a label I had initially called RSS (before feeds) that I renamed to RSSS to accommodate feeds, which I can't remove.

**Comment by omerfarukabaci** [comment]
@jacksonh I think you are right, it is a system label:

https://github.com/omnivore-app/omnivore/blob/main/packages/api/src/repository/label.ts#L17
