### ISSUE TITLE
Sync issues in the iOS apps

### ISSUE THREAD

**Issue by igorkulman** [omnivore-app/omnivore#3329]
With the latest iOS update I am experiencing sync issues.

This is what I do
- read an article on the iPad, archive it
- open the app on the iPhone, the article is still in inbox
- refresh the iPhone app (pull to refresh) .. the article is still in inbox
- refresh the iPad app (pull to refresh) .. the article is still in inbox in the iPhone

Basically the archive / delete state from one iOS device is not synced to the other, ever.

I tried the web app and there is what I found
- if I archive / delete an article on iPhone or iPad the change I see the change in the web app just OK
- if I archive or delete an article on the web the change is not done on iPhone or iOS

This leads me to a conclusion that syncing the state to iOS devices is broken.

I think it might be the same problem as https://github.com/omnivore-app/omnivore/issues/3295

**Comment by jacksonh** [comment]
hmm, thanks, and I assume both iPhone and iPad are online?

**Comment by jacksonh** [comment]
Ah thanks, i think i see the issue here. The deletes are being properly synced, but archives are not.

**Comment by jacksonh** [comment]
https://github.com/omnivore-app/omnivore/pull/3331

**Comment by jacksonh** [comment]
fix is available in TestFlight now

**Comment by jacksonh** [comment]
Available in the AppStore now. Will close this one but please re-open. Note there is a small sync delay of around 5s you might hit if trying to test, this is there to better handle Undo actions.
