### ISSUE TITLE
Chrome extension requires extra click to save a link

### ISSUE THREAD

**Issue by igorkulman** [omnivore-app/omnivore#3335]
In the Firefox extension I can right click on a link and save it

![Screenshot 2024-01-08 at 13 03 32](https://github.com/omnivore-app/omnivore/assets/4746070/70eeb441-ccbb-4681-a3e5-8793a735e1e2)

but with the Chrome extension I need to do one extra click to save it, which is kind of annoying

![Screenshot 2024-01-08 at 13 03 45](https://github.com/omnivore-app/omnivore/assets/4746070/0b32353e-a812-4133-9619-b5181b2e2889)

**Comment by DannieBGoode** [comment]
That is because you highlighted text, if you right click on the page without highlighting text before it should be 1 click only.
