### ISSUE TITLE
Error creating account

### ISSUE THREAD

**Issue by robertoftheedwards** [omnivore-app/omnivore#3337]
Device: iphone 13 mini
OS: 17.2.1
Browser: Safari
App ver: 1.41

1. I made an account 7 days ago (January 1, 2024) with “Sign in with Apple” in the iOS app.
2. I’m flighty and deleted my account through the same app within a couple minutes.
3. I got curious again and re-downloaded the iOS app today (January 8, 2024) and attempted to use the “Sign in with Apple” method to sign up again.
4. I can access the app, but my profile is empty (it just has the “@“ symbol with no username) and some functionality like creating a new email and deleting my account doesn’t work.
5. Attempted to sign up through iOS Safari with “Sign in with Apple” again.
6. I was presented with the step to enter a username, name, and bio.
7. After filling in that info and clicking next a message saying “Error creating account” appeared.

Other thing of possible note:
- I noticed that the same private relay email alias was being used. However I think that’s by design per Apple.

**Comment by robertoftheedwards** [comment]
Thanks! Just sent a message. Appreciate the quick response and explanation.

**Comment by jacksonh** [comment]
No problem. I will close this one but let me know (either here or in the form) if it has any issues.
