### ISSUE TITLE
Downloading audio does not seem to work in iOS

### ISSUE THREAD

**Issue by igorkulman** [omnivore-app/omnivore#3350]
In the iOS app when I open an article and tap Download Audio there is a toast at the bottom of the screen saying that the audio is being downloaded but no progress and no indication of error or success.

When I tap Download Audio again I just get a toast with a generic error. 

When I wait a bit longer and tap Download Audio I get the toast that audio is being downloaded again.

This UX makes it impossible to know if the audio is actually downloading, if it succeeded, if it errored out, if I can use it and it will work or not.

**Comment by jacksonh** [comment]
Thanks, I'm just going to remove this one for now.

**Comment by DavisOwen** [comment]
> Thanks, I'm just going to remove this one for now.

Any update on this? I would really benefit from the audio download feature, even if its not working perfectly.
