### ISSUE TITLE
iOS: Add a way to combine Inbox and Following on iPad

### ISSUE THREAD

**Issue by igorkulman** [omnivore-app/omnivore#3351]
Would be nice to be able to combine the Following and Inbox tabs. Having 2 separate tabs is confusing, I always look at the Inbox tab and forget to check the Following tab to see if there is anything in from RSS.

In previous app versions there was just one Inbox where I saw everything in a single place.

**Comment by jacksonh** [comment]
In Setting you can go to Filters and pick `Hide following tab`

**Comment by igorkulman** [comment]
Thanks, I missed this.

**Comment by igorkulman** [comment]
@jacksonh the Hide following tab setting does not do anything on iPad. Probably because here is no tab but a sidebar.
