### ISSUE TITLE
Feature Suggestion: Design improvement suggestion

### ISSUE THREAD

**Issue by ovizii** [omnivore-app/omnivore#3360]
I'm pretty happy with omnivore so far but while looking for alternatives before getting started I found another solution which in my opinion makes better use of the available space and requires fewer clicks for most actions while reading an article. I really think omnivore could get some inspiration from this other app. (no offence intended, this is simply a suggestion)

**Here is what the other app looks like. What I really like is that:**
- very little space is wasted at the top
- very little space is wasted on the left side
- the permanent sidebar on the right gives one-click access to all possible interactions with this one article/bookmark being viewed

![image](https://github.com/omnivore-app/omnivore/assets/837902/c283b518-4a51-407a-8b88-0bf7907df6d4)

**Comparing that to the current layout of omnivore, here are my improvement suggestions:**
 
- a lot of space is wasted at the top
- a lot of space is wasted on the left
- a lot of space is wasted on the right
- some metadata is visible below the title
- the rest of the interaction with this article/bookmark has to be accessed via multiple clicks via the menu on the left side
- the left side menu opens some function via modal pop-up, some open a sidebar on the right

![image](https://github.com/omnivore-app/omnivore/assets/837902/34c91115-dc59-4867-8f80-1d7a5a0f5176)

**Comment by jacksonh** [comment]
Thanks, regarding the margin size it is adjustable. Shorter lines of text are normally recommended for readability though.

**Comment by ovizii** [comment]
Thanks for taking a look. If you look closer, the length of the text lines is very similar, the other app simply uses the space to permanently display metadata in the sidebar on the right making things easier visible/accessible. 
its just about making better use of the available space and saving clicks for i.e. viewing metadata, editing tags, etc.

**Comment by jacksonh** [comment]
Ah ok, we do have plans to add a sidebar, just been focusing on other things lately and maybe more focused on reading experienced than other things.

As per needing to click a lot, I'd recommend using the keyboard commands.

**Comment by ovizii** [comment]
Thanks, I will look up the keyboard shortcuts in your docs. Those will be helpful. Feel free to close the ticket, for me the issue is resolved, I submitted my improvement suggestion. :-)

**Comment by HW05** [comment]
Hey @ovizii, here are some screenshots of mockups that I have been working on that features the side bar. 


![MacBook Air - 240](https://github.com/omnivore-app/omnivore/assets/115064895/b805a046-e8a9-4fce-bff6-75d2b0431b52)
![MacBook Air - 243](https://github.com/omnivore-app/omnivore/assets/115064895/f0764d9d-d5dd-439a-9056-296f4778524a)
![MacBook Air - 240](https://github.com/omnivore-app/omnivore/assets/115064895/029843b7-d70f-484e-bf0f-f29d2f8ceca4)
![MacBook Air - 243](https://github.com/omnivore-app/omnivore/assets/115064895/542983e6-81c2-43f8-978c-7840af047521)

**Comment by HW05** [comment]
Hey @ovizii, here are some screenshots of mockups that I have been working on that features the side bar.
![MacBook Air - 240](https://github.com/omnivore-app/omnivore/assets/115064895/3e26aaec-73c9-434b-92ed-66ab28b3d722)
![MacBook Air - 243](https://github.com/omnivore-app/omnivore/assets/115064895/cfb66d8d-c63f-4687-add7-6dfcd4867d3e)

![Capture](https://github.com/omnivore-app/omnivore/assets/115064895/0b451a18-b6fe-4da0-8674-c7a420f208eb)
![Capture1](https://github.com/omnivore-app/omnivore/assets/115064895/f963a9f1-c996-4c49-b034-fe3f8212a11b)

**Comment by ovizii** [comment]
Looks great, very close to what I screenshotted. That pretty much makes the menu on the left obsolete, right? 
I mean tags are on the right, the highlights, and notes are on the right, probably most of the metadata is on the right?
