### ISSUE TITLE
Add the dark theme from the web client on mobile

### ISSUE THREAD

**Issue by demetri-v** [omnivore-app/omnivore#3361]
It would be nice if the mobile clients had a dark theme like the web client.
The existing choice between full black and gray themes on the mobile clients is too steep, there should be something in between them.

Is it possible to expose the dark theme from web client on mobile?

**Comment by Rnbsov** [comment]
as a temporary solution you could try to turn on the Auto dark mode flag in chromium based browsers

![Screenshot_2024-01-11-20-25-53-506_com.android.chrome.jpg](https://github.com/omnivore-app/omnivore/assets/73550760/4ece2735-2d84-4e20-8a62-fa3b16e27777)

**Comment by Rnbsov** [comment]
as a temporary solution you could try to turn on the Auto dark mode flag in chromium based browsers

![Screenshot_2024-01-11-20-25-53-506_com.android.chrome.jpg](https://github.com/omnivore-app/omnivore/assets/73550760/4ece2735-2d84-4e20-8a62-fa3b16e27777)

And it will look like so

![Screenshot_2024-01-11-20-28-59-492_com.brave.browser.jpg](https://github.com/omnivore-app/omnivore/assets/73550760/d497c3e7-254d-4afc-923e-638385f2fdcb)

**Comment by demetri-v** [comment]
Thanks for your answer but it's not really what I've meant.
Let me explain

Take a look at these 2 screenshots

<img src="https://github.com/omnivore-app/omnivore/assets/80893378/35e9fb96-58a8-4589-a0e4-331d2cb2b3d0" width="300">
<img src="https://github.com/omnivore-app/omnivore/assets/80893378/ad181dcb-5df1-4482-94de-26f4dbd29b6e" width="300">

The left one is opened in a browser, the right one - in the Omnivore app on iOS 
I want to have a theme on the iOS app that looks the same as you provide in the web app version

**Comment by Rnbsov** [comment]
oh gotchu 👍
