### ISSUE TITLE
When multiselecting in Inbox filtered to Archive, bottom action button should be "Unarchive"

### ISSUE THREAD

**Issue by WillTwait** [omnivore-app/omnivore#3369]
For other filters, you would generally want to multi-select to archive. But when you are already in the `Archived` filter, the action button should be unarchive. Currently, it just gives you option to archive the already archived items.

![IMG_DB04D748E7FD-1](https://github.com/omnivore-app/omnivore/assets/1254659/8b4baacb-5134-4c08-9035-c88668c6e895)

**Comment by italovieira** [comment]
It's also occurs in web version:
![image](https://github.com/omnivore-app/omnivore/assets/8337230/14976236-38a8-41d5-b5ef-c4695e0c35bc)
