### ISSUE TITLE
Error when parsing front matter items when importing into Obsidian

### ISSUE THREAD

**Issue by wenlzhang** [omnivore-app/omnivore#3370]
I got the following errors when importing an article into Obsidian:
```
Error parsing front matter template YAMLParseError: Nested mappings are not allowed in compact mappings at line 14, column 12:

site_name: XX: YY
```

**Comment by natarslan** [comment]
Im having the same issue and I realised why this is happening.

**The error I get is this**
YAMLParseError: Nested mappings are not allowed in compact mappings

**Cause**
The dash character "-" in the title

**Solution**
Remove title from front matter

I will attach 2 screenshots demonstrating the fetches before and after removing the title from YAML.

**YAML with title** 
![omnivore yaml 1](https://github.com/omnivore-app/omnivore/assets/15086016/36293777-009f-4614-998d-3e8a4b4c7661)

**YAML without title**
![omnivore yaml 2](https://github.com/omnivore-app/omnivore/assets/15086016/2e83132f-a8d4-47d7-856c-a424e450783f)

**Request** 
It would be great if the characters in the title didnt impact the YAML. But I personally dont think its a big thing. Excluding the title from YAML is an ok solution for me. One can still add it inside the file (outside the YAML).

**Comment by jacksonh** [comment]
Hi, you should use a multi-line string for title like this:

```
title: >
  {{{title}}}
```

https://docs.omnivore.app/integrations/obsidian.html#front-matter-template

**Comment by natarslan** [comment]
> ```
> title: >
>   {{{title}}}
> ```

This was it. Somehow I accidentally removed ">" from my template. Thanks for pointing it out.
