### ISSUE TITLE
macOS: Safari extension does not show in the share sheet or context menu

### ISSUE THREAD

**Issue by igorkulman** [omnivore-app/omnivore#3371]
I installed the Omnivore macOS app to get the Safari extension but it does not show up in the share menu. 

It shows app in the Safari toolbar, I can save the currently open page but I cannot save any links because it does not show up in the share menu or context menu.

Looking at the extension shows an error

```
Failed to load images in default_icon for the browser_action or page_action manifest entry.
```

![Screenshot 2024-01-14 at 15 05 49](https://github.com/omnivore-app/omnivore/assets/4746070/fff6f189-e14f-4efa-ac89-8006f07bedb4)

**Comment by jacksonh** [comment]
Can I ask which version of Safari and MacOS you are on?

**Comment by jacksonh** [comment]
Actually, the Safari Extension wont display in the Share menu, I think the share menu is just for native mac apps. The extension should display on your browser bar something like this:

<img width="1233" alt="Screenshot 2024-01-15 at 10 09 53" src="https://github.com/omnivore-app/omnivore/assets/75189/d1dadbd6-0c1c-4d79-9649-c1cbe27eba10">

**Comment by igorkulman** [comment]
> Can I ask which version of Safari and MacOS you are on?

I am on Sonoma 14.2.1 (23C71) and Safari  17.2.1 (19617.1.17.11.12)

> Actually, the Safari Extension wont display in the Share menu, I think the share menu is just for native mac apps. The extension should display on your browser bar something like this:

I see the button in the toolbar and it works fine for saving the currently open page. That is fine. But how do I save a link?

I expected an option to save in a link context menu after a right click like in Firefox but there is nothing

![Screenshot 2024-01-15 at 8 20 31](https://github.com/omnivore-app/omnivore/assets/4746070/1a8ca5de-609e-4532-ae57-1f196417a266)

I thought that maybe you were not able to put it there (although it is possible seeing other extensions doing it) so I thought maybe I need to do one more click and do Share in the context menu but Omnivore is not in the share menu either. 

So how do I share a link to Omnivore from Safari?

**Comment by igorkulman** [comment]
@jacksonh any update on this? Not being able to save a link to Omnivore from context menu like in Firefox and having to visit the link to use the toolbar button is not ideal.

**Comment by jeffbowen** [comment]
I might be able to take a crack at this sometime soon. Doesn't look too hard:
- [Using contextual menu and toolbar item keys | Apple Developer Documentation](https://developer.apple.com/documentation/safariservices/safari_app_extensions/safari_app_extension_information_property_list_keys/using_contextual_menu_and_toolbar_item_keys#2958160)
- [Adjusting settings for contextual menu items | Apple Developer Documentation](https://developer.apple.com/documentation/safariservices/safari_app_extensions/safari_app_extension_information_property_list_keys/adjusting_settings_for_contextual_menu_items)

**Comment by jacksonh** [comment]
> @jacksonh any update on this? Not being able to save a link to Omnivore from context menu like in Firefox and having to visit the link to use the toolbar button is not ideal.

I think its actually all done, just because of Apple we have to re-submit the entire mac app to update the extension. And unfortunately it probably doesn't build right now. Could go back to an earlier branch too.

**Comment by jeffbowen** [comment]
Thanks for the heads up. I'll take a look at whatever the latest build is before trying anything.

**Comment by andszk** [comment]
any update on this issue? Were you able to build Mac version? Do you have link to issue causing Mac version not building right now? (Does it even have its own issue?)
