### ISSUE TITLE
Bug in parsing some tts data

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#3374]
Most likely something with quoting

From a user:

```
I’ve encountered this text to speech playback error often in the current and past versions of omnivore where the voice playback simply stops mid sentence randomly and the play/pause button vanishes. If I minimize the audio player, the banner says in red font “there was a problem playing the audio” or the like, and simply re-playing does not help get past the blockage. What I suspect is the culprit is the circled isolated quote in this screenshot. Playback failures tend to occur a little before these lone quotation marks and if I start the audio from after the quote, it is able to finish playing. Not 100% sure but hope it helps reproducing the bug. This particular article is here: https://archive.ph/20230806165118/https://www.nytimes.com/2023/08/04/opinion/oppenheimer-stalin.html
```

<img width="796" alt="Screenshot 2024-01-16 at 08 58 12" src="https://github.com/omnivore-app/omnivore/assets/75189/7489f3aa-5005-4951-986d-c0f5d9ee9ea1">

**Comment by sywhb** [comment]
```
Tokenized sentences [
  'Nor was Stalin any kind of naïve, unsuspecting victim of Hitler’s Barbarossa onslaught, as some historical clichés would have it.',
  'McMeekin makes an extended case that Stalin was preparing to attack Nazi Germany when Hitler attacked him, that the two dictators were basically in a race to see who could mobilize to betray the other first — and that the initial Soviet debacle in 1941 happened in part because Stalin was also pushing his military toward an offensive alignment, and they were caught in a “mid-mobilization limbo.',
  '”'
]
```

**Comment by DavisOwen** [comment]
For some reason I'm still getting this issue on iOS production. Smart quotes seem to break TTS

**Comment by jacksonh** [comment]
> For some reason I'm still getting this issue on iOS production. Smart quotes seem to break TTS

Thanks, do you have an article with them that you could share?

**Comment by DavisOwen** [comment]
Ok I spent quite a bit of time playing around trying to reliably reproduce this. The issue appears to be if 

1. A line starts with a quotation (doesn't matter if its smart quote or not). and there is no space between the quote and the first character.
2. The line is a run-on sentence, with no periods or newlines and it spans over 256 characters. 

Here is an example text (randomly generated):

"I never knew what hardship looked like until it started raining bowling balls Not all people who wander are lost Peanuts don't grow on trees, but cashews do Even with the snow falling outside, she felt it appropriate to wear her bikini He was sitting in a trash can with high street class

I used this free website to generate a link you can use to generate an omnivore article to reproduce https://ctxt.io/2/AADIS7tQFg. Just save that and try to TTS it.

**Comment by saeedesmaili** [comment]
I've added a few examples in https://github.com/omnivore-app/omnivore/issues/4008

**Comment by saeedesmaili** [comment]
Are there any updates on this issue?
