### ISSUE TITLE
Certain Labels Assigned to Everything

### ISSUE THREAD

**Issue by SamGreenwood1** [omnivore-app/omnivore#3386]
Encountering an issue where each message gets four duplicated labels, despite correct rule setup. Upon checking, no rule errors were found. However, attempting to remove these labels reveals an empty label selector. This leads to messages having incorrect labels and missing the intended ones.

**Comment by jacksonh** [comment]
@SamGreenwood1 can you add a screenshot of your rules?

**Comment by jacksonh** [comment]
Thanks, and which label was added to all pages?

**Comment by jacksonh** [comment]
I think there is a missing quote in the politics rule

**Comment by SamGreenwood1** [comment]
Though Israel, RAC, URJ and (sometimes) News are the labels being added inadvertently. RAC and URJ are the ones being added twice.

**Comment by SamGreenwood1** [comment]
I think it might be a problem with the "author:" operator.

**Comment by jacksonh** [comment]
If you use regular search with those queries do those items appear?
