### ISSUE TITLE
An abbr (abbreviation) HTML tag with a title containing "published" can break capture

### ISSUE THREAD

**Issue by justinsteven** [omnivore-app/omnivore#3387]
I noticed this when reading https://explained-from-first-principles.com/email

It contains things such as:

```html
<a href="[https://datatracker.ietf.org/doc/html/rfc2047](view-source:https://datatracker.ietf.org/doc/html/rfc2047)"><abbr title="Request for Comments, published by the Internet Engineering Task Force (IETF)">RFC</abbr> 2047</a> specifies how one can use non-<abbr title="American Standard Code for Information Interchange">ASCII</abbr> characters
in <a href="[https://datatracker.ietf.org/doc/html/rfc2047#page-8](view-source:https://datatracker.ietf.org/doc/html/rfc2047#page-8)">certain header field values</a>,
such as the <a href="[#subject](view-source:https://explained-from-first-principles.com/email/#subject)">subject</a> and the <a href="[#display-name](view-source:https://explained-from-first-principles.com/email/#display-name)">display names</a>.
```

i.e.

> RFC 2047 specifies how one can use non-ASCII characters in certain header field values, such as the subject and the display names.

Mousing over "RFC" shows a tooltip that says "Request for Comments, published by the Internet Engineering Task Force (IETF)"

Omnivore captures this as:

```html
<a data-omnivore-anchor-idx="9783" href="https://datatracker.ietf.org/doc/html/rfc2047"> 2047</a> specifies how one can use non-<abbr data-omnivore-anchor-idx="9784" title="American Standard Code for Information Interchange">ASCII</abbr> characters
in <a data-omnivore-anchor-idx="9785" href="https://datatracker.ietf.org/doc/html/rfc2047#page-8">certain header field values</a>,
such as the <a data-omnivore-anchor-idx="9786" href="#subject">subject</a> and the <a data-omnivore-anchor-idx="9787" href="#display-name">display names</a>.
```

i.e.

> 2047 specifies how one can use non-ASCII characters in certain header field values, such as the subject and the display names.

Note that "RFC" is missing from the capture. I suspect this is because it is in the source document as:

```html
<abbr title="[... SNIP ...] published [... SNIP ...]">RFC</abbr>
```

Omnivore is trying to interpret this as a publish date? It may be failing to do so, and thus omitting the abbr from the capture entirely?

# Minimal reproducer

Capturing the following:

```html
<html>
<body>
<p>
AAAA <abbr title="I am OK">BBBB</abbr> CCCC <abbr title="DDDD">EEEE</abbr> FFFF
</p>
</body>
</html>
```

Results in:

> AAAA BBBB CCCC EEEE FFFF

:+1: 

The following:

```html
<html>
<body>
<p>
AAAA <abbr title="published">BBBB</abbr> CCCC <abbr title="DDDD">EEEE</abbr> FFFF
</p>
</body>
</html>
```

Results in:

> AAAA CCCC EEEE FFFF

"BBBB" is missing.

An `abbr` with a title of simply "published" is obtuse. But as discussed above, an `abbr` with a title such as "Request for Comments, published by the Internet Engineering Task Force (IETF)" is sensible, and is used by at least one author.

**Comment by jacksonh** [comment]
Thanks, I suspect whats happening is that element gets extracted and assumed to be the node with publishedDate information. There's a pretty crude regex for extracting this, I'll look into how we can improve it without breaking anything.

Thank you soooo much for that minimum reproducible, makes this way easier.
