### ISSUE TITLE
正文捕获问题

### ISSUE THREAD

**Issue by StrollStars** [omnivore-app/omnivore#3397]
链接：https://mp.weixin.qq.com/s?__biz=MzUyMzUyNzM4Ng==&mid=2247486167&idx=1&sn=d8d1aa2a6594cbeba5def8c708bbb8cb#wechat_redirect
问题：尝试多次，都无法捕获到正文。

**Comment by StrollStars** [comment]
发现上述问题没有了，但是出现了新的问题，无法获取到标题。
链接：http://mp.weixin.qq.com/s?__biz=MzUyMzUyNzM4Ng==&mid=2247486304&idx=1&sn=a59e5cbefb3c6de893678ea90874bfb7&chksm=fa3a7ed5cd4df7c314acb5c0d2d90ad3e65e9bc12648de1f0d0265b0ce7d2e6f6fe968dbc728&scene=21#wechat_redirect

**Comment by StrollStars** [comment]
@sywhb 上述两个问题都解决了，但是我感觉很奇怪，以前一次性就能保存成功，这回要折腾好几次，甚至要等到第二天。是你们手动在调整吗？还是服务器抓取不够稳定？

**Comment by sywhb** [comment]
> @sywhb 上述两个问题都解决了，但是我感觉很奇怪，以前一次性就能保存成功，最近要折腾好几次，甚至要等到第二天。是你们手动调整帮忙保存了文章？还是服务器抓取不够稳定？

有一些是请求超时了，不知道是不是我们的 ip 被微信封了。我再测试一下

**Comment by StrollStars** [comment]
@sywhb 我开始也有这个猜测，但是后来几次折腾后又能成功了，如果不是你们后台调整过，这个问题就比较奇怪。

**Comment by StrollStars** [comment]
@sywhb 我发现安卓手机端保存成功率比网页版要高，但是很奇怪，保存文章不是服务端的操作么？和客户端也有关系？
