### ISSUE TITLE
Feature Request: remember reading progress when adding to omnivore

### ISSUE THREAD

**Issue by fvgendt** [omnivore-app/omnivore#3411]
Often I'm reading an article in my browser, and then I need to go and want to continue reading later. So, before I go I just add the articile to Omnivore. Then when I want to continue where I left off I open Omnivore, but I find that it hasn't picked up the progress that I already made in the browser. It would be neat if I could just continue reading in Omnivore from where I was left when I was reading in the browser.

As far as I know this feature is not yet supported, but I think it would be a great addition!

**Comment by jacksonh** [comment]
Ah interesting idea. I suppose its possible to get the top element at the time of save. It could cause a bit of confusion though as people would see lots of items with low read percentages.

**Comment by fvgendt** [comment]
> Ah interesting idea. I suppose its possible to get the top element at the time of save. It could cause a bit of confusion though as people would see lots of items with low read percentages.

I agree, but if it is possible to get the scroll bar position, a (in my opinion dirty, but reasonable) fix for this would be to only save the progress if the scroll bar is not entirely up.
