### ISSUE TITLE
rules seems don't work

### ISSUE THREAD

**Issue by up2young** [omnivore-app/omnivore#3432]
I set some rules but they don't work as expected, anything wrong with my setting?
![image](https://github.com/omnivore-app/omnivore/assets/1219571/a6621506-648d-4505-bcc0-b63a7c87e6c3)

**Comment by jacksonh** [comment]
on the first one `event.updated` shouldn't be there
on the second one `is:read()` isn't a valid rule. 

If you saw these in docs can you point me to it?

**Comment by harkmall** [comment]
I'm having an issue with my rule to archive read articles. Screenshot attached.
![image](https://github.com/omnivore-app/omnivore/assets/3711400/52796ace-53ba-4a7d-831e-2f2e22b7e665)

Not sure if it's relevant but I'm seeing the issue on the Inbox for subscribed newsletters.

**Comment by jacksonh** [comment]
Could you try `in:all is:read` ?

**Comment by up2young** [comment]
> Could you try `in:all is:read` ?

Thanks for your help. I've tried again, but still don't work.
![image](https://github.com/omnivore-app/omnivore/assets/1219571/340c96bd-2ce1-4895-953e-d9f1247b1119)

**Comment by up2young** [comment]
> on the first one `event.updated` shouldn't be there on the second one `is:read()` isn't a valid rule.
> 
> If you saw these in docs can you point me to it?

I saw `event.updated` in this part of doc: https://docs.omnivore.app/using/rules.html#the-event-object.  As for `is:read()` , that was just a misunderstanding.
