### ISSUE TITLE
Custom shortcut for "add to Omnivore" in extensions

### ISSUE THREAD

**Issue by MartinBernstorff** [omnivore-app/omnivore#3433]
Love the work you guys do! ❤️ 

The Chrome extension's shortcut conflicts with other extensions I have installed, and I am unable to change the shortcut. 

I don't have experience in Chrome extensions, but if someone experienced could point me in the right direction, I'm up for giving it a go with a PR 👍

**Comment by jacksonh** [comment]
Hey, yeah this is controlled by Chrome, here's a quick demo on how to access the setting: https://www.loom.com/share/13f5d97f4f24465dbc9418ab54768f4b

**Comment by MartinBernstorff** [comment]
Very kind, thanks a lot! Closing.
