### ISSUE TITLE
Default settings for search

### ISSUE THREAD

**Issue by thekettleison** [omnivore-app/omnivore#3436]
Hello! Love Omnivore, use it every day. Today though it took me a little while to uncover that to search all my articles ever saved, I have to add "in:all" to the search bar, especially when searching within a label. It's a bit unintuitive to me that way. I think of search as starting broadly, and then adding filters to narrow it down, not adding filters to widen the search. 

I'd recommend having the search default for archive status be "in:all" and for read status to include both read and unread.
<img width="586" alt="Screenshot 2024-01-24 at 4 26 47 PM" src="https://github.com/omnivore-app/omnivore/assets/121907631/6bf7818a-c90c-418d-b4d2-9d7c722c2389">

When I'm searching for a keyword, I'm more likely to want to start searching as widely as possible, then narrow it down as needed. Curious what others think!

**Comment by margani** [comment]
Couldn't you add a new Saved Search for "All (in:all)" and Pin it?

![image](https://github.com/user-attachments/assets/8fd15960-3095-4b8a-9406-b1201ead023f)

![image](https://github.com/user-attachments/assets/22556b5d-ce86-4b5a-ba00-f91ee69ade7d)

**Comment by thekettleison** [comment]
Yes, absolutely, that's a good way to search all once you know that's not the default.  I still would find it more intuitive that the default search behavior already be "in:all" and imagine others might not realize that searching will search only the inbox by default and exclude the archive, unless they're closely reading the docs :)

**Comment by margani** [comment]
Yes, you are right. I realised that clicking on a pinned Saved Search, resets other searches in the search box.
