### ISSUE TITLE
Text color in dark mode is too white

### ISSUE THREAD

**Issue by baptisteArno** [omnivore-app/omnivore#3439]
I'd love the Omnivore app to have the same theme that I'm using on Reader (I think they've nailed it in terms of eyes comfort at night)

https://github.com/omnivore-app/omnivore/assets/16015833/8e6858bd-3e41-4a40-a08e-fb3e2022cf10

**Comment by jacksonh** [comment]
You can go into advanced settings in the reader display settings (the thing where you change your font) and try disabling High Contrast

**Comment by baptisteArno** [comment]
Oh that's great to hear, thank you for that!
