### ISSUE TITLE
Feature request: display "decluttered" original in Omnivore 

### ISSUE THREAD

**Issue by kbdragon** [omnivore-app/omnivore#3450]
I came across https://unclutter.it/ and loved their approach: remove all burdensome elements (ads, etc.) and display the website in a recognizable way. 

Would something like this be possible to implement in Omnivore? Thanks

**Comment by jacksonh** [comment]
Yeah I do like his approach. Right now its quite a challenge as we do need some more formatting to be able to do text to speech and highlighting which rely on a certain underlying structure of the data.

**Comment by kbdragon** [comment]
Thanks for explaining. I hope it becomes possible in the future.
