### ISSUE TITLE
BUG : Labels not supporting "&" Symbol

### ISSUE THREAD

**Issue by hfactor** [omnivore-app/omnivore#3456]
While creating a label **A&B** in omnivore, it turns to **A&amp;B**. Other symbols are supported. 
<img width="1128" alt="Screenshot 2024-01-29 at 5 05 56 PM" src="https://github.com/omnivore-app/omnivore/assets/1788677/c043aba0-5b13-45d5-950a-8c84bef12bf2">

**Comment by jacksonh** [comment]
Definitely some weird double escaping here.
