### ISSUE TITLE
FR: Suggest similar articles

### ISSUE THREAD

**Issue by MartinBernstorff** [omnivore-app/omnivore#3465]
I love reading many articles on a similar subject in a row, to check which claims are "agreed upon" in a field, and which are more unique to a specific author. 

To that end, if Omnivore could recommend similar articles after reading a specific one (e.g. using word embedding), it could enable very nice discovery in my collection.

I imagine one would have to supply an embedding-provider API-key, so the user pays for the document embedding themselves.

What do you guys think? Niche use-case, or nice feature?

**Comment by jacksonh** [comment]
Hey @MartinBernstorff do you expect them to be other articles from in your library or from external sources?

**Comment by MartinBernstorff** [comment]
I'd mostly be interested in other articles from my library :-)
