### ISSUE TITLE
BUG: iOS crashing after saving and archiving

### ISSUE THREAD

**Issue by northgardner** [omnivore-app/omnivore#3471]
I have been experiencing the following bug frequently on the iOS app on my iPhone 13 (running iOS 17.2.1):

When I tap the archive button, or when I slick "save" after adding labels, the whole screen turns black. This happens frequently, but not all the time. When this happens I am usually on the subway, where there is no cellular service or wifi between stations.

**Comment by jacksonh** [comment]
Thanks, i think we tracked this one down last night and are working on a fix.

**Comment by jacksonh** [comment]
This is happening from within the reader view?

**Comment by northgardner** [comment]
Yes, it's happening when I'm in the reader view, and I have clicked the
archive icon, either on the page or in the menu, or after I have tapped
"save" after adding labels.

**Comment by northgardner** [comment]
This seems to be happening more often (and perhaps exclusively) in landscape orientation.   
  
  
  
  
  
  
  

  
  
>
