### ISSUE TITLE
Feed takes a long time to load

### ISSUE THREAD

**Issue by northgardner** [omnivore-app/omnivore#3472]
I use Omnivore frequently when riding the subway, where there is no cellular or wifi between stations. When I go to the feed, it often takes a long time for it to load. 
![signal-2024-01-31-113043](https://github.com/omnivore-app/omnivore/assets/13039331/d6a447fe-a7f0-414d-a842-0c96762b9bb8)

**Comment by jacksonh** [comment]
Are you sure you are offline there? Statusbar looks like its showing connection, i wonder if its a slow/breaking connection that its trying to load. Do you mind putting in airplane mode and seeing if you get the same results?

**Comment by northgardner** [comment]
I may have been online at that moment, as I may have been entering a station, where there is cellular service.   
  

  
This has not happened when I have gone on airplane mode.
  
  
  
  
  
  
  

  
  
>

**Comment by northgardner** [comment]
I've just seen this behavior when fully connected to wifi, although length of time it looked like that was shorter than it often has been when I'm in and out of cellular service. This time was about five seconds.

**Comment by northgardner** [comment]
After observing this over the past month, I no longer think this is related to being offline. The issue has continued though. I wonder if it is related to the number of items in my Inbox, which is in the thousands.

**Comment by chrismatheson** [comment]
Yes I see similar. Looks (to my untrained in this codebase eye) like maybe there is a 

```
if(online){
  refresh data then render
} elese {
  get data from cache then render
}
```

maybe a stale while refresh approach could make things feel a little snapper ?  https://www.geeksforgeeks.org/next-js-swr-stale-while-revalidate-introduction/

**Comment by jacksonh** [comment]
Do you happen to have a lot of PDFs at the top of your list?

**Comment by northgardner** [comment]
No. I’m not sure if I have any PDFs at all in my list.   
  
  
  
  
  
  
  

  
  
>
