### ISSUE TITLE
UX: Suggesting more intuitive color scheme for 'No results found for this query'

### ISSUE THREAD

**Issue by rodrigolourencofarinha** [omnivore-app/omnivore#3474]
I have some minor feedback from a fellow marketer's perspective. 

When a query is made and the message "No results found for this query" appears.

![Screenshot_2024-01-31_15-55-39](https://github.com/omnivore-app/omnivore/assets/62388933/1c0949a5-269e-4399-8ab7-b3467dca40ff)

![Screenshot_2024-01-31_15-56-05](https://github.com/omnivore-app/omnivore/assets/62388933/1989d20b-ebfd-4b35-8a40-2490bffd3b04)

The red color in the background seems a bit intrusive. Inexperienced users might associate this red color with a problem on the website or something they did wrong. Therefore, I suggest using a softer color, like grey, which would be more intuitive for customers. I know this is a minor detail, but since you are open to feedback, I thought it would be good to share this with you.

**Comment by jacksonh** [comment]
The red is gone. Thanks!
