### ISSUE TITLE
iPadOS 15.7.2 text properties menu bug

### ISSUE THREAD

**Issue by 1001ruchka** [omnivore-app/omnivore#3477]
iPadOS 15.7.2 
Bug with displaying text properties menu
![F0FC349B-FDDA-4263-9C7F-4277DC7D6D6F](https://github.com/omnivore-app/omnivore/assets/5934321/5d1d0002-2c40-4cd1-9c95-2240fbe11af9)

**Comment by jacksonh** [comment]
Thanks, a few people have reported this one but I've never been able to replicate
