### ISSUE TITLE
Archived items not synced in Obsidian

### ISSUE THREAD

**Issue by Subjuntivos** [omnivore-app/omnivore#3499]
As far as I have been able to understand, articles that are archived are not eligible for syncing in Obsidian vía API (I tried most variants).
I had a bunch of items with a lable (label:obs) that would not be imported into Obsidian, no matter what filter/setting I had, until I moved them back to the inbox (in omnivore).

In practice, it means that if I save an article to omnivore, with a label, and then read it and archive it, it won't be imported into obsidian next time I do a sync/resync, because of its quality of being ardchived.
Is this by design? Could we possibly override this?

Thanks a lot!

**Comment by jacksonh** [comment]
Hi, if you have a custom query you should add `in:all` to get archived items so something like `in:all label:Obsidian`

**Comment by jacksonh** [comment]
Going to close this as i am pretty sure its related to the default filter used.
