### ISSUE TITLE
Export/Download document to EPUB (& other format)

### ISSUE THREAD

**Issue by DanielChesters** [omnivore-app/omnivore#3504]
Hi,

Like I said [here](https://github.com/omnivore-app/omnivore/issues/2142#issuecomment-1920181251), I cannot consider migrate from Wallabag if I cannot export document to EPUB format.

Any hope to have a document export/download functionality with diverse document formats like EPUB or PDF ?

Thank you :pray:

**Comment by jacksonh** [comment]
Would HTML or Markdown be an acceptable format?

**Comment by jacksonh** [comment]
Ah never mind, I see the intent is to read on kindle not to just get data out.

**Comment by DanielChesters** [comment]
In my case, it will be to read on a Kindle (or another e-reader), so yes I focus on EPUB format, but it could be nice to have a bunch of formats like HTML, TXT, MD, PDF, etc.
