### ISSUE TITLE
[Feature Request] Add the abilitiy to exclude tags in search

### ISSUE THREAD

**Issue by flowingblaze** [omnivore-app/omnivore#3505]
When you search, your able to search by tag. I think there should be a way to exclude a tag when searching so that way everthing else but those tags show up in search.

**Comment by jacksonh** [comment]
Hi @flowingblaze you can use the `-label:` in your query, so like this would be no items tagged RSS `in:all -label:RSS`

**Comment by flowingblaze** [comment]
Ah I didn't see that in the docs. Thank you!

**Comment by jacksonh** [comment]
Yeah probably need to improve our docs more. Thanks for pointing out!
