### ISSUE TITLE
bug: bad support for www.zhihu.com

### ISSUE THREAD

**Issue by laybxc** [omnivore-app/omnivore#3510]
omnivore has bad support for www.zhihu.com. for example in this picture
![image](https://github.com/omnivore-app/omnivore/assets/73053168/986fabc8-06d4-47df-a080-5666ecab89ec)

**Comment by zhaoqxu-eth** [comment]
Is there any possibility of prioritizing better support for [www.zhihu.com](https://www.zhihu.com/)? As one of the most popular Chinese websites with 99 million active monthly users, it's a significant platform. I'm a heavy user of Zhihu, and the current formatting issues in Omnivore significantly hinder my experience with this fantastic read-it-later app.

**Comment by chs33** [comment]
+1 to this, Pocket did much better on Zhihu capture.
