### ISSUE TITLE
Duplicate "Article" objects are created in Readwise (affects PDF only?)

### ISSUE THREAD

**Issue by justinsteven** [omnivore-app/omnivore#3513]
I have connected Omnivore to Readwise.

I have loaded https://www.rfc-editor.org/rfc/pdfrfc/rfc5321.txt.pdf into Omnivore. Note that it is a PDF. I haven't noticed this behaviour happening with non-PDF type articles, but it's very readily reproducible with at least this PDF.

I have made two highlights in the PDF within Omnivore.

![image](https://github.com/omnivore-app/omnivore/assets/1893909/4bca963a-c1e1-4d76-86e5-befc17cb2868)

Approximately once per hour, a duplicate "Article" is created in Readwise for this PDF. Each time it is created, the two highlights are populated.

![image](https://github.com/omnivore-app/omnivore/assets/1893909/8727fb5c-f1df-42b1-803f-eda7ed3ce5b6)

![image](https://github.com/omnivore-app/omnivore/assets/1893909/c4e08450-1bbb-4ee8-b52a-6f662fd2f3c9)

My guess is that the Omnivore --> Readwise sync process runs approximately once per hour, and each time it runs, the "Article" object on the Readwise end is being recreated.

My https://readwise.io/api/books/?category=all says:

```json
[{"id": REDACTED, "book_data_id": REDACTED, "amazon_id": null, "title": "RFC5321 SMTP _2", "author": "RFC Editor", "readable_title": "RFC5321 SMTP _2", "resurface_weighting": 1.0, "cover_image_url": "REDACTED", "small_image_url": "REDACTED", "num_highlights": 2, "last_highlight_at": 1707264960, "is_article": false, "book_type": "omnivore", "filter_include": true, "category": "articles", "book_tags": [], "source_syncs_all_books_together": false}, {"id": REDACTED, "book_data_id": REDACTED, "amazon_id": null, "title": "RFC5321 SMTP _2", "author": "RFC Editor", "readable_title": "RFC5321 SMTP _2", "resurface_weighting": 1.0, "cover_image_url": "REDACTED", "small_image_url": "REDACTED", "num_highlights": 2, "last_highlight_at": 1707264960, "is_article": false, "book_type": "omnivore", "filter_include": true, "category": "articles", "book_tags": [], "source_syncs_all_books_together": false}, {"id": REDACTED, "book_data_id": REDACTED, "amazon_id": null, "title": "RFC5321 SMTP _2", "author": "RFC Editor", "readable_title": "RFC5321 SMTP _2", "resurface_weighting": 1.0, "cover_image_url": "REDACTED", "small_image_url": "REDACTED", "num_highlights": 2, "last_highlight_at": 1707264960, "is_article": false, "book_type": "omnivore", "filter_include": true, "category": "articles", "book_tags": [], "source_syncs_all_books_together": false}, {"id": REDACTED, "book_data_id": REDACTED, "amazon_id": null, "title": "RFC5321 SMTP _2", "author": "RFC Editor", "readable_title": "RFC5321 SMTP _2", "resurface_weighting": 1.0, "cover_image_url": "REDACTED", "small_image_url": "REDACTED", "num_highlights": 2, "last_highlight_at": 1707264960, "is_article": false, "book_type": "omnivore", "filter_include": true, "category": "articles", "book_tags": [], "source_syncs_all_books_together": false}, [... SNIP ...]
```

I've redacted several fields. The `id` and `book_data_id` values are all distinct. The image URL values are not all distinct.

# Expected behaviour

Duplicate items are not created at Readwise

**Comment by justinsteven** [comment]
Update: I made one additional highlight in the PDF and waited about an hour. I now have five instances of the article created within Readwise with two highlights, and one additional instance created within Readwise with three.

**Comment by justinsteven** [comment]
@jacksonh I re-added the same PDF (but forgot to rename it to something sensible in Omnivore), highlighted it, and allowed a few instances of it to be created in Readwise.

Based on this I can't see how the following differ in any way on the Readwise end:

1. A PDF in Omnivore, with highlights, synced to Readwise (https://www.rfc-editor.org/rfc/pdfrfc/rfc5321.txt.pdf)
2. A HTML article in Omnivore, with highlights, synced to Readwise (https://www.whatbitcoindid.com/podcast/whitfield-diffie-on-the-history-of-cryptography?format=amp)

e.g. Readwise says:

![image](https://github.com/omnivore-app/omnivore/assets/1893909/02be4be5-8bce-4c9b-900a-ea9ca1b6d1b1)

![image](https://github.com/omnivore-app/omnivore/assets/1893909/b6e829b2-b460-46e9-9e12-3b1ae5c9bf39)

![image](https://github.com/omnivore-app/omnivore/assets/1893909/8f51cd62-33cc-4669-9943-3381740deb9b)

https://readwise.io/api/books/?category=all says:

```json
// SNIP

{
	"3": {
		"id": REDACTED,
		"book_data_id": REDACTED,
		"amazon_id": null,
		"title": "Enscript Output",
		"author": "RFC Editor",
		"readable_title": "Enscript Output",
		"resurface_weighting": 1,
		"cover_image_url": "https://readwise-assets.s3.amazonaws.com/static/images/REDACTED.png",
		"small_image_url": "https://readwise-assets.s3.amazonaws.com/static/images/REDACTED.png",
		"num_highlights": 1,
		"last_highlight_at": 1707287669,
		"is_article": false,
		"book_type": "omnivore",
		"filter_include": true,
		"category": "articles",
		"book_tags": [],
		"source_syncs_all_books_together": false
	}
}

{
	"4": {
		"id": REDACTED,
		"book_data_id": REDACTED,
		"amazon_id": null,
		"title": "Whitfield Diffie on the History of Cryptography",
		"author": "Peter McCormack",
		"readable_title": "Whitfield Diffie on the History of Cryptography",
		"resurface_weighting": 1,
		"cover_image_url": "https://proxy-prod.omnivore-image-cache.app/REDACTED",
		"small_image_url": "https://proxy-prod.omnivore-image-cache.app/REDACTED",
		"num_highlights": 1,
		"last_highlight_at": 1707220426,
		"is_article": false,
		"book_type": "omnivore",
		"filter_include": true,
		"category": "articles",
		"book_tags": [],
		"source_syncs_all_books_together": false
	}
}

// SNIP
```

**Comment by jacksonh** [comment]
Ah so I guess for PDFs readwise doesn't have a URL to deduplicate with. That means we will probably have to maintain some state from them to keep those IDs

**Comment by thiswillbeyourgithub** [comment]
Maybe related : when highlighting PDF the highlight appears in yellow, and I noticed that often (after changing pages ? after reloading ? i don't know!) I noticed that the highlight was a darker shade of yellow. It's actually because there are duplicate highlights created on top of it (confirmed by deleting the highlight and seeing the color get lighter and lighter ; also confirmed by adding a note to the first highlight and seeing that I can only access if later if I delete the "above" layers of duplicates). All of this is on the android version 0.0.188
