### ISSUE TITLE
**Add Labels** Autocomplete Prevents Expected Usage on Mac Desktop App

### ISSUE THREAD

**Issue by mjs271** [omnivore-app/omnivore#3520]
Hello, all. First wanna say that I love the app and realize that the desktop app is very much a work in progress. Wanted to put this on your radar, though.

The issue I'm having is that if I attempt to add labels to an already imported article, via `right click` > `Add Labels`, the autocomplete appears to fully prevent me from most methods of usage.

E.g., If I want to tag something **_To Do_**, I type `To` and the autocomplete dropdown menu instantly pops up (provided that nothing else begins with T and is still in the filtered options below). At this point, I could use my mouse/trackpad to choose from the available options in the dropdown or list below. However, the expected keyboard options are unavailable to me. Namely, I cannot use arrow keys to choose from the list, nor can I continue typing out the full name of my desired label, **_To Do_**, with the only keyboard option I've found at this point being to hit <kbd>esc</kbd> to exit the autocomplete popup.

The above is mainly ergonomics, but there are a couple of behaviors I'd consider an actual bug. First, if I type `To` and then press <kbd>space</kbd>, the label _To_ is immediately applied and, if not already present, added to the list of labels. This behavior appears to be the same whether this is already a label or not, meaning labels with spaces cannot be added. Additionally, if I choose `Create new label` from the dropdown menu, the label _To_ is immediately applied.

The one "workaround" for this I've found (really more of what I'd consider a non-ideal, but expected behavior) is I can still choose the `Create: "To" label` from the list of labels below. This brings up a new popup window where I can fully type the label name and choose a color.

**Note:** I'm using macOS 14.3 and Omnivore v1.38.0

**Comment by jacksonh** [comment]
Thanks @mjs271 so if you type `To ` a label with that name is created? Can i ask if you are using English? I just tried and wasn't quite able to replicate.

**Comment by mjs271** [comment]
Yes to English. And creating a new label on <kbd> space </kbd> depends on whether or not there is an available autocompletion. I would guess there's a decent chance you have already created tags like "Tools" or something like that. The _new tag on space_ behavior could probably be recreated vi typing `zzxz` +  <kbd> space </kbd> (e.g., `zzxz `).

Although, it's certainly possible something goofy is going on in my app that's causing this behavior
