### ISSUE TITLE
建议优化知乎回答的保存区域

### ISSUE THREAD

**Issue by StrollStars** [omnivore-app/omnivore#3525]
知乎回答的页面比较复杂，其实针对每个回答网页，需要保存的内容只有一个问题和一个回答，以下举例：
保存链接：https://www.zhihu.com/question/643652513/answer/3391863276
需要保存的区域为下图红框部分，其他都不重要，而且也保存不完整：
![image](https://github.com/omnivore-app/omnivore/assets/10942225/24af3eb7-a7c3-43a3-8361-fd27570c2096)
@sywhb 希望能够优化一下。

**Comment by ishowman** [comment]
similar to https://github.com/omnivore-app/omnivore/issues/3510
