### ISSUE TITLE
Error unsubscribing

### ISSUE THREAD

**Issue by jasondunsmore** [omnivore-app/omnivore#3527]
Whenever I click on Unsubscribe on an article, I see the message "Error unsubscribing"

![2024-02-12_07-45](https://github.com/omnivore-app/omnivore/assets/53437/60e1f0cb-11df-4af4-9cfe-f845fba53453)

**Comment by jacksonh** [comment]
@jasondunsmore so when you try to unsubscribe from an RSS feed this happens? Or its trying to unsubscribe from an individual item?

**Comment by jasondunsmore** [comment]
@jacksonh It happens when I try to unsubscribe from an individual item. I can unsubscribe from feeds just fine.

**Comment by jacksonh** [comment]
NOTE: `unsubscribe` takes a subscription id, but the `search` API just returns the subscription name/feedURL, so when unsubscribing using the library menu item we will need to first query for the ID, and then unsub.
