### ISSUE TITLE
Allow to access the GraphQL Playground

### ISSUE THREAD

**Issue by noghartt** [omnivore-app/omnivore#3543]
Expose the access for GraphQL Playground, where the users that wants to integrate via API can easily have a feedback around requesting some queries.

Could be something like

```
/graphql/playground
```

**Comment by jacksonh** [comment]
Is this the one? https://github.com/graphql/graphql-playground

**Comment by noghartt** [comment]
> Is this the one? https://github.com/graphql/graphql-playground

yes, it is

i think that it's a good way to approach through the graphql schema, more interactively, further than reading the schema.gql
