### ISSUE TITLE
Feature request: session manager

### ISSUE THREAD

**Issue by PandaBrrr** [omnivore-app/omnivore#3558]
Omnivore needs a session manager. Simple request; I hope it's simple to implement.

I'm currently logged in on X devices, and to be honest, I'm not sure what X is. If I were to lose a device, a potential attacker would have access to all my saved articles, gain knowledge of my interest, and be able to read my comments on pieces I already read. 

While I'm not that interesting, I am paranoid, as I'm sure are many users of open source read it later services. 

The solution? A list of logged in devices and the ability to force log out a device remotely. 

Thank you!

**Comment by jacksonh** [comment]
Thanks for the idea, I think actually quite complex to implement but I'll think about how we could.

I suggest using full disk encryption and passcodes on your devices.

**Comment by PandaBrrr** [comment]
Thank you 🙏
