### ISSUE TITLE
Reddit pages can no longer be saved

### ISSUE THREAD

**Issue by mathisgauthey** [omnivore-app/omnivore#3559]
Hey there, when saving a page on reddit, it is titled `Blocked` with the following saved markdown :

```txt
whoa there, pardner!
Your request has been blocked due to a network policy.

Try logging in or creating an account here to get back to browsing.

If you're running a script or application, please register or sign in with your developer credentials here. Additionally make sure your User-Agent is not empty and is something unique and descriptive and try again. if you're supplying an alternate User-Agent string, try changing back to default as that can sometimes result in a block.

You can read Reddit's Terms of Service here.

if you think that we've incorrectly blocked you or you would like to discuss easier ways to get the data you want, please file a ticket here.

when contacting us, please include your ip address which is: **.**.***.** and reddit account
```

It'd been happening for a while now, any idea what's happening? Thanks in advance !

**Comment by jacksonh** [comment]
Hi, yes reddit is blocking third parties from accessing the site.

**Comment by stevenmathews** [comment]
Does it work with Pocket because they are owned by Mozilla and have access?

**Comment by jacksonh** [comment]
Can you provide a Reddit url that you saved to Pocket and you got a readable version? Everything I see just opens the original.

**Comment by stevenmathews** [comment]
https://www.reddit.com/r/nextfuckinglevel/s/nocf9WFRTq?utm_source=pocket_mylist

When I open in Pocket it says "Would you like to leave Firefox to view this content?". I can then view it in the Reddit app (Android). 

However if I try to save it in Omnivore I get the same message as the first comment in this issue.

**Comment by mastino21** [comment]
I confirm I am facing the same problem when trying to add subreddit RSS feed. I understand this is on reddit side, however those feeds work well with an RSS reader like Inoreader, so something should be also related to how Omnivore fetches reddit.

**Comment by jacksonh** [comment]
> I confirm I am facing the same problem when trying to add subreddit RSS feed. I understand this is on reddit side, however those feeds work well with an RSS reader like Inoreader, so something should be also related to how Omnivore fetches reddit.

Mind posting a feed thats working for you in inoreader?

**Comment by jacksonh** [comment]
> https://www.reddit.com/r/nextfuckinglevel/s/nocf9WFRTq?utm_source=pocket_mylist
> 
> When I open in Pocket it says "Would you like to leave Firefox to view this content?". I can then view it in the Reddit app (Android).
> 
> However if I try to save it in Omnivore I get the same message as the first comment in this issue.

yeah so just opening the original. I guess we could a popup for this, but you can just press the `Open original` button too.

**Comment by mastino21** [comment]
> > I confirm I am facing the same problem when trying to add subreddit RSS feed. I understand this is on reddit side, however those feeds work well with an RSS reader like Inoreader, so something should be also related to how Omnivore fetches reddit.
> 
> Mind posting a feed thats working for you in inoreader?

https://old.reddit.com/r/steamdeals/.rss
https://old.reddit.com/r/GameDeals/.rss

and a few others always with the same syntax.

I did some further testing and I can confirm that those feeds work also with other online RSS readers like Feedly and Newsblur.

**Comment by mathisgauthey** [comment]
As a workaround, I'm currently saving using `old.reddit` => This [extension](https://addons.mozilla.org/en-US/firefox/addon/old-reddit-redirect/) simplifies the process.

And yes, it does work with Omnivore.

**Comment by stevenmathews** [comment]
> > https://www.reddit.com/r/nextfuckinglevel/s/nocf9WFRTq?utm_source=pocket_mylist
> > When I open in Pocket it says "Would you like to leave Firefox to view this content?". I can then view it in the Reddit app (Android).
> > However if I try to save it in Omnivore I get the same message as the first comment in this issue.
> 
> yeah so just opening the original. I guess we could a popup for this, but you can just press the `Open original` button too.

A couple of other keys differences between the two at the moment is Pocket shows the title instead of 'Blocked' and if the saved post is text only it gets displayed in the Pocket app and can be highlighted.

**Comment by jacksonh** [comment]
> > > https://www.reddit.com/r/nextfuckinglevel/s/nocf9WFRTq?utm_source=pocket_mylist
> > > When I open in Pocket it says "Would you like to leave Firefox to view this content?". I can then view it in the Reddit app (Android).
> > > However if I try to save it in Omnivore I get the same message as the first comment in this issue.
> > 
> > 
> > yeah so just opening the original. I guess we could a popup for this, but you can just press the `Open original` button too.
> 
> A couple of other keys differences between the two at the moment is Pocket shows the title instead of 'Blocked' and if the saved post is text only it gets displayed in the Pocket app and can be highlighted.

Can you give a link of a text only one?

**Comment by awandepan** [comment]
> > I confirm I am facing the same problem when trying to add subreddit RSS feed. I understand this is on reddit side, however those feeds work well with an RSS reader like Inoreader, so something should be also related to how Omnivore fetches reddit.
> 
> Mind posting a feed thats working for you in inoreader?

https://github.com/Athou/commafeed/ this RSS Reader also can show up reddit feed properly, but i don't know how

**Comment by mastino21** [comment]
> As a workaround, I'm currently saving using `old.reddit` => This [extension](https://addons.mozilla.org/en-US/firefox/addon/old-reddit-redirect/) simplifies the process.
> 
> And yes, it does work with Omnivore.

yes old.reddit works well, but when just using www.reddit it does not. Not a big problem, though, I'll use old.reddit.

**Comment by jpabbuehl** [comment]
Old Reddit works fine, but unfortunately, it only fetches the OP post and not the comments. I'm using the web extension. Is anyone able to get the comments, too?
