### ISSUE TITLE
Select shortcut does not work properly in web version

### ISSUE THREAD

**Issue by javiavid** [omnivore-app/omnivore#3562]
Clear search bar and Select Article have the same shortcut, select article does not work properly.

I have found that pressing the X key twice quickly selects the item, but perhaps this could be simpler by changing the shortcut, and I have not found any documentation on having to do it this way.

<img width="356" alt="image" src="https://github.com/omnivore-app/omnivore/assets/7627504/94bd5858-8cb0-465f-b5fe-38d49dc552ef">

**Comment by jacksonh** [comment]
Thanks, i think this is a regression since some recent changes so the search bar is active now. you are right we probably need to change the key

**Comment by jacksonh** [comment]
Fix in here https://github.com/omnivore-app/omnivore/pull/3629
