### ISSUE TITLE
Issue with Omnivore Extension on Mullvad Browser

### ISSUE THREAD

**Issue by hanweikung** [omnivore-app/omnivore#3565]
I'm able to install the Omnivore extension on the [Mullvad browser](https://mullvad.net/en/browser). However, when trying to save a webpage, it keeps showing that I'm not logged into my Omnivore account, stopping me from saving the webpage. Any thoughts on why this might be happening?

![Screenshot from 2024-02-22 20-30-37](https://github.com/omnivore-app/omnivore/assets/643825/19635d0a-24e9-466d-8777-abe6b9427690)

**Comment by jacksonh** [comment]
Hi, likely the auth token being blocked. To work around this you can create an API key in Omnivore, then go to the extension options and set the API key for auth.

**Comment by hanweikung** [comment]
> Hi, likely the auth token being blocked. To work around this you can create an API key in Omnivore, then go to the extension options and set the API key for auth.

The solution worked. Thank you for your help.
