### ISSUE TITLE
Misleading message: 'Saved to Omnivore'

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [omnivore-app/omnivore#3569]
Hi,

On Android when using the Share feature then selecting Omnivore, there is a small "window" appearing from down the screen that says "**Saved** to Omnivore".

I noticed that when I'm in an area with low signal coverage this window can stay quite long and even error out.

Hence I deduce that it should instead say "**Saving** to Omnivore".

I think it would be worth changing that string as I have been confused several times already. Not knowing if my article was indeed saved or not. And opening Omnivore to check is not an option because in low coverage area I can imagine the window taking some time to appear in the app.

That's all cheers have a nice day :)

**Comment by jacksonh** [comment]
The issue here is it shouldn't be relying on network to save. It should be saving the URL locally first.
