### ISSUE TITLE
Unexpected server error when trying to query the GraphQL API using the example in the docs

### ISSUE THREAD

**Issue by hxu** [omnivore-app/omnivore#3574]
Hi, I'm trying to experiment with the API following the docs here: https://docs.omnivore.app/integrations/api.html, but when I run the example command, it gives an unexpected server error.

```
curl -X POST -d '{ "query": "query Viewer { me { id name } }" }' -H 'content-type: application/json' -H 'authorization: $OMNI_KEY' https://api-prod.omnivore.app/api/graphql
{"errors":[{"message":"Unexpected server error"}]}
```

I tried fiddling with the request, all to no avail:

- Adding `Bearer` in front of the token
- Adjusting the query strings to trying `User`, `Hello`, or other variations in the schema file (I am not an expert in GraphQL, so I could be reading it wrong)

Can you help me check if this is something wrong with my query or if it's genuinely something wrong with the server?

**Comment by jacksonh** [comment]
hey @hxu that looks about right. Are you using an environment variable for `OMNI_KEY` or is that just for the bug report? Could it be that your shell isn't substituting in single ticks, this works for me:

```
omnivore-infra$ OMNI_KEY="....." curl -X POST -d '{ "query": "query Viewer { me { id } }" }' -H "authorization: $OMNI_KEY" -H "content-type: application/json" https://api-prod.omnivore.app/api/graphql
```

**Comment by jacksonh** [comment]
Oh sorry I also noticed that our auth library expects the uppercase `Authorization`

**Comment by hxu** [comment]
Ah, good catch on the quotes -- it was that the key was not being replaced. My mistake!
