### ISSUE TITLE
Bug report: my article cannot be found with type:article but only via type:

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [omnivore-app/omnivore#3582]
Hi,

I was looking for an article I read for a while and couldn't find it in my logseq graph. I finally understood that my custom search for omnivore in logseq was `in:archive type:article` and that indeed I couldn't find the article on omnivore using those.

**The only way I found to find this document via search was by using `in:archive type:` so I take it as meaning that my article is not of article/pdf/file/highlights so it's a bug.**

In the end for my logseq graph I'll go with `in:archive -type:highlights`

**Comment by jacksonh** [comment]
the `type:` in the above shouldn't have any effect there. Not every non PDF item will get set as `article` as that information comes from open graph metadata. Does `in:archive` not return your item?

**Comment by thiswillbeyourgithub** [comment]
Hi, the article is still the same as for the other issue : https://anr.fr/fr/france-2030/programmes-et-equipements-prioritaires-de-recherche-pepr/propsy-programme-projet-en-psychiatrie-de-precision/

My issue is that the following work:
`propsy in:archive`
`propsy in:archive type:`


while the following don't work:
`propsy in:archive type`
`propsy in:archive type:article`
`propsy in:archive type:file`
`propsy in:archive type:pdf`
`propsy in:archive type:highlights`


So what's the type of my document?


PS: okay I now see that `propsy in:archive whatever:` works too so that means that unset filters are ignored (btw that shouldn't happen no? if `whatever:` is not a valid filter but also doesn't appear in a document then no documents should be returned I think)

**Comment by jacksonh** [comment]
Unless you are explicitly looking for PDFs I wouldn't worry about type at all
