### ISSUE TITLE
Bug report for search: case sensitivity + in:archive + full text

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [omnivore-app/omnivore#3583]
I was reading [the following article](https://anr.fr/fr/france-2030/programmes-et-equipements-prioritaires-de-recherche-pepr/propsy-programme-projet-en-psychiatrie-de-precision/) and noticed that 

1. searching for `PROPSY` worked but `propsy` did not so apparently the search is case sensitive by default.
2. when the article was archived it seems the search only worked with `in:all` or `in:archive` so the search does not go through the archive by default contrary to the doc
3. Searching `PROPSY Précision` works, but `PROPSY Précisio` does not, so it does not appear to be a full text search to me

Quote [from the doc](https://docs.omnivore.app/using/search.html#filtering-by-type) : 
> Omnivore will perform full text search across library items' content, title, description, and site by default. 

Thanks!

**Comment by thiswillbeyourgithub** [comment]
Hi @jacksonh  thanks for the quick reply :)

1. me neither, I don't know why but now I seem to find it using `propsy in:all`, false alarm sorry, I'll get back to you if I figure out what I did.
2. In [this page](https://docs.omnivore.app/using/search.html) in this line : `Omnivore will perform full text search across library items' content, title, description, and site by default.`. Granted further down there is `in:inbox (the default selected option) Show unarchived items` but to me the first line is misleading. If it searches across the whole library I expect the different filters to apply only if I type them, not to have any filter by default. In my opinion it would be a good idea to automatically add "in:inbox" to the search so that the user can visually see the filter that applies. Or to use in:all by default (that seems best to me).
3. Okay I didn't know you used a stemmer. And the wording `will peform full text search` to me indicate no stemming, not just that you're searching through text+metadata. So I think it might be a good idea to make it a bit more explicit in the docs too.

**Comment by jacksonh** [comment]
Docs updated.
