### ISSUE TITLE
unable to resolve redirect/tracking URLs

### ISSUE THREAD

**Issue by klutchell** [omnivore-app/omnivore#3588]
I'm struggling to determine when this was introduced, but I think it was around the 1.4x release? It would also help to know if anyone else is experiencing this or if it's just my device.

<img src="https://github.com/omnivore-app/omnivore/assets/20458272/8f41d7d6-0c02-4170-88f1-080cdec536bf" width="50%" height="50%">

Clicking links in existing saved articles presents this popup to directly save the URL without opening it. Often these URLs are tracking redirects with tokens parameters, etc, but they always resolve to the final content eventually.

For the past few weeks, using this method to save URLs leaves them in a state of "Your link is being saved..." with the title of the tracking URL not the content. So it seems at some point the resolver stopped following redirects?

<img src="https://github.com/omnivore-app/omnivore/assets/20458272/2868372f-ccda-4d5a-bdfb-39c196ff64d3" width="50%" height="50%">

Opening the content in a browser and saving it after the redirects are followed works fine and the articles are parsed. I swear this used to work really well and I've tried logging out of my app and clearing the device cache.

Is there something else I can be doing to determine the root cause? Am I correct that saving pages with redirects used to work?

**Comment by klutchell** [comment]
UPDATE: I just tried to save via the API in Firefox on MacOS and encountered a different result.

> https://omnivore.app/api/save?url=https://click.convertkit-mail.com/0vuv7k42d0i9hoe50v6flhwew8k55/6qheh8h7n4kpd0ao/aHR0cHM6Ly9sb25nZm9ybS5hc21hcnRiZWFyLmNvbS9zdGFydHVwLWJlYXRzLWluY3VtYmVudD91dG1fc291cmNlPWNvbnZlcnRraXQmdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249YXNtYXJ0YmVhcl9uZXdzbGV0dGVy

After a few seconds the article is created with the error `Something went wrong while processing the link, please try again in a moment`

When saving a link with redirects via the context menu in Firefox the article is created with the content `We were unable to parse this page.`.

But if I open the page directly and save from the extension or bookmarklet it works great.

So it seems this is not the iOS app but something with how article saving is processed in the background?

**Comment by jacksonh** [comment]
Thanks, i actually suspect it could be something else. CloudFlare blocking those requests on the backend. I'll look into it more closely

**Comment by jacksonh** [comment]
I think my first guess was wrong. Doesn't look like this one is using CloudFlare at all.

**Comment by klutchell** [comment]
Here are some additional example URLs that follow the same pattern:
- https://substack.com/redirect/cf8ae3fc-957e-4b8b-84bd-4844547fbde6?j=eyJ1Ijoid2NxcSJ9.r9_sOyroVG3NWJm0uBFtxmDw0-hjJpWISuPD6bQEI7U
- https://link.theverge.com/click/34453381.7603/aHR0cHM6Ly9zaWduYWwub3JnL2Jsb2cvcGhvbmUtbnVtYmVyLXByaXZhY3ktdXNlcm5hbWVzLz91ZWlkPTBkYjE3MTUxMWE5MWJhNWRlN2E4N2Q1OTM3N2U1ZTRh/63c6b01a98b5ba770a0086a9Bea652f3b

**Comment by jacksonh** [comment]
hey @klutchell this should be resolved now. Do you mind verifying on your side?

**Comment by klutchell** [comment]
Yes, those types of redirect URLs started working last night! Was it a server side change?

**Comment by jacksonh** [comment]
> Yes, those types of redirect URLs started working last night! Was it a server side change?

Yeah an issue with handling upserts on URLs that don't match the original saved URL. I'll close this one now.
