### ISSUE TITLE
Pocket import never ends / frozen?

### ISSUE THREAD

**Issue by apotenza92** [omnivore-app/omnivore#3590]
Hi, I started an import from Pocket to Omnivore of 1926 URLs and within the first few minutes it quickly imported 1369 items. 

Initial email: "We have started processing 1926 URLs. 0 URLs are invalid."

Since then (about 9 hours ago), no more items have been imported. Is this expected behaviour and the remainder of the items will import eventually? Is an email sent once all the items are imported?

Thanks.

**Comment by jacksonh** [comment]
Hi, can I ask how you got the count that was imported?

**Comment by apotenza92** [comment]
Was going to write my own script to query the API but came across [this](https://github.com/Cito/omnivore-export) that already does it. Just used the 'summary' script which outputs the following:

```
Summarizing...

* Inbox: 188
* Archive: 1181

* Page types:
Article: 430 | File   :  19 | Image  :   3 | Profile:   2 | Unknown: 627
Video  : 180 | Website: 108
```

**Comment by jacksonh** [comment]
Do you mind also going to this page and checking the count there? https://omnivore.app/tools/bulk 

Just don't click anything!

**Comment by jacksonh** [comment]
Is there a chance a bunch of these are old URLs that might not be valid anymore. They will get retried a few times and then the final email will be sent, that's likely what happened, but I'm not sure why a final report hasn't come through.

**Comment by apotenza92** [comment]
Yeah that's very likely the reason. Some of those links go back almost 10 years. Good to know the reason though thanks for getting back to me so fast. I'll let you know if the final email comes through eventually.

**Comment by jacksonh** [comment]
Yeah its strange that the email didn't come, I wonder if the queue is stuck still trying to resolve some dead domains

**Comment by apotenza92** [comment]
I never received the final import message. I'm worried it's messing with my Obsidian import now too. Obsidian will only sync about 60 articles then fails... Not sure what's happening

**Comment by jacksonh** [comment]
I don't think the two should interfere, other than the 1300ish items being a really large import for the plugin to run. Perhaps getting rate limited. 

Can you open the developer console on Obsidian and look for errors?

**Comment by apotenza92** [comment]
![Screenshot 2024-02-28 at 2 34 02 pm](https://github.com/omnivore-app/omnivore/assets/53612685/f97bad36-8eab-4450-8301-d32c63d667c0)

Ah no worries. This is all I'm seeing.

**Comment by jacksonh** [comment]
huh 404 is quite strange. @sywhb any ideas why that would occur? If some sync I assume you haven't changed the API url

**Comment by apotenza92** [comment]
I deleted the obsidian plugin, made a new API key and reinstalled and all seems to be working now. All good. Thanks for all your help!
