### ISSUE TITLE
Launch Native YouTube App from Inbox List

### ISSUE THREAD

**Issue by michaelwoodruff** [omnivore-app/omnivore#3604]
Love this app. I'd like to see some optimizations for video. Once I add a video from YouTube and I see in my inbox. I'd like to launch the native YouTube on my phone. Currently it takes too many clicks to get there to make it worth saving videos to my inbox. Thanks.

**Comment by jacksonh** [comment]
We are working on our own youtube player, so you can have access to highlighting and note taking features for youtube videos, in terms of opening original, I don't know if we have many options to make that quicker, UI-wise how would you want to open original vs open in omnivore?

**Comment by michaelwoodruff** [comment]
Have it open in native app rather than web browser, which eventually lets you "Open in App", but its too many steps. Not sure technically how this is done, but seem several reader apps do this.

The "Play" app does this and has a lot of good features, but its not web-based and the UI has some issues.

https://marcosatanaka.com/
https://apps.apple.com/us/app/play-save-videos-watch-later/id1596506190
https://www.macstories.net/reviews/play-a-fantastic-utility-for-saving-and-organizing-youtube-videos-for-later/

**Comment by jacksonh** [comment]
Ah I see so you mean when you click "Open original" from the reader
