### ISSUE TITLE
FR: more informative error when parsing failed

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [omnivore-app/omnivore#3609]
I think that instead of seeing "We were unable to parse this page." it would be nice to add a reason afterwards. That might help understanding what went wrong

**Comment by Sirself** [comment]
> I think that instead of seeing "We were unable to parse this page." it would be nice to add a reason afterwards. That might help understanding what went wrong

I've encountered the same issue as well. Have you found out the cause? Is there something wrong with the configuration?
