### ISSUE TITLE
iOS "Share to Omnivore" fails when offline, but still shows success UI

### ISSUE THREAD

**Issue by nickpascucci** [omnivore-app/omnivore#3611]
## Context
Omnivore iOS Version 1.44.0
iOS 16.6.1

## Expected Behavior
When trying to save an article by sharing a pre-loaded web page from Safari to the iOS Omnivore app while offline, one of two things should happen:

1. The save may fail because the Omnivore server is unavailable, and this should be reflected in the UI.
2. The save may succeed by capturing the cached content locally into the Omnivore app. (I don't think this is technically possible given the constraints of iOS sharing at the moment.)

## Actual Behavior
Saving the article fails (as expected) but the UI shows a success message.

## Reproduction Steps
1. Load a web page in Safari while connected to the internet.
2. Enable airplane mode.
3. Share the pre-loaded web page to Omnivore via the iOS sharing dialog.
4. Note that the UI shows "Saved to Omnivore" instead of an error message.

## Screenshots

![IMG_0B8A7E5898ED-1](https://github.com/omnivore-app/omnivore/assets/636796/4de677ef-0150-4bb5-98c8-e1343e6f143d)

Note that:
- The device is in airplane mode
- The UI shows a "Saved to Omnivore" confirmation

**Comment by jacksonh** [comment]
It should be saved locally and will be synced when you are back online

**Comment by nickpascucci** [comment]
Ah, cool! Just tested it and yes, indeed it does. 

Thinking about the feedback here, maybe it would be helpful to provide a "pending download" placeholder in the app to show that the request to get the article was received but that it can't be completed until there's internet access. What do you think?
