### ISSUE TITLE
No feeds found for URL

### ISSUE THREAD

**Issue by unresolved-contradictions** [omnivore-app/omnivore#3612]
When trying to add a specific RSS feed, the iOS app returns “No feeds found for URL”.

URLs used:
- https://www.opendemocracy.net/en/feed
- https://www.opendemocracy.net/feed

Both URLs return RSS feeds outside of Omnivore and I have successfully added the feed to other RSS apps.

**Comment by jacksonh** [comment]
I suspect what is happening is this new CloudFlare blocking issue a lot of feeds have hit. Here's what happens when i fetch the first feed:

```
$ curl -I https://www.opendemocracy.net/en/feed/ 
HTTP/2 403 
date: Mon, 04 Mar 2024 01:07:23 GMT
content-type: text/html; charset=UTF-8
x-frame-options: SAMEORIGIN
referrer-policy: same-origin
cache-control: max-age=15
expires: Mon, 04 Mar 2024 01:07:38 GMT
server: cloudflare
cf-ray: 85edf815ae624ca1-SIN
alt-svc: h3=":443"; ma=86400

```

**Comment by benjaminwelch** [comment]
I'm running into the same issue. I add a feed and nothing shows up but I can add them to other RSS readers. For example:
- https://www.raptitude.com/feed/

I would also like to add the entire feed, not just one article. I can't figure out why some feeds get everything and why some, just the most recent post. Might be related to this issue.

Very excited about Omnivore.
