### ISSUE TITLE
Implement scanForFeeds on Web

### ISSUE THREAD

**Issue by noghartt** [omnivore-app/omnivore#3613]
A specific improvement on the workflow to handle import of new RSS feeds would be the ability to find the metatag link related to `application/rss+xml` that are being exported by the site.

So, instead of acessing directly the feed URL that we need import, we could add the link of the site that exports this metatag that everything should work as expected.

This is a good UX improvement for import specific kind of RSS feed, like YouTube channels.

**Comment by jacksonh** [comment]
Yeah we do have this on iOS, i need to add it on web or android. Its some UI work as many pages have multiple feeds.
