### ISSUE TITLE
Ghost article that can only be seen on mobile app and sync through API, but not on web

### ISSUE THREAD

**Issue by KenMercusLai** [omnivore-app/omnivore#3621]
I recently found there's an issue of syncing articles from omnivore to my obsidian:  
![image](https://github.com/omnivore-app/omnivore/assets/5419014/180d2a26-64e3-4759-9814-260435fa0f79)

Since Chinese searching wasn't well supported by Omnivore, so I decided to search the phrase: "Jiang on X"

Interestingly, this article seemed be visible only on iOS app (as showing below, clicking lead to inf loading) or through the API (which caused the issue) , 
![image](https://github.com/omnivore-app/omnivore/assets/5419014/df3c32a6-6677-463c-8dc8-bf98edcf075b)
![image](https://github.com/omnivore-app/omnivore/assets/5419014/2235a69c-0fd2-43ac-9a4e-f5427764da83)

but not on web
![web search result](https://github.com/omnivore-app/omnivore/assets/5419014/d8d6aabe-7cc8-48cb-9ffe-f1450b1edc70)

**Comment by jacksonh** [comment]
Can you try querying `in:all Jiang on X`
