### ISSUE TITLE
Omnivore ducks instead of pauses/resumes when interrupted by iOS notifications

### ISSUE THREAD

**Issue by justinsteven** [omnivore-app/omnivore#3627]
Take Pocket Casts as an example. While listening using headphones, when Siri interrupts playback to read a notification, the playback is paused. When the notification is done being read, the playback resumes.

Omnivore, while reading an article (with the screen locked if it makes a difference), does not pause upon interruption. This is odd to me - I thought it would be handled by https://github.com/omnivore-app/omnivore/blob/74129ffbd7bb04f8f518855e3c02445267f8db64/apple/OmnivoreKit/Sources/Services/AudioSession/AudioController.swift#L933 - but I'm by no means familiar with Swift or iOS development, so perhaps there's a bug. Instead, the audio is ducked, the notification plays atop the Omnivore playback, and then the audio is returned to full volume.

For me, this happens when my iPhone is locked and I'm listening to Omnivore using AirPods.

**Comment by koogunmo** [comment]
I'm also seeing this issue. It is quite annoying.
