### ISSUE TITLE
Auto capitalize note typing in android

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [omnivore-app/omnivore#3635]
Hi,

I noticed that when typing a note on android on a highlight, the typing field does not automatically autocapitalize and I think it should?

Have a nice day

**Comment by Smeagol2069** [comment]
I am able to reproduce this issue, imo this could be considered a bug rather than a feature request. 

Omnivore Android, 0.194.1

I'm using Gboard for my keyboard

**Comment by jacksonh** [comment]
https://github.com/omnivore-app/omnivore/pull/3776

**Comment by Smeagol2069** [comment]
I can no longer reproduce this after updating to 0.200.5

**Comment by jacksonh** [comment]
Thank you for verifying!
