### ISSUE TITLE
FR: confirm on swipe on android

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [omnivore-app/omnivore#3639]
Hi,

I live in the constant fear that when scrolling on my android tablet I'll inadvertedly swipe and delete an article.

Possible solutions:
* confirm on deletion (but that could be a pain for subscriptions for example, if you want to delete a buch, but IMHO we should rely on batch selection then delete instead of swiping)
* instead of deleting : send to a trash bin that is emptied every 48h, that would avoid cardiac arrests
* disable swiping
* reduce the sensitivity of the swipe

**Comment by jacksonh** [comment]
There is a trash bin that has items for 14 days. There isn't a great way to recover right now though

**Comment by stefanosansone** [comment]
we may consider a toggle in the settings for the swipe to delete feature
