### ISSUE TITLE
Full text search for Chinese is wrong.

### ISSUE THREAD

**Issue by moulai** [omnivore-app/omnivore#3640]
Full text search for Chinese is wrong. The article cannot be found or the search result is incomplete.

For example, an article titled "TimeGPT：第一个时间序列的大模型" is in the archived category.
![image](https://github.com/omnivore-app/omnivore/assets/8275836/a04b5c9a-dc0e-4301-b89d-e564c96991bc)

When searching keyword "时间序列", which appears directly in the title, no results were found.
![image](https://github.com/omnivore-app/omnivore/assets/8275836/76566b9f-dd14-44ef-816d-6383e60d36c8)

When searching keyword "模型", which also appears directly in the title, an article was found that contained "model" in the text. However, not all articles containing “model” were retrieved.
![image](https://github.com/omnivore-app/omnivore/assets/8275836/9c77d129-b524-4d19-bd55-403c95a8f2f1)

**Comment by jacksonh** [comment]
Will link this with another issue and close
