### ISSUE TITLE
mark as read automatically on scroll

### ISSUE THREAD

**Issue by xolvum** [omnivore-app/omnivore#3647]
is there a way to mark articles as read automatically when you scroll by them?

this is great whne having a busy rss feed and especially when browsing on phone.

**Comment by jacksonh** [comment]
There isn't right now. We are thinking of adding the concept of "seen". I will say Omnivore is more designed for less busy feeds where you intend on reading a decent amount of the items. We are trying to improve UX for busier feeds though.

**Comment by xolvum** [comment]
tha
