### ISSUE TITLE
After unsubscribing from a subscription on web, can't unscribe from more until page refresh

### ISSUE THREAD

**Issue by WillTwait** [omnivore-app/omnivore#3648]
repro: 
- unsub from a subscription in `/settings/subscriptions`
- can no longer click `...` button to unsub from more
- refresh page, and buttons are now clickable

**Comment by jacksonh** [comment]
I suspect this is related to a bug we've seen in our modals library, thanks for reporting.

**Comment by jacksonh** [comment]
Deploying a fix for this one now.
