### ISSUE TITLE
Chrome: Twitter has stopped working

### ISSUE THREAD

**Issue by dairefagan** [omnivore-app/omnivore#3664]
Twitter using the Chrome extension was working great but I noticed in recently it has stopped. Can this please be fixed?

Ubuntu 22.04, Brave v 1.63.169, Omnivore 2.10.0.

![image](https://github.com/omnivore-app/omnivore/assets/12515718/69362d59-2201-4e83-bb82-3bdad9159767)

Original: https://twitter.com/fasc1nate/status/1767592186173165915

**Comment by jacksonh** [comment]
Hey, we don't support twitter as they block third party access now.
