### ISSUE TITLE
FR: display number of articles in each compartment (inbox, archive, etc)

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [omnivore-app/omnivore#3681]
I'm talking about the left panel in the web app (at least):
![image](https://github.com/omnivore-app/omnivore/assets/26625900/0d7627f3-3e21-4c1c-99f5-a6f239c76329)

I think it would be interesting to know how many articles I have in each section like `Inbox (83)`

**Comment by Cito** [comment]
see also #2749
