### ISSUE TITLE
Feature Request: TTS autodetect/switch playback language based on HTML locale

### ISSUE THREAD

**Issue by b-mq** [omnivore-app/omnivore#3684]
Hi there, first of all, thank you very much for this great app! 
I read a lot of blogs in different languages (mostly English and German) and I also like to use the TTS function on iOS (by the way, the quality of the languages is fantastic!). 
Depending on the saved bookmark, I have to change the language manually each time so that it is played back correctly. 

**Idea**
Couldn't the homepage language (locale) be extracted from the HTML metadata and taken into account when playing through TTS, so that the playback automatically adapts to the playback language?

Thank You.

**Comment by jacksonh** [comment]
Hi we do attempt to do this, but it depends on the page. Can you give an example where it did not work?

**Comment by b-mq** [comment]
Of course.
For example, I have saved an article from [Heise](https://www.heise.de/hintergrund/Die-xz-Hintertuer-das-verborgene-Oster-Drama-der-IT-9673038.html) and one from [TheVerge](https://www.theverge.com/24100979/altstore-europe-app-marketplace-price-games).
If I play the German article from [Heise](https://www.heise.de/hintergrund/Die-xz-Hintertuer-das-verborgene-Oster-Drama-der-IT-9673038.html) and select a German language, it is played correctly in German with my selected voice.
If I now play an [English article](https://www.theverge.com/24100979/altstore-europe-app-marketplace-price-games), the German voice is read out in English. Here it would be nice if my pre-selected English language and speaker were automatically used for the playback.

Example Video: https://youtube.com/shorts/5-dZmcIZfl0
