### ISSUE TITLE
Bloomberg newsletter does not show up in library

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#37]
Reported by a user. I signed up on demo to validate.

**Comment by jacksonh** [comment]
@sywhb i think this one is working now, right?

**Comment by sywhb** [comment]
Yes. It works well on demo and I am waiting for tmr's newsletter to show up in my prod app

**Comment by joeshaw** [comment]
FYI, today's newsletter did not show up in my library and was delivered by email instead.

**Comment by jacksonh** [comment]
Same issue for me today.

**Comment by jacksonh** [comment]
Looks like this is the sender we missed `From: Matt Levine <noreply@mail.bloombergview.com>\n' +`

**Comment by sywhb** [comment]
> Looks like this is the sender we missed `From: Matt Levine <noreply@mail.bloombergview.com>\n' +`

Yeah. This email address is new. I need to update the mailer's regex to include such
