### ISSUE TITLE
increasing limit of words/characters imported

### ISSUE THREAD

**Issue by jpabbuehl** [omnivore-app/omnivore#3704]
Hello,

I'd like to know if there is any possibility of increasing the limit for words/characters imported.
When clicking on the save article Chrome extension, I observed that only the top part of the blog is imported.
Word count has a hard limit of ~35'000 words / 250'000 for characters.

Thanks
JP

**Comment by jacksonh** [comment]
Do you have an example page where you are seeing this?

**Comment by jpabbuehl** [comment]
yes.
