### ISSUE TITLE
FR: Request full text search to support multiple lanuage like Chinese, Japanese, etc.

### ISSUE THREAD

**Issue by myzWILLmake** [omnivore-app/omnivore#3706]
I can see it create full text index inside pgsql at here:

https://github.com/omnivore-app/omnivore/blob/14fc7316694a48272cc6dc799ef631eb92b8d680/packages/db/migrations/0031.do.add_tsv_column_to_articles.sql#L9-L13

Is it possible to add more languages?

**Comment by jacksonh** [comment]
Linking this issue https://github.com/omnivore-app/omnivore/issues/3640

**Comment by takan1** [comment]
@jacksonh I tested it now and it still doesn't pick up Japanese words that are in title of the article.
