### ISSUE TITLE
FR: Use browser on iOS when selecting "Open" for a link

### ISSUE THREAD

**Issue by daenney** [omnivore-app/omnivore#3713]
When clicking on a link while reading in Omnivore, the menu that opens provides 3 options:
* Open
* Copy Link
* Save in Omnivore

Unfortunately, the "Open" option cannot be configured to do anything other than use an embedded browser view. It would be much nicer if this could use the default browser configured on iOS, or be user customisable. For example, I would want links to open in Firefox Focus instead (which happens to also be my default browser).

Alternatively, if clicking a link would open up the Share sheet instead, then the user could select an application of their choice to view that link in, and not be limited to "Open", "Copy Link" and "Save in Omnivore".

**Comment by jacksonh** [comment]
Thanks, I don't think the share sheet would work as the `Save in Omnivore` feature was one of our more requested ones. I think just straight open in browser might make the most sense, or at least have a toggle like "Open in browser", "Open in inapp browser" in the settings.

Tooot does this nicely

![Screenshot 2024-03-22 at 21 15 16](https://github.com/omnivore-app/omnivore/assets/75189/a5195a23-6345-44cd-8e41-381fd25d7791)

**Comment by daenney** [comment]
Ah yeah, that makes sense. I'd be happy with a preference for the browser, or even just the additional option as shown in that screenshot.

**Comment by jacksonh** [comment]
https://github.com/omnivore-app/omnivore/pull/3733

**Comment by daenney** [comment]
Just got the update with this feature yesterday. Works as promised. Thank you so much!
