### ISSUE TITLE
Copy link on iOS doesn't copy the expected link

### ISSUE THREAD

**Issue by daenney** [omnivore-app/omnivore#3715]
When reading in Omnivore on iOS and clicking a link, a menu opens with the options to "open", "copy link" and "save to omnivore". Due to #3713, I usually want to go for "copy link" so I can open it in a different browser.

However, when choosing "copy link", the link that's being displayed isn't the link that gets copied. Instead, it seems to copy the link to the full article. Sometimes that results in a link to omnivore.app/<some uuid> if it's not otherwise available which results in a 404 unless you're logged in to Omnivore in that browser.

In the screenshot below, I've tapped on the underlined "USBGuard" in the article, which brings up the menu. It shows the correct link, and then I chose "copy link". However, the result of pasting that link anywhere else (I chose the Notes app for the screenshot) is unexpected.

![IMG_4778](https://github.com/omnivore-app/omnivore/assets/569574/faac7dca-1a24-4429-aeae-39daf07883a1)
![IMG_4779](https://github.com/omnivore-app/omnivore/assets/569574/035a9035-3855-4198-90ac-16b8eb3a1d82)

**Comment by daenney** [comment]
One other thing, the "open" action does work correctly. It opens the link displayed in the menu, not the original article.

**Comment by jacksonh** [comment]
Thanks, fixed that one in here too https://github.com/omnivore-app/omnivore/pull/3733

**Comment by daenney** [comment]
Just tested it out in the new app version. It works as expected now! :rocket:
