### ISSUE TITLE
Bug: overlapping highlight get merged

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [omnivore-app/omnivore#3750]
First let's create a highlight
![image](https://github.com/omnivore-app/omnivore/assets/26625900/a91598bf-f625-4912-9e2e-639293677e26)

Then another highlight from the bottom up that overlaps slightly with above (This time I chose the color red)
![image](https://github.com/omnivore-app/omnivore/assets/26625900/e863828f-87b5-4100-a914-54de284b8101)

As you can see they merged in the notebook panel
![image](https://github.com/omnivore-app/omnivore/assets/26625900/c57c67aa-8dc1-4e87-bd02-48bb627fd808)

Also, the merged highlight appears red on the text overlay but yellow in the notebook panel
![image](https://github.com/omnivore-app/omnivore/assets/26625900/799ea066-cb86-4431-aa14-73af1ec3fe73)

Reloading the page makes it appear yellow again
![image](https://github.com/omnivore-app/omnivore/assets/26625900/ad98366d-618f-45e7-9bf9-2e296715b16d)59)

**Comment by jacksonh** [comment]
Yes you can not have overlapping highlights, they will be automatically merged.

**Comment by thiswillbeyourgithub** [comment]
Oh okay. To me this is not expected. I see myself benefiting from having highlights from a bird's eye view in one highlight as well as a highlight inside on a specific sentence too.

**Comment by thiswillbeyourgithub** [comment]
Are you open to discussing the merging of highlights? I don't recall seeing this in any other reader app.
