### ISSUE TITLE
Syntax highlighint in dark mode is unreadable on iOS

### ISSUE THREAD

**Issue by daenney** [omnivore-app/omnivore#3770]
When a post has a code block, Omnivore provides some syntax highlighting. This highlighting works fine in light mode, but is illegible when the device switches to dark mode (at night).

The black text gets inverted to white, but the background on the code block remains light grey. This contrast is far too low to be readable.

This is [the article in question](https://blog.kuzudb.com/post/in-praise-of-rdf/) if you want to test it yourself.

### light mode

![IMG_4801](https://github.com/omnivore-app/omnivore/assets/569574/8ff1d53c-44e2-47f3-bf3b-a04c4e33a875)

### dark mode

![IMG_4802](https://github.com/omnivore-app/omnivore/assets/569574/cddafa97-58c8-4ca7-9633-b3e88d6ca62d)

**Comment by jacksonh** [comment]
Hmm in this case its a bit hard to deal with because its embedding the style elements.
