### ISSUE TITLE
Transparent PNG is rendered with black background on iOS

### ISSUE THREAD

**Issue by daenney** [omnivore-app/omnivore#3771]
When an article has a PNG image with a transparent background and you tap on it to be able to magnify and pan around, the image gets rendered with a black background. This renders multiple classes of images unreadable, especially diagrams since they often use black for box outlines, arrows and text.

I think at least in light mode, it would make most sense to use a white background. Not sure what to do with dark mode, maybe a grey that still has a high enough contrast with pure black?

Image is [from this article](https://blog.kuzudb.com/post/in-praise-of-rdf/)

### inline

![IMG_4803](https://github.com/omnivore-app/omnivore/assets/569574/83f1408e-22eb-450a-aa53-28132823c156)

### image viewer

![IMG_4804](https://github.com/omnivore-app/omnivore/assets/569574/1aa81be8-3651-4586-a971-f6a61e7122aa)

**Comment by jacksonh** [comment]
Switched this one to use the theme background in a branch I'm working on. Probably the best solution so the user has some control.
