### ISSUE TITLE
No confirmation emails

### ISSUE THREAD

**Issue by Marcel7Be4** [omnivore-app/omnivore#3774]
When signing up for a Newsletter, sometimes I'm told to confirm my subscription through an email. However, with Omnivore, these emails never seem to arrive. Not into my Omnivore inbox, and not on my normal email as a redirect. Are there any solutions that don't require me to delete my current Omnivore email?

**Comment by jacksonh** [comment]
Hi, yes we are having some issue with our email provider. Can you see the confirmation email on this page?

https://omnivore.app/settings/emails/recent

**Comment by jacksonh** [comment]
I'll close this one now as the issues have been resolved
