### ISSUE TITLE
Pocket integration can't be disconnected

### ISSUE THREAD

**Issue by www-wagner** [omnivore-app/omnivore#3788]
I've made the connection to Pocket using _Integration_ option in Omnivore.

All my stuff has been imported correctly to Omnivore but I realized so many broken links (old stuff from Pocket). Then I clean up the broken stuff and reorganized my tags (labels) in Pocket and tried to restart the process to import all the stuff again. I've deleted all the previous items imported before from Omnivore.

But I can't disconnect my Pocket account. When I click _Disconnect_ button, nothing happens! In the Pocket app settings, I've revoked the Omnivore access but nothing have changed in Omnivore app.

Is this a bug?

**Comment by sotakal** [comment]
Yeah, it's strange in general that you "integrate" Pocket for the migration. Makes me wonder whether there is a regular sync set up, and I can keep saving articles to Pocket and they are synced to Omnivore automatically. Probably not, but it surely is strange user experience the way it is.

**Comment by chs33** [comment]
Encounter the same issue here. The disconnect button just greyed out. and nothing happens when clicked the greyed button

**Comment by tnaseem** [comment]
I have a similar problem, but in my case, it hasn't imported anything in over a couple of days. Clicking on the Disconnect button does nothing.

I've even gone into Pocket and revoked access there, but it's still the same.

**Comment by jacksonh** [comment]
Importing is quite expensive for us and we'd prefer if people don't do it multiple times. Will update the description to say its a one time import. 

> I have a similar problem, but in my case, it hasn't imported anything in over a couple of days. Clicking on the Disconnect button does nothing.
> 
> I've even gone into Pocket and revoked access there, but it's still the same.

Can you send a message using feedback? Pocket imports are limited to one time as they are quite expensive for us. I'll update the description.

**Comment by tnaseem** [comment]
> Can you send a message using feedback? Pocket imports are limited to one time as they are quite expensive for us. I'll update the description.

Many thanks for explaining this!

For me, it's no longer a huge issue. I've already started manually moving over the links from Pocket (There aren't that many after I purged a lot!). I was only interested in the import function as I wrongly assumed it would keep both in sync.

Thanks for the explanation and I totally understand.

**Comment by mcarpe** [comment]
> I have a similar problem, but in my case, it hasn't imported anything in over a couple of days. Clicking on the Disconnect button does nothing.
> 
> I've even gone into Pocket and revoked access there, but it's still the same.

Same problem here. Nothing has happened and it seems like I can't disconnect...
