### ISSUE TITLE
Highlight order in the notebook

### ISSUE THREAD

**Issue by sywhb** [omnivore-app/omnivore#3789]
【圆圈高亮标注内容】 应该要在 【方框高亮标注内容】 之后在符合行文逻辑

![image](https://github.com/omnivore-app/omnivore/assets/12963965/ec10e42f-63ac-475e-8fa1-6835bc1a8481)

**Comment by kuosandys** [comment]
I'd like to help solve this issue - could I be assigned to this if no one is currently working on it?

**Comment by jacksonh** [comment]
@kuosandys thanks!

**Comment by aassoiants** [comment]
I still find this to be an issue
