### ISSUE TITLE
GIF are not supported

### ISSUE THREAD

**Issue by lgssml** [omnivore-app/omnivore#3806]
cloud you get it supports the gif.

**Comment by jacksonh** [comment]
Hi GIFs should be supported but some may be blocked or fail for other reasons. Can you supply a link that isn't displaying GIFs?

**Comment by lgssml** [comment]
> Hi GIFs should be supported but some may be blocked or fail for other reasons. Can you supply a link that isn't displaying GIFs?

zhihu.com this site isnot support gif
https://zhuanlan.zhihu.com/p/73080771?utm_id=0
have more. 
like this 
![Screenshot_2024-04-09-12-23-45-404_com zhihu android-edit](https://github.com/omnivore-app/omnivore/assets/97518298/beff6e84-e30d-4035-b968-a6e25d44323b)
![Screenshot_2024-04-09-12-23-13-481_app omnivore omnivore-edit](https://github.com/omnivore-app/omnivore/assets/97518298/643ed666-aa03-47b5-8839-a410d0ffd41a)

**Comment by lgssml** [comment]
> Hi GIFs should be supported but some may be blocked or fail for other reasons. Can you supply a link that isn't displaying GIFs?

gifs turn into pictures

**Comment by Smeagol2069** [comment]
I think the original site causes the issue.

When first loaded, it is a .jpg file after you tap/click on the image it turns into .webp

Before:
https://pic4.zhimg.com/v2-fc0be8e32aca8572d72ae4280906700b_b.jpg

After:
https://pic4.zhimg.com/v2-fc0be8e32aca8572d72ae4280906700b_b.webp

**Comment by lgssml** [comment]
> I think the original site causes the issue.
> 
> When first loaded, it is a .jpg file after you tap/click on the image it turns into .webp
> 
> Before: https://pic4.zhimg.com/v2-fc0be8e32aca8572d72ae4280906700b_b.jpg
> 
> After: https://pic4.zhimg.com/v2-fc0be8e32aca8572d72ae4280906700b_b.webp

Yes, that might be the reason, but I'd rather know how to get that GIF. This complicates my collection of web pages

**Comment by jagrutatwork** [comment]
So is this an issue or not?
