### ISSUE TITLE
PDF import issue

### ISSUE THREAD

**Issue by daenney** [omnivore-app/omnivore#3807]
I tried to add https://www.usenix.org/system/files/sec23winter-prepub-107-bouhoula.pdf to Omnivore using the Add > PDF (in the web UI).

However, it's severely struggling with it. It's been trying to import it about an hour now and I keep seeing the green progress bar just bouncing back and forth. After a while it gives up, until I reload the page.

Trying to open the PDF, I get:

> An error occurred while loading the document. Try reloading the page

It also seems to randomly crash Omnivore. Like suddenly my Omnivore tab closes in Firefox and I get an https://pspdfkit.com/ homepage tab substituted for it. It's all a little strange.

**Comment by jacksonh** [comment]
@daenney thanks. Did it happen more than once if you re-imported it? I was able to add this one fine in our test environment, I dont see anything in particular that would cause issues with this PDF. 

Also, have you had other PDFs work? I'm also wondering if it could be some plugin/security issue.

**Comment by daenney** [comment]
I have a couple of other PDFs in it, without issue.

I re-downloaded the PDF and uploaded again, and now things do work. I wonder if something went wrong with the transfer causing the PDF to be broken the first time around.

**Comment by jacksonh** [comment]
Yeah there's two places it could have broken, the PDF upload or the process on the backend that validates the PDF and adds the content to our search index. We definitely have some bugs with the later that we were planning on working on this week so I'll leave this open and see if i can find the issue in our logs.

**Comment by jacksonh** [comment]
I'll close this one out for now. We've improved the indexer a bit.
