### ISSUE TITLE
Math input error when HTML use katex

### ISSUE THREAD

**Issue by gilbertoolimpio** [omnivore-app/omnivore#3809]
Hello everyone!

I collected the page from [Hugging Face](https://huggingface.co/blog/lbourdois/get-on-the-ssm-train) where there are some mathematical formulas using KaTeX. The issue occurs with HTML rendering by the Omnivore web as you can see in the figure below.
<img width="837" alt="image" src="https://github.com/omnivore-app/omnivore/assets/4010050/0a37b9c1-a915-46aa-bdea-5c88a5009459">

Perhaps it's not an error given that the application's intention is to be a "read later" (hence the link to the original article), but in any case, here's the report of the error encountered.

Best regards.

**Comment by Smeagol2069** [comment]
I still new here, but it looks like MathJax tries to render the equation and fails which causes the issue -- after some searching it seems like a lot of applications have trouble from the formatting 😅 

> Perhaps it's not an error given that the application's intention is to be a "read later" (hence the link to the original article), but in any case, here's the report of the error encountered

I do think this is an error, the link is a backup measure
