### ISSUE TITLE
LABEL_ALREADY_EXISTS issue

### ISSUE THREAD

**Issue by clementbrizard** [omnivore-app/omnivore#3820]
Hi,

First, thank you for your job :)

I am often unable to create a label. When I check the API calls, I see the following answer:

```json
{
  "data": {
    "createLabel": {
      "errorCodes": [
        "LABEL_ALREADY_EXISTS"
      ]
    }
  }
}
```

Whereas the label does not exist, at least in my labels.

Thank you in advance :)

**Comment by jacksonh** [comment]
Hi @clementbrizard can i ask when this occurs for you? You are using curl or you are doing it in the UI and it occurs?

**Comment by sywhb** [comment]
Hey @clementbrizard , this should be fixed now :)

Sorry for the inconvenience caused

**Comment by sywhb** [comment]
Nice. I will close this issue as completed ;)
