### ISSUE TITLE
Receiving Posts from Unknown Feeds (no Subscription).

### ISSUE THREAD

**Issue by ttntm** [omnivore-app/omnivore#3825]
Hi there,

I already noticed this happening last week, but it's a little extreme today, so I decided to open this issue.

You'll see all the feeds I have subscribed to in the following screenshot, and also many posts from feeds I am not subscribed to (all the ones marked with the selection checkbox):

![image](https://github.com/omnivore-app/omnivore/assets/41571384/3f086be5-b469-4f7f-9bdc-ffb2f26fbe12)

I'm a bit confused, wondering where these posts are coming from and what I can do to stop it.

Thanks!

**Comment by ttntm** [comment]
> Just googled "Ye Olde Blogroll" and got this page that has those posts on it: https://blogroll.org/ -- could that be the source?

seems right, apologies for my ignorance.

I shall crawl back under my rock and hide in shame now.

**Comment by jacksonh** [comment]
hah not your fault at all. I was just thinking we need to make it way easier to see where something comes from and make it easy to unsubscribe
