### ISSUE TITLE
Android: 'About > Feedback' crashes app

### ISSUE THREAD

**Issue by maphew** [omnivore-app/omnivore#3832]
Using "3-dot menu > About > Feedback" crashes the Omnivore app on my Pixel 6 Pro phone.

Omnivore version Stable 0.200.5

Android 14 kernel 5.10.189-android13-4-00012-g1217bb583cc5-ab11174560
#1 Mon Dec 4 18:59:42 UTC 2023

**Comment by jacksonh** [comment]
@maphew was this installed from the Play store or the GitHub releases?

**Comment by jacksonh** [comment]
> I'm pretty sure installed from Play Store. Is there a way to tell for sure after the fact? @jacksonh

hah honestly no i don't think so. We should bake something in though. This might explain the lack of feedback from Android users recently!

**Comment by GalaxyM105** [comment]
I can also confirm that this is happening on my pixel 8 Pro as well, exactly how OP has described it. I have attached my device info. It is also for the 0.200.5 version of Omnivore.![Screenshot_20240422-235401.png](https://github.com/omnivore-app/omnivore/assets/167799079/350128f6-ed53-4042-883a-e2a42df2217a)

**Comment by GalaxyM105** [comment]
And I did download from Google play.

**Comment by GalaxyM105** [comment]
That worked, Thank you!
