### ISSUE TITLE
Wish: show email addresses in Android app

### ISSUE THREAD

**Issue by maphew** [omnivore-app/omnivore#3833]
It would be nice for Omnivore app About or Preferences screens to show the Omnivore email addresses that can be used to sign up for email newsletters.

**Comment by ashutoshsaboo** [comment]
Same for ios. There's an email addresses section in settings in ios app, but it doesn't seem to load all the created aliases on web ui. It doesn't even allow creating new email addresses from ios app, even though that's possible in web app. 

Not sure if that's a bug, or it's just a placeholder. @jacksonh
