### ISSUE TITLE
Bug: Can't update Article Front Matter metadata in Preferences

### ISSUE THREAD

**Issue by connerxyz** [omnivore-app/omnivore#3841]
Anything I put in this box is not saved and is instead overwritten.

<img width="1188" alt="image" src="https://github.com/omnivore-app/omnivore/assets/3486466/a048e4bf-61eb-4a00-9fe6-b99e482cf3e6">

Example if I put the following in the box:

`siteName,dateSaved,datePublished,type,description,author`

It reverts back to 

`type, description, author`

**Comment by jacksonh** [comment]
Actually, nevermind, i verified this happening to me too. only if i try to change the setting, my original ones were not overwritten. @sywhb can you take a look?

**Comment by sywhb** [comment]
Hey @jacksonh @connerxyz, the variables should be in snake case, e.g. `site_name`. 

For example, this settings
<img width="804" alt="Screenshot 2024-04-21 at 10 12 35 AM" src="https://github.com/omnivore-app/omnivore/assets/12963965/e691b674-912d-4228-84bd-3479a7e665d7">

can produce:
<img width="756" alt="Screenshot 2024-04-21 at 10 14 49 AM" src="https://github.com/omnivore-app/omnivore/assets/12963965/f2c86142-fb4a-40e8-b82b-f6adc62ba565">

The [guide](https://docs.omnivore.app/integrations/obsidian.html#front-matter) is also provided in the settings too and you can see it in the screenshot.

**Comment by connerxyz** [comment]
Thanks @sywhb! This worked.

I could have sworn the link the reference page in Omnivore's preferences pane in Obsidian was showing camelCase parameters. Anyway, I see they're snake_case now.
