### ISSUE TITLE
Failed to fetch content

### ISSUE THREAD

**Issue by domonnss** [omnivore-app/omnivore#3862]
I use self hosting RSShub to generate the feeds.
![66efe33531ec0a6282a01afdb0c923f4](https://github.com/omnivore-app/omnivore/assets/60506557/6181fbf0-eb3f-49a5-bbd2-2d01977e26bd)
But it failed to fetch content.
![image](https://github.com/omnivore-app/omnivore/assets/60506557/cc906590-bb4e-42e6-b47f-2e7baa359892)
According to the XML file,it's right.
![image](https://github.com/omnivore-app/omnivore/assets/60506557/2315d7f6-9ed7-4ea4-a6ae-636d480184eb)
SO,I tried it on https://rssviewer.app/. it works good.

What should i do?

**Comment by jacksonh** [comment]
For that feed can you change the Fetch link attribute to Never? On the feeds page you can set it.

<img width="969" alt="Screenshot 2024-04-24 at 17 50 18" src="https://github.com/omnivore-app/omnivore/assets/75189/80d08042-0162-45be-86d6-796d7effb9d4">

**Comment by domonnss** [comment]
thanks,I'll try it.

**Comment by domonnss** [comment]
It does not work out.
1 hour ago,i deployed my rsshub from docker to docker compose.
![47a5e880c541d764f28988fe5d13c01e](https://github.com/omnivore-app/omnivore/assets/60506557/bc7e5d27-c872-48c3-8a1d-82307c37bec1)
the feed content is empy.
changed the Fetch link attribute to Never,it failed to fetch content.
![395a73e6d2498ec381ecdb2278b9bb89](https://github.com/omnivore-app/omnivore/assets/60506557/52009389-e171-43ba-8da9-cf17f81037ce)

**Comment by jacksonh** [comment]
It will only refresh every four hours.

**Comment by domonnss** [comment]
> It will only refresh every four hours.

Can local deployment change this?

**Comment by jacksonh** [comment]
> > It will only refresh every four hours.
> 
> Can local deployment change this?

Yeah you could refresh it whenever you want.

**Comment by domonnss** [comment]
> > > It will only refresh every four hours.
> > 
> > 
> > Can local deployment change this?
> 
> Yeah you could refresh it whenever you want.

thanks,I'm deploying it!

**Comment by domonnss** [comment]
After reading [documents](https://docs.omnivore.app/using/feeds.html),I have figured it out.THX.
