### ISSUE TITLE
FR: API endpoints for labels

### ISSUE THREAD

**Issue by robertandrews** [omnivore-app/omnivore#3895]
Including:

- Get labels
- Add label
- Delete label
- Rename label
- Merge labels

See: https://developer.raindrop.io/v1/tags

**Comment by jacksonh** [comment]
Using the GraphQL API there is:
    
```
    Get labels:  `Query { labels: LabelsResult! }`
    Add label: `Mutation { createLabel(input: CreateLabelInput!): CreateLabelResult! }`
    Delete label: ` Mutation { deleteLabel(id: ID!): DeleteLabelResult! }`
    Rename label: `Mutation updateLabel(input: UpdateLabelInput!): UpdateLabelResult!`
    Merge labels: // for this you'd probably want to use search for the two labels, apply a new one, then delete.
```

I'll close this out because i think we have all the functionality needed here. Please feel free to re-open if you need anything.

**Comment by robertandrews** [comment]
Oh, I see…

> Reference documentation is not created for the GraphQL API, but the schema can be accessed [on GitHub](https://github.com/omnivore-app/omnivore/blob/main/packages/api/src/schema.ts).

Also, I’ve never used a GraphQL API.
