### ISSUE TITLE
Error creating account 

### ISSUE THREAD

**Issue by Lorestan00** [omnivore-app/omnivore#3921]
I haven't used omnivore for maybe a month and today when trying to use the chrome extension it asked me to login (I did this via google login) and then asked me to add in a username. I don't remember ever creating one. I entered in a username which seemed available and then it said 'error creating account'

PLease help

**Comment by jacksonh** [comment]
Sounds like you have already created an account via email then tried to create the same account with Gmail?

**Comment by jacksonh** [comment]
You'll need to reach out via the feedback page or feedback@omnivore.app with your email address so we can check on your account. I don't think this is a bug though so I will close this issue.
