### ISSUE TITLE
RSS feed Article thumbnails are not displaying for many Websites.

### ISSUE THREAD

**Issue by Nexus-Gits** [omnivore-app/omnivore#3970]
Fix failed to get thumbnail from rss feed. Rss does not show any thumbail to this rss feed:

1. https://beebom.com/feed/
2. https://techcrunch.com/feed/

Also add the support for avatars in account.  @sywhb @jacksonh @satindar

**Comment by sywhb** [comment]
Subscribed to them for testing

**Comment by sywhb** [comment]
Avatars are a nice thing to add 😄

**Comment by sywhb** [comment]
The fix is in demo environment and the thumbnails are shown correctly
