### ISSUE TITLE
微信公众号文章抓取失败

### ISSUE THREAD

**Issue by StrollStars** [omnivore-app/omnivore#3971]
链接：https://mp.weixin.qq.com/s?__biz=MzUyMzUyNzM4Ng==&mid=2247513712&idx=2&sn=b51ffc1853167f0b008014cb26417fb2#wechat_redirect
@sywhb 这回换了手机还是不行，麻烦看一下。

**Comment by sywhb** [comment]
Hey @StrollStars, 我在电脑和手机上似乎都可以正常保存。请问你那边的抓取失败是什么样子的？

<img width="805" alt="Screenshot 2024-05-20 at 12 12 12 PM" src="https://github.com/omnivore-app/omnivore/assets/12963965/75da3f69-aea9-4f37-97cc-3bbdaf4760a4">

![IMG_1183](https://github.com/omnivore-app/omnivore/assets/12963965/7ff1e5e7-3d55-4155-98a2-c88a72312a70)

**Comment by StrollStars** [comment]
@sywhb 感谢回复，多次折腾后好了，不过标题还是没能获取到，好在能够手动改。
记得正文部分有一个按钮，显示点击查看原文，下回我记得放截图上来。

**Comment by StrollStars** [comment]
@sywhb 不是，是微信公众平台，之前也有出现过。

**Comment by pengxy0** [comment]
> @sywhb 不是，是**微信公众平台**，之前也有出现过。

这个貌似有时候抓取内容比较慢，而且也不知道是不是网络的问题，有时候好久都不能抓取到内容，有时却挺快的。希望开发者能解决这个问题！

**Comment by StrollStars** [comment]
@pengxy0 确实如此，我这边的现象和你相同。
现在的问题是表现得没有规律，我有时候换时间段或者换手机能够将失败的文章抓取成，有时候又不能。
开始以为是 @sywhb 后台调整了服务器，但是从它的截图来看又不是，所以我也搞不清楚问题到底在哪。

**Comment by pengxy0** [comment]
> @pengxy0 确实如此，我这边的现象和你相同。 现在的问题是表现得没有规律，我有时候换时间段或者换手机能够将失败的文章抓取成，有时候又不能。 开始以为是 @sywhb 后台调整了服务器，但是从它的截图来看又不是，所以我也搞不清楚问题到底在哪。

是的，我还是暂时性将公众号内容放在zotero吧，网页快照也挺好用的。

**Comment by StrollStars** [comment]
@pengxy0 我最近的两篇都无法获取到标题，好在可以手改。
用zotero的好处是网页能够原汁原味，但是它的附件文件名无法改成网页标题就很麻烦。

**Comment by pengxy0** [comment]
> @pengxy0 我最近的两篇都无法获取到标题，好在可以手改。 用zotero的好处是网页能够原汁原味，但是它的附件文件名无法改成网页标题就很麻烦。

我觉得对于附件文件名到不存在什么，你可以保存条目类型为播客帖子或者网页，标题都可以改啊。你意思是文件里面的标题吗？那你可以找个插件，在网页里改好之后，再保存到zotero。目前zotero最不方便的地方是移动端不能保存快照。头痛。

**Comment by StrollStars** [comment]
@pengxy0 我指的是用zotero自带的Chrome扩展保存，文件名会是一串随机英文字母，并且通过设置或插件无法修改附件的文件名。如果是用第三方扩展保存成文件再放入zotero也可以，不过这就没必要用zotero了，所以我没用zotero了。至于移动端我目前也没有解决办法，当初的为知其实还不错，可惜没有更新了。

**Comment by pengxy0** [comment]
> @pengxy0 我指的是用zotero自带的Chrome扩展保存，文件名会是一串随机英文字母，并且通过设置或插件无法修改附件的文件名。如果是用第三方扩展保存成文件再放入zotero也可以，不过这就没必要用zotero了，所以我没用zotero了。至于移动端我目前也没有解决办法，当初的为知其实还不错，可惜没有更新了。

噢噢，我一直没遇到过，zotero的文件名是一串字母的情况，都是很正常的标题😂😂

**Comment by StrollStars** [comment]
@pengxy0 我是通过它的Chrome扩展保存的网页，其顶级是网页标题，但网页作为附件保存在顶级下的子级，该文件以随机英文字母命名，且无法自动重命名。不知我说清楚了没有。

**Comment by pengxy0** [comment]
> @pengxy0 我是通过它的Chrome扩展保存的网页，其顶级是网页标题，但网页作为附件保存在顶级下的子级，该文件以随机英文字母命名，且无法自动重命名。不知我说清楚了没有。

你说的是这里的吧？希望我没理解错😂

![image](https://github.com/omnivore-app/omnivore/assets/130196652/b9b6ad6b-174a-40f1-88d5-856f4a220b74)

**Comment by StrollStars** [comment]
@pengxy0 如下图：
![](https://www.zotero.org/static/images/home/screenshot-1.4.png)
中间部分行首有个向右的三角形，右侧有作者和年份信息的就是顶级，点击三角形展开后的内容是子级，也就是附件。
比如图中的Full Text PDF，它在磁盘上就是以随机字母命名的文件保存的。

**Comment by pengxy0** [comment]
@StrollStars 你试试这个软件吧，可以重命名的，博主也在B站发了介绍视频。我咩有遇到你这种问题😄

**Comment by StrollStars** [comment]
@pengxy0 谢谢你的好意，现在我已经直接保存网页文件，暂时不想折腾了。😅

**Comment by pengxy0** [comment]
> @pengxy0 谢谢你的好意，现在我已经直接保存网页文件，暂时不想折腾了。😅

没事儿，不客气

**Comment by StrollStars** [comment]
@pengxy0 我又来了，结果我还是折腾上了😅
[zotero-attanger](https://github.com/MuiseDestiny/zotero-attanger)和[ZotFile](http://zotfile.com/)是不是属于同类型的扩展，装一个就够了？

**Comment by pengxy0** [comment]
> @pengxy0 我又来了，结果我还是折腾上了😅 [zotero-attanger](https://github.com/MuiseDestiny/zotero-attanger)和[ZotFile](http://zotfile.com/)是不是属于同类型的扩展，装一个就够了？ 还有前面我说直接保存了网页文件，我想导入进去，本来打算用后者，是不是前者也能做到？

hhhh是滴，zotero 7版本你就装zotero-attanger，zotfile已经不维护了。zotero安卓端貌似快要能保存网页了。我还在观望中

**Comment by StrollStars** [comment]
@pengxy0 先前我用的是6正式版，现在7还在测试中，也不知要多久出正式版，然后7有个不喜欢的地方是多进程。
那zotero-attanger不能用在6上面吗？感谢告知`zotfile已经不维护了`。
我想解决的问题其实是快照名，如下图：
![1](https://github.com/omnivore-app/omnivore/assets/10942225/8f709584-01a7-49b9-a120-62a6dceee6fa)
![2](https://github.com/omnivore-app/omnivore/assets/10942225/53dbd0b2-9ed4-4f82-b2f9-3e84b5e75f57)
下面那张图片的文件名是否能自动重命名成上面那张图中，红框上面那个顶级的标题？

**Comment by pengxy0** [comment]
不知道可不可以用在 6 上，你在插件区看一下。另外我明白你要改快照的名字，我也觉得它很细节，也有一丝想法改它，但后来想着他还有条目名称在，就想着无所谓了哈哈哈

**Comment by StrollStars** [comment]
@pengxy0 那就是说这个插件还是没办法自动重命名快照？而Zotero自带功能（设置中有）也无法自动重命名快照，但是手动却是可以的，总觉得哪里不太对。
在Zotero里面是无所谓的，就是在文件管理器里看起来别扭。
Zotero有`about:config`，它有说明文档吗？

**Comment by pengxy0** [comment]
@StrollStars 是的，现在不能自动重命名快照，我一般不在文件管理器中找它。你说的这个config，我不太清楚，没有研究这个。

**Comment by StrollStars** [comment]
@pengxy0 我发现Zotero内置的SingleFile扩展落后于SingleFile本身，这个有办法单独更新吗？
[zotero-attanger](https://github.com/MuiseDestiny/zotero-attanger)并不兼容6，等官方出7正式版了。

**Comment by pengxy0** [comment]
@StrollStars 不太清楚这个😄，但你可以用7️⃣啊，界面很好看，用起来也不差。

**Comment by StrollStars** [comment]
@pengxy0 问下，Zotero有没有批量添加标签的插件？

**Comment by pengxy0** [comment]
> @pengxy0 请教下，Zotero有没有批量添加标签的插件？

选中多个条目直接拖到左下侧的某个标签，就可以了

**Comment by StrollStars** [comment]
> > @pengxy0 请教下，Zotero有没有批量添加标签的插件？
> 
> 选中多个条目直接拖到左下侧的某个标签，就可以了

我发现这样有个弊端，就是标签多了以后，拖放有点不方便。
新建子分类可以解决这个问题，不过如果一个条目出现在多个子分类中，是不是没有办法看出来？
而且我感觉有了标签以后，子分类好像用处不大了。

**Comment by pengxy0** [comment]
拖放标签这个真的没撒好主意。
但是子分类和标签，你需要做下归类，哪些关键词，你是需要建立子分类，哪些关键词你需要建立标签，这个你做好，应该就还是方便寻找了。让它俩共同承担你对文献的分类，就都比较轻松。让其中一个承担了所有，那另外一个不就成摆设了。😂😂

**Comment by StrollStars** [comment]
@pengxy0 我现在基本依靠标签，没用子分类，因为标签更灵活。
还有个问题就是我前面想请教的，我有办法看出一个条目出现在两个子分类中吗？好像做不到是吗？

**Comment by pengxy0** [comment]
@看到的，一种方法是你选中条目，crtl+单击，就会显示；另一种是zotero7现在的版本，可以在右边看到。
![image](https://github.com/omnivore-app/omnivore/assets/130196652/eb810ac2-1e0f-4dfb-a940-68b2045a31b1)

**Comment by StrollStars** [comment]
@pengxy0 感谢指教，确实可以，不过都只能单条查看？有没有批量的办法？其自带的重复的条目是如何判定的？

**Comment by pengxy0** [comment]
> @pengxy0 感谢指教，确实可以，不过都只能单条查看？有没有批量的办法？其自带的重复的条目是如何判定的？

no 😂好像无法判定

只能自己去看

**Comment by StrollStars** [comment]
@pengxy0 是不是不能选择不含特定标签的对象？

**Comment by StrollStars** [comment]
@pengxy0 用上了7的正式版，发现两个问题，一个是子级内容不能有笔记，全部迁移成笔记要花点时间。二是条码的标签点了变成修改，6上好像是显示该标签的所有条目，感觉这个改变反而不好。
