### ISSUE TITLE
Posts from deleted subscription still keep appearing

### ISSUE THREAD

**Issue by igorkulman** [omnivore-app/omnivore#3991]
I subscribed to blog X by adding the RSS feed to the subscriptions.

After a while I deleted the subscription to blog X from Omnivore. It is no longer showing in the subscription list in the iOS app or on the web.

Yet I still get new posts from blog X showing in Omnivore when they are published and appear in the RSS I no longer follow.

**Comment by jacksonh** [comment]
I'd need some more details to look into this. Can you give me the original feed and maybe a screenshot or the URL of one of the items you think came from it after unsubscribing?

**Comment by igorkulman** [comment]
At the moment in Inbox I see a post from lapcatsoftware.com that I did not save and it shows as coming from subscriptions 

![Screenshot 2024-05-29 at 19 39 23](https://github.com/omnivore-app/omnivore/assets/4746070/bf37995e-2070-4d04-b84c-e61afc7fc81a)

But when I open the subscription list at https://omnivore.app/settings/subscriptions the lapcatsoftware.com RSS is not there anymore because I deleted it months ago.

| |  |
| -------- | ------- |
| ![Screenshot 2024-05-29 at 19 41 25](https://github.com/omnivore-app/omnivore/assets/4746070/a62e08d0-594d-4955-b218-38821e2eb167) | ![Screenshot 2024-05-29 at 19 41 32](https://github.com/omnivore-app/omnivore/assets/4746070/dc48d28f-7a81-40d1-ae2d-ee1dee51f3da)   |

**Comment by jacksonh** [comment]
[Feed URL](https://lapcatsoftware.com/articles/atom.xml)

<img width="330" alt="Screenshot 2024-05-30 at 09 20 07" src="https://github.com/omnivore-app/omnivore/assets/75189/99a5dea1-cbca-4006-8ff3-669c835d716d">

<img width="776" alt="Screenshot 2024-05-30 at 09 21 04" src="https://github.com/omnivore-app/omnivore/assets/75189/a2f1dc56-e79e-4f9e-a757-4f65359bf26c">
