### ISSUE TITLE
Browser E-Mail Login/Signup Error

### ISSUE THREAD

**Issue by patrickc-sb** [omnivore-app/omnivore#4080]
Hey,

I tried to create an account (E-Mail signup) for Omnivore yesterday but always got "An unknown error occurred" when creating my account. After a couple of retries to rule out typos I tried it over the Android companion app. It worked with the same credentials, I do have my account now. 
However, I just tried to logging in on my computer over the browser and I get the same error:
<img width="644" alt="grafik" src="https://github.com/omnivore-app/omnivore/assets/102750591/99674f06-97c8-4847-8c7f-6519a5e45f00">

Primarily I'm using a Macbook with Librewolf (Firefox) but I also tried it with the current Chrome browser.

Did anyone have the same issue? I searched the existing issues for a similar one but didn't find one.

Thanks,
patrickc-sb

**Comment by RahulMishra0722** [comment]
you trying to set-up?? its working fine for me i made an account just to check and it works fine as long as you pass the captch test it works fine

**Comment by patrickc-sb** [comment]
I tried and got the error while setting up. More precisely when clicking the signup button (with the form filled out). I then tried setting up my account via Android app, that worked. But I get the same error when I try to log in over my Browser on my computer.
The login on the Android app worked.

I did not get any captcha so far when I tried, also not over using Chrome. Weird. I just get this very general error message.

**Comment by patrickc-sb** [comment]
Ok, so this was some kind of weird local Browser issue... The captcha was missing, the error occurs when the captcha is not solved. I tried Safari, it worked there. Then I updated my chrome and my Librewolf. I have the captcha in both now and was able to log in.

The issue is resolved!

@RahulMishra0722 Thanks for you quick response and for testing!

**Comment by patrickc-sb** [comment]
Closing issue.
