### ISSUE TITLE
ui bug when bulk upload pdfs

### ISSUE THREAD

**Issue by weeebdev** [omnivore-app/omnivore#4089]
<img width="465" alt="image" src="https://github.com/omnivore-app/omnivore/assets/48881444/6f0780d5-85be-4b36-9a14-79a388217803">

ig need to add scroll

**Comment by gitkrishnapathak** [comment]
I want to solve it. Can you assign me ?

**Comment by weeebdev** [comment]
> I want to solve it. Can you assign me ?

I do not think I can. Could you do that @jacksonh ?

**Comment by moadavou** [comment]
I would like to help out with this one 😊

**Comment by devansh-m12** [comment]
can i work on this issue ?

**Comment by jacksonh** [comment]
> can i work on this issue ?

hey @moadavou i saw you unassigned, i assume issues getting setup to work on it?

**Comment by moadavou** [comment]
@jacksonh Yes, sorry. It didn't download properly. I'll probably try again when I have some more time.
