### ISSUE TITLE
Generate RSS and/or JSON feeds of shared links and highlights

### ISSUE THREAD

**Issue by xplosionmind** [omnivore-app/omnivore#409]
It would be awesome to have the possibility of generating RSS feeds for:
- [ ] each tag’s articles
- [ ] unread articles
- [ ] favorited articles
- [ ] archived/read articles

This feature can be used both for reading saved articles in RSS reader apps, or to share what the user reads concerning a specific set

**Comment by jacksonh** [comment]
Hey @xplosionmind, i like this idea. I think it can be basically built on our search API, each of the above is a searchable phrase now (except Favorite which we don't have right now). So we could do something like:

- `https://omnivore.app/xplosionmind/search.rss?label:programming`
- `https://omnivore.app/xplosionmind/search.rss?is:unread`
- `https://omnivore.app/xplosionmind/search.rss?is:archived`

One issue is auth, I know some services will put a secret in the url, and other's use HTTP basic authentication.

**Comment by jacksonh** [comment]
Mind me asking a couple follow up questions?

- Which RSS readers are you using?
- Any reason you prefer to read there instead of in Omnivore?
- Would you want a public RSS feed also? Like "Hey follow everything I'm reading" 
- Also, do you want a feed of your highlights or of articles you save?

**Comment by xplosionmind** [comment]
- I am using [Feedbin](https://feedbin.com)
- To be completely honest, I would not be using this feature much for this purpose. If I would, it would be to have **all of the things I want to read in one single place/app**, without having to switch
- This is exactly what I intend to use RSS feeds for
- For this purpose, I think having implementation with highlighting-focused software would be much more useful and effective. See #412

**Comment by jacksonh** [comment]
Thanks that helps. So do you think if we had all these feeds you would do your reading in Feedbin?

Or, would it be better for you if Omnivore could ingest RSS feeds, and then you could read "everything" in Omnivore?

**Comment by xplosionmind** [comment]
As I pointed out, I would not be using this feature really much, but I know many people who would take advantage of the first solution. Instead I would love to use RSS feeds to share what I am reading.

**Comment by jacksonh** [comment]
Thanks, just wanted to clarify. The sharing aspect is quite interesting to me too. We do have some designs to have a profile page where you can share, but exposing that as RSS makes a lot of sense also.

**Comment by jacksonh** [comment]
This is a mockup of the public profile page. We had it working for a while, but disabled it to focus on some more core pieces. I think adding RSS right there would make a lot of sense. 

<img width="543" alt="Screen Shot 2022-04-13 at 10 37 41" src="https://user-images.githubusercontent.com/75189/163238535-680475aa-fcba-4656-b64e-6ebda5e0c32a.png">

**Comment by jacksonh** [comment]
@xplosionmind in your sharing scenario, would you want to share with the whole world, like a public shared timeline similar to twitter, or do you think you'd want a select group of people to share with, more like a facebook where follow requests have to be approved?

**Comment by xplosionmind** [comment]
Thanks for asking! I would definitely use it to share **with the whole world**.

**Comment by xplosionmind** [comment]
Furthermore, I stumbled upon [JSON Feed](https://jsonfeed.org), and I believe it to be much better in the case of Omnivore, built with JavaScript

**Comment by jacksonh** [comment]
Oh yes, that does look a lot more consumable for developers.

**Comment by jacksonh** [comment]
Updated UI for profile/follow pages

<img width="690" alt="Screen Shot 2022-05-12 at 12 21 58" src="https://user-images.githubusercontent.com/75189/168152449-962b3aaf-f28d-4c69-9b31-051e9ac94e5d.png">

**Comment by Yubuxin** [comment]
> 



> Mind me asking a couple follow up questions?
> 
> * Which RSS readers are you using?
> * Any reason you prefer to read there instead of in Omnivore?
> * Would you want a public RSS feed also? Like "Hey follow everything I'm reading"
> * Also, do you want a feed of your highlights or of articles you save?

Thanks for developing such an excellent software firstly.

Endorse the proposal of @xplosionmind . I want the favorited articles to automatically generate RSS for seamlessly integrating with other note-taking or knowledge tools that support RSS (Devonthink being the most obvious example), as well as further processing. This will be a very useful feature for me.

**Comment by trijste** [comment]
I would like to have rss feeds fed into omnivore alongside my manually saved content. Otherwise I'm stuck between apps. I'm usually skimming headlines and deleting the majority, but sometimes I'm saving to read later.

**Comment by Warden20** [comment]
I will use it in integration with KOReader to send articles to my kindle or ereader
