### ISSUE TITLE
Notion intergration: There was an error updating Notion settings.

### ISSUE THREAD

**Issue by pharazone** [omnivore-app/omnivore#4098]
I want to use the intergration function for my notion, but when I pasted my notion database ID, it showed 'There was an error updating Notion settings.'
![image](https://github.com/omnivore-app/omnivore/assets/11215634/20b865ae-d538-4426-ac44-9d103631ed6b)

**Comment by sywhb** [comment]
Hey @pharazone, would you mind sharing a screenshot of the database created in your Notion?
