### ISSUE TITLE
Advanced/Full text search

### ISSUE THREAD

**Issue by xplosionmind** [omnivore-app/omnivore#410]
It would be super awesome if full text search could be provided, so that users can be empowered an search for details in articles even if they forgot the title.

Furthermore, an advanced search feature should enable to choose whether to look for the searched term in the title, in the content, or in the description, etc…

**Comment by jacksonh** [comment]
Hey @xplosionmind, we are using Elastic right now for search so we do have full text search on content. There are also some advanced queries available, but not documented quite yet. Here are the ones I know, but "ll cc @sywhb here too, who worked on this:

- labels (and, or, not):
 - or: `label:Hockey,Swimming`
 - and: `label:Hockey label:Swimming`
 - not: `label:programming`

type: `is:file` `is:highlight`

highlights: `has:highlights`

states: `in:unread` `in:read` `in:archive` `in:inbox`

I really like adding `title`, `content`, `description`, and also `site` as search options. Any others you can think would be useful?

**Comment by sywhb** [comment]
Thanks @jacksonh. Yes, we support all these queries. Some small changes here:

## For labels:
* not: `-label:<label_name>`

## For type:
* `type:file` or `type:highlight`

## For basic query, we are doing full-text search on `title`, `content` and `description`. We could make them as search options too in the next iteration.

**Comment by sywhb** [comment]
#445 belongs to here too
