### ISSUE TITLE
Hypothesis integration

### ISSUE THREAD

**Issue by xplosionmind** [omnivore-app/omnivore#412]
Hi! First of all sorry for opening so many issues in one time, but Omnivore appears to be so awesome and promising that I cannot wait to have features I value a lot to start using it.

---

I am very fond of [Hypothesis](https://hypothes.is), the most used highlighting service that is open source, too.

How great would it be if annotations and highlights on Omnivore could automatically be synchronized and saved on my Hypothesis account? Would it be feasible? I believe it would be game-changing.

**Comment by jacksonh** [comment]
Hey, @xplosionmind actually we really appreciate the issues, helps a lot. 

With Hypothesis, do you think you'd normally be creating highlights on pages, and then when you save to Omnivore you want to ingest all those highlights? 

Or is your preference to highlight things in Omnivore and push those highlights out?

I'll investigate their API a little. I've only encountered Hypothesis once before, but we are just adding some API functionality too, so this could be a good test case.

**Comment by xplosionmind** [comment]
I believe that as I would save the web page on Omnivore anyways, highlighting inside the app itself and then exporting the same highlights to Hypothesis would be very nice.

Nevertheless, also the other way around could be very useful: I would love to import in Omnivore articles that I highlighted already.

**Comment by jacksonh** [comment]
API docs: https://h.readthedocs.io/en/latest/api/

**Comment by cogscides** [comment]
This would be amazing to have, as it could also add support for many other apps/services that integrate Hypothesis API. For example, Obsidian has a hypothesis integration.

**Comment by jacksonh** [comment]
Thanks for bumping this one up @cogscides. Definitely helps to know what people want. Can i ask you the same question I asked @xplosionmind to understand the use cases:

> With Hypothesis, do you think you'd normally be creating highlights on pages, and then when you save to Omnivore you want to ingest all those highlights?
> 
> Or is your preference to highlight things in Omnivore and push those highlights out?

**Comment by cogscides** [comment]
@jacksonh I think more frequently will be the second workflow to highlight in Omnivore and push those to the Hypothesis.
But the first one is also possible.

**Comment by pdelre** [comment]
> Nevertheless, also the other way around could be very useful: I would love to import in Omnivore articles that I highlighted already.

I'd probably fall more into this use case. My first reader is the native browser and Hypothesis's [bookmarklet](https://web.hypothes.is/help/installing-the-bookmarklet/) works on both Chrome Desktop & Mobile and provides seamless, cross-platform note taking capabilities. Only if an article is very long or something I know I'll want to read will I send it to a "read later" service, ie Omnivore, but I wish to use the other features of Omnivore (saved has/will read list, markdown copy, PKM integrations).

The alternative/existing flow is when reading in Chrome, come across something interesting:
- Save to Omnivore
- Open Omnivore
- Find the interesting text
- Highlight

The preferred is when reading in Chrome, come across something interesting:
- Load Hypothesis bookmarklet
- Highlight
- (Async transfer to Omnivore)

_(This is branching out of this issue but there's a wild alternative where a yet-to-exist Omnivore bookmarklet lets me highlight in the browser on an article's native site, which results in the article to be store in Omnivore for future reference.)_

**Comment by xplosionmind** [comment]
To further support the relevance of social highlighting, I find this article very insightful!

[***How Social Annotation Outshines Traditional Discussion Boards in Learning Management Systems***](https://web.hypothes.is/blog/transforming-education-how-social-annotation-outshines-traditional-discussion-boards-in-learning-management-systems)
