### ISSUE TITLE
Bug when editing tag description, breaking when inserting description with double quote

### ISSUE THREAD

**Issue by noghartt** [omnivore-app/omnivore#4123]
![image](https://github.com/omnivore-app/omnivore/assets/47952043/547f06b6-e67b-4c26-afcf-97a0d535935c)

When I insert a new tag description containing a double quote, the server return a 400 with a GraphQL error, like the print above. See the mutation:

```graphql
    mutation {
      updateLabel(
        input: {
          color: "#7BE4FF"
          name: "til"
          description: ""today i learned" articles"
          labelId: "<label id>"
        }
      ) {
        ... on UpdateLabelSuccess {
          label {
            id
            name
            color
            description
            createdAt
          }
        }
        ... on UpdateLabelError {
          errorCodes
        }
      }
    }
  
```

**Comment by fbtot** [comment]
The same problem occurs with label names as well. It only happens when editing existing labels, not when creating a new one.

As a temporary workaround, you can escape double quotes manually (`\"today i learned\" articles`).

**Comment by jacksonh** [comment]
Yeah this uses some old string interpolation that it really shouldn't. Thanks for raising.

**Comment by jacksonh** [comment]
https://github.com/omnivore-app/omnivore/pull/4171
