### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by qazxcdswe123** [omnivore-app/omnivore#4139]
This issue was first raised in discord: https://discord.com/channels/844965259462311966/1115896629124411504/1244935431137656903

And it only occur on URL: https://hsivonen.fi/encoding_rs/. Both safari, chrome, firefox and android app are affected. But omnivore mac app from app store would work.

Reply from @jacksonh 
> this is kind of an amazing bug. We use `window.webkit` on iOS, so there are some special handlers for that. But this article has `<h4 id="webkit" data-omnivore-anchor-idx="3256">` so it resolves to true!

**Comment by jacksonh** [comment]
Hi, this one has been fixed locally but I haven't been able to deploy the fix yet as we have some other web bits that are in testing.
