### ISSUE TITLE
Supporting Markdown in annotations

### ISSUE THREAD

**Issue by xplosionmind** [omnivore-app/omnivore#414]
What if by annotating something in an article I would like to refer to another one I read somewhere else?  
What if I would like to use text formatting?  
What if I would like to embed an image of which I have the URL already?

I believe **implementing Markdown** in annotations would be super useful to create connections, but also to provide the capability of formatting text and adding more stuff inside annotations.

**Comment by jacksonh** [comment]
Yeah, i think this is a good idea, markdown is great for public text formatting. Especially considering public sharing. In the case where I am sharing my annotations publicly (see an attached mockup), I think I would want a lot of control over the formatting of my annotations.

<img width="392" alt="Screen Shot 2022-04-12 at 23 04 05" src="https://user-images.githubusercontent.com/75189/163110733-42a75134-86f9-4c5e-ac30-915ce83a25a3.png">

**Comment by jacksonh** [comment]
Done!
