### ISSUE TITLE
cannot sign up

### ISSUE THREAD

**Issue by forgetpwd** [omnivore-app/omnivore#4145]
after many trials, no matter with my google account or email, it always show all kinds of errors.
even after i click the email verification link, it still ask me to create a profile. but when i type in my username and full name,
it shows error again.

is this app really working?

**Comment by jacksonh** [comment]
@forgetpwd yes works fine for most. It sounds like your account might be in a pending state. Can you message using the tool on this page so i can lookup your email?  https://omnivore.app/support

**Comment by forgetpwd** [comment]
it is working now.  yo are right. it is likely due to the pending so i had to wait a couple of hours.
