### ISSUE TITLE
Obsidian plugin integration

### ISSUE THREAD

**Issue by xplosionmind** [omnivore-app/omnivore#415]
Having the possibility of annotating thoughts concerning what is being read is extremely productive and useful. Nevertheless, often such annotations after being written get forgotten and lay in that saved article forever.

An effective solution, a further step after #414, could be **synchronizing annotations with [Obsidian](https://obsidian.md)**, where the user could link to other already annotated concepts its thoughts concerning the article in Omnivore.

I submitted [this plugin idea on the Obsidian forum](https://forum.obsidian.md/t/omnivore-integration/35752), where I explained a bit more in detail the process I envision.

**Comment by jacksonh** [comment]
Link to API docs: https://github.com/obsidianmd/obsidian-api

**Comment by xplosionmind** [comment]
I am sorry, I forgot I created this issue and I created https://github.com/omnivore-app/logseq-omnivore/issues/71, which is a duplicate.

**Comment by jacksonh** [comment]
Hey good news, we have an Obsidian plugin that is under review right now. We are hopeful it will be released this week.
