### ISSUE TITLE
Take "Front Matter Template" out of advanced settings

### ISSUE THREAD

**Issue by EnriqueTMT** [omnivore-app/omnivore#4158]
# Problem(s)

- It's very easy to misinterpret the `Articles > Front Matter` section in the plugin's settings as a the template for the users "Front Matter".
- "If you want to use a custom front matter template, you can enter it below under the advanced settings" takes a fine print approach. The font is pretty small and the users eyes are primarily taken to the "Front Matter" header and the "Reference" hyperlink to a page with an example Front Matter template.
- Nesting some of the settings option under "Advanced Settings" is not a common for most of the popular Obsidian plugins.

# Solution(s)

- Since the "Front Matter Template" is no more intimidating or advanced than the "Article Template", it should be above `Articles > Front Matter` or under `Articles > Article Template`.
	- This will make it a little easier for new users to integrate a Front Matter Template into their imports.

**Comment by jacksonh** [comment]
I appreciate the report, but almost all our Obsidian support issues are related to people creating custom front matter templates that then create invalid yaml in the front matter.
