### ISSUE TITLE
Android app crashes when I send a link to the app.

### ISSUE THREAD

**Issue by CodingFan72** [omnivore-app/omnivore#4161]
Since the latest update, the app crashes as soon as I send a link. 

I received a message from the system that the app has crashed several times. 

When  I stop the app, the message does not appear immediately after the first share, but the app does not save the shared link.

 I use a Samsung S23 with Android 14.

**Comment by h3half** [comment]
I'm also having this problem. When I open the app to see my saved links it'll load fine, but if I swipe down to refresh the list the app crashes.

Device: Pixel 6
Android version: 14
Android security update: June 5, 2024
Google Play system update: June 1, 2024

**Comment by FilSalustri** [comment]
Same problem here on a Pixel 8, with all current updates applied.

**Comment by bigmadkev** [comment]
Same issue latest updated fold 5

**Comment by jacksonh** [comment]
I believe this is resolved now. Please open if you are still having the issue
