### ISSUE TITLE
网页版登录地址跳转错误

### ISSUE THREAD

**Issue by StrollStars** [omnivore-app/omnivore#4197]
@sywhb 网页版登录后，地址跳转 https://omnivore.app/l/home ，显示一片空白，要将地址手动修改成 https://omnivore.app/home ，才能显示出内容。

**Comment by sywhb** [comment]
@StrollStars 这个网址是我们新的主页，还没上线。。 幸亏你发现了，我马上修复

**Comment by sywhb** [comment]
问题已经修复 🙏
