### ISSUE TITLE
微信公号文保存问题

### ISSUE THREAD

**Issue by StrollStars** [omnivore-app/omnivore#4198]
1. Android客户端保存文章的过程中，经常提示`保存您的页面时出错`，要保存好几次才能成功。
2. Android客户端保存文章的元数据中，PUBLISHED内容为空（Android客户端看不到无法修改），TITLE经常为微信公众平台。

@sywhb 问题出现有几个月了，希望能修复一下。

**Comment by sywhb** [comment]
不好意思哈 @StrollStars  😬 ，给你带来了不便。

**Comment by StrollStars** [comment]
@StrollStars 好像有更麻烦的问题，高亮划线会丢失，我用的是安卓客户端。

**Comment by StrollStars** [comment]
@sywhb 今日保存顺利，感谢修复。

**Comment by StrollStars** [comment]
@sywhb 之前关闭早了，还请看下第二个问题。

**Comment by StrollStars** [comment]
@sywhb 目前微信公众号文章的发布日期和时间提取到元数据还是有问题，麻烦再看一下。

**Comment by sywhb** [comment]
@StrollStars 请问你是用浏览器保存的吗？

**Comment by StrollStars** [comment]
@sywhb 用的是安卓客户端，今天发现已经能够提取了。
