### ISSUE TITLE
Cannot build Selfhost build-and-push-images.sh

### ISSUE THREAD

**Issue by codevski** [omnivore-app/omnivore#4209]
Trying to run the selfhost .sh build and running into this error:

> [builder 15/28] RUN yarn install --pure-lockfile:                                                                                                        
#21 1.824 yarn install v1.22.19
#21 2.265 [1/4] Resolving packages...
#21 4.642 error Couldn't find package "@omnivore/utils@1.0.0" required by "@omnivore/content-handler@1.0.0" on the "npm" registry.
#21 4.643 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
#21 4.651 Error: Couldn't find package "@omnivore/utils@1.0.0" required by "@omnivore/text-to-speech-handler@1.0.0" on the "npm" registry.
#21 4.651     at MessageError.ExtendableBuiltin (/opt/yarn-v1.22.19/lib/cli.js:721:66)
#21 4.651     at new MessageError (/opt/yarn-v1.22.19/lib/cli.js:750:123)
#21 4.651     at PackageRequest.<anonymous> (/opt/yarn-v1.22.19/lib/cli.js:36590:17)
#21 4.651     at Generator.throw (<anonymous>)
#21 4.651     at step (/opt/yarn-v1.22.19/lib/cli.js:310:30)
#21 4.651     at /opt/yarn-v1.22.19/lib/cli.js:323:13
#21 4.651     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
------
process "/bin/sh -c yarn install --pure-lockfile" did not complete successfully: exit code: 1

not sure if the script is out of date?

**Comment by jacksonh** [comment]
I think maybe the Dockerfile is missing a line here. /cc @sywhb

**Comment by codevski** [comment]
correct I think its missing:

```COPY /packages/utils/package.json ./packages/utils/package.json```

Seems like its continuing to build now

**Comment by sywhb** [comment]
We have added the missing lines to the docker file
