### ISSUE TITLE
Is there anyway that I can annotate/highlight directly  on the web, instead of saving the article first? 

### ISSUE THREAD

**Issue by gxcuit** [omnivore-app/omnivore#4213]
Hi there, I want to be able to annotate and highlight directly on the web, similar to how [Readwise's highlighter ](https://chromewebstore.google.com/detail/readwise-highlighter/jjhefcfhmnkfeepcpnilbbkaadhngkbi)works. However, with Omnivore, I have to save the article first and then annotate within Omnivore.

Is there any way that I can annotate/highlight directly on the web, instead of saving the article first? 

Thanks

**Comment by jacksonh** [comment]
There is not.
