### ISSUE TITLE
MacOs version not updated last 7months

### ISSUE THREAD

**Issue by andszk** [omnivore-app/omnivore#4216]
I'm waiting for some fixes for MacOs client, that are already fixed, but app version for MacOs is stuck on 1.38 last 7months. Just today there was an iOS update but not for MacOS. What's the problem? Please release new version for the MacOs if able to.

**Comment by jacksonh** [comment]
Hi, you should use the web version over the macOS version.

**Comment by andszk** [comment]
Does the web version support downloading articles for the future without internet access? Like flights?

Also does this mean that Mac version is abandoned and will receive no further updates?
