### ISSUE TITLE
Bug:Sometimes can't add sucess ,and no any tips and error.

### ISSUE THREAD

**Issue by wu4339** [omnivore-app/omnivore#4225]
Right now ,Item show need download all website. when add fail ,no any tips and error.

suggest : when add website , immediately add one item no need waiting .Even if it fails we can know .

**Comment by jacksonh** [comment]
Can you describe your issue more?

**Comment by wu4339** [comment]
> Can you describe your issue more? 

Sometimes an add failure occurs without any prompting。
