### ISSUE TITLE
Saving the URL https://www.reddit.com/ fails

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#472]
Steps to reproduce:

1. Running locally click the Add Link dialog and enter `https://www.reddit.com/`
2. Notice how in Chromium the page is flashing
3. Eventually it should hit a 30s timeout

There are two major issues we need to resolve here. 

1. There's no item added to the library, so the save is completely lost. (Adding our stub element could resolve this)
2. I believe the javascript we execute on the page is failing. In these cases we can probably fallback to something else to capture content.

**Comment by sywhb** [comment]
I can replicate this issue but saving a post works.
What should be the expected bahavior to add links from `https://www.reddit.com/`?
Create an item for each post?
