### ISSUE TITLE
Saving image url fails

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#535]
Calling SaveURL on the following URL fails: https://pbs.twimg.com/media/FR2VxBLUcAEGOIA.jpg

**Comment by jacksonh** [comment]
We should be able to handle these in puppeteer by wrapping in a small image box.

**Comment by sywhb** [comment]
<img width="1022" alt="Screenshot 2022-05-05 at 12 17 42 PM" src="https://user-images.githubusercontent.com/12963965/166863050-18bcd8e2-c55a-4a56-beb9-7fba9c35043e.png">
I wrapped it in a small image box with a title to avoid it being removed by readability
