### ISSUE TITLE
Tweets in newsletters are not rendered correctly 

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#569]
Embedded tweets in newsletters are not always rendered correctly 

TODO: need a test case here.

**Comment by jacksonh** [comment]
Screenshot from Milk Road. You can see the tweet content is displayed but we remove the tweet embedded iframe 

![image](https://user-images.githubusercontent.com/75189/167538138-e20d6830-7c43-4090-a8dc-fec00b1b5cd6.png)

**Comment by sywhb** [comment]
Hey @jacksonh, this tweet is not an embedded tweet actually and it does not have a twitter url either. It's a well-formatted `<table>` looks like twitter in the newsletter, so when we parse it, we replaced it with a `<div>`.
I can think about creating a layout to make it a bit more like twitter?

**Comment by sywhb** [comment]
Oh actually it has a link to the tweet which I use to fetch the content and embedded it
Or we could just use the static content we have in the newsletter

**Comment by sywhb** [comment]
<img width="803" alt="Screenshot 2022-05-12 at 10 49 55 AM" src="https://user-images.githubusercontent.com/12963965/167982296-02ffadb0-95d0-4e8e-a7c3-a970931852ab.png">
Ok now it looks like this

**Comment by jacksonh** [comment]
Oh, i wonder if this uses the twitter embedding code. There was another newsletter recently with the same issue. I'll try to find some more test cases.

**Comment by jacksonh** [comment]
Here's another newsletter where we lost the tweet: https://michaelshellenberger.substack.com/p/the-2-minute-20-second-video-that?s=r 

@sywhb can you drop the formatted DIV HTML into this issue? We should prioritize this one as data is being lost.

**Comment by sywhb** [comment]
> Here's another newsletter where we lost the tweet: https://michaelshellenberger.substack.com/p/the-2-minute-20-second-video-that?s=r
> 
> @sywhb can you drop the formatted DIV HTML into this issue? We should prioritize this one as data is being lost.

This tweet was embedded in a formatted `div` with a proxy url so I have to fetch tweet-id from that proxy url and created a `tweet-placeholder` for it

**Comment by sywhb** [comment]
It was in this PR: #723
