### ISSUE TITLE
Duplicated image on page

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#589]
https://www.wired.com/2008/12/mf-self-help/ the top image is duplicated here. Likely a high/low res issue.

**Comment by sywhb** [comment]
Hey @jacksonh, this seems to be fixed.

<img width="992" alt="Screenshot 2022-05-12 at 6 12 53 PM" src="https://user-images.githubusercontent.com/12963965/168047911-0a2c0c0e-9943-473d-b2f2-ac6684ae2227.png">

**Comment by jacksonh** [comment]
Oh I wonder if it only happens when saving from iOS. 

![image](https://user-images.githubusercontent.com/75189/168513462-ce705659-e1cf-44c2-b0b2-77690c815d6d.png)
