### ISSUE TITLE
API to subscribe to popular newsletters

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#606]
To enable this onboarding screen we need an API to subscribe to popular newsletters. This API should take a newsletter id (we can probably use short names), and subscribe the user to that newsletter. If the user does not have a newsletter-email created yet, one should be created automatically. 

I think each of these newsletters can be subscribed to with an HTTP request, we just need to figure out the request pattern.

<img width="1265" alt="Screen Shot 2022-05-12 at 15 20 58" src="https://user-images.githubusercontent.com/75189/168177121-24637405-140e-4818-8064-7801b6950b08.png">

**Comment by jacksonh** [comment]
List of newsletters we should support (short name, long name, URL):

- `axios_essentials`, Daily Essentials: Axios AM · PM · Finish Line, https://www.axios.com/newsletters (Note Axios signup page lets you select multiple newsletters for sign up at once. We just want the first, Axios Daily Essentials)
- `slow_boring`, Slow Boring, https://www.slowboring.com/ 
- `money_stuff`, Matt Levine: Money Stuff, https://www.bloomberg.com/opinion/authors/ARbTQlRLRjE/matthew-s-levine 
- `morning_brew`, Morning Brew, https://www.morningbrew.com/ 
- `marginal_revolution`, Marginal Revolution, https://marginalrevolution.com/ -- NOTE: this one requires confirmation. Ideally we can figure out how to automatically confirm these subscriptions for users

**Comment by jacksonh** [comment]
@sywhb this is a first set we don't need to get all of them working. Also, for ones like Slow Boring that are hosted on Subsctack, if we can generalize the code to subscribe to Substack newsletters we can probably add some more of those. 

If any seem particularly hard to do we can leave them out.

**Comment by jacksonh** [comment]
I think we can skip marginal revolution for now. It's frequency is a little too high for this use case.

**Comment by sywhb** [comment]
Hey @jacksonh, I have wrapped up a PR here: https://github.com/omnivore-app/omnivore/pull/638

It has a new API `subscribe` which takes a newsletter's short name like `money_stuff`, and responds with a subscription created in db.

For each subscription, it will make an HTTP request to the newsletter to subscribe to it.
In this PR, we support:
* axios_essentials
* morning_brew
* money_stuff
* milk_road (still has some authentication issue with recaptcha token)

Both `slow_boring` and `pragmatic_engineer` require email confirmation, so I haven't implemented the solution to them for now.

**Comment by jacksonh** [comment]
Looks like I put the wrong URL for Money Stuff. This is the proper URL: https://www.bloomberg.com/account/newsletters the one I put, gives you alerts when there is a new post, but not the content.

**Comment by sywhb** [comment]
URL updated
