### ISSUE TITLE
Edit title and description modal

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#628]
Users would like to edit titles and descriptions of items. This should be available in the library view, via the long press context menu, and in the reader view, via the top right menu. 

<img width="392" alt="Screen Shot 2022-05-16 at 12 26 13" src="https://user-images.githubusercontent.com/75189/168667445-8b87a96a-4894-4f0f-b65e-bd4e4308c95f.png">

**Comment by jacksonh** [comment]
Note there is a ticket here to create the API: https://github.com/omnivore-app/omnivore/issues/626

**Comment by satindar** [comment]
Deployed in v1.9.0
