### ISSUE TITLE
YouTube iFrames are being removed by readability 

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#641]
This HTML from youtube-handler is having its iFrame removed:

```
    <html>
      <head><title>The Story of Celeste's Development</title>
      <meta property="og:image" content="https://i.ytimg.com/vi/c3mbELVqAmo/hqdefault.jpg" />
      <meta property="og:image:secure_url" content="https://i.ytimg.com/vi/c3mbELVqAmo/hqdefault.jpg" />
      <meta property="og:title" content="The Story of Celeste's Development" />
      <meta property="og:description" content="" />
      <meta property="og:article:author" content="Noclip - Video Game Documentaries" />
      </head>
      <body>
      <center>
      <iframe width="619.4690265486726" height="350" src="https://www.youtube.com/embed/c3mbELVqAmo" title="The Story of Celeste's Development" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      </center>
      <br />
        <a href="https://www.youtube.com/watch?v=c3mbELVqAmo">The Story of Celeste's Development</a>
        <div itemscope="" itemprop="author" itemtype="http://schema.org/Person">By <a href="https://www.youtube.com/c/NoclipVideo">Noclip - Video Game Documentaries</a></div>
      </body>
    </html>
```

**Comment by jacksonh** [comment]
Can test this by saving this URL: https://www.youtube.com/watch?v=c3mbELVqAmo

**Comment by jacksonh** [comment]
I wasn't able to figure out this issue, but it seems like in this block we don't append the iframe:

```
      for (var s = 0, sl = siblings.length; s < sl; s++) {
        var sibling = siblings[s];
        var append = false;

        this.log("Looking at sibling node:", sibling, sibling.readability ? ("with score " + sibling.readability.contentScore) : "");
        this.log("Sibling has score", sibling.readability ? sibling.readability.contentScore : "Unknown");

```

**Comment by jacksonh** [comment]
Created a test here: https://github.com/omnivore-app/omnivore/pull/642

**Comment by sywhb** [comment]
> I wasn't able to figure out this issue, but it seems like in this block we don't append the iframe:
> 
> ```
>       for (var s = 0, sl = siblings.length; s < sl; s++) {
>         var sibling = siblings[s];
>         var append = false;
> 
>         this.log("Looking at sibling node:", sibling, sibling.readability ? ("with score " + sibling.readability.contentScore) : "");
>         this.log("Sibling has score", sibling.readability ? sibling.readability.contentScore : "Unknown");
> ```

I'm not sure if we should append the iframe here because the content score is less than the threshold.
So I did a trick to wrap the video title and uploader hyperlink in a `<p>` so they will not get deleted regardless of content score in case some of the title is shorter like this one.
@jacksonh

**Comment by sywhb** [comment]
Saved page looks like this
<img width="782" alt="Screenshot 2022-05-18 at 11 26 49 AM" src="https://user-images.githubusercontent.com/12963965/168952578-5c7eb37d-0280-4144-99e5-3909557e4751.png">
