### ISSUE TITLE
GitHub blog article fails to parse

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#647]
https://github.blog/2022-05-16-how-were-using-projects-to-build-projects:/ -- content display report from a user.

**Comment by sywhb** [comment]
Fixed in #650 
<img width="889" alt="Screenshot 2022-05-18 at 3 56 34 PM" src="https://user-images.githubusercontent.com/12963965/168987701-c63a025f-0fd1-477f-ac26-f32d8c04645f.png">
