### ISSUE TITLE
Reduce Network Calls -iOS

### ISSUE THREAD

**Issue by satindar** [omnivore-app/omnivore#669]
When we prefetch content we should confirm we out of synch before asking for highlights and htmlContent again.

Maybe by comparing the savedAt timestamp saved in CoreData with the one we recently fetched?

**Comment by jacksonh** [comment]
https://github.com/omnivore-app/omnivore/issues/674

**Comment by satindar** [comment]
> @satindar i think you did this one already?

Yeah we can close this one now.
