### ISSUE TITLE
Fix Core Data warnings and possible threading violations 

### ISSUE THREAD

**Issue by satindar** [omnivore-app/omnivore#670]
We're creating a background context before calling loadPersistentStores. Probably not an issue but...maybe!

We possibly have a threading violation on a current viewer lookup. Need to review that.

**Comment by sixten** [comment]
I see that you have `com.apple.CoreData.ConcurrencyDebug` enabled on the iOS app scheme. Do you have any stack traces from that for the threading violations? Or a reproducible test case?
