### ISSUE TITLE
Add chip for sorting 

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#672]
We should add a chip beside the labels chip that lets user's sort, it can use a normal menu (like the first chip) with three options:

- Time Saved (sort:saved_at)
- Last Read (sort:updated_at)
- Relevance (sort:score)

TODO: we also need to figure out how to do ascending / descending

**Comment by jacksonh** [comment]
Assigning to myself to figure out design.

**Comment by jacksonh** [comment]
Options i think make sense:

- Recently Read
- Recently Saved
- Relevance
- Least recently Saved

**Comment by jacksonh** [comment]
Ok final list for the sort chip (title, search string):

- Newest: `sort:saved`
- Oldest: `sort:saved-DESC`
- Recently Read: `sort:updated`
- Recently Published: `sort:published`
- Relevance: `sort:score`

![IMG_C570C01401C0-1](https://user-images.githubusercontent.com/75189/169885585-93608080-ba40-49f6-88d0-d8e8a79440eb.jpeg)

**Comment by satindar** [comment]
Deployed on v1.8.0 (except for recently read but we have another issue open for that)
