### ISSUE TITLE
Filter by language

### ISSUE THREAD

**Issue by xplosionmind** [omnivore-app/omnivore#686]
At the time of saving, Omnivore should check the language of the saved page.

By doing so, it can be added a language filter while searching.

**Comment by xplosionmind** [comment]
Hi! I see this issue has been close, hence the feature should have been implemented, but in production I see no language filter, on omnivore.app.
![Screen Shot 2022-06-29 at 9 44 54 AM](https://user-images.githubusercontent.com/42862428/176380912-b481de50-5b76-4c6f-a294-a55b6cea60f3.jpg)

**Comment by sywhb** [comment]
Thanks for the report. We have only added the advanced search syntax `language:english` but yeah i will open another ticket for the UI.
