### ISSUE TITLE
Filter/sort by date published/added

### ISSUE THREAD

**Issue by xplosionmind** [omnivore-app/omnivore#687]
- It would be awesome if a user could sort articles both by time published and by time added.
- It could also specified a time-range and use it as a filter

**Comment by jacksonh** [comment]
Ticket for UI for this on iOS: https://github.com/omnivore-app/omnivore/issues/672

**Comment by sywhb** [comment]
API updated in #698 

Now it supports sort/filter by `published time` or `saved time`.
Syntax looks like:

* sorting
`sort: published` or `sort:published-asc` in ascending order

* filtering
** specific date: `saved:2022-05-23`: saved on `2022-05-23`
** range: `published:2022-05-23..*`: published from `2022-05-23` till now (* could be replaced with a specific date)

**Comment by xplosionmind** [comment]
Hi! Thanks for implementing this! Nevertheless, both in the webapp and in the iOS app I only see filtering options, not sorting ones (not only for the dates, for everything)

**Comment by sywhb** [comment]
> Hi! Thanks for implementing this! Nevertheless, both in the webapp and in the iOS app I only see filtering options, not sorting ones (not only for the dates, for anything)

You are welcome!
So far we only support this feature by using search query and we are working on the UI part as in here #672

**Comment by xplosionmind** [comment]
You are awesome! Thank you!
