### ISSUE TITLE
Support for webhooks

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#690]
As part of our API support, we need to add webhooks. This will allow a couple workflows, like triggering an [IFTTT](https://ifttt.com/) app or posting highlights into Discord.

**Comment by jacksonh** [comment]
The two most important flows from a user perspective are "new page saved" and "new highlight created".

**Comment by sywhb** [comment]
So we can let users set a `webhook_url`, `request method`, `body` and `operation` of a workflow and then we store it in our db.
When the matching operation happens, we could trigger the webhook

**Comment by sywhb** [comment]
The UI to create a trigger may look like this
![image](https://user-images.githubusercontent.com/12963965/169943114-b7f59438-ac5b-4252-8124-de2327b4cc1e.png)

**Comment by jacksonh** [comment]
@sywhb exactly, here is a screenshot from GitHub:

It looks like the options relevant to us are:

- URL
- Method (not sure if this needs to be configurable, seems like POST always makes sense)
- Content type (JSON or form data) -- just JSON is probably fine to start

We could also have a filter for event type:
- highlight created
- link created

<img width="793" alt="Screen Shot 2022-05-23 at 09 46 13" src="https://user-images.githubusercontent.com/75189/169943103-ac2f3921-e7e2-44fe-b836-9d30f4d992e8.png">

**Comment by sywhb** [comment]
Yeah, `event_type` is needed too.
Maybe just:
* link activity
* highlight activity

And we will send events of creation, deletion and update accordingly
@jacksonh

**Comment by jacksonh** [comment]
@sywhb yeah that makes sense to me

**Comment by jacksonh** [comment]
I don't know how this would work, because labels are added later, but I could see some workflow where you might not have something sent until a label is added. Like say I add an `Omnivore` label to a page, then the web hook would be triggered. 

For a first step though I think just the default triggers will be enough to start testing stuff.
