### ISSUE TITLE
Highlight search is case sensitive

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#702]
It looks like search with type:highlights is case sensitive. See two attached screenshots

![image](https://user-images.githubusercontent.com/75189/170148576-078e2b08-4fe4-4adc-954e-01df08921870.png)

![image](https://user-images.githubusercontent.com/75189/170148587-b9933e26-3e23-4e7f-b2c3-6114ceb3d424.png)

**Comment by sywhb** [comment]
Yeah it uses text analyzer and maybe I should have lowercase normalized the text
