### ISSUE TITLE
When searching for highlights we should include document title, description, content as secondary indexes

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#704]
Ranking should probably be highlight text * 5, title * 3, description * 2, content

**Comment by sywhb** [comment]
<img width="1326" alt="Screenshot 2022-06-02 at 12 16 35 PM" src="https://user-images.githubusercontent.com/12963965/171551963-fdc0fee8-4f3d-4710-8fa2-8ef922817c07.png">
Verified in web demo

**Comment by jacksonh** [comment]
Ah this is a big improvement. Much more expected results.
