### ISSUE TITLE
Tweet missing from article

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#720]
When saved via iOS share extension this article is missing a tweet: https://electrek.co/2022/05/26/georgia-solar-panel-manufacturing/

**Comment by sywhb** [comment]
<img width="910" alt="Screenshot 2022-06-02 at 12 08 08 PM" src="https://user-images.githubusercontent.com/12963965/171551175-96e50d0f-5a4e-4e93-87c7-c410079d9eba.png">
Verified in web demo
