### ISSUE TITLE
Arrow and font button on the navigation bar not working

### ISSUE THREAD

**Issue by sywhb** [omnivore-app/omnivore#786]
I reproduce it in this article http://www.artofluis.com/3d-work/the-art-of-the-witness/soon-swamp-bunkers I was reading it, tested the arrow, it worked, got back to the article list. Went back to reading that article, clicked on one of the images to see it better, this opened a popup (integrated browser), then I closed the popup, and this is when the arrow stops workin
![](https://cdn.discordapp.com/attachments/942463305107259432/985831779351035994/image.png)

![](https://cdn.discordapp.com/attachments/942463305107259432/985832887083466782/IMG_3434.png)
g

**Comment by satindar** [comment]
Merged a fix into main
