### ISSUE TITLE
Include open dyslexic in fonts

### ISSUE THREAD

**Issue by trashhalo** [omnivore-app/omnivore#830]
I have ADHD and some readers offer the font Open dyslexic to help us stay focused while reading long form texts and I find it very helpful. Could you include this as an option? It should be pretty straightforward to do

If you're open to it, I could open the pull request to do this change.

**Comment by jacksonh** [comment]
Hi @trashhalo thank you for filing this. Will try to add today. I had seen this font but wasn't sure if it was helpful, so really glad you brought it up.

**Comment by jacksonh** [comment]
@trashhalo here is a screenshot, testing this out now. 

I picked the OpenDyslexic 2 version. There's also a version 3, but it doesn't include Italic which we use in longer block quotes.

The heading isn't updated here, will work on getting those fixed also.

<img width="868" alt="Screen Shot 2022-06-21 at 15 00 57" src="https://user-images.githubusercontent.com/75189/174907388-9ee04f84-669a-4eac-af34-9c773c9fbb5d.png">

**Comment by trashhalo** [comment]
That looks fantastic! For what it's worth for me, the header is not a high priority because its hard to read. Long blocks of text and headers are generally pretty short. Thanks for prioritizing this so quickly!!

**Comment by jacksonh** [comment]
@trashhalo great. I think it might not be deployed until tomorrow. Was kind of funny timing as I'd been in the middle of rewriting parts of the font selector. I'll update this ticket when its out.

**Comment by jacksonh** [comment]
Hi @trashhalo this should be available on https://omnivore.app now. It will also be in the next iOS update (usually those are bi-weekly).
