### ISSUE TITLE
Economist article removes image

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#848]
An image is removed from this article that shouldn't be: https://www.economist.com/graphic-detail/2022/06/22/the-worlds-most-liveable-cities

**Comment by sywhb** [comment]
<img width="809" alt="Screenshot 2022-06-28 at 9 49 30 PM" src="https://user-images.githubusercontent.com/12963965/176195382-07fe2a3d-5b88-45e2-ac23-823463fc3c1e.png">
Hey @jacksonh this article requires authentication to read. I guess that's why we didn't scrape the image
