### ISSUE TITLE
Update plugin title in Logseq marketplace

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#865]
It looks like its still showing the old title

**Comment by sywhb** [comment]
Description updated here: https://github.com/logseq/marketplace/pull/206

**Comment by sywhb** [comment]
<img width="428" alt="Screenshot 2022-06-25 at 9 23 28 PM" src="https://user-images.githubusercontent.com/12963965/175775395-2acc1011-714e-4c5e-b864-2032c2b54ad4.png">

**Comment by jacksonh** [comment]
🙏
