### ISSUE TITLE
nzz.ch page is missing content

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#880]
This page is not displaying all data, it seems like it could be in the fetch, as generating a testcase creates a blank page. Content might also be burried in iframes. 

https://www.nzz.ch/international/brics-gipfel-putin-findet-neue-wirtschaftspartner-nzz-ld.1690310?reduced=true

**Comment by sywhb** [comment]
The image tag has `width="6450" height="4300"`

**Comment by sywhb** [comment]
It requires login access to the web page so the content is not scraped at all
