### ISSUE TITLE
Android share doesn't seem to work 404

### ISSUE THREAD

**Issue by trashhalo** [omnivore-app/omnivore#884]
https://www.nytimes.com/2022/06/26/opinion/justice-alito-reproductive-justice-constitution-abortion.html

I have pwa installed on my phone. I tried to share url with omnivore and this is what I see

![Screenshot_20220626-141334.png](https://user-images.githubusercontent.com/177491/175828226-7894e2c1-81cb-47f5-be9b-b85af1973652.png)

If this is normal behavior then maybe update the page to say something else

**Comment by jacksonh** [comment]
Thank you @trashhalo we had a similar issue reported today too and are investigating. Are you sharing from Chrome into the Omnivore PWA?

**Comment by trashhalo** [comment]
That's correct. From chrome to omnivore

**Comment by jacksonh** [comment]
@trashhalo thank you. And can you confirm whether the article is added to your library? I haven't been able to replicate this issue locally, but I think whats happening is the redirect after save is failing and sending to an invalid URL.

**Comment by trashhalo** [comment]
After it 404ed I went and clicked "add link" and added it that way. I didn't see it already added but it could have been in a cached state

**Comment by jacksonh** [comment]
Ok thank you, sorry about this I'm trying to add a little more logging now to figure out the issue.

**Comment by trashhalo** [comment]
I have a pixel 6 so I'm on like the latest Android and I know that they've made changes to the share system and more recent versions. So if you get some logs up there and you want me to share something again let me know

**Comment by jacksonh** [comment]
Sorry didn't mean to close this

**Comment by jacksonh** [comment]
That's really useful info on Android version. I will update my device.

**Comment by jacksonh** [comment]
@trashhalo can you try logging out (from the drop down menu in the top right) and then logging in within the PWA and then saving an article again?

**Comment by jacksonh** [comment]
@trashhalo ah that is great, gives me a good idea of what is going on (something with a cookie redirect).

Yeah you are right. For some reason that article can not be parsed. I'm going to handle that separately, it doesn't seem related. 

Keeping this issue open, as it seems there are two issues:

- in the PWA the API cookie is not always set during auth
- When we receive a 401 during the save operation in the PWA we are not shown a useful error and redirected to `/undefined` which creates a 404 error

**Comment by jacksonh** [comment]
Going to close this as we have a different issue about auth tokens not being set.
