### ISSUE TITLE
Images are not fetched on feynmanlectures site

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#89]
When saving pages such as https://www.feynmanlectures.caltech.edu/I_01.html from the feynmanlectures site we fail to fetch images. The server is sending a 403 response. What is happening is on the site when you load a page there is a cookie set by the page, that cookie authorizes fetching the images, so individual requests, like the ones made by the image proxy are rejected.

**Comment by odebroqueville** [comment]
Does this mean that the HTTP request HEADER needs to be modified to accept cookies or that you need to set a cookie when making a request?

**Comment by jacksonh** [comment]
Their site requires a cookie be set. I think they are using some tool to prevent scraping. So when you first enter the site it will set a cookie in your browser, and then when you request the image it will pass that cookie
