### ISSUE TITLE
Improve table used on the `/settings/api` page

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#895]
Video shows a few problems with this table:

https://www.loom.com/share/a5b689adaa43447ba5a199afb6b4fc67

1. It looks like the header elements and the values aren't aligned, you can see when i resize the window the headers are not above the correct elements anymore.
2. The date should be formatted in a more readable local time
3. In mobile the view doesn't make a lot of sense. We might need to add labels to the values

**Comment by jacksonh** [comment]
Two more issues I just found. These happen in Safari:

- The `Expires On` on the far right extends past the header when resizing
- The text colour for the input dropdown is white on a white backround

**Comment by jacksonh** [comment]
I believe this resolves the last issue I brought up: https://github.com/omnivore-app/omnivore/commit/c2ce6a478b80a5f7a7db54f6f29e7d1bbc198e99

**Comment by rupin90** [comment]
I think we can close this issue now? I am closing it for now, I can reopen if needed.
