### ISSUE TITLE
Improve labels coloring and displaying in dark mode

### ISSUE THREAD

**Issue by xplosionmind** [omnivore-app/omnivore#901]
Labels should be readable regardless of the color and of the theme. In this screenshot, it appears that, for example, that blue labels are not well readable in dark mode.

![Screen Shot 2022-06-29 at 10 01 08 AM](https://user-images.githubusercontent.com/42862428/176384648-967306d7-e863-4007-a212-5a8bb8a49df5.jpg)

**Comment by rupin90** [comment]
Do we have predefined colors based on different themes? Is there a mapping of colors according to theme?

**Comment by satindar** [comment]
On iOS we calculate the Luminance value and if it's less than 0.5 we consider it a dark color and use a white text color.

This seems like the way to calculate the same with JS:

https://gist.github.com/jfsiii/5641126

**Comment by rupin90** [comment]
Wow, thank you 🙏

**Comment by jacksonh** [comment]
Hey Rupin, your PR improves things a lot but I think we might want to adopt something like GitHub where it switches between filled and outlined based on theme. I'm working out the rules now, but here are two screenshots:
<img width="815" alt="Screen Shot 2022-07-08 at 12 00 27" src="https://user-images.githubusercontent.com/75189/178054613-b4317008-483c-4e8e-bb23-b6a93f92cc49.png">

<img width="867" alt="Screen Shot 2022-07-08 at 12 00 48" src="https://user-images.githubusercontent.com/75189/178054600-cb7a1f6a-ffab-4ecd-b4c4-9067d071111f.png">

**Comment by rupin90** [comment]
@jacksonh  - Yeah true. What I understood is 

 - in light theme,  user selected colors applied as a background instead as a text. If the background is dark then the text color is white, if background is light then text color is black.
 - in dark theme, user selected colors applied as a text (with border and a translucent background). There is definitely a lightness threshold that is brightening the text even more!
      - exception with Black color is that  - it is applied as a background with white text.

**Comment by rupin90** [comment]
Final outcome to implement
1. The label outline - 
 - border in dark theme
 - No border in light theme 

2. The background color -
  - Dark theme 
      - translucent/low opacity user selected  color with brightened border.
 -  Light Theme
      -  user selected  color with full opacity

3. Foreground color - 
  -  Dark theme
     - user selected label color is the text color
  - Light theme
     -  if user selected dark color then text is white
     - if user selected light color then text is black

**Comment by rupin90** [comment]
Do we already have a way to set the background color? - this is for the light theme.

**Comment by jacksonh** [comment]
@rupin90 I think for light theme its just as simple as setting the background color to the label color.

**Comment by rupin90** [comment]
I am closing this issue since the PR is merged.
