### ISSUE TITLE
Set tags and archived status after saving

### ISSUE THREAD

**Issue by xplosionmind** [omnivore-app/omnivore#905]
Immediately after saving, this is what is displayed:

![Screen Shot 2022-06-29 at 10 27 08 PM](https://user-images.githubusercontent.com/42862428/176538405-fbfafd17-c869-4632-b1a4-d62417ddd2a4.jpg)

Instead, it should be possible to edit something straight up. Let’s take the good old [Wallabager](https://github.com/wallabag/wallabagger) as an example:

![Screen Shot 2022-06-29 at 10 33 02 PM](https://user-images.githubusercontent.com/42862428/176539367-e712b785-e1bd-4a39-8793-84842edafaad.jpg)

From there, I can:
- [ ] Edit the title
- [ ] Archive/Mark as read
- [ ] Add to favorites
- [ ] add tags
  - [ ] with suggestions/autocompletion
- [ ] delete entry (if it was added by mistake)

**Comment by jacksonh** [comment]
Thanks for the mockup. We were actually just about to start on this for iOS (ticket here: https://github.com/omnivore-app/omnivore/issues/648 ) but hadn't thought about how it should look on web. 

I like the idea of archiving immediately.

**Comment by xplosionmind** [comment]
> I like the idea of archiving immediately.

I use this as a sort of “Reads Log”: I save and archive in Omnivore most of the articles I read, by labeling and sorting them, so that I can retrieve more easily what I learned.

**Comment by anarcat** [comment]
coming from wallabag (which, credit to them, is where the above "mockup" comes from, it's actually a screenshot!) this is a dealbreaker for me: the workflow to archive/mark as read (what's the difference, actually?) is too clunky for me to use Omnivore as a daily driver... I archive a *lot* of articles for future reference, and use tagging extensively to find that stuff later. I have 25k articles with (!!) 7k tags in wallabag right now, and i am on a constant struggle to keep the amount of "unread" stuff down....

**Comment by xplosionmind** [comment]
This issue was probably forgotten, but this feature has been implemented! 🎉
