### ISSUE TITLE
Multiple keyboard shortcuts (hotkeys) to interact with the browser extensions

### ISSUE THREAD

**Issue by xplosionmind** [omnivore-app/omnivore#906]
[Wallabager](https://github.com/wallabag/wallabagger) can be called with `opt` + `W`.

![Screen Shot 2022-06-29 at 10 36 29 PM](https://user-images.githubusercontent.com/42862428/176539882-66bd18d1-feda-4d55-8d05-00fa71796fda.jpg)

The Omnivore extension does not even provide a shortcut to be set, yet.

**Comment by jacksonh** [comment]
Good one, we have a small extension update planned for next week. Seems like we should be able to fit this in. Any ideas on the I wonder if `OPTION + O` makes sense or maybe `OPTION + S` (save)

**Comment by xplosionmind** [comment]
I vote for `OPTION` + `O`, but it is not too important, since e.g. in Firefox (as the screenshot above shows) the shortcut can be fully customized.

You only need to set the hooks/commands that have the possibility of a shortcut to be added.

I would *also* add:
- `OPTION` + `SHIFT` + `O`: save and open in Omnivore
- `OPTION` + `CTRL` + `O` / `OPTION` + `A`: save and archive
- `OPTION` + `D`: save and mark as favorite (`D` makes sense because in Firefox `CMD` + `D` adds the present page to favorites in bookmarks)

**Comment by jacksonh** [comment]
Duplicated here: https://github.com/omnivore-app/omnivore/issues/484

**Comment by jacksonh** [comment]
This is partially available in the Chrome and Firefox updates v0.1.26. We added save support but not the other options yet. We can probably add those when we clean up the extension options.

**Comment by xplosionmind** [comment]
Thanks a lot, @jacksonh! It is a great start.

**Comment by b2m9** [comment]
@jacksonh Is there a way to change the shortcut or at least deactivate it? `Option + O` is used to write the nordic letter `ø` (for non-nordic layouts). So every time I type an `ø`, I'm saving the page to Omnivore. Not ideal.

**Comment by jacksonh** [comment]
@b2m9 yeah these extension shortcuts are actually controlled by the browser (I think for this reason). Its really weird to get to, here is a demo of doing it on Chrome:

https://www.loom.com/share/e641db9a06a242a391260eac64dc7beb

**Comment by b2m9** [comment]
@jacksonh How did I not know that? Thank you very much for not solving my issue but also teaching me something new.

**Comment by xplosionmind** [comment]
A little update: there is one shortcut available to save the current page, but it is only one. It would be great to have more than one. I will change the title of this issue for clarity.
