### ISSUE TITLE
auth cookie is sometimes not set for omnivore.app domain 

### ISSUE THREAD

**Issue by ashinonyx** [omnivore-app/omnivore#908]
Brave is a Chromium browser, so I was able to install the extension from the Chrome store. However, even when I'm logged in on this browser, the extension will only prompt me to log in when clicked, and does not save the article.

**Comment by jacksonh** [comment]
Thanks @ashinonyx we do use a cookie to authenticate, i wonder if Brave's extra security is preventing auth.

I am downloading now to test.

**Comment by jacksonh** [comment]
@ashinonyx did you build the extension yourself to install in Brave?

**Comment by ashinonyx** [comment]
@jacksonh I did not, but could give it a shot with some guidance on how to do so.

**Comment by jacksonh** [comment]
@ashinonyx actually i just got Brave installed and realize the Chrome store works. 

One other thing, can you try going to https://omnivore.app in Brave, logging out using the menu in the top right, and then logging back in again, and then try saving a link with the extension?

**Comment by ashinonyx** [comment]
@jacksonh looks like that did the trick! What an embarrassingly simple answer, haha!

**Comment by jacksonh** [comment]
@ashinonyx thanks. This has happened a few times now. Still trying to figure out why but the cookie isn't being set correctly occasionally on login. 

Are you using Google or Apple to login?

**Comment by ashinonyx** [comment]
@jacksonh Apple

**Comment by jacksonh** [comment]
@ashinonyx great, thank yoU!
