### ISSUE TITLE
Newsletter is not recognized as a newsletter

### ISSUE THREAD

**Issue by jacksonh** [omnivore-app/omnivore#914]
https://www.getrevue.co/profile/bsunter

**Comment by sywhb** [comment]
testing on demo

**Comment by sywhb** [comment]
This #1107 PR would be useful for the other Revue newsletters like https://www.getrevue.co/profile/TheWolfDen

**Comment by sywhb** [comment]
@jacksonh

**Comment by sywhb** [comment]
It is working in Demo @jacksonh
