### ISSUE TITLE
saving the same page by extension and by adding links creates two items in Omnivore

### ISSUE THREAD

**Issue by sywhb** [omnivore-app/omnivore#950]

**Comment by jacksonh** [comment]
I have a feeling what is happening here is the canonical URL is different for some reason.

**Comment by sywhb** [comment]
> I have a feeling what is happening here is the canonical URL is different for some reason.

Checking...

**Comment by sywhb** [comment]
@jacksonh it's actually a bug in the backend. fixed in #955
