### ISSUE TITLE
Removing link from webapp does not reflect removal in iOS app

### ISSUE THREAD

**Issue by wingy3181** [omnivore-app/omnivore#980]
Hi, 

I find that when you delete a link via the web app via right clicking an article and selecting Remove and then confirming the removal does not reflect the change within the iOS app after refreshing and/or logging in/out.

However the reverse is ok if I remove the article in the iOS app, then it will reflect in the webapp after I refresh the site.

I've sourced the graphQL calls to the following but can't seem to find the difference.
They seem ok

WebApp
- https://github.com/omnivore-app/omnivore/blob/main/packages/web/lib/networking/mutations/deleteLinkMutation.ts

iOS
- https://github.com/omnivore-app/omnivore/blob/main/apple/OmnivoreKit/Sources/Services/DataService/Mutations/RemoveLink.swift

**Comment by jacksonh** [comment]
Thanks @wingy3181 this is a bug in how we are handling deletes. I think we are going to have to update our sync API to handle this correctly.

**Comment by sywhb** [comment]
https://automerge.org/

**Comment by sywhb** [comment]
#1035

**Comment by jacksonh** [comment]
@satindar can you prioritize integrating with this API for sync?

**Comment by sywhb** [comment]
Closed with #1035
