### ISSUE TITLE
Android share is not available when installing via different chrome based browser

### ISSUE THREAD

**Issue by aparaschiv** [omnivore-app/omnivore#997]
My default browser is Brave and i have disabled chrome (although tried installing via brave with chrome enabled). After installing the pwa via brave browser, the android share is not available.
I've also tried this with microsoft edge.

Is this issue related to how other chrome based browsers handle pwas or it only works on chrome browser

**Comment by jacksonh** [comment]
Thanks @aparaschiv I'll have to test this case, I'm not sure exactly how the operating system handles these share extensions with relations to the default browser. Looking into it now...

**Comment by hazre** [comment]
Any update on this? considering there is no other way to share a link to a PWA on android?

I've tried this with Chrome 108 and Edge 107 on Android 13

**Comment by jacksonh** [comment]
Hey @hazre we actually just uploaded our first native Android build to the Play store. Its still very early, but makes saving on Android much nicer. 

The build still needs to be approved by Google, but I can update this ticket when we are approved (usually about 48hrs).

**Comment by andrezgz** [comment]
Hi @jacksonh, any news on this issue?
