### ISSUE TITLE
Readwise integration

### ISSUE THREAD

**Issue by ashinonyx** [omnivore-app/omnivore#999]
Really liking Omnivore so far, it's just missing one thing that would make it almost perfect for me: Readwise integration!

I've reached out to them and they have noted my request, but they also suggested that this could be worked on Omnivore's end as well, using [Readwise's API](https://readwise.io/api_deets).

**Comment by jacksonh** [comment]
Hey @ashinonyx yeah I think the Readwise team is correct here. Its probably up to use to push highlights into Readwise. 

Can you just quickly explain what you'd like to do? I assume what you want is, when you add a highlight or note in Omnivore, its pushed to Readwise?

**Comment by ashinonyx** [comment]
@jacksonh Yes, that's exactly it. I'd like to see highlights made in Omnivore get pushed to Readwise

**Comment by jacksonh** [comment]
@ashinonyx thanks. I'll look at their API again, I think this should be possible, its not too different from our webhooks support.

**Comment by ashinonyx** [comment]
@jacksonh Sounds great! Thanks for the help!

**Comment by jacksonh** [comment]
Hey @ashinonyx we are starting to test this integration now. Would you be interested in testing?

**Comment by jonoberg** [comment]
@jacksonh I can also help with testing

**Comment by jacksonh** [comment]
@jonoberg awesome. I will shoot you an email tomorrow with some instructions. Thanks!

**Comment by ashinonyx** [comment]
@jacksonh sure, I'd be happy to help!

**Comment by jacksonh** [comment]
@ashinonyx @jonoberg if you go to this URL, you can click the Readwise button: https://omnivore.app/settings/integrations -- from there you can add your readwise API token to Omnivore. That should start a process where your highlights are synced into readwise. 

If you want to disconnect, you can just go to the same page and click `Remove`

**Comment by jacksonh** [comment]
Actually, we just found one issue we need to work out. Sorry about that, should be ready this weekend.

**Comment by jacksonh** [comment]
@jonoberg @ashinonyx sorry for the delay, this is working now:

To test:

go to this URL, and click the Readwise button: https://omnivore.app/settings/integrations -- from there add your Readwise API token (there is a link to get your token from Readwise). That should start a process where your highlights are synced into Readwise. Historical highlights will be imported, and any new highlights in Omnivore.

**Comment by jonoberg** [comment]
I just set it up and it looks to have worked great. Thanks for making this happen!

**Comment by howarddo2208** [comment]
Just tested it out, seem like that the labels from Omnivore didn't sync into document tags like I had expected. It would be great if it was the case.

**Comment by jacksonh** [comment]
Thanks @howarddo2208. It looks like we can do this by appending the labels to a note using their Inline Tagging feature: You can also use this field to create tags thanks to our [inline tagging](https://blog.readwise.io/tag-your-highlights-while-you-read/) functionality.

```
note	string	Annotation note attached to the specific highlight.
You can also use this field to create tags thanks to our [inline tagging](https://blog.readwise.io/tag-your-highlights-while-you-read/) functionality.
```

/cc @sywhb

**Comment by howarddo2208** [comment]
Oh yeah the inline tagging wasn't my concern. What I mentioned is the document tag, which is just like Omnivore's label. Here's an example 
![image](https://user-images.githubusercontent.com/62332195/209360736-e0e26af8-3720-4337-9180-94bdee507e20.png)

**Comment by jacksonh** [comment]
Thanks @howarddo2208 to add those document tags like `passion` did you add `.passion` when saving that item to Readwise?

**Comment by howarddo2208** [comment]
I added document tags through their in-house Reader app upon importing a document, later the tags will sync automatically. 
For Kindle highlights imported via myclipping.txt, I have to assign tags later in the Readwise Dashboard.

The inline tag only sticks to its highlight, not the document. Not sure if there is an API to assign document tags, though, there should be, I guess.
![image](https://user-images.githubusercontent.com/62332195/209365014-82f1b164-c0b1-4b3a-9f1e-53652d1c2463.png)
![image](https://user-images.githubusercontent.com/62332195/209365081-1d0d7759-83b0-41f7-97e4-4baf4b0e51a1.png)

**Comment by jacksonh** [comment]
Got it, thank you. I'll try to figure it out in their API.

**Comment by howarddo2208** [comment]
One thing I want to add is the search filter like the logseq plugin options. I don't want to sync everything into Readwise, then later having to discard one by one manually. It would be nice if I can sync only entries with a specific label I defined.

**Comment by jacksonh** [comment]
@sywhb With the recent change to webhooks is it possible to do the same for readwise allowing for a filter?

**Comment by jacksonh** [comment]
@sywhb so user could just set an arbitrary filter when setting up the integration?
